#!/usr/bin/env python3
"""Build src/image.c: the TOPS-10 core image of ARCHON, loaded from the
raw DECsystem-10 SAVE files archon.low / archon.shr.

File format (deduced, see docs/REVERSE-ENGINEERING.md):
  Each 36-bit PDP-10 word occupies 5 bytes.  Byte k (k=0..4) holds one
  7-bit character/septet right-justified; the spare 36th bit of the word
  is the high bit of byte 4.  (ANSI-ASCII / "5 septets per word" tape mode.)

  archon.low is a TOPS-10 .SAV-format low segment: a chain of IOWD blocks
  <-count,,addr-1> each followed by <count> data words, ending with a
  JRST to the start address.
  archon.shr is the shareable high segment, loaded at 400000 octal.

  Every file off this tape lost the word at file index 3674.  In
  archon.low that is "h wal" inside the room description "You're at the
  base of the north wall, by the gate."; in archon.shr it is a PUSHJ.
  See docs for the proofs.
"""
import os, sys

RAW = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..',
                   'dump_original')
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'image.c')
WMASK = (1 << 36) - 1

def words(path):
    data = open(path, 'rb').read()
    if len(data) % 5:
        sys.exit('%s: length %d is not a multiple of 5' % (path, len(data)))
    out = []
    for i in range(0, len(data), 5):
        b = data[i:i+5]
        w = 0
        for j in range(5):
            w = (w << 7) | (b[j] & 0x7f)
        out.append(((w << 1) | ((b[4] >> 7) & 1)) & WMASK)
    return out

def text(w):
    return ''.join(chr((w >> (29 - 7*k)) & 0x7f) for k in range(5))

def main():
    low = words(os.path.join(RAW, 'archon.low'))
    hgh = words(os.path.join(RAW, 'archon.shr'))

    # --- repair the dropped words -------------------------------------
    # Both files lost the word at file index 3674 in transfer.  In
    # archon.low that is the word "h wal" inside the room description
    # "You're at the base of the north wall, by the gate."; in
    # archon.shr it is the PUSHJ 17,423145 (FOROTS end-of-I/O-statement)
    # that closes an implied-DO WRITE loop.  See docs for the proofs.
    LOST = 3674
    # Unlike the high segment's, the low segment's gap has no donor to
    # copy from: the rooms either side of it are the north *tower* and
    # the *northwest* corner, so no other word in the file reads
    # "h wal".  It does not need one.  The line runs "You're at the
    # base of the nort<gap>l, by the gate.", the room is the north
    # wall, and five characters of A5 pack to exactly one word.
    if text(low[LOST]) == 'l, by' and text(low[LOST-1]) == ' nort':
        low.insert(LOST, 0o641016760730)   # "h wal"
    elif text(low[LOST]) != 'h wal':
        sys.exit('archon.low does not look like the expected image')

    if hgh[LOST] == 0o254000403434 and hgh[LOST-1] == 0o254000407124:
        hgh.insert(LOST, 0o260740423145)
    elif hgh[LOST] != 0o260740423145:
        sys.exit('archon.shr does not look like the expected image')

    # --- walk the .SAV IOWD chain -------------------------------------
    blocks, i = [], 0
    while i < len(low):
        h = low[i]
        lh, rh = h >> 18, h & 0o777777
        if lh < 0o400000:           # non-negative left half: terminator
            start = rh
            break
        n = 0o1000000 - lh
        blocks.append((rh + 1, low[i+1:i+1+n]))
        i += 1 + n
    else:
        sys.exit('ran off the end of archon.low without a terminator')

    if h >> 27 != 0o254:
        sys.exit('terminator is not a JRST: %012o' % h)

    jbff = blocks[-1][0] + len(blocks[-1][1])
    declared = None
    for a, ws in blocks:
        for k, w in enumerate(ws):
            if a + k == 0o121:
                declared = w & 0o777777
    # .JBFF is first-free, so the loaded data must stop at or below it.
    # It stops four words short here: SAVE omits a trailing run that was
    # zero when the image was written, and the loader zero-fills anyway.
    if declared < jbff:
        sys.exit('data runs past .JBFF: %o > %o' % (jbff, declared))

    total = sum(len(ws) for _, ws in blocks)
    sys.stderr.write('low: %d blocks, %d words, 0%o..0%o\n'
                     % (len(blocks), total, blocks[0][0], jbff - 1))
    sys.stderr.write('high: %d words at 0400000, start 0%o\n' % (len(hgh), start))

    # --- emit ---------------------------------------------------------
    with open(OUT, 'w') as f:
        f.write('/* Generated by tools/mkimage.py -- do not edit. */\n')
        f.write('#include "pdp10.h"\n\n')
        f.write('const int image_start = 0%o;\n' % start)
        f.write('const int image_hisegtop = 0%o;\n\n' % (0o400000 + len(hgh)))
        f.write('/* Each entry: address, count, then <count> words. Terminated by count 0. */\n')
        f.write('const w36 image_data[] = {\n')
        n = 0
        def emit(addr, ws):
            nonlocal n
            f.write('/*%06o*/ 0%o, 0%o,\n' % (addr, addr, len(ws)))
            for k in range(0, len(ws), 6):
                f.write('  ' + ' '.join('0%o,' % w for w in ws[k:k+6]) + '\n')
        for a, ws in blocks:
            emit(a, ws)
            n += len(ws) + 2
        emit(0o400000, hgh)
        n += len(hgh) + 2
        f.write('  0, 0\n};\n')
    sys.stderr.write('wrote %s (%d words)\n' % (OUT, n))

main()
