"""Embed TYMBASIC's run-phase message file, TBAMSG.SHR, in the port.

When a TYMBASIC program hits a run-phase error the runtime opens
SYS:TBAMSG.SHR and reads the message text out of it.  Tymshare's system
directory is not part of this port, so without the file every error comes
out as "TBA system error" instead of, say, "Array subscript out of bounds".

data/tbamsg.shr is ftsys/tbamsg.shr.4 from the Tymshare tapes, dated
1981-08-10: the newest system copy older than the 1984 game.  The copies in
fttba/, spunkdev/ and tbatlib/ work with this runtime too.  It is a MACRO
program's save file, not a TYMBASIC one, so it does not have the missing
word every TBA-compiled .SHR on the tape has.

    python tools/mkmsg.py        writes src/tbamsg.c
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'data', 'tbamsg.shr')
OUT = os.path.join(HERE, '..', 'src', 'tbamsg.c')

data = open(SRC, 'rb').read()
# Like the other disk files on the tape, the last word's trailing nulls were
# trimmed (7122 bytes, not 7125); the loader rounds up, so leave it be.
lines = ['/* Generated by tools/mkmsg.py from data/tbamsg.shr -- do not edit. */',
         '/* SYS:TBAMSG.SHR, the TYMBASIC run-phase message file (ftsys, 1981-08-10). */',
         '',
         'const unsigned char tbamsg_shr[] = {']
for i in range(0, len(data), 20):
    lines.append('    ' + ','.join(str(b) for b in data[i:i+20]) + ',')
lines += ['};', 'const unsigned tbamsg_shr_len = sizeof tbamsg_shr;', '']
open(OUT, 'w', newline='\n').write('\n'.join(lines))
print('wrote %s (%d words)' % (OUT, (len(data) + 4) // 5))
