.TH DUNE 6
.SH NAME
dune \- worm wars
.SH SYNOPSIS
.B dune
.SH DESCRIPTION
.PP
.I Dune
is a game of exploration, greed, and cunning.
It is also a game of ... patience.
Although there are some superficial similarities to aspects of
the excellent Science Fiction trilogy by Frank Herbert this game
has no official connection with those works.
It really owes its inspiration to a game called "Snake" at the
Rand Corporation which is probably an ancestor of the games called
"Snake" in the Berkeley Software Distributions.
.PP
When
.I dune
is executed it asks whether you wish instructions.
Here is an excerpt from those instructions:
.RS
You are in a strange, barren world consisting of nothing but sand dunes that
stretch in all directions as far as the eye can see ...
After a little exploration you discover that this world is rectangular!  It is
bounded on the north, south, east and west by high cliffs formed from a glassy
substance which you cannot climb.

As you wander you discover that:
.IP a)
Periodically a large bag of `spice' appears on the surface of the dunes,
.IP b)
There is a hole which probably leads back where you came from.
.IP c)
An immense WORM prowls around ready to eat anyone who desecrates
the sacred spice bags.
.PP
You also observe that:
.IP d)
The worm shows great deference to the bags of spice and the hole and will
not pass over, (or under), them.
.RE
.PP
A record is kept of the most successful explorer to date and is displayed
to all players.
.SH AUTHOR
Peter S. Langston
