"""Embed the game source (src_original/foo.lsp, unchanged) and fixes.lsp in sources.h."""
import os

here = os.path.dirname(os.path.abspath(__file__))
original = os.path.join(here, '..', '..', 'src_original', 'foo.lsp')


def literal(path):
    data = open(path, 'rb').read().decode('ascii')
    out = []
    for line in data.splitlines(True):
        esc = line.replace('\\', '\\\\').replace('"', '\\"').replace('\t', '\\t')
        esc = esc.replace('\r', '\\r').replace('\n', '\\n')
        out.append('"%s"' % esc)
    return '\n'.join(out) or '""'


with open(os.path.join(here, 'sources.h'), 'w', newline='\n') as f:
    f.write('/* generated by mksources.py - do not edit */\n')
    f.write('static const char SRC_FOO[] =\n%s;\n' % literal(original))
    f.write('static const char SRC_FIXES[] =\n%s;\n' % literal(os.path.join(here, 'fixes.lsp')))
