C     FTN77,L
C     $EMA /TRVCOM/, /LINCOM/, /VOCCOM/
C======================================================================C
C                                                                      C
C REVISION LIST:                                                       C
C                                                                      C
C --DATE-- --BY-- -- D E S C R I P T I O N --                          C
C                                                                      C
C  3/07/81 AW     -ORIGINAL VERSION-                                   C
C  12/12/86 JLA   -RTE-A VERSION-                                      C
C  2/10/87 JLA    -EXPANDED CAVE AND OTHER GOODIES                     C
C  7/13/87 JLA    -FIXED SCORING, DATA BASE & OTHER BUGS               C
C                                                                      C
C======================================================================C
C 
C  I/O ROUTINES (SPEK, PSPEK, RSPEK, GETIN, ECHO, YES, SAVE, RESTORE) 
C 
C 
      SUBROUTINE SPEK(WORD)
C 
C  PRINT THE MESSAGE IN WORD N OF LINES ARRAY.
C  PRECEED IT WITH A BLANK LINE UNLESS BLKLIN IS FALSE. 
C 
      IMPLICIT NONE 
C 
      INTEGER*2 WORD,I,N,L,PNT,OLDPNT 
C 
      include 'alphas.fi'
      include 'ioccom.fi'
      include 'lincom.fi'
C 
      N=WORD
D     WRITE(CRT,1000) N 
D1000 FORMAT("Subroutine 'SPEK' entered with N = ",I5)  
      IF(N.EQ.0) RETURN 
      IF(BLKLIN.AND.NOINPT) WRITE(CRT,'(" ")')
      NOINPT=.TRUE. 
      PNT=LINES(N)
      OLDPNT = PNT
 1010 N=N+1 
      L=LINES(N)+N
      IF(LINES(N).LT.1 .OR. LINES(N).GT.44) CALL BUG(28)
      N=N+1 
      IF(LINES(N).NE.EOF) WRITE(CRT,1020) (LINES(I),I=N,L)
      N=L+1 
      PNT=LINES(N)
      IF(PNT .EQ. OLDPNT) GO TO 1010
 1020 FORMAT(44A2)
      RETURN
      END 
C     $EMA /TRVCOM/, /LINCOM/, /VOCCOM/
      SUBROUTINE PSPEK(MSG,SKIP)
C 
C  FIND THE SKIP+1ST MESSAGE FOR OBJECT MSG AND PRINT IT. 
C  MSG SHOULD BE THE INDEX OF THE OBJECT. 
C  (INVEN+N+1 MESSAGE IS PROP=N MESSAGE). 
C 
      IMPLICIT NONE 
C 
      include 'txtcom.fi'
      include 'lincom.fi'
      include 'ioccom.fi'
C 
      INTEGER*2 I,J,L,M,MSG,SKIP,PNT,OLDPNT 
C 
D     WRITE(CRT,1000) MSG,SKIP  
D1000 FORMAT("Subroutine 'PSPEK' entered with MSG = ",I5, 
D    &  "    SKIP = ",I5) 
      M=PTEXT(MSG)
      IF(SKIP.LT.0) GO TO 1020
      OLDPNT=MSG
      DO I=1,SKIP+1 
 1010   M=M+1 
        M=LINES(M)+M+1
        PNT=LINES(M)
        L=LINES(M+1)
        IF(L.LT.1 .OR. L.GT.44) CALL BUG(28)
D       WRITE(CRT,2000) M,PNT,(LINES(J),J=M+2,M+L+1)
D2000   FORMAT("PSPEK: M=",I6,"  PNT=",I6,2X,44A2)
        IF(PNT .EQ. OLDPNT) GO TO 1010
        OLDPNT=PNT
      ENDDO 
C 
 1020 CALL SPEK(M)
C 
      RETURN
      END 
      SUBROUTINE RSPEK(I)
C 
C  PRINT THE I-TH "RANDOM" MESSAGE (SECTION 6 OF DATABASE). 
C 
      IMPLICIT NONE 
C 
      include 'txtcom.fi'
      include 'ioccom.fi'
C 
      INTEGER*2 I 
C 
D     WRITE(CRT,1000) I 
D1000 FORMAT("Subroutine 'RSPEK' entered with I = ",I5) 
      IF(I.NE.0) CALL SPEK(RTEXT(I))  
C 
      RETURN
      END 
      SUBROUTINE MSPEK(I)
C 
C  PRINT THE I-TH "MAGIC" MESSAGE FROM SECTION 12 OF DATABASE 
C 
      IMPLICIT NONE 
C 
      include 'txtcom.fi'
      include 'ioccom.fi'
C 
      INTEGER*2 I 
C 
      IF(I.NE.0) CALL SPEK(MTEXT(I))
C 
      RETURN
      END 
      SUBROUTINE GETIN(WORD1,WORD2,WORD3)
C     & ,Get Input from Terminal <250929.1142>
C 
C  GET A COMMAND FROM THE ADVENTURER.  SNARF OUT THE FIRST WORD, PAD
C  IT WITH BLANKS, AND RETURN IT IN WORD1. ANY NUMBER OF BLANKS MAY 
C  FOLLOW THE WORD.  IF A SECOND WORD APPEARS, IT IS RETURNED IN  
C  WORD2, ELSE WORD2 IS SET TO BLANKS. UP TO 16 CHARACTERS ARE
C  ALLOWED IN EACH WORD. WORD3 IS NOT USED NORMALLY.
C 
C  THIS ROUTINE IS ALMOST COMPLETELY DIFFERENT FROM THE PDP-11 VERSION. 
C 
      IMPLICIT NONE 
C 
      include 'ioccom.fi'
C 
      INTEGER*2 WORD1(8),WORD2(8),WORD3(8)
      INTEGER*2 TEMP1(8),TEMP2(8),TEMP3(8)
      INTEGER*2 I,TRIMLEN 
      CHARACTER*16 MESS1,MESS2,MESS3
      CHARACTER*48 BUFFER 
C 
      EQUIVALENCE (TEMP1,MESS1),(TEMP2,MESS2),(TEMP3,MESS3) 
C 
      NOINPT=.FALSE.
      IF(BLKLIN) WRITE(CRT,'(" ")') 
  100 WRITE(CRT,200)
  200 FORMAT(">",$)
      READ(KBD,300,END=9000) BUFFER
  300 FORMAT(A48) 
      CALL CASEFOLD(BUFFER) 
      IF(TRIMLEN(BUFFER).LT.1) THEN 
        CALL MSPEK(29)
        GO TO 100 
      ENDIF 
      DO I=1,8
        TEMP1(I)=8224 
        TEMP2(I)=8224 
        TEMP3(I)=8224 
      ENDDO 
C 
C  PARSE STRING INTO THREE WORDS
C 
      CALL SPLITSTRING(BUFFER,MESS1,MESS3)
      CALL SPLITSTRING(MESS3,MESS2,MESS3) 
C 
C  RETURN THREE INPUT WORD ARRAYS IN UPPER CASE 
C 
      DO I=1,8
        WORD1(I)=TEMP1(I) 
        WORD2(I)=TEMP2(I) 
        WORD3(I)=TEMP3(I) 
      ENDDO 
      IF(WORD2(1).EQ.8224) WORD2(1)=0 
      IF(WORD3(1).EQ.8224) WORD3(1)=0 
C 
D     WRITE(CRT,500) WORD1,WORD2,WORD3
D 500 FORMAT("GETIN returns: ",8A2,1X,8A2,1X,8A2) 
C 
      RETURN
C 
 9000 WRITE(CRT,'(/"[end of input]")')
      CALL EXIT
      END 
C     $EMA /TRVCOM/, /LINCOM/, /VOCCOM/
      SUBROUTINE ECHO(WORD1,WORD2,WORD3)
C 
C  SPELL OUT ABREVEATIONS AND DELETE LITTLE ADVERBS OR ADJATIVES. 
C 
      IMPLICIT NONE 
C 
      include 'ioccom.fi'
      include 'voccom.fi'
C 
      INTEGER*2 WORD1(8),WORD2(8),WORD3(8)
      INTEGER*2 TEMP1(8),TEMP2(8) 
      INTEGER*2 L1,L2,I,J,INDEX 
      INTEGER*2 UPCLR(2),TRIMLEN
      INTEGER*2 MAP(12,14),MAPSIZ 
C 
      CHARACTER*16 MESS1,MESS2
C 
      EQUIVALENCE (TEMP1,MESS1),(TEMP2,MESS2) 
C 
      DATA UPCLR/6977,6989/ 
C 
      DATA MAP/8277,8224,8224,8224,20565,8224,8224,8224,8224,8224,8224,8224, 
     &         8260,8224,8224,8224,20292,20055,8224,8224,8224,8224,8224,8224, 
     &         8270,8224,8224,8224,20302,21586,8264,8224,8224,8224,8224,8224, 
     &         8261,8224,8224,8224,16709,21587,8224,8224,8224,8224,8224,8224, 
     &         8275,8224,8224,8224,20307,21589,8264,8224,8224,8224,8224,8224, 
     &         8279,8224,8224,8224,17751,21587,8224,8224,8224,8224,8224,8224, 
     &         17742,8224,8224,8224,20302,21586,17736,21313,8276,8224,8224,8224, 
     &         22350,8224,8224,8224,20302,21586,22344,21317,8276,8224,8224,8224, 
     &         17747,8224,8224,8224,20307,21589,17736,21313,8276,8224,8224,8224, 
     &         22355,8224,8224,8224,20307,21589,22344,21317,8276,8224,8224,8224, 
     &         8255,8224,8224,8224,17736,20556,8224,8224,8224,8224,8224,8224, 
     &         20565,21587,8274,8224,20565,21587,18753,21330,8224,8224,8224,8224, 
     &         20036,21587,8274,8224,20292,20055,21587,18753,21330,8224,8224,8224, 
     &         12872,8271,8224,8224,16727,17748,8274,8224,8224,8224,8224,8224/ 
      DATA MAPSIZ/14/ 
C 
C  GET RID OF 'A', 'AN', 'AND', 'THE', 'OF', 'TO', 'FROM' FROM SECOND WORD
C  AND REPLACE IT WITH THIRD WORD IF ANY. 
C 
      IF(WORD2(1).NE.0) THEN
        IF(WORD2(1).EQ.8257 .AND. WORD2(2).EQ.8224 .OR. 
     &     WORD2(1).EQ.20033 .AND. WORD2(2).EQ.8224 .OR. 
     &     WORD2(1).EQ.20033 .AND. WORD2(2).EQ.8260 .OR. 
     &     WORD2(1).EQ.18516 .AND. WORD2(2).EQ.8261 .OR. 
     &     WORD2(1).EQ.17999 .AND. WORD2(2).EQ.8224 .OR. 
     &     WORD2(1).EQ.20308 .AND. WORD2(2).EQ.8224 .OR. 
     &     WORD2(1).EQ.21062 .AND. WORD2(2).EQ.19791 ) THEN 
          IF(WORD3(1).NE.0) THEN
            DO I=1,8
              WORD2(I)=WORD3(I) 
              WORD3(I)=0
            ENDDO 
          ENDIF 
        ENDIF 
      ENDIF 
C 
C  COPY WORDS INTO STRING BUFFERS 
C 
      DO I=1,8
        TEMP1(I)=WORD1(I) 
        TEMP2(I)=WORD2(I) 
      ENDDO 
C 
C  MAP ABREVIATIONS TO FULL SPELLING
C 
      DO I=1,MAPSIZ 
        DO J=1,4
          IF(TEMP1(J).NE.MAP(J,I)) GO TO 100
        ENDDO 
        DO J=1,8
          TEMP1(J)=MAP(J+4,I) 
        ENDDO 
  100   DO J=1,4
          IF(TEMP2(J).NE.MAP(J,I)) GO TO 200
        ENDDO 
        DO J=1,8
          TEMP2(J)=MAP(J+4,I) 
        ENDDO 
  200   CONTINUE
      ENDDO 
C 
C  LOOK UP ABREVIATIONS 
C 
      CALL VOCAB(TEMP1,-1,J,INDEX)
      IF(J.GE.0) THEN 
        DO I=1,8
          TEMP1(I)=ATAB(I,INDEX)
        ENDDO 
      ENDIF 
      CALL VOCAB(TEMP2,-1,J,INDEX)
      IF(J.GE.0) THEN 
        DO I=1,8
          TEMP2(I)=ATAB(I,INDEX)
        ENDDO 
      ENDIF 
C 
C  SHIFT TO LOWER CASE AND ECHO BACK TO TERMINAL
C
      L1=TRIMLEN(MESS1)
      IF(L1.LT.1) RETURN
      CALL LOWER(MESS1(2:16))
      L2=TRIMLEN(MESS2)
      IF(L2.LT.1) THEN
        MESS2(1:1)=' '
        L2=1
      ENDIF
      CALL LOWER(MESS2)
!     ESC-A ESC-M ONLY WORKS ON HP TERMS. DISABLED. -DWH
C     WRITE(CRT,300) UPCLR,MESS1(1:L1)//' '//MESS2(1:L2)
  300 FORMAT(2A2,">",A)
C
      RETURN
      END
      LOGICAL*2 FUNCTION YES(X,Y,Z)
C
C  CALL YESX (BELOW) WITH MESSAGES FROM SECTION 6.
C
      IMPLICIT NONE
C 
      INTEGER*2 X,Y,Z 
      EXTERNAL RSPEK
      LOGICAL*2 YESX
C 
      YES=YESX(X,Y,Z,RSPEK) 
      RETURN
      END 
      LOGICAL*2 FUNCTION YESX(X,Y,Z,SPK)
C     & ,Get Yes/No from Terminal <250929.1142>
C 
C  PRINT MESSAGE X, WAIT FOR YES/NO ANSWER.  IF YES, PRINT Y AND LEAVE YEA
C  TRUE; IF NO, PRINT Z AND LEAVE YEA FALSE.  SPK IS EITHER RSPEK OR MSPEK. 
C 
      IMPLICIT NONE 
C 
      include 'ioccom.fi'
      include 'alphas.fi'
C 
      INTEGER*2 X,Y,Z,REPLY(8),DUMMY(8) 
C 
D     WRITE(CRT,1000) X,Y,Z 
D1000 FORMAT("YESX:",3I8) 
 1010 IF(X.NE.0) CALL SPK(X)  
      CALL GETIN(REPLY,DUMMY,DUMMY) 
      IF(REPLY(1).EQ.CYE .OR. REPLY(1).EQ.CY) THEN
        REPLY(1)=CYE
        REPLY(2)=8275 
      ENDIF 
      IF(REPLY(1).EQ.CN) REPLY(1)=CNO 
      CALL ECHO(REPLY,DUMMY,DUMMY)
      IF(REPLY(1).EQ.CYE) THEN
        YESX=.TRUE. 
        IF(Y.NE.0) CALL SPK(Y)  
      ELSEIF(REPLY(1).EQ.CNO) THEN
        YESX=.FALSE.
        IF(Z.NE.0) CALL SPK(Z)
      ELSE
        CALL MSPEK(30)
        GO TO 1010
      ENDIF
C
      RETURN
      END
      SUBROUTINE CLEAR(CRT)
C
C  CLEAR HP 262X OR 264X CRT SCREEN
C
      IMPLICIT NONE
C
      INTEGER*2 CRT,CLR(2)
      DATA CLR/7016,6986/
C
C     WRITE(CRT,10) CLR      !DON'T ALLOW CLEAR SCREEN - DWH
   10 FORMAT(2A2)
      RETURN
      END
      SUBROUTINE BUG(NUM)
C
      IMPLICIT NONE
C
      include 'ioccom.fi'
C
      INTEGER*2 NUM
C
C  THE FOLLOWING CONDITIONS ARE CURRENTLY CONSIDERED FATAL BUGS.  NUMBERS < 20
C  ARE DETECTED WHILE READING THE DATABASE; THE OTHERS OCCUR AT "RUN TIME".
C     0     MESSAGE LINE > 70 CHARACTERS
C     1     NULL LINE IN MESSAGE
C     2     TOO MANY WORDS OF MESSAGES
C     3     TOO MANY TRAVEL OPTIONS
C     4     TOO MANY VOCABULARY WORDS
C     5     REQUIRED VOCABULARY WORD NOT FOUND
C     6     TOO MANY RTEXT OR MTEXT MESSAGES
C     7     TOO MANY HINTS
C     8     LOCATION HAS COND BIT BEING SET TWICE 
C     9     INVALID SECTION NUMBER IN DATABASE
C     10    TOO MANY LOCATIONS
C     11    TOO MANY PLAYER CLASSIFICATIONS 
C     12    TOO MANY OBJECTS
C     13    TOO MANY VERBS
C     14    TOO MANY CONDITIONS 
C 
C     20    SPECIAL TRAVEL (500>L>300) EXCEEDS GO TO LIST 
C     21    RAN OFF END OF VOCABULARY TABLE 
C     22    VOCABULARY TYPE (N/1000) NOT BETWEEN 0 AND 3
C     23    INTRANSITIVE ACTION VERB EXCEEDS GO TO LIST 
C     24    TRANSITIVE ACTION VERB EXCEEDS GO TO LIST 
C     25    CONDITIONAL TRAVEL ENTRY WITH NO ALTERNATIVE
C     26    LOCATION HAS NO TRAVEL ENTRIES
C     27    HINT NUMBER EXCEEDS GO TO LIST  
C     28    DATABASE LINE TOO LONG
C     29    INVALID LOC VALUE 
C     30    INVALID LOC VALUE 
C 
      WRITE(CRT,100) NUM  
  100 FORMAT ("Fatal error",I3,", consult your local wizard."/) 
      CALL EXIT 
      END 
      INTEGER*2 FUNCTION RNDM(RANGE)
C 
C A VARIANT USING THE RANDOM NUMBER GENERATOR IN FORTRAN LIBRARY. 
C 
      IMPLICIT NONE 
C 
      INTEGER*2 RANGE 
      REAL*4 URAN,FLOAT 
C 
      RNDM=URAN(0)*REAL(RANGE) 
C 
      RETURN
      END 
      SUBROUTINE LOWER(BUFFER)
C 
      IMPLICIT NONE 
C 
      INTEGER*2 I,LEN,TRIMLEN 
      CHARACTER*(*) BUFFER
C 
      LEN=TRIMLEN(BUFFER) 
      IF(LEN.LT.1 .OR. LEN.GT.80) RETURN
      DO I=1,LEN
        IF(BUFFER(I:I).GE.'A' .AND. BUFFER(I:I).LE.'Z') THEN
          BUFFER(I:I)=CHAR(ICHAR(BUFFER(I:I))+32)
        ENDIF 
      ENDDO 
C 
      RETURN
      END 
C     $EMA /TRVCOM/, /LINCOM/, /VOCCOM/
      SUBROUTINE MAGIC
C 
      IMPLICIT NONE 
C 
      include 'alphas.fi'
      include 'arycom.fi'
      include 'ioccom.fi'
      include 'magcom.fi'
      include 'miscom.fi'
      include 'placom.fi'
      include 'trvcom.fi'
      include 'txtcom.fi'
      include 'voccom.fi'
C 
      LOGICAL*2 GUARD,YESX,SAVED
C 
      INTEGER*2 I,J,INDEX,ANSWER,COMMAND(16),MAXCMD 
      INTEGER*2 IHRS,IMINS,OUTLU,NLOC,ERROR 
      INTEGER*2 IANS,IPROP,ID(8)
      INTEGER*2 FMPPURGE
C 
      REAL*4 ROPEN,RSHUT
C 
      EXTERNAL MSPEK
C 
      DATA COMMAND/18511, 17736, 8255, 22597, 20300, 17747, 21840, 18764,
     &             16723, 20548, 21072, 19536, 21584, 21057, 17238, 21836/
      DATA MAXCMD /16/
C 
C  SEE IF THEY KNOW ANY MAGIC 
C 
      IF(.NOT.GUARD(0)) THEN
        CALL MSPEK(35)
        RETURN
      ENDIF 
C 
      OUTLU=CRT 
      SAVED=.FALSE. 
   10 CALL MSPEK(31)
   20 CALL MSPEK(32)
      READ(KBD,30,END=9000) ANSWER 
   30 FORMAT(A2)
      CALL CLCUC(ANSWER,1)
C 
      DO I=1,MAXCMD 
        INDEX=I 
        IF(ANSWER.EQ.COMMAND(I)) GO TO 40 
      ENDDO 
      CALL MSPEK(10)
      GO TO 10
C 
C  BRANCH TO COMMAND
C 
   40 GO TO (100,200,200,400,500,600,700,800,900,1000,1100, 
     &  1200,1300,1400,1500,1600) INDEX 
C 
C  OPENING HOURS
C 
  100 DO I=1,2
        DO J=1,10 
          IHOURS(I,J)=0 
        ENDDO 
      ENDDO 
C 
      CALL MSPEK(11)
      DO I=1,10 
        INDEX=I 
  110   READ(KBD,*,END=9000) ROPEN,RSHUT 
        IF(ROPEN.LT.0.0) GO TO 120
        IHRS=INT(ROPEN) 
        ROPEN=ROPEN-INT(ROPEN)
        ROPEN=ROPEN*100 
        IMINS=INT(ROPEN+0.5)
        IF(IHRS.LT.0 .OR. IHRS.GT.24 .OR. 
     &     IMINS.LT.0 .OR. IMINS.GT.60) THEN
          CALL MSPEK(12)
          GO TO 110 
        ENDIF 
        IHOURS(1,I)=IHRS*60+IMINS 
C 
        IF(RSHUT.LT.0.0) THEN 
          CALL MSPEK(13)
          GO TO 110 
        ENDIF 
        IHRS=INT(RSHUT) 
        RSHUT=RSHUT-INT(RSHUT)
        RSHUT=RSHUT*100 
        IMINS=INT(RSHUT+0.5)
        IF(IHRS.LT.0 .OR. IHRS.GT.24 .OR. 
     &     IMINS.LT.0 .OR. IMINS.GT.60) THEN
          CALL MSPEK(13)
          GO TO 110 
        ENDIF 
        IHOURS(2,I)=IHRS*60+IMINS 
      ENDDO 
C 
  120 IF(IHOURS(1,INDEX).EQ.0) THEN 
        IHOURS(1,INDEX)=-1
        IHOURS(2,INDEX)=-1
      ENDIF 
      CALL MSPEK(6) 
      CALL HOURS
      GO TO 20
C 
C  DISPLAY HELP 
C 
  200 CALL MSPEK(31)
      GO TO 20
C 
C  EXIT 
C 
  400 IF(.NOT.SAVED) CALL MSPEK(14) 
      CALL MSPEK(16)
      RETURN
C 
C  MODIFY CURRENT LOCATION
C 
  500 CALL MSPEK(17)
      WRITE(CRT,510) LOC
  510 FORMAT(I5)
      CALL MSPEK(18)
      READ(KBD,*,ERR=520,END=9000) NLOC
  520 IF(NLOC.LT.1 .OR. NLOC.GT.LOCSIZ) THEN
        CALL MSPEK(19)
        GO TO 500 
      ENDIF 
      CALL SPEK(LTEXT(NLOC))
      IF(YESX(20,21,22,MSPEK)) THEN 
        LOC=NLOC
        GO TO 20
      ENDIF 
      GO TO 500 
C 
C  SET SUSPEND AND MAX PLAY TIMES 
C 
  600 WRITE(CRT,610) MAXSUS,MAXAMT
  610 FORMAT(/"Current suspend time is",I4," minutes and maximum",
     & " playing time is",I4," minutes.") 
      CALL MSPEK(7) 
      READ(KBD,*,END=9000) MAXSUS,MAXAMT 
      GO TO 20
C 
C  PURGE FILE ADVENTURE.DAT 
C 
  700 ERROR=FMPPURGE('ADVENTURE.DAT') 
      IF(ERROR.LT.0) THEN 
        CALL FMPREPORTERROR(ERROR,'ADVENTURE.DAT')
      ELSE
        CALL MSPEK(15)
      ENDIF 
      GO TO 20
C 
C  LIGHT THE LAMP 
C 
  800 PROP(LAMP)=1
      CALL CARRY(LAMP,3)
      CALL MSPEK(23)
      GO TO 20
C 
C  SAVE CHANGES MADE TO GAME
C 
  900 CALL SAVE('ADVENTURE.DAT')
      SAVED=.TRUE.
      GO TO 20
C 
C  DISPLAY DWARFS AND PIRATE LOCATIONS
C 
 1000 DO I=1,6
        IF(DLOC(I).NE.0) THEN 
          NOINPT=.FALSE.
          WRITE(CRT,1010) I,DLOC(I),DSEEN(I)
          CALL SPEK(LTEXT(DLOC(I))) 
        ENDIF 
      ENDDO 
 1010 FORMAT(/"Dwarf no.",I2,"   Location",I4,"   Seen ",L1)
      IF(CHLOC.NE.0) THEN 
        NOINPT=.FALSE.
        WRITE(CRT,'(/"Chest location:",I4)') CHLOC
        CALL SPEK(LTEXT(CHLOC)) 
      ENDIF 
      IF(CHLOC2.NE.0) THEN
        NOINPT=.FALSE.
        WRITE(CRT,'(/"Alternate chest location:",I4)') CHLOC2 
        CALL SPEK(LTEXT(CHLOC2))
      ENDIF 
      IF(DALTLC.NE.0) THEN
        NOINPT=.FALSE.
        WRITE(CRT,'(/"Alternate dwarf location:",I4)') DALTLC 
        CALL SPEK(LTEXT(DALTLC))
      ENDIF 
      GO TO 20
C 
C  DISPLAY PROPERTY TABLE 
C 
 1100 CALL MSPEK(24)
      INDEX=-1
      READ(KBD,*,ERR=1110,END=9000) INDEX
 1110 IF(INDEX.EQ.0) GO TO 20 
      IF(INDEX.LT.1 .OR. INDEX.GT.100) THEN 
        CALL MSPEK(25)
        GO TO 1100
      ENDIF 
      WRITE(CRT,1120) INDEX 
 1120 FORMAT(/"PROP Table for Index",I4)
      CALL PSPEK(INDEX,PROP(INDEX)) 
      WRITE(CRT,1130) PROP(INDEX) 
 1130 FORMAT(/"PROP value is currently",I3, 
     &  ",  Enter new value: ",$)
      READ(KBD,*,END=9000) PROP(INDEX) 
      GO TO 20
C 
C  DISPLAY PLACOM AND ABB 
C 
 1200 DO I=1,LOCSIZ 
        IF(ATLOC(I).NE.0 .OR.ABB(I).NE.0) THEN
          WRITE(OUTLU,1210) I,ATLOC(I),I,ABB(I) 
        ENDIF 
 1210   FORMAT(" ATLOC array (",I3,") =",I6,6X, 
     &         "   ABB array (",I3,") =",I6)
      ENDDO 
      DO I=1,100
        IF(PLACE(I).NE.0 .OR. FIXED(I).NE.0) THEN 
          WRITE(OUTLU,1220) I,PLACE(I),I,FIXED(I) 
        ENDIF 
 1220   FORMAT(" PLACE array (",I3,") =",I6,6X, 
     &         " FIXED array (",I3,") =",I6)
      ENDDO 
      DO I=1,200
        IF(LINK(I).NE.0) WRITE(OUTLU,1230) I,LINK(I)
 1230   FORMAT(" LINK array  (",I3,") =",I6)
      ENDDO 
      WRITE(OUTLU,1240) HOLDNG
 1240 FORMAT(" HOLDNG =",I6)
      GO TO 20
C 
C  DISPLAY PTEXT
C 
 1300 DO I=1,100
        IF(PTEXT(I).NE.0) THEN
          WRITE(OUTLU,1310) I,PTEXT(I)
 1310     FORMAT(" PTEXT array (",I3,") =",I6)
          IF(OUTLU.EQ.CRT) THEN 
            BLKLIN=.FALSE.
            CALL PSPEK(I,0) 
            BLKLIN=.TRUE. 
          ENDIF 
        ENDIF 
      ENDDO 
      GO TO 20
C 
C  DISPLAY ARYCOM 
C 
 1400 DO I=1,100
        IF(PLAC(I).NE.0 .OR. FIXD(I).NE.0) THEN 
          WRITE(OUTLU,1410) I,PLAC(I),I,FIXD(I) 
 1410     FORMAT(" PLAC array  (",I3,") =",I6,6X, 
     &           " FIXD array  (",I3,") =",I6)
        ENDIF 
      ENDDO 
      DO I=1,LOCSIZ 
        IF(KEY(I).NE.0 .OR. COND(I).NE.0) THEN
          WRITE(OUTLU,1420) I,KEY(I),I,COND(I)
 1420     FORMAT(" KEY array   (",I3,") =",I6,6X, 
     &           " COND array  (",I3,") =",I6)
        ENDIF 
      ENDDO 
      GO TO 20
C 
C  DISPLAY VOCAB INFORMATION
C 
 1500 CALL MSPEK(26)
      READ(KBD,1510,END=9000) ID 
 1510 FORMAT(8A2) 
      CALL CLCUC(ID,8)
      CALL VOCAB(ID,-1,IANS,INDEX)
      IPROP=MOD(IANS,1000)
      WRITE(CRT,1520) IANS,IPROP,ID 
 1520 FORMAT("VOCAB =",I5,",  PROP =",I4,2X,8A2)
      GO TO 20
C 
C  ALTER OUTPUT LU
C 
 1600 WRITE(CRT,1610) OUTLU 
 1610 FORMAT("Current output LU =",I3,", new LU? ",$)
      READ(KBD,*,END=9000) OUTLU 
      GO TO 20
C 
C 
 9000 RETURN
      END 
C     $EMA /TRVCOM/, /LINCOM/, /VOCCOM/
C 
      SUBROUTINE SAVE(FILENAME)
C 
C  IF YOU CHANGE THE SIZE OF ANY COMMON, BE SURE TO CHANGE THIS CODE
C  NOTE THAT IOCCOM IS NOT SAVED BUT IS USED FOR COMMUNICATION. 
C 
      IMPLICIT NONE 
C 
      include 'alphas.fi'
      include 'arycom.fi'
      include 'ioccom.fi'
      include 'lincom.fi'
      include 'magcom.fi'
      include 'miscom.fi'
      include 'placom.fi'
      include 'trvcom.fi'
      include 'txtcom.fi'
      include 'voccom.fi'
C 
      LOGICAL*2 YES 
C 
      CHARACTER*(*) FILENAME
      CHARACTER*64 NAME 
C 
      INTEGER*2 I,J,N,ERROR,TRIMLEN,NFIOB 
      LOGICAL*2 NOFILE,HASFILE
      INTEGER*2 ALPDAT(12),ARYDAT(750)
      INTEGER*2 MAGDAT(24),MISDAT(270),PLADAT(551)
      INTEGER*2 TRVDAT(2401),TXTDAT(667),VOCDAT(3061) 
C 
      EQUIVALENCE (BLANK,ALPDAT),(PLAC,ARYDAT)
      EQUIVALENCE (DEMO,MAGDAT),(LINUSE,MISDAT),(ATLOC,PLADAT)
      EQUIVALENCE (TRAVEL,TRVDAT),(ASCVAR,TXTDAT),(KTAB,VOCDAT) 
C 
C  ADD TYPE AND SIZE TO FILE NAME AND THEN OPEN 
C 
      N=TRIMLEN(FILENAME) 
      IF(N.LT.1 .OR. N.GT.55) THEN
        CALL FMPREPORTERROR(-15,FILENAME) 
        RETURN
      ENDIF 
      DO I=1,64 
        IF(I.LE.N) THEN 
          NAME(I:I)=FILENAME(I:I) 
        ELSE
          NAME(I:I)=' ' 
        ENDIF 
      ENDDO 
      DO I=1,N
        IF(NAME(N:N).EQ.':') GO TO 20 
      ENDDO 
C     RTE file type and size suffix; meaningless off the machine.
C     NAME(N+1:N+8)=':::3:300'
C     N=N+8 
C 
   20 CALL CASEFOLD(NAME) 
      OPEN(UNIT=LU,FILE=NAME,STATUS='NEW',ACCESS='SEQUENTIAL',
     &  FORM='UNFORMATTED',IOSTAT=ERROR,ERR=100)
   30 WRITE(CRT,40) NAME(1:N) 
   40 FORMAT(/"Saving data base in file ",A)
C 
C  WRITE REVISION 
C 
      WRITE(LU,IOSTAT=ERROR,ERR=120) REVISION 
C 
C  WRITE ALPHAS 
C 
      WRITE(LU) (ALPDAT(I),I=1,12)
C 
C  WRITE ARYCOM 
C 
      DO I=1,15 
        J=(I-1)*50+1
        WRITE(LU) (ARYDAT(N),N=J,J+49)
      ENDDO 
C 
C  WRITE LINCOM 
C 
      DO I=1,560
        J=(I-1)*50+1
        WRITE(LU) (LINES(N),N=J,J+49) 
      ENDDO 
C 
C  WRITE MAGCOM 
C 
      WRITE(LU) (MAGDAT(I),I=1,24)
C 
C WRITE MISCOM
C 
      DO I=1,5
        J=(I-1)*50+1
        WRITE(LU) (MISDAT(N),N=J,J+49)
      ENDDO 
      WRITE(LU) (MISDAT(I),I=251,270) 
C 
C  WRITE PLACOM 
C 
      DO I=1,11 
        J=(I-1)*50+1
        WRITE(LU) (PLADAT(N),N=J,J+49)
      ENDDO 
      WRITE(LU) HOLDNG
C 
C  WRITE TRVCOM 
C 
      DO I=1,48 
        J=(I-1)*50+1
        WRITE(LU) (TRVDAT(N),N=J,J+49)
      ENDDO 
      WRITE(LU) TRVSIZ
C 
C  WRITE TXTCOM 
C 
      DO I=1,13 
        J=(I-1)*50+1
        WRITE(LU) (TXTDAT(N),N=J,J+49)
      ENDDO 
      WRITE(LU) (TXTDAT(I),I=651,667) 
C 
C  WRITE VOCCOM 
C 
      DO I=1,51 
        J=(I-1)*60+1
        WRITE(LU) (VOCDAT(N),N=J,J+59)
      ENDDO 
      WRITE(LU) TABSIZ
C 
      CLOSE(UNIT=LU)
      RETURN
C 
C  FILE OPEN ERROR
C 
  100 IF(HASFILE(NAME)) THEN 
        WRITE(CRT,110) NAME(1:N)
  110   FORMAT(/"File ",A," already exists.") 
        IF(YES(220,54,54)) THEN 
          OPEN(UNIT=LU,FILE=NAME,STATUS='OLD',ACCESS='SEQUENTIAL',
     &      FORM='UNFORMATTED',IOSTAT=ERROR,ERR=120) 
          GO TO 30
        ENDIF 
        RETURN
      ENDIF 
  120 WRITE(CRT,110) ERROR,NAME(1:N)
  130 FORMAT(/"Error",I5," trying to open file ",A) 
      RETURN
      END 
C     $EMA /TRVCOM/, /LINCOM/, /VOCCOM/
C 
      SUBROUTINE RESTORE(FILENAME)
C     &  ,Restore Common from File <250929.1142>
C 
C  IF YOU CHANGE THE SIZE OF ANY COMMON, BE SURE TO CHANGE THIS CODE
C 
      IMPLICIT NONE 
C 
      include 'alphas.fi'
      include 'arycom.fi'
      include 'ioccom.fi'
      include 'lincom.fi'
      include 'magcom.fi'
      include 'miscom.fi'
      include 'placom.fi'
      include 'trvcom.fi'
      include 'txtcom.fi'
      include 'voccom.fi'
C 
      LOGICAL*2 YES 
C 
      CHARACTER*(*) FILENAME
      CHARACTER*64 NAME 
C 
      INTEGER*2 I,J,N,ERROR,TRIMLEN,NFIOB 
      LOGICAL*2 NOFILE,HASFILE
      INTEGER*2 ALPDAT(12),ARYDAT(750)
      INTEGER*2 MAGDAT(24),MISDAT(270),PLADAT(551)
      INTEGER*2 TRVDAT(2401),TXTDAT(667),VOCDAT(3061) 
C 
      EQUIVALENCE (BLANK,ALPDAT),(PLAC,ARYDAT)
      EQUIVALENCE (DEMO,MAGDAT),(LINUSE,MISDAT),(ATLOC,PLADAT)
      EQUIVALENCE (TRAVEL,TRVDAT),(ASCVAR,TXTDAT),(KTAB,VOCDAT) 
C 
C  MAKE SURE NAME IS OK AND OPEN FILE 
C 
      RESTART=.FALSE. 
      N=TRIMLEN(FILENAME) 
      IF(N.LT.1 .OR. N.GT.63) THEN
        CALL FMPREPORTERROR(-15,FILENAME) 
        RETURN
      ENDIF 
      DO I=1,64 
        IF(I.LE.N) THEN 
          NAME(I:I)=FILENAME(I:I) 
        ELSE
          NAME(I:I)=' ' 
        ENDIF 
      ENDDO 
C 
   20 CALL CASEFOLD(NAME) 
      OPEN(UNIT=LU,FILE=NAME,STATUS='OLD',ACCESS='SEQUENTIAL',
     &  FORM='UNFORMATTED',IOSTAT=ERROR,ERR=100)
   30 WRITE(CRT,40) NAME(1:N) 
   40 FORMAT(/"Restoring data base from file ",A) 
C 
C  READ REVISION  
C 
      READ(LU,IOSTAT=ERROR,ERR=120) REVISION
C 
C  READ ALPHAS
C 
      READ(LU) (ALPDAT(I),I=1,12) 
C 
C  READ ARYCOM
C 
      DO I=1,15 
        J=(I-1)*50+1
        READ(LU) (ARYDAT(N),N=J,J+49) 
      ENDDO 
C 
C  READ LINCOM
C 
      DO I=1,560
        J=(I-1)*50+1
        READ(LU) (LINES(N),N=J,J+49)
      ENDDO 
C 
C  READ MAGCOM
C 
      READ(LU) (MAGDAT(I),I=1,24) 
C 
C READ MISCOM 
C 
      DO I=1,5
        J=(I-1)*50+1
        READ(LU) (MISDAT(N),N=J,J+49) 
      ENDDO 
      READ(LU) (MISDAT(I),I=251,270)
C 
C  READ PLACOM
C 
      DO I=1,11 
        J=(I-1)*50+1
        READ(LU) (PLADAT(N),N=J,J+49) 
      ENDDO 
      READ(LU) HOLDNG 
C 
C  READ TRVCOM
C 
      DO I=1,48 
        J=(I-1)*50+1
        READ(LU) (TRVDAT(N),N=J,J+49) 
      ENDDO 
      READ(LU) TRVSIZ 
C 
C  READ TXTCOM
C 
      DO I=1,13 
        J=(I-1)*50+1
        READ(LU) (TXTDAT(N),N=J,J+49) 
      ENDDO 
      READ(LU) (TXTDAT(I),I=651,667)
C 
C  READ VOCCOM
C 
      DO I=1,51 
        J=(I-1)*60+1
        READ(LU) (VOCDAT(N),N=J,J+59) 
      ENDDO 
      READ(LU) TABSIZ 
C 
      CLOSE(UNIT=LU)
      RESTART=.TRUE.
      RETURN
C 
C  FILE OPEN ERROR
C 
  100 IF(NOFILE(NAME)) THEN 
        WRITE(CRT,110) NAME(1:N)
  110   FORMAT(/"File ",A," does not exist. No restore made.")
        RETURN
      ENDIF 
  120 WRITE(CRT,110) ERROR,NAME(1:N)
  130 FORMAT(/"Error",I5," trying to open file ",A) 
      RETURN
      END 

