# -*- coding: utf-8 -*-
"""Emit src/data.h -- the glossary, compiled, for the C interpreter.

Nothing here is authored: every string and every jump comes out of
`data/doc01.bin`, which `extract.py` pulls unmodified from the disk image.

    python gendata.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import parse  # noqa: E402

OPS = ["TEXT", "RETURN", "TAB", "PROMPT", "EXECUTE", "NKEYS", "IFKEY", "CMD",
       "IFCOND", "END", "GOTO", "PAGE", "PAGERET", "SEARCH", "INSERT",
       "BEEP", "EAST", "SOUTH", "BACKSPACE", "CANCEL", "NOTE", "CENTER",
       "UNDERSCORE", "COMMAND", "DECTAB", "ERROR", "COPY", "DELETE",
       "FORMAT", "INDENT"]

ALIAS = {"N-KEYS": "NKEYS", "DEC-TAB": "DECTAB"}


def cstr(s):
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "	":
            out.append("\t")
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append(" ")
    return '"%s"' % "".join(out)


def main():
    prog = parse.program()
    used = set()
    for _, body in prog:
        for op, _ in body:
            used.add(ALIAS.get(op, op))
    unknown = sorted(u for u in used if u not in OPS)
    if unknown:
        print("unknown opcodes:", unknown, file=sys.stderr)

    out = []
    out.append("/* data.h -- generated by tools/gendata.py.  Do not edit.")
    out.append(" *")
    out.append(" * The Misty Marsh glossary, compiled straight out of the Wang disk")
    out.append(" * image.  Every string below is the game's own text.")
    out.append(" */")
    out.append("#ifndef MISTY_DATA_H")
    out.append("#define MISTY_DATA_H")
    out.append("")
    out.append("typedef enum {")
    for o in OPS:
        out.append("    OP_%s," % o)
    out.append("    OP_NONE")
    out.append("} Opcode;")
    out.append("")
    out.append("typedef struct { Opcode op; const char *arg; } Op;")
    out.append("typedef struct { char key; int n; const Op *ops; } Entry;")
    out.append("")

    for i, (key, body) in enumerate(prog):
        out.append("static const Op ops_%d[] = {" % i)
        for op, arg in body:
            name = ALIAS.get(op, op)
            if name not in OPS:
                continue
            out.append("    { OP_%s, %s }," % (name, cstr(arg) if arg else "0"))
        out.append("    { OP_NONE, 0 }")
        out.append("};")
    out.append("")
    out.append("static const Entry entries[] = {")
    for i, (key, body) in enumerate(prog):
        n = sum(1 for op, _ in body if ALIAS.get(op, op) in OPS)
        if key == "'":
            ck = "\\'"
        elif key == "\\":
            ck = "\\\\"
        elif ord(key) < 32:
            ck = "\\%03o" % ord(key)      # the synthetic start entry
        else:
            ck = key
        out.append("    { '%s', %d, ops_%d }," % (ck, n, i))
    out.append("};")
    out.append("static const int n_entries = %d;" % len(prog))
    out.append("")
    out.append("#endif")

    path = os.path.join(HERE, "..", "src", "data.h")
    open(path, "w", newline="\n").write("\n".join(out) + "\n")
    print("wrote %s: %d entries, %d ops" %
          (path, len(prog), sum(len(b) for _, b in prog)))


if __name__ == "__main__":
    main()
