; wru=034   is CTRL-\ to break out to SIMH
set console wru=034
set cpu 4096k kl10b
set tua rh20
set rpa rh20
; set rpb rh20
set ni enable
set cty rsx20
att lp20 -n KL_prt.lst
set rpa0 rp06
set rpa1 rp06
att rpa0 -f dbd9 dsk/klb_psv7_0.rp06
att rpa1 -f dbd9 dsk/klb_psv7_1.rp06
;	** uncomment the line below if you want to Telnet into your system @ port 2021  (change port # if desired)
;att tty -U 2021
load -c bts/boot.exb
echo
echo *****************************************************************************
echo After you quit the game:
echo
echo At the @ prompt, type ENA and hit Enter.
echo At the $ prompt, hit Ctrl-E then type CEASE NOW and hit Enter.
echo Hit Enter again at the [Confirm] prompt.-
echo When "Shutdown complete" appears, hit Ctrl-Break, echo type q and hit Enter.
echo *****************************************************************************
echo
expect "BOOT>" send "\r"; continue
expect -i -r "Dumpable" send -t after=1000,"\r"; continue
expect -r "21017\)[\r\n]+.*" send "LOGIN OPERATOR TEST\r"; continue
expect -i -r "End of LOGIN.CMD.1[\r\n]+@" send "R GAME:ADVENTURE\r"; continue
cont
