ASMB,R,L
      NAM DLINK,7 (TWH) 1982-11-18 DUNGEON SEGMENT LINKER
      ENT DLINK,RETRN,DLIN2
      EXT SEGLD,.ENTR,SEG,DUNGB,DUNGC,DUNGD,DUNGE,DUNGF
*
* CALLING SEQUENCE:
*
*     CALL DLINK(ISEGN,IPAR1,IPAR2,IPAR3)
*
*          WHERE: ISEG IS THE ARRAY CONTAINING THE DESIRED SEGMENT NAME
*                 IPAR1-IPAR3 ARE PARAMETERS
*
* DLINK SCHEDULES THE SEGMENT AND THE SEGMENT SHOULD THEN RETURN
* TO THE MAIN BY A
*
*     CALL RETRN
*
*          WHERE RETRN IS AN ENTRY POINT IN DLINK AND RETURNS CONTROL
*                     TO THE ORIGINAL CALLING POINT IN THE MAIN
*
NAMA  DEF NAMAD
*
NAMAD BSS 1         SEGMENT NAME
PAR1  BSS 1         PARAMETER 1
PAR2  BSS 1         PARAMETER 2
PAR3  BSS 1         PARAMETER 3
*
DLINK NOP
      JSB .ENTR     GET PARAMETER ADDR'S
      DEF NAMAD
      JMP DL1
*
* ALTERNATE ENTRY TO DO THE FUNCTION W/O CHANGING RETURN ADDRESS.
*
NAM2A DEF NAM2
NAM2  BSS 4         AS ABOVE
DLIN2 NOP
      JSB .ENTR     GET PARAMETER ADDR'S
      DEF NAM2
      LDA NAM2A
      LDB NAMA      MOVE THEM TO OTHER ENTRY
      MVW D4        AND CONTINUE
*
DL1   LDA PAR1,I
      STA SEG
      LDA PAR2,I    SET UP PARAM'S TO SEG.
      STA SEG+1
      LDA PAR3,I
      STA SEG+2
*
      LDA NAMAD
      LDB NOWAD     ADD. OF NAME OF CUR. SEG.
      CMW D3
      JMP EQ        SAME SEGMENT AGAIN
*
      NOP
      LDA NAMAD
      STA CALLP
      LDB NOWAD
      MVW D3        STORE NAME FOR NEXT TIME
*
      JSB SEGLD     CALL THE NEW SEGMENT
      DEF RTN
CALLP BSS 1
      DEF IERR
RTN   EQU *         NEVER RETURNS HERE
*
EQ    ADA N1
      LDA A,I       LAST WORD OF NAME
      CPA B
      JSB DUNGB
      CPA C         GO TO RIGHT ENTRY POINT
      JSB DUNGC      FOR SEGMENT
      CPA D
      JSB DUNGD
      CPA E
      JSB DUNGE
      CPA F         IT HAD BETTER HAVE
      JSB DUNGF     MATCHED ONE OF THOSE!
*
RETRN NOP
      JMP DLINK,I   RETURN TO MAIN PROGRAM
*
A     EQU 0
RCODE DEC 8
D3    DEC 3
D4    DEC 4
IERR  BSS 1
N1    DEC -1
B     ASC 1,B
C     ASC 1,C
D     ASC 1,D
E     ASC 1,E
F     ASC 1,F
NOWAD DEF NOW
NOW   ASC 3,XXXXX
      END
