.TH TODAY 6
.SH NAME
today \- what is special about this date?
.SH SYNOPSIS
.B today
.SH DESCRIPTION
.PP
.I Today,
(an acronym for
\fIt\fPemporally-\fIo\fPganized-\fId\fPata-\fIa\fPbout-\fIy\fPesteryear),
relates interesting facts associated with today;
national holidays (in many nations) and birthdays of famous people
are intermingled with historic disasters and other,
more humorous references.
.SH FILES
dates	Intersting [sic] facts
.SH AUTHOR
Peter S. Langston
