      SUBROUTINE PGETLN(UNIT,BUF)
C
C  PORT: READ ONE RECORD OF TEXT INTO A CHARACTER VARIABLE, BLANK PADDED.
C  THE ORIGINAL READ CHARACTERS STRAIGHT INTO INTEGER ARRAYS WITH "A1"
C  FORMAT.  GFORTRAN ACCEPTS THAT BUT READS THE FIELD AS IF IT WERE
C  NUMERIC - A COMMA ENDS IT AND THE REST OF THE LINE IS LOST - SO EVERY
C  SUCH READ GOES THROUGH HERE AND PUNPK INSTEAD.
C
C  END OF FILE ON THE TERMINAL (UNIT 5) ENDS THE PROGRAM QUIETLY, WHICH IS
C  WHAT A PIPED SCRIPT NEEDS; ON THE SEL THE TERMINAL NEVER RAN OUT.
C
      IMPLICIT INTEGER*4(A-Z)
      CHARACTER*(*) BUF
C
      BUF=' '
      READ(UNIT,1,END=9,ERR=9)BUF
1     FORMAT(A)
      RETURN
9     IF(UNIT.EQ.5)STOP
      WRITE(6,10)UNIT
10    FORMAT(' PORT: END OF FILE ON UNIT',I3)
      STOP
      END
      SUBROUTINE PUNPK(STR,IARR,N)
C
C  PORT: ONE CHARACTER PER WORD, AS "A1" DID ON THE SEL 32.  THE CHARACTER
C  GOES IN THE LOW-ORDER BYTE, WHICH IS THE BYTE GFORTRAN'S "A1" WRITES
C  BACK OUT (THE SEL USED THE HIGH-ORDER BYTE WITH BLANKS AFTER IT;
C  NOTHING IN THE PROGRAM CARES WHICH, ONLY THAT READING AND WRITING
C  AGREE).
C
      IMPLICIT INTEGER*4(A-Z)
      CHARACTER*(*) STR
      DIMENSION IARR(N)
C
      DO 10 I=1,N
10    IARR(I)=ICHAR(STR(I:I))
      RETURN
      END
