      SUBROUTINE IOINIT(DUMMY)
C
C  PORT: THE SEL VERSION SET TTYI/TTYO/DBFI TO RTM LOGICAL FILE CODES AND
C  ATTACHED ADV.DATA AND ADV.LINE WITH M:ALOC1.  HERE THEY ARE UNIT NUMBERS
C  AND THE FILES SIT BESIDE THE PROGRAM.  BLKLIN IS LEFT ALONE, AS IT WAS:
C  IT COMES OUT OF THE SAVED COMMON BLOCKS, AND MAINT SETS IT.
C
      IMPLICIT INTEGER*4(A-Z)
      LOGICAL BLKLIN
      COMMON /IOSCOM/ TTYI,TTYO,BLKLIN,DBFI
      CHARACTER*260 PDIR
C
      TTYI=5
      TTYO=6
      DBFI=1
      CALL PGMDIR(PDIR,PDLEN)
      OPEN(DBFI,FILE=PDIR(1:PDLEN)//'adv.data',STATUS='OLD',ERR=91)
      CALL PLDLIN
      RETURN
C
91    WRITE(6,92)
92    FORMAT(' PORT: CANNOT OPEN ADV.DATA')
      STOP
      END
      INTEGER*4 FUNCTION LINES(INDEX)
C
C  PORT: ON THE SEL THE 9800 WORDS OF MESSAGE TEXT DID NOT FIT IN MEMORY,
C  SO LINES WAS A FUNCTION OVER A RANDOM ACCESS FILE (ADV.LINE), PAGED 192
C  WORDS AT A TIME BY THE ASSEMBLER MODULE IN THE LAST JOB OF THE PRINTOUT.
C  HERE THE ARRAY IS SIMPLY IN MEMORY, WRITTEN OUT BY SAVLINES AND READ
C  BACK BY PLDLIN, SO THE FILE STILL EXISTS AND STILL HOLDS THE SAME WORDS.
C
      IMPLICIT INTEGER*4(A-Z)
      COMMON /PLNCOM/ LNBUF
      DIMENSION LNBUF(9800)
C
      LINES=0
      IF(INDEX.GE.1.AND.INDEX.LE.9800)LINES=LNBUF(INDEX)
      RETURN
      END
      SUBROUTINE SETLINES(INDEX,VALUE)
C
C  PORT: SEE LINES.
C
      IMPLICIT INTEGER*4(A-Z)
      COMMON /PLNCOM/ LNBUF
      DIMENSION LNBUF(9800)
C
      IF(INDEX.GE.1.AND.INDEX.LE.9800)LNBUF(INDEX)=VALUE
      RETURN
      END
      SUBROUTINE SAVLINES
C
C  PORT: SEE LINES.  WRITES ADV.LINE BESIDE THE PROGRAM.
C
      IMPLICIT INTEGER*4(A-Z)
      COMMON /PLNCOM/ LNBUF
      DIMENSION LNBUF(9800)
      CHARACTER*260 PDIR
C
      CALL PGMDIR(PDIR,PDLEN)
      OPEN(4,FILE=PDIR(1:PDLEN)//'adv.line',STATUS='UNKNOWN',
     1     FORM='UNFORMATTED',ERR=9)
      WRITE(4)LNBUF
      CLOSE(4)
9     RETURN
      END
      SUBROUTINE PLDLIN
C
C  PORT: READ ADV.LINE BACK, IF IT IS THERE.  ON A FIRST RUN IT IS NOT, AND
C  THE PROGRAM BUILDS THE TEXT FROM ADV.DATA AND SAVES IT.
C
      IMPLICIT INTEGER*4(A-Z)
      COMMON /PLNCOM/ LNBUF
      DIMENSION LNBUF(9800)
      CHARACTER*260 PDIR
C
      DO 1 I=1,9800
1     LNBUF(I)=0
      CALL PGMDIR(PDIR,PDLEN)
      OPEN(4,FILE=PDIR(1:PDLEN)//'adv.line',STATUS='OLD',
     1     FORM='UNFORMATTED',ERR=9)
      READ(4,ERR=8,END=8)LNBUF
8     CLOSE(4)
9     RETURN
      END
      SUBROUTINE LDCOMN(L,FNAME,CMADDR,CMSIZE)
C
C  PORT: THE COMMON BLOCKS COME BACK FROM A FILE, AS THEY DID - THE SAME
C  ELEVEN ADDRESS RANGES, SET UP BY ADDR AND SIZE IN THE MAIN PROGRAM AND
C  TRANSFERRED BY PXFER (SRC\\PORT\\PSEL.C) INSTEAD OF BY IO AND RTM'S
C  BUFFERIN.  L TRUE MEANS THE FRESH GAME THE WIZARD SAVED (NEWGAME2),
C  L FALSE A SUSPENDED ONE.  A FILE THAT IS NOT THERE IS NOT AN ERROR: ON
C  THE FIRST RUN THERE IS NOTHING TO LOAD AND THE PROGRAM BUILDS THE GAME
C  FROM ADV.DATA INSTEAD.
C
      IMPLICIT INTEGER*4(A-Z)
      LOGICAL L
      DIMENSION FNAME(10),CMADDR(4,11),CMSIZE(11)
      CHARACTER*300 PATH
C
      CALL PPATH(L,FNAME,PATH,PLEN)
      CALL PXFER(PATH(1:PLEN),CMADDR,CMSIZE,11,0,OK)
      RETURN
      END
      SUBROUTINE SVCOMN(L,FNAME,CMADDR,CMSIZE)
C
C  PORT: SEE LDCOMN.  THE WIZARD'S SAVE ALSO WRITES THE MESSAGE TEXT, AS
C  THE ORIGINAL DID WITH SAVLINES.
C
      IMPLICIT INTEGER*4(A-Z)
      LOGICAL L
      LOGICAL BLKLIN
      COMMON /IOSCOM/ TTYI,TTYO,BLKLIN,DBFI
      DIMENSION FNAME(10),CMADDR(4,11),CMSIZE(11)
      CHARACTER*300 PATH
C
      IF(L)CALL SAVLINES
      CALL PPATH(L,FNAME,PATH,PLEN)
      CALL PXFER(PATH(1:PLEN),CMADDR,CMSIZE,11,1,OK)
      IF(OK.EQ.0)RETURN
      WRITE(TTYO,903)
903   FORMAT(' I AM SORRY, BUT I CAN''T CREATE OR FIND YOUR FILE')
      RETURN
      END
      SUBROUTINE PPATH(L,FNAME,PATH,PLEN)
C
C  PORT: WHERE A SAVED GAME LIVES.  THE WIZARD'S FRESH GAME IS NEWGAME2
C  BESIDE THE PROGRAM, AS IT WAS; A PLAYER'S SUSPENDED GAME GOES IN SAVES\\
C  UNDER THE NAME HE TYPED, WHICH REACHES HERE AS TEN WORDS OF ONE
C  CHARACTER EACH (THE ORIGINAL PASSED THEM TO RTM THE SAME WAY).
C
      IMPLICIT INTEGER*4(A-Z)
      LOGICAL L
      DIMENSION FNAME(10)
      CHARACTER*(*) PATH
      CHARACTER*260 PDIR
      CHARACTER*10 NAME
C
      CALL PGMDIR(PDIR,PDLEN)
      IF(.NOT.L)GOTO 10
      PATH=PDIR(1:PDLEN)//'newgame2.sav'
      PLEN=PDLEN+12
      RETURN
C
10    NAME=' '
      K=0
      DO 11 I=1,10
         C=FNAME(I)
         IF(C.GE.97.AND.C.LE.122)C=C-32
         IF(C.LT.48)GOTO 11
         IF(C.GT.57.AND.C.LT.65)GOTO 11
         IF(C.GT.90)GOTO 11
         K=K+1
         NAME(K:K)=CHAR(C)
11    CONTINUE
      IF(K.EQ.0)NAME='OLDGAME'
      IF(K.EQ.0)K=7
      PATH=PDIR(1:PDLEN)//'saves/'//NAME(1:K)//'.sav'
      PLEN=PDLEN+6+K+4
      RETURN
      END
      SUBROUTINE DATIME(D,T)
C
C  PORT: REPLACES THE SEL VERSION, WHICH READ RTM'S DATE STRING STRAIGHT
C  OUT OF ABSOLUTE MEMORY WITH AN INLINE ASSEMBLER BLOCK (LD 6,3ZAB0) AND
C  THE TIME WITH M:TDAY.  D IS DAYS SINCE SATURDAY 1 JULY 1978 AND T IS
C  MINUTES PAST MIDNIGHT, AS THEY WERE.  --day/--time OVERRIDE BOTH.
C
      IMPLICIT INTEGER*4(A-Z)
      COMMON /POPTCM/ NOFIX,FDATE,FTIME,AUTOWZ
      DIMENSION V(8)
C
      CALL DATE_AND_TIME(VALUES=V)
      T=V(5)*60+V(6)
      D=PJULDY(V(1),V(2),V(3))-PJULDY(1978,7,1)
      IF(FDATE.GE.0)D=FDATE
      IF(FTIME.GE.0)T=FTIME
      RETURN
      END
      INTEGER*4 FUNCTION PJULDY(Y,M,DD)
C
C  PORT: DAY NUMBER, SO THAT DATIME CAN COUNT DAYS SINCE 1 JULY 1978.
C
      IMPLICIT INTEGER*4(A-Z)
C
      A=(14-M)/12
      YY=Y+4800-A
      MM=M+12*A-3
      PJULDY=DD+(153*MM+2)/5+365*YY+YY/4-YY/100+YY/400-32045
      RETURN
      END
      SUBROUTINE ABORT
C
C  PORT: WAS M:ABORT (0,'CAVE').
C
      WRITE(6,1)
1     FORMAT(' PORT: THE CAVE HAS COLLAPSED (ABORT)')
      STOP
      END
      SUBROUTINE SHUTDOWN
C
C  PORT: THE SEL VERSION WROTE AN END OF FILE TO THE TERMINAL SO THAT TSS
C  WOULD WAKE UP, AND TOLD THE PLAYER TO TYPE CONTROL-G.
C
      IMPLICIT INTEGER*4(A-Z)
      LOGICAL BLKLIN
      COMMON /IOSCOM/ TTYI,TTYO,BLKLIN,DBFI
C
      WRITE(TTYO,100)
100   FORMAT(///,' *** END OF ADVENTURE ***')
      STOP
      END
