"""The play records ADVENTURE 6.1/9 left behind, made readable.

    games.log    one entry per finished game (ENVLOG / LOG / ENVIRN)
    winner.log   the scoreboard behind "The best player since ..."
    gripe.log    GRIPE entries, each with the room the player stood in
    billbd.dat   the billboard the game shows at the start

    python logs.py     writes ../games-log.tsv and ../logs.txt
"""
import collections, os, re
from pdp10 import ARCH, HERE

RDIR = os.path.dirname(HERE)


def text(name):
    raw = open(os.path.join(ARCH, name), "rb").read()
    return raw.replace(b"\0", b"").decode("ascii").replace("\r\n", "\n").replace("\r", "\n")


HEAD = re.compile(r"^ (.{10}) finished ADVENTURE at +(\d+-\w{3}-\d\d) (\d\d:\d\d) +VER: (\d+\.\d+)/ *(\d+)\.")
PLAY = re.compile(r"^ +Played for +(\d+) min, +(\d+) sec\. +(\S+) +(\S+)")
SCORE = re.compile(r"^ +(-?\d+) points; +(\d+) Turns; +(\d+) Reincarnations; +(\d+) Pauses\.")
NUMS = re.compile(r"^ +((?:\d+/)+) *$")


def games():
    out, cur = [], None
    for line in text("games.log").split("\n"):
        m = HEAD.match(line)
        if m:
            cur = dict(player=m.group(1).strip(), date=m.group(2), time=m.group(3),
                       version="%s/%s" % (m.group(4), m.group(5)), treasures=[], events=[])
            out.append(cur)
            continue
        if cur is None:
            continue
        m = PLAY.match(line)
        if m:
            cur.update(minutes=int(m.group(1)), seconds=int(m.group(2)),
                       ending=m.group(3).rstrip("."), cave=m.group(4).rstrip("."))
            continue
        m = SCORE.match(line)
        if m:
            cur.update(points=int(m.group(1)), turns=int(m.group(2)),
                       reincarnations=int(m.group(3)), pauses=int(m.group(4)))
            continue
        m = NUMS.match(line)
        if m:
            cur["treasures"] += [int(x) for x in m.group(1).split("/") if x]
            continue
        if line.strip():
            # Achievement names are A5/A10 constants followed by "/"; one
            # of them ("WELL ") keeps its trailing blank before the slash.
            cur["events"] += [x.strip() for x in line.strip().split("/") if x.strip()]
    return out


def main():
    gs = games()
    cols = ["date", "time", "player", "version", "minutes", "seconds", "ending", "cave",
            "points", "turns", "reincarnations", "pauses", "treasures", "events"]
    with open(os.path.join(RDIR, "games-log.tsv"), "w", newline="\n") as fp:
        fp.write("\t".join(cols) + "\n")
        for g in gs:
            row = [str(g.get(c, "")) for c in cols[:-2]]
            row.append("/".join(str(t) for t in g["treasures"]))
            row.append("/".join(g["events"]))
            fp.write("\t".join(row) + "\n")

    L = []
    w = L.append
    w("What survives of ADVENTURE 6.1/9's own records, from fungames.7z.")
    w("Generated by tools/logs.py from archive_original/.")
    w("")
    w("== games.log: %d games ==" % len(gs))
    w("From %s to %s; every one of them VER %s." % (
        gs[0]["date"], gs[-1]["date"], ", ".join(sorted(set(g["version"] for g in gs)))))
    w("")
    byp = collections.OrderedDict()
    for g in gs:
        byp.setdefault(g["player"], []).append(g)
    w("%-11s %5s %7s %8s %11s" % ("player", "games", "best", "turns", "last played"))
    for p, l in sorted(byp.items(), key=lambda kv: -len(kv[1])):
        w("%-11s %5d %7d %8d %11s" % (p, len(l), max(x["points"] for x in l),
                                     max(x["turns"] for x in l), l[-1]["date"]))
    w("")
    w("How games ended: " + ", ".join("%s %d" % kv for kv in collections.Counter(g["ending"] for g in gs).most_common()))
    w("Cave status at the end: " + ", ".join("%s %d" % kv for kv in collections.Counter(g["cave"] for g in gs).most_common()))
    w("Most points in one game: %d (%s, %s)." % max((g["points"], g["player"], g["date"]) for g in gs))
    w("Most turns in one game: %d." % max(g["turns"] for g in gs))
    w("")
    w("Each entry's third and fourth lines come from ENVIRN.  The numbers are")
    w("objects for which VALUE -- 6.1/3 calls the same routine OBJVAL(OBJ,")
    w("FULVAL, CURVAL) -- says the player holds the full value: treasures")
    w("scored in full.  The names are events, from a table of thirty that 6.1/3")
    w("carries unchanged.")
    w("")
    tc = collections.Counter(t for g in gs for t in set(g["treasures"]))
    w("Treasure objects scored in full, with the number of games: " +
      ", ".join("%d x%d" % kv for kv in sorted(tc.items())))
    w("")
    ec = collections.Counter(e for g in gs for e in set(g["events"]))
    ep = collections.defaultdict(set)
    for g in gs:
        for e in g["events"]:
            ep[e].add(g["player"])
    order = ["SNK", "DOG", "BLU", "CONCH", "SAFE", "COMBO", "WMP", "CHAIN", "ANVIL", "SWD",
             "PYR", "EMR", "JOSH", "RUG", "CHEST", "QSAND", "VINE", "BUSH", "ROSE", "ELF",
             "WELL", "COURT", "CASTLE KEEP", "COPTER", "CTL RM", "FLOOD", "MINE COLLAPSED",
             "FALCON", "VAULT", "GARDEN"]
    w("Events, in the order of the game's table, with games and players:")
    for e in order:
        w("   %-15s %3d games  %s" % (e, ec.get(e, 0), ", ".join(sorted(ep.get(e, [])))))
    extra = sorted(set(ec) - set(order))
    if extra:
        w("   not in the table: " + ", ".join(extra))
    w("")
    w("== winner.log ==")
    w(text("winner.log").rstrip())
    w("")
    w("== gripe.log ==")
    w(text("gripe.log").replace("\f", "").strip("\n"))
    w("")
    w("== billbd.dat ==")
    w(text("billbd.dat").rstrip())
    w("")
    w("== wizdef.dat ==")
    w(text("wizdef.dat").rstrip())
    w("")
    w("== new-adventure.cmd ==")
    w(text("new-adventure.cmd").rstrip())
    open(os.path.join(RDIR, "logs.txt"), "w", newline="\n").write("\n".join(L) + "\n")
    print("\n".join(L[:60]))


if __name__ == "__main__":
    main()
