#!/bin/sh
# ======================================================================
#  Build the Windows port of Eric Roberts' Wellesley Adventure (665
#  points, newadv.F, last modified March 2010), the way his Makefile did:
#
#    1. allcom.F includes every COMMON block; nm on its object gives the
#       block sizes (common.h), and volatile.fg picks the blocks SAVE
#       writes (volatile.h)
#    2. setup.exe (setup.F + advlib.F) compiles text.dat into the COMMON
#       blocks and dumps them as data.c
#    3. newadv.exe = newadv.F + advlib.F + aparse.F + data.c + csub.c
#    4. newadv.exe and billboard.txt are staged in this folder
#
#  Needs MinGW-w64 gcc and gfortran on PATH (Strawberry Perl has both).
# ======================================================================
set -e
cd "$(dirname "$0")"

ORIG=../src_original/ROBE0665
OUT=.build
FC="gfortran -O2 -std=legacy -ffixed-line-length-none"
# -fcommon: csub.c and common.c declare the COMMON blocks as C arrays that
# must merge with gfortran's common symbols and with data.c's definitions
CC="gcc -O2 -fcommon"

rm -rf "$OUT"
mkdir -p "$OUT"
cp src/*.F src/*.h src/*.c src/nmcom.awk src/volatile.fg "$OUT/"
cp "$ORIG/text.dat" "$ORIG/billboard.txt" "$OUT/"
cd "$OUT"

# 1. COMMON block table.  pcom.h is left out: it is not a COMMON include
#    but a stray list of the params.h names (the allcom.F in the source
#    tree, generated with ls [a-z]*com.h, picked it up and cannot compile).
{
    echo '#include "params.h"'
    printf '\tIMPLICIT INTEGER (A-Z)\n'
    ls -1 [a-z]*com.h | grep -v '^pcom\.h$' | sed 's/.*/#include "&"/'
    printf '\tEND\n'
} > allcom.F
$FC -c allcom.F
nm allcom.o | awk -f nmcom.awk > common.h
grep -F -f volatile.fg common.h > volatile.h
# /HLDCOM/, which volatile.fg misses by a typo ("hdlcom"): csub.c saves it
# too unless --no-fixes (Fix 1)
grep -F 'hldcom_' common.h > holder.h

# 2. the database
$CC -c common.c csub.c
$FC -c setup.F advlib.F
$FC -static -o setup.exe setup.o advlib.o common.o csub.o
./setup.exe > setup.log
#    setup stamps today's date into VERCOM (VERDAT, printed in the opening
#    banner); Roberts' own data.c carries " 3-Mar-10", the day newadv.F was
#    last modified.  Everything else must come out byte for byte the same,
#    and then his file is the one compiled.
novercom() { tr -d '\r' < "$1" | awk '/^char vercom_/ {skip=1} !skip {print} /^};/ {skip=0}'; }
novercom data.c > data_new.txt
novercom "../$ORIG/data.c" > data_orig.txt
if ! cmp -s data_new.txt data_orig.txt; then
    echo "data.c from text.dat differs from Roberts' own beyond the date stamp"
    exit 1
fi
echo "data.c: text.dat compiles to Roberts' own data.c (apart from the date stamp)"
cp "../$ORIG/data.c" data.c

# 3. the game
$CC -c data.c
$FC -c newadv.F aparse.F
$FC -static -o newadv.exe newadv.o advlib.o aparse.o data.o csub.o

cd ..
cp "$OUT/newadv.exe" "$OUT/billboard.txt" .
echo "built newadv.exe; run play.bat"

# 4. the browser edition (V6.4.2, 665 points), which is not this source:
#    archive_original/Browser/Big.js run by the C implementation of Roberts'
#    SVM that lives in the Starter Adventure's port (ROBE0240 ...)
SVM=$(ls -d ../../ROBE0240*/port/src/svm.c 2>/dev/null | head -n 1)
if [ -n "$SVM" ]; then
    {
        echo "/* generated by build.sh from archive_original/Browser/Big.js */"
        echo "const int svm_image[] = {"
        awk 'on && /^\]/ { exit } on { print } !on && /\[/ { on = 1 }' ../archive_original/Browser/Big.js
        echo "};"
        echo "const int svm_image_len = (int)(sizeof svm_image / sizeof svm_image[0]);"
    } > "$OUT/big_image.c"
    gcc -O2 -Wall -Wno-overflow -DPROGNAME='"wellesley"' -o wellesley.exe "$SVM" "$OUT/big_image.c" -lm
    echo "built wellesley.exe; run play-wellesley.bat"
else
    echo "ROBE0240 folder not found - wellesley.exe not built"
fi
