#!/usr/bin/env python3
"""Cut what the port runs out of the NorthStar DOS disk image.

    mkdata.py <101DISK.NSI> <out.h>

The disk is NorthStar DOS 5.1, double density: 350 blocks of 512 bytes; the
directory (16-byte entries: 8-character name, block address, length in
blocks, type, and for a machine-code file its load address) fills the first
four blocks.  Written as C arrays:

  dos[]     the file DOS (6 blocks, at 2000H) - only its data is read
  hybasic[] the file HYBASIC (26 blocks, loaded at 2D00H): North Star BASIC
  dback[]   the file DBACK, the game: tokenised lines up to the end byte
  listing[] DBACK listed as text, to be typed into HYBASIC, which tokenises
            it again (the port checks the result against dback[])

The tokens are listed with HYBASIC's own keyword table (each keyword
follows its token byte there); 9A is a line number, two bytes.
"""

import hashlib
import sys

BLOCK = 512


def entry(d, name):
    for k in range(0, 4 * BLOCK, 16):
        e = d[k:k + 16]
        if e[:8] == name.ljust(8).encode():
            return (e[8] | e[9] << 8, e[10] | e[11] << 8, e[12],
                    e[13] | e[14] << 8)
    raise SystemExit('no %s in the directory' % name)


def keywords(interp):
    i = interp.find(b'\x80LET\x81FOR')
    assert i >= 0
    table = {}
    j = i
    while interp[j] != 0xFF:
        tok = interp[j]
        j += 1
        k = j
        while interp[k] < 0x80:
            k += 1
        table.setdefault(tok, interp[j:k].decode('latin-1'))
        j = k
    return table


def listing(prog, kw):
    lines = []
    p = 0
    while prog[p] != 1:
        n = prog[p]
        body = prog[p + 3:p + n - 1]
        out = ''
        i = 0
        q = False
        while i < len(body):
            c = body[i]
            if c == 0x22:
                q = not q
            if q or c < 0x80:
                out += chr(c)
                i += 1
            elif c == 0x9A:
                out += str(body[i + 1] | body[i + 2] << 8)
                i += 3
            else:
                out += kw[c]
                i += 1
        lines.append('%d%s' % (prog[p + 1] | prog[p + 2] << 8, out))
        p += n
    return lines, prog[:p + 1]


def carray(name, data):
    s = 'static const unsigned char %s[%d] = {\n' % (name, len(data))
    for i in range(0, len(data), 16):
        s += '    ' + ','.join('0x%02x' % c for c in data[i:i + 16]) + ',\n'
    return s + '};\n'


def cstr(t):
    return '"' + t.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    d = open(sys.argv[1], 'rb').read()
    assert len(d) == 179200
    a, n, t, _ = entry(d, 'DOS')
    dos = d[a * BLOCK:(a + n) * BLOCK]
    a, n, t, load = entry(d, 'HYBASIC')
    assert load == 0x2D00, hex(load)
    hy = d[a * BLOCK:(a + n) * BLOCK]
    a, n, t, _ = entry(d, 'DBACK')
    assert (a, n, t & 0x7F) == (140, 20, 2)
    lines, prog = listing(d[a * BLOCK:(a + n) * BLOCK], keywords(hy))
    assert len(lines) == 179
    with open(sys.argv[2], 'w', newline='\n') as h:
        h.write('/* generated by mkdata.py from 101DISK.NSI (md5 %s) */\n'
                % hashlib.md5(d).hexdigest())
        h.write(carray('dos', dos))
        h.write(carray('hybasic', hy))
        h.write('/* DBACK: %d lines, %d bytes, md5 %s */\n'
                % (len(lines), len(prog), hashlib.md5(prog).hexdigest()))
        h.write(carray('dback', prog))
        h.write('static const char *const listing[] = {\n')
        for l in lines:
            h.write('    %s,\n' % cstr(l))
        h.write('    0\n};\n')
    print('mkdata: DOS %d, HYBASIC %d, DBACK %d lines %d bytes'
          % (len(dos), len(hy), len(lines), len(prog)))


if __name__ == '__main__':
    main()
