      SUBROUTINE IOINIT(DUMMY)
C
C  PORT: THE PRIME SET TTYI AND TTYO TO UNIT 1, ITS TERMINAL, AND OPENED THE
C  DATABASE ON UNIT 5 WITH SRCH$$.  HERE THE TERMINAL IS 5 AND 6 AND THE
C  DATABASE - THE FILE THE PRIME CALLED COMMON - SITS BESIDE THE PROGRAM.
C
      IMPLICIT INTEGER (A-Z)
      LOGICAL BLKLIN
      COMMON /IOSCOM/ TTYI,TTYO,BLKLIN,DBFI
      CHARACTER*260 PDIR
C
      TTYI = 5
      TTYO = 6
      DBFI = 1
      CALL PGMDIR(PDIR,PDLEN)
      OPEN(DBFI,FILE=PDIR(1:PDLEN)//'common',STATUS='OLD',ERR=91)
      RETURN
C
91    WRITE(6,92)
92    FORMAT(' PORT: cannot open the database file COMMON')
      STOP
      END
      SUBROUTINE PUNITS
C
C  PORT: THE UNIT NUMBERS, WHICH THE SAVED COMMON BLOCKS WOULD OTHERWISE
C  OVERWRITE WITH THE PRIME'S.
C
      IMPLICIT INTEGER (A-Z)
      LOGICAL BLKLIN
      COMMON /IOSCOM/ TTYI,TTYO,BLKLIN,DBFI
C
      TTYI = 5
      TTYO = 6
      DBFI = 1
      RETURN
      END
      SUBROUTINE DATIME(D,T)
C
C  PORT: THE PRIME'S OWN DOFY$A RETURNED (YEAR-1900).(DAY OF YEAR) AS A REAL
C  AND TIME$A THE TIME IN HOURS; THE ARITHMETIC BELOW IS THE ORIGINAL'S, SO
C  D IS STILL DAYS SINCE 1 JANUARY 1977 (A SATURDAY) AND T MINUTES PAST
C  MIDNIGHT.  --day/--time OVERRIDE BOTH.
C
      IMPLICIT INTEGER (A-Z)
      COMMON /POPTCM/ NOFIX,FDAY,FTIME,AUTOWZ,FSEED
      DIMENSION V(8),MDAYS(12)
      DATA MDAYS/0,31,59,90,120,151,181,212,243,273,304,334/
C
      CALL DATE_AND_TIME(VALUES=V)
      DOY = MDAYS(V(2))+V(3)
      IF(V(2).LE.2)GOTO 10
      IF(MOD(V(1),4).NE.0)GOTO 10
      IF(MOD(V(1),100).EQ.0.AND.MOD(V(1),400).NE.0)GOTO 10
      DOY = DOY+1
10    N = V(1)-1900-77
      D = 1461*(N/4) + 365*MOD(N,4) + DOY
      T = V(5)*60+V(6)
      IF(FDAY.GE.0)D = FDAY
      IF(FTIME.GE.0)T = FTIME
      RETURN
      END
      REAL FUNCTION PRAND(R)
C
C  PORT: PRIMOS'S RAND$A, MEASURED ON THE EMULATOR: R BECOMES
C  MOD(16807*R, 2**31-1) AND THE RESULT IS R/(2**31-1) - LEHMER'S MINIMAL
C  STANDARD.  THE PRODUCT NEEDS MORE THAN 32 BITS, SO IT IS DONE IN 64.
C
      IMPLICIT INTEGER (A-Z)
      INTEGER*8 Q
C
      Q = INT(R,8)*16807_8
      R = INT(MOD(Q,2147483647_8))
      PRAND = REAL(R)/2147483647.0
      RETURN
      END
      SUBROUTINE PRNDI(R)
C
C  PORT: PRIMOS'S RNDI$A SEEDED THE GENERATOR FROM THE CLOCK.  --seed MAKES
C  A RUN REPRODUCIBLE.
C
      IMPLICIT INTEGER (A-Z)
      COMMON /POPTCM/ NOFIX,FDAY,FTIME,AUTOWZ,FSEED
      DIMENSION V(8)
C
      IF(FSEED.GT.0)GOTO 10
      CALL DATE_AND_TIME(VALUES=V)
      R = ((V(5)*60+V(6))*60+V(7))*100+V(8)/10
      IF(R.LE.0)R = 1
      RETURN
10    R = FSEED
      RETURN
      END
      SUBROUTINE LDCOMN(QNAME,NAME,CMADRS,CMSZES)
C
C  PORT: THE ELEVEN COMMON BLOCK RANGES COME BACK FROM A FILE, AS THEY DID,
C  BUT THROUGH PXFER (SRC\\PORT\\PPRIMEC.C) INSTEAD OF PRWF$$.  QNAME TRUE
C  MEANS THE SYSTEM FILE - ADVCOM, THE GAME AS THE WIZARD SET IT UP - AND
C  FALSE A SUSPENDED GAME UNDER THE NAME THE PLAYER GAVE.  A MISSING SYSTEM
C  FILE IS NOT AN ERROR: THE PROGRAM THEN BUILDS THE GAME FROM THE DATABASE.
C
      IMPLICIT INTEGER (A-Z)
      LOGICAL QNAME
      LOGICAL BLKLIN
      COMMON /IOSCOM/ TTYI,TTYO,BLKLIN,DBFI
      DIMENSION CMADRS(4,11),CMSZES(11),NAME(10)
      CHARACTER*300 PATH
C
      CALL PPATH(QNAME,NAME,PATH,PLEN)
      IF(PLEN.EQ.0)GOTO 40
      CALL PXFER(PATH(1:PLEN),CMADRS,CMSZES,11,0,OK)
C  PORT: /IOSCOM/ IS ONE OF THE SAVED BLOCKS, SO THE FILE CARRIES THE UNIT
C  NUMBERS THE PRIME USED - 1 FOR THE TERMINAL AND 5 FOR THE DATABASE.  PUT
C  THE PORT'S BACK; BLKLIN IS GAME STATE AND STAYS AS SAVED.
      IF(OK.EQ.0)CALL PUNITS
      IF(OK.EQ.0.OR.QNAME)RETURN
      WRITE(TTYO,41)
41    FORMAT(' I see no saved game of that name.')
      RETURN
C
40    CALL PPROMPT(NAME)
      GOTO 1
1     CALL PPATH(QNAME,NAME,PATH,PLEN)
      IF(PLEN.EQ.0)RETURN
      CALL PXFER(PATH(1:PLEN),CMADRS,CMSZES,11,0,OK)
      RETURN
      END
      SUBROUTINE SVCOMN(QNAME,NAME,CMADRS,CMSZES)
C
C  PORT: SEE LDCOMN.
C
      IMPLICIT INTEGER (A-Z)
      LOGICAL QNAME
      LOGICAL BLKLIN
      COMMON /IOSCOM/ TTYI,TTYO,BLKLIN,DBFI
      DIMENSION CMADRS(4,11),CMSZES(11),NAME(10)
      CHARACTER*300 PATH
C
      CALL PPATH(QNAME,NAME,PATH,PLEN)
      IF(PLEN.EQ.0)CALL PPROMPT(NAME)
      IF(PLEN.EQ.0)CALL PPATH(QNAME,NAME,PATH,PLEN)
      IF(PLEN.EQ.0)RETURN
      CALL PXFER(PATH(1:PLEN),CMADRS,CMSZES,11,1,OK)
      IF(OK.EQ.0)RETURN
      WRITE(TTYO,41)
41    FORMAT(' I cannot write that file.')
      RETURN
      END
      SUBROUTINE PPROMPT(NAME)
C
C  PORT: THE ORIGINAL ASKED WITH TNOUA, WHICH WROTE WITHOUT A NEWLINE.
C
      IMPLICIT INTEGER (A-Z)
      DIMENSION NAME(10)
      CHARACTER*132 PBUF
      LOGICAL BLKLIN
      COMMON /IOSCOM/ TTYI,TTYO,BLKLIN,DBFI
C
      WRITE(TTYO,1)
1     FORMAT(' What file should I use? ')
      CALL PGETLN(TTYI,PBUF)
      CALL PUNPK(PBUF,NAME,10)
      RETURN
      END
      SUBROUTINE PPATH(QNAME,NAME,PATH,PLEN)
C
C  PORT: WHERE A SAVED GAME LIVES.  THE SYSTEM FILE IS ADVCOM BESIDE THE
C  PROGRAM, AS IT WAS; A PLAYER'S GAME GOES IN SAVES\\ UNDER THE NAME HE
C  TYPED, WHICH REACHES HERE AS TEN WORDS OF ONE CHARACTER EACH.
C
      IMPLICIT INTEGER (A-Z)
      LOGICAL QNAME
      DIMENSION NAME(10)
      CHARACTER*(*) PATH
      CHARACTER*260 PDIR
      CHARACTER*10 FNAME
C
      CALL PGMDIR(PDIR,PDLEN)
      IF(.NOT.QNAME)GOTO 10
      PATH = PDIR(1:PDLEN)//'advcom.dat'
      PLEN = PDLEN+10
      RETURN
C
10    FNAME = ' '
      K = 0
      DO 11 I = 1,10
         C = NAME(I)
         IF(C.GE.97.AND.C.LE.122)C = C-32
         IF(C.LT.48)GOTO 11
         IF(C.GT.57.AND.C.LT.65)GOTO 11
         IF(C.GT.90)GOTO 11
         K = K+1
         FNAME(K:K) = CHAR(C)
11    CONTINUE
      PLEN = 0
      IF(K.EQ.0)RETURN
      PATH = PDIR(1:PDLEN)//'saves/'//FNAME(1:K)//'.sav'
      PLEN = PDLEN+6+K+4
      RETURN
      END
      SUBROUTINE PGETLN(UNIT,BUF)
C
C  PORT: READ ONE RECORD OF TEXT INTO A CHARACTER VARIABLE, BLANK PADDED.
C  THE ORIGINAL READ CHARACTERS STRAIGHT INTO INTEGER ARRAYS WITH "A1"
C  FORMAT; GFORTRAN ACCEPTS THAT BUT READS THE FIELD AS IF IT WERE NUMERIC,
C  SO A COMMA WOULD END IT AND THE REST OF THE LINE WOULD BE LOST.
C
      IMPLICIT INTEGER (A-Z)
      CHARACTER*(*) BUF
C
      BUF = ' '
      READ(UNIT,1,END=9,ERR=9)BUF
1     FORMAT(A)
      RETURN
9     IF(UNIT.EQ.5)STOP
      WRITE(6,10)UNIT
10    FORMAT(' PORT: end of file on unit',I3)
      STOP
      END
      SUBROUTINE PUNPK(STR,IARR,N)
C
C  PORT: ONE CHARACTER PER WORD, AS "A1" DID ON THE PRIME.  THE CHARACTER
C  GOES IN THE LOW-ORDER BYTE, WHICH IS THE BYTE GFORTRAN'S "A1" WRITES BACK
C  OUT; THE PRIME USED THE HIGH-ORDER BYTE.  NOTHING IN THE PROGRAM CARES
C  WHICH, ONLY THAT READING AND WRITING AGREE.
C
      IMPLICIT INTEGER (A-Z)
      CHARACTER*(*) STR
      DIMENSION IARR(N)
C
      DO 10 I = 1,N
10    IARR(I) = ICHAR(STR(I:I))
      RETURN
      END
      SUBROUTINE POPTS
C
C  PORT: COMMAND LINE OPTIONS.  NONE OF THIS IS IN THE ORIGINAL.
C
      IMPLICIT INTEGER (A-Z)
      COMMON /POPTCM/ NOFIX,FDAY,FTIME,AUTOWZ,FSEED
      CHARACTER*80 ARG
C
      NOFIX = 0
      FDAY = -1
      FTIME = -1
      AUTOWZ = 0
      FSEED = 0
C
      N = COMMAND_ARGUMENT_COUNT()
      I = 0
1     I = I+1
      IF(I.GT.N)RETURN
      CALL GET_COMMAND_ARGUMENT(I,ARG)
      IF(ARG.EQ.'--no-fixes')GOTO 10
      IF(ARG.EQ.'--auto')GOTO 11
      IF(ARG.EQ.'--day')GOTO 20
      IF(ARG.EQ.'--time')GOTO 30
      IF(ARG.EQ.'--seed')GOTO 40
      IF(ARG.EQ.'-h'.OR.ARG.EQ.'--help')GOTO 100
      WRITE(6,2)ARG(1:MAX(1,LEN_TRIM(ARG)))
2     FORMAT(' unknown option: ',A)
      GOTO 100
C
10    NOFIX = 1
      GOTO 1
11    AUTOWZ = 1
      GOTO 1
20    I = I+1
      IF(I.GT.N)GOTO 100
      CALL GET_COMMAND_ARGUMENT(I,ARG)
      READ(ARG,*,ERR=100)FDAY
      GOTO 1
30    I = I+1
      IF(I.GT.N)GOTO 100
      CALL GET_COMMAND_ARGUMENT(I,ARG)
      READ(ARG,*,ERR=100)K
      IF(K.LT.0.OR.K.GT.2359)GOTO 100
      FTIME = (K/100)*60+MOD(K,100)
      GOTO 1
40    I = I+1
      IF(I.GT.N)GOTO 100
      CALL GET_COMMAND_ARGUMENT(I,ARG)
      READ(ARG,*,ERR=100)FSEED
      IF(FSEED.LE.0)GOTO 100
      GOTO 1
C
100   WRITE(6,101)
101   FORMAT(
     1' usage: advent [options]',/
     2'   --seed N      start the random number generator at N',/
     3'   --day N       pretend N days have passed since 1 Jan 1977',/
     4'   --time HHMM   pretend the time is HH:MM',/
     5'   --auto        pass the wizard test without being asked',/
     6'   --no-fixes    leave the port fixes out (see README)',/
     7'   -h, --help    this text')
      STOP
      END
      PROGRAM PADVENT
C
C  PORT: THE PRIME'S SEG MADE THE SUBROUTINE CALLED MAIN THE ENTRY POINT OF
C  THE RUN FILE; GFORTRAN NEEDS A MAIN PROGRAM, SO HERE IS ONE.
C
      CALL MAIN
      END
      SUBROUTINE TOOCT(N)
C
C  PORT: PRIMOS'S TOOCT TYPED AN INTEGER*2 AS SIX OCTAL DIGITS WITHOUT A
C  NEWLINE.  PSPEAK PASSES IT AN INTEGER*4 - THE PROGRAM IS COMPILED -INTL -
C  SO ON THE PRIME IT PRINTED THE HIGH-ORDER HALFWORD, WHICH FOR A SMALL
C  NUMBER IS ZERO.  THAT IS WHY THE LEFT-OVER TRACE IN PSPEAK PRINTS
C  "000000 000000" IN FRONT OF EVERY OBJECT ON THE REAL MACHINE, AND WHY IT
C  DOES HERE (SEE ..\README.md).
C
      IMPLICIT INTEGER (A-Z)
C
      H = IAND(ISHFT(N,-16),65535)
      WRITE(6,1)H
1     FORMAT(O6.6,$)
      RETURN
      END
      SUBROUTINE T1OU(N)
C
C  PORT: TYPED ONE CHARACTER FROM AN INTEGER*2.  MEASURED ON THE EMULATOR IT
C  IS THE LOW-ORDER BYTE OF THE HALFWORD - THE SECOND CHARACTER OF A LITERAL
C  - WHICH IS WHY PSPEAK'S T1OU('  ') PRINTS ONE BLANK.
C
      IMPLICIT INTEGER (A-Z)
C
      C = IAND(ISHFT(N,-8),255)
      WRITE(6,1)CHAR(C)
1     FORMAT(A1,$)
      RETURN
      END
      SUBROUTINE TONL
C
C  PORT: TYPED A NEWLINE.
C
      WRITE(6,1)
1     FORMAT(1X)
      RETURN
      END
      SUBROUTINE TODEC(N)
C
C  PORT: TYPED AN INTEGER*2 IN DECIMAL IN SIX COLUMNS, WITHOUT A NEWLINE -
C  AGAIN THE HIGH-ORDER HALFWORD OF WHAT PSPEAK HANDS IT, AND SIGNED.  A
C  NEGATIVE NUMBER PRINTS AS A MINUS SIGN AND THEN THE MAGNITUDE IN FIVE
C  COLUMNS, WHICH IS HOW "-    1" COMES OUT OF THE REAL MACHINE (MEASURED:
C  1, -1, 123, -123, 32767, -32768 GIVE "     1", "-    1", "   123",
C  "-  123", " 32767", "-32768").
C
      IMPLICIT INTEGER (A-Z)
C
      H = IAND(ISHFT(N,-16),65535)
      IF(H.GE.32768)H = H-65536
      IF(H.LT.0)GOTO 10
      WRITE(6,1)H
1     FORMAT(I6,$)
      RETURN
10    WRITE(6,2)-H
2     FORMAT('-',I5,$)
      RETURN
      END
