echo Compiling adv01.ftn
ftn7x adv01.ftn - -
  
echo Compiling adv03.ftn
ftn7x adv03.ftn - -
  
echo Compiling adv05.ftn
ftn7x adv05.ftn - -
  
echo Assembling adv14.asm
macro adv14.asm adv14.lst adv14.rel
  
echo Assembling adv15.asm
macro adv15.asm adv15.lst adv15.rel
  
echo Assembling adv24.asm
macro adv24.asm adv24.lst adv24.rel
  
echo Assembling adv25.asm
macro adv25.asm adv25.lst adv25.rel
  
echo Assembling adv34.asm
macro adv34.asm adv34.lst adv34.rel
  
echo Assembling adv44.asm
macro adv44.asm adv44.lst adv44.rel
  
echo Assembling adv54.asm
macro adv54.asm adv54.lst adv54.rel
  
echo Assembling adv64.asm
macro adv64.asm adv64.lst adv64.rel
  
echo Compiling advf4.ftn
ftn7x advf4.ftn - -
  
echo Compiling advg4.ftn
ftn7x advg4.ftn - -
  
echo Compiling advx2.ftn
ftn7x advx2.ftn - -
  
echo Compiling advy2.ftn
ftn7x advy2.ftn - -
  
echo Assembling iof.asm
macro iof.asm iof.lst iof.rel
  
echo Assembling irp.asm
macro irp.asm irp.lst irp.rel
  
echo Assembling linkret.asm
macro linkret.asm linkret.lst linkret.rel
  
echo Assembling narg.asm
macro narg.asm narg.lst narg.rel
  
echo Assembling susp.asm
macro susp.asm susp.lst susp.rel
  
