#!/bin/sh
# ======================================================================
#  Build wellesley.exe: the browser edition of Eric Roberts' Wellesley
#  Adventure (V6.4.2, 665 points), ../archive_original/Browser/Big.js,
#  run by the C implementation of Roberts' SVM that lives in the
#  Starter Adventure's port (ROBE0240 ...).
#
#  Needs a MinGW-w64 gcc on PATH (Strawberry Perl's works).
# ======================================================================
set -e
cd "$(dirname "$0")"

OUT=.build
mkdir -p "$OUT"

SVM=$(ls -d ../../../ROBE0240*/reconstruction/port/src/svm.c 2>/dev/null | head -n 1)
if [ -z "$SVM" ]; then
    echo "ROBE0240 folder not found - wellesley.exe not built"
    exit 1
fi

# the code array of ../archive_original/Browser/Big.js as C
{
    echo "/* generated by build.sh from archive_original/Browser/Big.js */"
    echo "const int svm_image[] = {"
    awk 'on && /^\]/ { exit } on { print } !on && /\[/ { on = 1 }' ../archive_original/Browser/Big.js
    echo "};"
    echo "const int svm_image_len = (int)(sizeof svm_image / sizeof svm_image[0]);"
} > "$OUT/big_image.c"

gcc -O2 -Wall -Wno-overflow -DPROGNAME='"wellesley"' -o wellesley.exe "$SVM" "$OUT/big_image.c" -lm
echo "built wellesley.exe; start run.bat"
