#!/bin/sh
# ======================================================================
#  Build starter.exe: the SVM machine and WebFor run-time (src/svm.c)
#  with the browser's compiled Starter Adventure (Small.js) embedded.
#
#  Needs a MinGW-w64 gcc on PATH (Strawberry Perl's works).
# ======================================================================
set -e
cd "$(dirname "$0")"

OUT=.build
mkdir -p "$OUT"

# the code array of ../archive_original/Browser/Small.js as C
{
    echo "/* generated by build.sh from archive_original/Browser/Small.js */"
    echo "const int svm_image[] = {"
    awk 'on && /^\]/ { exit } on { print } !on && /\[/ { on = 1 }' ../archive_original/Browser/Small.js
    echo "};"
    echo "const int svm_image_len = (int)(sizeof svm_image / sizeof svm_image[0]);"
} > "$OUT/image.c"

gcc -O2 -Wall -Wno-overflow -o starter.exe src/svm.c "$OUT/image.c" -lm
echo "built starter.exe; start run.bat"
