#!/usr/bin/env python3
"""Write images.c: the Adventure task's two segments and its CAVE data file,
from the copies in ../../src_original, as C arrays.

    python mkimages.py [SRC_ORIGINAL] [OUT.c]
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, '..', '..', 'src_original')
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, 'images.c')

FILES = [
    ('adven_proc', 'ADVEN.proc.bin', 0xB294,
     'procedure segment ADVEN (ID >01) of .GAMES.PROG, loaded at >0000'),
    ('adven_task', 'ADVEN.task.bin', 0x2494,
     'task segment ADVEN (ID >08) of .GAMES.PROG, loaded at >B2A0'),
    ('cave_data', 'CAVE.bin', 28 * 1728,
     'the relative record file .GAMES.FILES.CAVE: 28 records of 1728 bytes'),
]

out = ['/* images.c - generated by mkimages.py from src_original; do not edit */',
       '#include "images.h"', '']
for name, fn, size, what in FILES:
    data = open(os.path.join(SRC, fn), 'rb').read()
    if len(data) != size:
        sys.exit('%s: %d bytes, expected %d' % (fn, len(data), size))
    out.append('/* %s (%s, md5 %s) */' % (what, fn, hashlib.md5(data).hexdigest()))
    out.append('const unsigned char %s[%d] = {' % (name, size))
    for i in range(0, size, 16):
        out.append('    ' + ','.join('0x%02X' % b for b in data[i:i + 16]) + ',')
    out.append('};')
    out.append('')
open(OUT, 'w', newline='\n').write('\n'.join(out))
print('wrote', OUT)
