C     FTN77,L
C     $EMA /TRVCOM/, /VOCCOM/
C 
      SUBROUTINE MAIN
C======================================================================C
C                                                                      C
C REVISION LIST:                                                       C
C                                                                      C
C --DATE-- --BY-- -- D E S C R I P T I O N --                          C
C                                                                      C
C  3/07/81 AW     -ORIGINAL VERSION-                                   C
C 12/12/86 JLA    -FTN77,LINK,MACRO & CI COMPATABLE                    C
C  2/10/87 JLA    -EXPANDED CAVE AND OTHER GOODIES                     C
C  7/13/87 JLA    -FIXED SCORING, DATA BASE & OTHER BUGS               C
C                                                                      C
C======================================================================C
C 
C ADVENTURES
C 
C MODIFIED BY KENT BLACKETT 
C             ENGINEERING SYSTEMS GROUP 
C             DIGITAL EQUIPMENT CORP. 
C             15-JUL-77 
C MODIFIED BY     BOB SUPNIK
C           DISK ENGINEERING
C           21-OCT-77 
C 
C ORIGINAL VERSION WAS FOR DECSYSTEM-10 
C NEXT VERSION WAS FOR FORTRAN IV-PLUS UNDER
C THE IAS OPERATING SYSTEM ON THE PDP-11/70 
C THIS VERSION IS FOR FORTRAN 77 USING AN HP 1000 
C 
C 
C  CURRENT LIMITS:
C 
C     800 TRAVEL OPTIONS (TRAVEL, TRVSIZ).
C     330 VOCABULARY WORDS (KTAB, ATAB, TABSIZ).
C     150 LOCATIONS (LTEXT, STEXT, KEY, COND, ABB, ATLOC, LOCSIZ).
C     100 OBJECTS (PLAC, PLACE, FIXD, FIXED, LINK (TWICE), PTEXT, PROP).
C      35 "ACTION" VERBS (ACTSPK, VRBSIZ).
C     230 RANDOM MESSAGES (RTEXT, RTXSIZ).
C      10 DIFFERENT PLAYER CLASSIFICATIONS (CTEXT, CVAL, CLSMAX). 
C      10 HINTS, LESS 3 (HINTLC, HINTED, HINTS, HNTSIZ).
C      35 MAGIC MESSAGES (MTEXT, MAGSIZ). 
C 
C  THERE ARE ALSO LIMITS WHICH CANNOT BE EXCEEDED DUE TO THE STRUCTURE OF 
C  THE DATABASE.  (E.G., THE VOCABULARY USES N/1000 TO DETERMINE WORD TYPE, 
C  SO THERE CAN'T BE MORE THAN 1000 WORDS.)  THESE UPPER LIMITS ARE:
C 
C     1000 NON-SYNONYMOUS VOCABULARY WORDS
C     300 LOCATIONS 
C     100 OBJECTS 
C 
      IMPLICIT NONE 
C 
C  COMMON VARIABLES 
C 
      include 'alphas.fi'
      include 'arycom.fi'
      include 'ioccom.fi'
      include 'magcom.fi'
      include 'miscom.fi'
      include 'placom.fi'
      include 'trvcom.fi'
      include 'txtcom.fi'
      include 'voccom.fi'
C 
C  LOCAL VARIABLES
C 
      LOGICAL*2 FORCED,PCT,YES,YEA,GUARD,PRIMTIM
      LOGICAL*2 TOTNG,HERE,AT,BITST,DARK,WZDARK 
C 
      INTEGER*2 KLOD,HINT,ITEMP,I,J,K,INDEX 
C     Statement-function dummies handed literal constants.
      INTEGER*4 DUMMY,NPCT,NBIT,PBOTL
      INTEGER*2 LIQ,LIQ2,LIQLC,KLZ1,KLZ2,WD1(8),WD2(8),WD3(8) 
      INTEGER*2 ZZ1,ZZ2,ZZ3,ZZ4,OLDLC2,K2,LL,L,N,IQ,JQ,KQ,LQ,MQ 
      INTEGER*2 LBIT
      INTEGER*2 ATTACK,DTOTAL,STICK,KENT
C 
      CHARACTER*64 FILENAME 
C 
C  EXTERNAL FUNCTIONS 
C 
      INTEGER*2 RNDM,PUT
      REAL*4 TIMER
C 
C  STATEMENT FUNCTIONS
C 
C  TOTNG(OBJ)    = TRUE IF THE OBJ IS BEING CARRIED 
C  HERE(OBJ)      = TRUE IF THE OBJ IS AT "LOC" (OR IS BEING CARRIED) 
C  AT(OBJ)  = TRUE IF ON EITHER SIDE OF TWO-PLACED OBJECT 
C  LIQ(DUMMY)     = OBJECT NUMBER OF LIQUID IN BOTTLE 
C  LIQLOC(LOC)    = OBJECT NUMBER OF LIQUID (IF ANY) AT LOC 
C  BITST(L,N)    = TRUE IF COND(L) HAS BIT N SET (BIT 0 IS UNITS BIT) 
C  FORCED(LOC)    = TRUE IF LOC MOVES WITHOUT ASKING FOR INPUT (COND=2) 
C  DARK(DUMMY)    = TRUE IF LOCATION "LOC" IS DARK
C  PCT(N)       = TRUE N% OF THE TIME (N INTEGER FROM 0 TO 100) 
C 
C  WZDARK SAYS WHETHER THE LOC HE'S LEAVING WAS DARK
C  LMWARN SAYS WHETHER HE'S BEEN WARNED ABOUT LAMP GOING DIM
C  CLOSNG SAYS WHETHER ITS CLOSING TIME YET 
C  PANIC SAYS WHETHER HE'S FOUND OUT HE'S TRAPPED IN THE CAVE 
C  CLOSED SAYS WHETHER WE'RE ALL THE WAY CLOSED 
C  GAVEUP SAYS WHETHER HE EXITED VIA "QUIT" 
C  SCORNG INDICATES TO THE SCORE ROUTINE WHETHER WE'RE DOING A "SCORE" COMMAND
C  DEMO IS TRUE IF THIS IS A PRIME-TIME DEMONSTRATION GAME
C  YEA IS RANDOM YES/NO REPLY 
C 
C 
      TOTNG(KLOD)=(PLACE(KLOD).EQ.-1) 
      HERE(KLOD)=(PLACE(KLOD).EQ.LOC).OR.(TOTNG(KLOD))
      AT(KLOD)=PLACE(KLOD).EQ.LOC.OR.FIXED(KLOD).EQ.LOC 
      LIQ2(PBOTL)=(1-PBOTL)*WATER+(PBOTL/2)*(WATER+OIL) 
      LIQ(DUMMY)=LIQ2(MAX(PROP(BOTTLE),-1-PROP(BOTTLE))) 
      LIQLC(KLOD)=LIQ2((MOD(COND(KLOD)/2*2,8)-5)*MOD(COND(KLOD)/4,2)+1) 
      BITST(LBIT,NBIT)=IAND(COND(LBIT),ISHFT(1_2,NBIT)).NE.0
      FORCED(KLOD)=COND(KLOD).EQ.2
      DARK(DUMMY)=(MOD(COND(LOC),2).EQ.0).AND.(PROP(LAMP).EQ.0.OR.
     &      .NOT.HERE(LAMP))
      PCT(NPCT)=(RNDM(100).LT.NPCT) 
C 
C  DESCRIPTION OF THE DATABASE FORMAT 
C 
C 
C  THE DATA FILE CONTAINS SEVERAL SECTIONS.  EACH BEGINS WITH A LINE CONTAINING 
C  A NUMBER IDENTIFYING THE SECTION, AND ENDS WITH A LINE CONTAINING "-1".
C 
C  SECTION 1: LONG FORM DESCRIPTIONS.  EACH LINE CONTAINS A LOCATION NUMBER,
C     A COMMA, AND A LINE OF TEXT.  THE SET OF (NECESSARILY ADJACENT) LINES 
C     WHOSE NUMBERS ARE X FORM THE LONG DESCRIPTION OF LOCATION X.
C 
C  SECTION 2: SHORT FORM DESCRIPTIONS.  SAME FORMAT AS LONG FORM.  NOT ALL
C     PLACES HAVE SHORT DESCRIPTIONS. 
C 
C  SECTION 3: TRAVEL TABLE.  EACH LINE CONTAINS A LOCATION NUMBER (X), A SECOND 
C     LOCATION NUMBER (Y), AND A LIST OF MOTION NUMBERS (SEE SECTION 4).
C     EACH MOTION REPRESENTS A VERB WHICH WILL GO TO Y IF CURRENTLY AT X. 
C     Y, IN TURN, IS INTERPRETED AS FOLLOWS.  LET M=Y/1000, N=Y MOD 1000. 
C           IF N<=300   IT IS THE LOCATION TO GO TO.
C           IF 300<N<=500     N-300 IS USED IN A COMPUTED GO TO TO
C                             A SECTION OF SPECIAL CODE.
C           IF N>500    MESSAGE N-500 FROM SECTION 6 IS PRINTED,
C                             AND HE STAYS WHEREVER HE IS.
C     MEANWHILE, M SPECIFIES THE CONDITIONS ON THE MOTION.
C           IF M=0            IT'S UNCONDITIONAL. 
C           IF 0<M<100  IT IS DONE WITH M% PROBABILITY. 
C           IF M=100    UNCONDITIONAL, BUT FORBIDDEN TO DWARVES.
C           IF 100<M<=200     HE MUST BE CARRYING OBJECT M-100. 
C           IF 200<M<=300     MUST BE CARRYING OR IN SAME ROOM AS M-200.
C           IF 300<M<=400     PROP(M MOD 100) MUST *NOT* BE 0.
C           IF 400<M<=500     PROP(M MOD 100) MUST *NOT* BE 1.
C           IF 500<M<=600     PROP(M MOD 100) MUST *NOT* BE 2, ETC. 
C     IF THE CONDITION (IF ANY) IS NOT MET, THEN THE NEXT *DIFFERENT* 
C     "DESTINATION" VALUE IS USED (UNLESS IT FAILS TO MEET *ITS* CONDITIONS,
C     IN WHICH CASE THE NEXT IS FOUND, ETC.).  TYPICALLY, THE NEXT DEST WILL
C     BE FOR ONE OF THE SAME VERBS, SO THAT ITS ONLY USE IS AS THE ALTERNATE
C     DESTINATION FOR THOSE VERBS.  FOR INSTANCE: 
C           15    110    22     29    31    34    35    23    43
C           15      0    14     29
C     THIS SAYS THAT, FROM LOC 15, ANY OF THE VERBS 29, 31, ETC., WILL TAKE 
C     HIM TO 22 IF HE'S CARRYING OBJECT 10, AND OTHERWISE WILL GO TO 14.
C           11    303      8      49
C           11      0      9      50
C     THIS SAYS THAT, FROM 11, 49 TAKES HIM TO 8 UNLESS PROP(3)=0, IN WHICH 
C     CASE HE GOES TO 9.  VERB 50 TAKES HIM TO 9 REGARDLESS OF PROP(3). 
C 
C  SECTION 4: VOCABULARY.  EACH LINE CONTAINS A NUMBER (N), A TAB, AND A
C     FIVE-LETTER WORD.  CALL M=N/1000.  IF M=0, THEN THE WORD IS A MOTION
C     VERB FOR USE IN TRAVELLING (SEE SECTION 3).  ELSE, IF M=1, THE WORD IS
C     AN OBJECT.  ELSE, IF M=2, THE WORD IS AN ACTION VERB (SUCH AS "CARRY" 
C     OR "ATTACK").  ELSE, IF M=3, THE WORD IS A SPECIAL CASE VERB (SUCH AS 
C     "DIG") AND N MOD 1000 IS AN INDEX INTO SECTION 6.  OBJECTS FROM 50 TO 
C     (CURRENTLY, ANYWAY) 79 ARE CONSIDERED TREASURES (FOR PIRATE, CLOSEOUT). 
C 
C  SECTION 5: OBJECT DESCRIPTIONS.  EACH LINE CONTAINS A NUMBER (N), A TAB, 
C     AND A MESSAGE.  IF N IS FROM 1 TO 100, THE MESSAGE IS THE "INVENTORY" 
C     MESSAGE FOR OBJECT N.  OTHERWISE, N SHOULD BE 000, 100, 200, ETC., AND
C     THE MESSAGE SHOULD BE THE DESCRIPTION OF THE PRECEDING OBJECT WHEN ITS
C     PROP VALUE IS N/100.  THE N/100 IS USED ONLY TO DISTINGUISH MULTIPLE
C     MESSAGES FROM MULTI-LINE MESSAGES; THE PROP INFO ACTUALLY REQUIRES ALL
C     MESSAGES FOR AN OBJECT TO BE PRESENT AND CONSECUTIVE.  PROPERTIES WHICH 
C     PRODUCE NO MESSAGE SHOULD BE GIVEN THE MESSAGE ">$<". 
C 
C  SECTION 6: ARBITRARY MESSAGES.  SAME FORMAT AS SECTIONS 1, 2, AND 5, EXCEPT
C     THE NUMBERS BEAR NO RELATION TO ANYTHING (EXCEPT FOR SPECIAL VERBS
C     IN SECTION 4).
C 
C  SECTION 7: OBJECT LOCATIONS.  EACH LINE CONTAINS AN OBJECT NUMBER AND ITS
C     INITIAL LOCATION (ZERO (OR OMITTED) IF NONE).  IF THE OBJECT IS 
C     IMMOVABLE, THE LOCATION IS FOLLOWED BY A "-1".  IF IT HAS TWO LOCATIONS 
C     (E.G. THE GRATE) THE FIRST LOCATION IS FOLLOWED WITH THE SECOND, AND
C     THE OBJECT IS ASSUMED TO BE IMMOVABLE.
C 
C  SECTION 8: ACTION DEFAULTS.  EACH LINE CONTAINS AN "ACTION-VERB" NUMBER AND
C     THE INDEX (IN SECTION 6) OF THE DEFAULT MESSAGE FOR THE VERB. 
C 
C  SECTION 9: LIQUID ASSETS, ETC.  EACH LINE CONTAINS A NUMBER (N) AND UP TO 20 
C     LOCATION NUMBERS.  BIT N (WHERE 0 IS THE UNITS BIT) IS SET IN COND(LOC) 
C     FOR EACH LOC GIVEN.  THE COND BITS CURRENTLY ASSIGNED ARE:
C           0     LIGHT 
C           1     IF BIT 2 IS ON: ON FOR OIL, OFF FOR WATER 
C           2     LIQUID ASSET, SEE BIT 1 
C           3     PIRATE DOESN'T GO HERE UNLESS FOLLOWING PLAYER
C     OTHER BITS ARE USED TO INDICATE AREAS OF INTEREST TO "HINT" ROUTINES: 
C           4     TRYING TO GET INTO CAVE 
C           5     TRYING TO CATCH BIRD
C           6     TRYING TO DEAL WITH SNAKE 
C           7     LOST IN MAZE
C           8     PONDERING DARK ROOM 
C           9     AT WITT'S END 
C     COND(LOC) IS SET TO 2, OVERRIDING ALL OTHER BITS, IF LOC HAS FORCED 
C     MOTION. 
C 
C  SECTION 10: CLASS MESSAGES.  EACH LINE CONTAINS A NUMBER (N), A TAB, AND A 
C     MESSAGE DESCRIBING A CLASSIFICATION OF PLAYER.  THE SCORING SECTION 
C     SELECTS THE APPROPRIATE MESSAGE, WHERE EACH MESSAGE IS CONSIDERED TO
C     APPLY TO PLAYERS WHOSE SCORES ARE HIGHER THAN THE PREVIOUS N BUT NOT
C     HIGHER THAN THIS N.  NOTE THAT THESE SCORES PROBABLY CHANGE WITH EVERY
C     MODIFICATION (AND PARTICULARLY EXPANSION) OF THE PROGRAM. 
C 
C  SECTION 11: HINTS.  EACH LINE CONTAINS A HINT NUMBER (CORRESPONDING TO A 
C     COND BIT, SEE SECTION 9), THE NUMBER OF TURNS HE MUST BE AT THE RIGHT 
C     LOC(S) BEFORE TRIGGERING THE HINT, THE POINTS DEDUCTED FOR TAKING THE 
C     HINT, THE MESSAGE NUMBER (SECTION 6) OF THE QUESTION, AND THE MESSAGE 
C     NUMBER OF THE HINT.  THESE VALUES ARE STASHED IN THE "HINTS" ARRAY. 
C     HNTMAX IS SET TO THE MAX HINT NUMBER (<= HNTSIZ).  NUMBERS 1-3 ARE
C     UNUSABLE SINCE COND BITS ARE OTHERWISE ASSIGNED, SO 2 IS USED TO
C     REMEMBER IF HE'S READ THE CLUE IN THE REPOSITORY, AND 3 IS USED TO
C     REMEMBER WHETHER HE ASKED FOR INSTRUCTIONS (GETS MORE TURNS, BUT LOSES
C     POINTS).
C 
C  SECTION 12: MAGIC MESSAGES. IDENTICAL TO SECTION 6 EXCEPT PUT IN A SEPARATE
C     SECTION FOR EASIER REFERENCE.  MAGIC MESSAGES ARE USED BY THE STARTUP,
C     MAINTENANCE MODE, AND RELATED ROUTINES. 
C 
C  SECTION 0: END OF DATABASE.
C 
C=====================================================================
C 
C  START-UP, DWARF STUFF
C 
      CALL CLEAR(CRT) 
      IF(RESTART) THEN
        CALL RSPEK(207) 
        GO TO 1310
      ENDIF 
 1000 I=RNDM(1) 
      HINTED(3)=YES(65,1,0) 
      NEWLOC=1
      LOC=NEWLOC
C 
C  NOTE: LIMIT SIZE SHOULD BE CHANGED WHEN CAVE IS EXPANDED.
C 
      IF(HINTED(3)) THEN
        LIMIT=1200
      ELSE
        LIMIT=400 
      ENDIF 
C 
C  CAN'T LEAVE CAVE ONCE IT'S CLOSING (EXCEPT BY MAIN OFFICE).
C 
 1010 IF(LOC.LT.1 .OR. LOC.GT.LOCSIZ) CALL BUG(29)
      IF(NEWLOC.GE.9.OR.NEWLOC.EQ.0.OR..NOT.CLOSNG) GO TO 1020
      CALL RSPEK(130) 
      NEWLOC=LOC
      IF(.NOT.PANIC) CLOCK2=15
      PANIC=.TRUE.
C 
C  SEE IF A DWARF HAS SEEN HIM AND HAS COME FROM WHERE HE WANTS TO GO.  IF SO,
C  THE DWARF'S BLOCKING HIS WAY.  IF COMING FROM PLACE FORBIDDEN TO PIRATE
C  (DWARVES ROOTED IN PLACE) LET HIM GET OUT (AND ATTACKED).
C 
 1020 IF(NEWLOC.EQ.LOC.OR.FORCED(LOC).OR.BITST(LOC,3)) GO TO 1040 
C 
      DO I=1,5
        IF(ODLOC(I).EQ.NEWLOC .AND. DSEEN(I)) GO TO 1030
      ENDDO 
      GO TO 1040
C 
 1030 NEWLOC=LOC
      CALL RSPEK(2) 
 1040 LOC=NEWLOC
C 
D     WRITE(CRT,3000) LOC,NEWLOC,OLDLOC,
D    &   CLSSES,(CVAL(I),I=1,6) 
D3000 FORMAT("MAIN: LOC",I6,"  NEWLOC",I6,"  OLDLOC",I6,"  CLSSES",I6/
D    &       "      CVAL",6I6)
C 
C  DWARF STUFF.  SEE EARLIER COMMENTS FOR DESCRIPTION OF VARIABLES.  REMEMBER 
C  SIXTH DWARF IS PIRATE AND IS THUS VERY DIFFERENT EXCEPT FOR MOTION RULES.
C 
C  FIRST OFF, DON'T LET THE DWARVES FOLLOW HIM INTO A PIT OR A WALL.  ACTIVATE
C  THE WHOLE MESS THE FIRST TIME HE GETS AS FAR AS THE HALL OF MISTS (LOC 15).
C  IF NEWLOC IS FORBIDDEN TO PIRATE (IN PARTICULAR, IF IT'S BEYOND THE TROLL
C  BRIDGE), BYPASS DWARF STUFF.  THAT WAY PIRATE CAN'T STEAL RETURN TOLL, AND 
C  DWARVES CAN'T MEET THE BEAR.  ALSO MEANS DWARVES WON'T FOLLOW HIM INTO DEAD
C  END IN MAZE, BUT C'EST LA VIE.  THEY'LL WAIT FOR HIM OUTSIDE THE DEAD END. 
C 
      IF(LOC.EQ.0.OR.FORCED(LOC).OR.BITST(NEWLOC,3)) GO TO 1230 
      IF(DFLAG.NE.0) GO TO 1050 
      IF(LOC.GE.15) DFLAG=1 
      GO TO 1230
C 
C  WHEN WE ENCOUNTER THE FIRST DWARF, WE KILL 0, 1, OR 2 OF THE 5 DWARVES.
C  IF ANY OF THE SURVIVORS IS AT LOC, REPLACE HIM WITH THE ALTERNATE. 
C 
 1050 IF(DFLAG.NE.1) GO TO 1060 
      IF(LOC.LT.15.OR.PCT(95)) GO TO 1230 
      DFLAG=2 
      DO I=1,2
        J=1+RNDM(5) 
        IF(PCT(50)) DLOC(J)=0 
      ENDDO 
      DO I=1,5
        IF(DLOC(I).EQ.LOC) DLOC(I)=DALTLC 
        ODLOC(I)=DLOC(I)
      ENDDO 
      CALL RSPEK(3) 
      CALL DROP(AXE,LOC)
      GO TO 1230
C 
C  THINGS ARE IN FULL SWING.  MOVE EACH DWARF AT RANDOM, EXCEPT IF HE'S SEEN US 
C  HE STICKS WITH US.  DWARVES NEVER GO TO LOCS <15.  IF WANDERING AT RANDOM, 
C  THEY DON'T BACK UP UNLESS THERE'S NO ALTERNATIVE.  IF THEY DON'T HAVE TO 
C  MOVE, THEY ATTACK.  AND, OF COURSE, DEAD DWARVES DON'T DO MUCH OF ANYTHING.
C 
 1060 DTOTAL=0
      ATTACK=0
      STICK=0 
      DO 1160 I=1,6 
        IF(DLOC(I).EQ.0) GO TO 1160 
        J=1 
        KK=DLOC(I)
        KK=KEY(KK)
        IF(KK.EQ.0) GO TO 1090
 1070   NEWLOC=TRVLOC(KK) 
C 
C  THE FOLLOWING LINE WAS ADDED TO KEEP THE GAME FROM BLOWING UP
C 
        IF(NEWLOC.LT.1) GO TO 1090
        IF(NEWLOC.GT.300.OR.NEWLOC.LT.15.OR.NEWLOC.EQ.ODLOC(I)
     &      .OR.(J.GT.1.AND.NEWLOC.EQ.TK(J-1)).OR.J.GE.20 
     &      .OR.NEWLOC.EQ.DLOC(I).OR.FORCED(NEWLOC) 
     &      .OR.(I.EQ.6.AND.BITST(NEWLOC,3))
     &      .OR.TRVCON(KK).EQ.100) GO TO 1080 
        TK(J)=NEWLOC
        J=J+1 
 1080   KK=KK+1 
        IF(TRAVEL(KK-1).GE.0) GO TO 1070
 1090   TK(J)=ODLOC(I)
        IF(J.GE.2) J=J-1
        J=1+RNDM(J) 
        ODLOC(I)=DLOC(I)
        DLOC(I)=TK(J) 
        DSEEN(I)=(DSEEN(I).AND.LOC.GE.15) 
     &      .OR.(DLOC(I).EQ.LOC.OR.ODLOC(I).EQ.LOC) 
        IF(.NOT.DSEEN(I)) GO TO 1160
        DLOC(I)=LOC 
        IF(I.NE.6) GO TO 1150 
C 
C  THE PIRATE'S SPOTTED HIM.  HE LEAVES HIM ALONE ONCE WE'VE FOUND CHEST. 
C  K COUNTS IF A TREASURE IS HERE.  IF NOT, AND TALLY=TALLY2 PLUS ONE FOR 
C  AN UNSEEN CHEST, LET THE PIRATE BE SPOTTED.
C 
        IF(LOC.EQ.CHLOC.OR.PROP(CHEST).GE.0) GO TO 1160 
        K=0 
        DO 1100 J=50,MAXTRS 
C 
C  PIRATE WON'T TAKE PYRAMID FROM PLOVER ROOM OR DARK ROOM (TOO EASY!). 
C 
        IF(J.EQ.PYRAM.AND.(LOC.EQ.PLAC(PYRAM) 
     &        .OR.LOC.EQ.PLAC(EMRALD))) GO TO 1100
        IF(TOTNG(J)) GO TO 1110 
 1100   IF(HERE(J))K=1
        IF(TALLY.EQ.TALLY2+1.AND.K.EQ.0.AND.PLACE(CHEST).EQ.0 
     &        .AND.HERE(LAMP).AND.PROP(LAMP).EQ.1) GO TO 1140 
        IF(ODLOC(6).NE.DLOC(6).AND.PCT(20))CALL RSPEK(127)
        GO TO 1160
C 
 1110 CALL RSPEK(128) 
C 
C  DON'T STEAL CHEST BACK FROM TROLL! 
C 
        IF(PLACE(MESSAG).EQ.0)CALL MOVE(CHEST,CHLOC)
        CALL MOVE(MESSAG,CHLOC2)
        DO 1120 J=50,MAXTRS 
          IF(J.EQ.PYRAM.AND.(LOC.EQ.PLAC(PYRAM) 
     &          .OR.LOC.EQ.PLAC(EMRALD))) GO TO 1120
          IF(AT(J).AND.FIXED(J).EQ.0)CALL CARRY(J,LOC)
          IF(TOTNG(J))CALL DROP(J,CHLOC)
 1120   CONTINUE
 1130   DLOC(6)=CHLOC 
        ODLOC(6)=CHLOC
        DSEEN(6)=.FALSE.
        GO TO 1160
C 
 1140   CALL RSPEK(186) 
        CALL MOVE(CHEST,CHLOC)
        CALL MOVE(MESSAG,CHLOC2)
        GO TO 1130
C 
C  THIS THREATENING LITTLE DWARF IS IN THE ROOM WITH HIM! 
C 
 1150   DTOTAL=DTOTAL+1 
        IF(ODLOC(I).NE.DLOC(I)) GO TO 1160
        ATTACK=ATTACK+1 
        IF(KNFLOC.GE.0)KNFLOC=LOC 
        IF(RNDM(1000).LT.95*(DFLAG-2))STICK=STICK+1 
 1160 CONTINUE
C 
C  NOW WE KNOW WHAT'S HAPPENING.  LET'S TELL THE POOR SUCKER ABOUT IT.
C 
      IF(DTOTAL.EQ.0) GO TO 1230
      IF(DTOTAL.EQ.1) THEN
        CALL RSPEK(4) 
      ELSE
        WRITE(CRT,1170) DTOTAL
      ENDIF 
 1170 FORMAT(/"There are ",I1," threatening little dwarves in the"
     &      ," room with you.") 
      IF(ATTACK.EQ.0) GO TO 1230
      IF(DFLAG.EQ.2) DFLAG=3
      IF(ATTACK.EQ.1) GO TO 1220
      WRITE(CRT,1180) ATTACK
 1180 FORMAT(/I1," of them throw knives at you!") 
      K=6 
 1190 IF(STICK.GT.1) THEN 
        WRITE(CRT,1200) STICK 
      ELSE
        CALL RSPEK(K+STICK) 
        IF(STICK.EQ.0) GO TO 1230 
      ENDIF 
 1200 FORMAT(/I1," of them get you!") 
 1210 OLDLC2=LOC
      GO TO 1960
C 
 1220 CALL RSPEK(5) 
      K=52
      GO TO 1190
C 
C  DESCRIBE THE CURRENT LOCATION AND (MAYBE) GET NEXT COMMAND.
C 
C  PRINT TEXT FOR CURRENT LOC.
C 
 1230 IF(LOC.EQ.0) GO TO 1960 
      KK=STEXT(LOC) 
      KENT=0
      IF (ABBNUM.NE.0) KENT=MOD(ABB(LOC),ABBNUM)
      IF (KENT.EQ.0.OR.KK.EQ.0) KK=LTEXT(LOC) 
      IF(FORCED(LOC).OR..NOT.DARK(0)) GO TO 1240
      IF(WZDARK.AND.PCT(35)) GO TO 1950 
      KK=RTEXT(16)
 1240 IF(TOTNG(BEAR)) CALL RSPEK(141) 
      CALL SPEK(KK) 
      K=1 
      IF(FORCED(LOC)) GO TO 1680
      IF(LOC.EQ.33.AND.PCT(25).AND..NOT.CLOSNG) CALL RSPEK(8) 
C 
C  PRINT OUT DESCRIPTIONS OF OBJECTS AT THIS LOCATION.  IF NOT CLOSING AND
C  PROPERTY VALUE IS NEGATIVE, TALLY OFF ANOTHER TREASURE.  RUG IS SPECIAL
C  CASE; ONCE SEEN, ITS PROP IS 1 (DRAGON ON IT) TILL DRAGON IS KILLED. 
C  SIMILARLY FOR CHAIN; PROP IS INITIALLY 1 (LOCKED TO BEAR).  THESE HACKS
C  ARE BECAUSE PROP=0 IS NEEDED TO GET FULL SCORE.
C 
      IF(DARK(0)) GO TO 1310
      ABB(LOC)=ABB(LOC)+1 
      I=ATLOC(LOC)
 1250 IF(I.EQ.0) GO TO 1310 
      OBJ=I 
      IF(OBJ.GT.100) OBJ=OBJ-100
      IF(OBJ.EQ.STEPS.AND.TOTNG(NUGGET)) GO TO 1270 
      IF(PROP(OBJ).GE.0) GO TO 1260 
      IF(CLOSED) GO TO 1270 
      PROP(OBJ)=0 
      IF(OBJ.EQ.RUG.OR.OBJ.EQ.CHAIN) PROP(OBJ)=1
      TALLY=TALLY-1 
C 
C  IF REMAINING TREASURES TOO ELUSIVE, ZAP HIS LAMP.
C 
      IF(TALLY.EQ.TALLY2.AND.TALLY.NE.0) LIMIT=MIN(35,LIMIT) 
 1260 KK=PROP(OBJ)
C 
D     WRITE(CRT,6543) LOC,OBJ,PROP(OBJ),ATLOC(LOC),ABB(LOC) 
D6543 FORMAT("LOC,OBJ,PROP(OBJ),ATLOC(LOC),ABB(LOC)",/,5I6) 
C 
      IF(OBJ.EQ.STEPS.AND.LOC.EQ.FIXED(STEPS)) KK=1 
      CALL PSPEK(OBJ,KK)
      IF(LOC.EQ.149 .AND. OBJ.EQ.CHARO) THEN
        IF(PROP(CHARO).EQ.2) PROP(CHARO)=3
        IF(PROP(CHARO).EQ.1) PROP(CHARO)=2
      ENDIF 
 1270 I=LINK(I) 
      GO TO 1250
C 
 1280 K=54
 1290 SPK=K 
 1300 CALL RSPEK(SPK) 
C 
 1310 VERB=0
      OBJ=0 
      IF(LOC.LT.1 .OR. LOC.GT.LOCSIZ) CALL BUG(30)
C 
C  CHECK TO SEE IF HE IS AT THE STATUE WITH IT FACING HIM 
C  OR BEING TRAPPED IN ALCOVE, MAGIC, CHARON LOOP.
C 
      IF(LOC.EQ.147) THEN 
        IF(PROP(STATU).EQ.2) THEN 
          LOC=0 
          GO TO 1960
        ENDIF 
        IF(PROP(CHAMPA).EQ.1 .AND. PCT(10)) THEN
          CALL RSPEK(222) 
          PROP(STATU)=2 
        ENDIF 
        IF(PROP(STATU).EQ.0 .AND. TOTNG(ROD)) PROP(STATU)=1 
        IF(PROP(STATU).EQ.1 .AND. .NOT.TOTNG(ROD)) PROP(STATU)=0
      ENDIF 
C 
C  CHECK IF THIS LOC IS ELIGIBLE FOR ANY HINTS.  IF BEEN HERE LONG ENOUGH,
C  BRANCH TO HELP SECTION (ON LATER PAGE).  HINTS ALL COME BACK HERE EVENTUALLY 
C  TO FINISH THE LOOP.  IGNORE "HINTS" < 4 (SPECIAL STUFF, SEE DATABASE NOTES). 
C 
 1320 DO HINT=4,HNTMAX
        IF(.NOT.HINTED(HINT)) THEN
          IF(.NOT.BITST(LOC,INT(HINT))) HINTLC(HINT)=-1
          HINTLC(HINT)=HINTLC(HINT)+1 
          IF(HINTLC(HINT).GE.HINTS(HINT,1)) THEN
C 
C  HINTS
C 
C  COME HERE IT'S BEEN LONG ENOUGH AT REQUIRED LOC(S) FOR SOME UNUSED HINT. 
C  HINT NUMBER IS IN VARIABLE "HINT".  BRANCH TO QUICK TEST FOR ADDITIONAL
C  CONDITIONS, THEN COME BACK TO DO NEAT STUFF.  GO TO 1340 IF CONDITIONS ARE 
C  MET AND WE WANT TO OFFER THE HINT.  GO TO 1360 TO CLEAR HINTLC BACK TO 
C  ZERO.  GO TO 1370 TO TAKE NO ACTION YET. 
C 
            GO TO (1380 ,1390 ,1400 ,1410 ,1420 ,1340, 1340) (HINT-3) 
C                  CAVE  BIRD  SNAKE MAZE  DARK  WITT  HEIR 
 1330       WRITE(CRT,1335) HINT
 1335       FORMAT("HINT:",I6)
            CALL BUG(27)
C 
 1340       HINTLC(HINT)=0
            IF(.NOT.YES(HINTS(HINT,3),0,54)) GO TO 1440 
            WRITE(CRT,1350 ) HINTS(HINT,2)
 1350       FORMAT(/"I am prepared to give you a hint,",
     &             " but it will cost you",I2," points.") 
            HINTED(HINT)=YES(175,HINTS(HINT,4),54)
            IF(HINTED(HINT).AND.LIMIT.GT.30)
     &         LIMIT=LIMIT+30*HINTS(HINT,2) 
 1360       HINTLC(HINT)=0
 1370       GO TO 1440
C 
C  NOW FOR THE QUICK TESTS.  SEE DATABASE DESCRIPTION FOR ONE-LINE NOTES. 
C 
 1380       IF(PROP(GRATE).EQ.0.AND..NOT.HERE(KEYS)) GO TO 1340 
            GO TO 1360
C 
 1390       IF(HERE(BIRD).AND.TOTNG(ROD).AND.OBJ.EQ.BIRD) GO TO 1340
            GO TO 1370
C 
 1400       IF(HERE(SNAKE).AND..NOT.HERE(BIRD)) GO TO 1340
            GO TO 1360
C 
 1410       IF(ATLOC(LOC).EQ.0.AND.ATLOC(OLDLOC).EQ.0 
     &       .AND.ATLOC(OLDLC2).EQ.0.AND.HOLDNG.GT.1) GO TO 1340
            GO TO 1360
C 
 1420       IF(PROP(EMRALD).NE.-1.AND.PROP(PYRAM).EQ.-1) GO TO 1340 
            GO TO 1360
C 
 1440     ENDIF 
        ENDIF 
      ENDDO 
C 
C  KICK THE RANDOM NUMBER GENERATOR JUST TO ADD VARIETY TO THE CHASE.  ALSO,
C  IF CLOSING TIME, CHECK FOR ANY OBJECTS BEING TOTED WITH PROP < 0 AND SET 
C  THE PROP TO -1-PROP.  THIS WAY OBJECTS WON'T BE DESCRIBED UNTIL THEY'VE
C  BEEN PICKED UP AND PUT DOWN SEPARATE FROM THEIR RESPECTIVE PILES.  DON'T 
C  TICK CLOCK1 UNLESS WELL INTO CAVE (AND NOT AT Y2). 
C 
      IF(CLOSED) THEN 
        IF(PROP(OYSTER).LT.0.AND.TOTNG(OYSTER)) 
     &      CALL PSPEK(OYSTER,1)
        DO I=1,100
          IF(TOTNG(I).AND.PROP(I).LT.0) PROP(I)=-1-PROP(I)
        ENDDO 
      ENDIF 
      WZDARK=DARK(0)
      IF(KNFLOC.GT.0.AND.KNFLOC.NE.LOC) KNFLOC=0
      I=RNDM(1) 
C 
C  ASK FOR A COMMAND AND ECHO BACK INTERPRETATION
C
      CALL GETIN(WD1,WD2,WD3)
      CALL ECHO(WD1,WD2,WD3)
C
D     WRITE(CRT,3010) LOC,VERB,WD1,WD2,WD3
D3010 FORMAT("LOC=",I6,"   VERB=",I6,3(2X,8A2))
C
C  EVERY INPUT, CHECK "FOOBAR" FLAG.  IF ZERO, NOTHING'S GOING ON.  IF POS,
C  MAKE NEG.  IF NEG, HE SKIPPED A WORD, SO MAKE IT ZERO. CHECK TO SEE
C  DEMO GAME IS OVER. ALSO CHECK FOR PRIME TIME OR GAME TOO LONG.
C
 1450 CONTINUE
      FOOBAR=MIN(0,-FOOBAR)
      TURNS=TURNS+1
      IF(DEMO .AND. TURNS.GE.SHORT) THEN
        CALL MSPEK(1)
        GO TO 2990
      ENDIF
      IF(DEMO .OR. WIZARD) GO TO 1455
C     IF(TIMER(1)/60.GT.AMOUNT) THEN  !TIMER & AMOUNT BUGGY. SKIP -DWH
C       CALL MSPEK(1)
C       GO TO 1940
C     ENDIF
      IF(PRIMTIM(0)) THEN
        CALL MSPEK(2)
        CALL HOURS
        GO TO 1940
      ENDIF
C
 1455 IF(TALLY.EQ.0.AND.LOC.GE.15.AND.LOC.NE.33) CLOCK1=CLOCK1-1
      IF(CLOCK1.EQ.0) GO TO 1980
      IF(CLOCK1.LT.0) CLOCK2=CLOCK2-1
      IF(CLOCK2.EQ.0) GO TO 1990
      IF(PROP(LAMP).EQ.1) LIMIT=LIMIT-1
      IF(LIMIT.LE.30.AND.HERE(BATTER).AND.PROP(BATTER).EQ.0
     &      .AND.HERE(LAMP)) GO TO 2000
      IF(LIMIT.EQ.0) GO TO 2020
      IF(LIMIT.LT.0.AND.LOC.LE.8) GO TO 2780
      IF(LIMIT.LE.30) GO TO 2010
 1460 K=43
      IF(LIQLC(LOC).EQ.WATER) K=70
C 
C  DO PRELIMINARY ANALYSIS OF SENTENCE TO FIND CERTAIN SPECIAL
C  CASES, VIZ,
C 
C  ENTER <WATER,STREAM> 
C  ENTER <LOCATION> 
C  <WATER,OIL> <PLANT,DOOR> 
C 
      CALL VOCAB(WD1,-1,I,INDEX)
      CALL VOCAB(WD2,-1,J,INDEX)
      IF(WD1(1).NE.CEN .OR. WD1(2).NE.CTE) GO TO 1470 
      IF(J .EQ. (WATER+1000)
     &      .OR. J .EQ. STREAM) GO TO 1290
      IF(WD2(1) .NE. 0) GO TO 1510
 1470 IF((I .NE. (WATER+1000) .AND. I .NE. (OIL+1000))
     &      .OR. (J .NE. (PLANT+1000) .AND. J .NE. (DOOR+1000)))
     &      GO TO 1480
      WD2(1)=CPO
      WD2(2)=CUR
      DO I=3,8
        WD2(I)=BLANK
      ENDDO 
 1480 IF(WD1(1) .EQ. CWE .AND. WD1(2) .EQ. CST .AND. PCT(10)) 
     &      CALL RSPEK(17)
 1490 CALL VOCAB(WD1,-1,I,INDEX)
      IF(I.EQ.-1) GO TO 1520
      K=MOD(I,1000) 
      KQ=I/1000+1 
      GO TO (1680,1580,1530,1290) KQ
 1500 CALL BUG(22)
C 
C  GET SECOND WORD FOR ANALYSIS.
C 
 1510 DO I=1,8
        WD1(I)=WD2(I) 
        WD2(I)=0
      ENDDO 
      GO TO 1480
C 
C  GEE, I DON'T UNDERSTAND. 
C 
 1520 SPK=60
      IF(PCT(20)) SPK=61
      IF(PCT(20)) SPK=13
      CALL RSPEK(SPK) 
      GO TO 1320
C 
C  ANALYSE A VERB.  REMEMBER WHAT IT WAS, GO BACK FOR OBJECT IF SECOND WORD 
C  UNLESS VERB IS "SAY", WHICH SNARFS ARBITRARY SECOND WORD.
C 
 1530 VERB=K
      SPK=ACTSPK(VERB)
      IF(WD2(1).NE.0.AND.VERB.NE.SAY) GO TO 1510
      IF(VERB.EQ.SAY) OBJ=WD2(1)
      IF(OBJ.NE.0) GO TO 1560 
C 
C  ANALYSE AN INTRANSITIVE VERB (IE, NO OBJECT GIVEN YET).
C 
 1540 GO TO(2050,2030,2030,2260,1280,2260,2320,2330,2030,2030,
C           TAKE DROP  SAY OPEN NOTH LOCK   ON  OFF WAVE CALM 
C 
     &      1300,2350,2390,2410,2440,2030,2030,2520,2030,2550,
C           WALK KILL POUR  EAT DRNK  RUB TOSS QUIT FIND INVN 
C 
     &      2030,2620,2640,2650,2680,2700,2710,2030,2030,2760,
C           FEED FILL BLST SCOR  FOO  BRF READ BREK WAKE SUSP 
C 
     &      2770,1890,1900,1910,1920,1930,2900,2910,2920,2930) VERB 
C           HOUR LOVE KISS MAGI SAVE RSTR MOVE TURN WAIT WHY
C 
 1550 CALL BUG(23)
C 
C  ANALYSE A TRANSITIVE VERB. 
C 
 1560 GO TO(2060,2140,2220,2270,1280,2270,2320,2330,2340,1300,
C           TAKE DROP  SAY OPEN NOTH LOCK   ON  OFF WAVE CALM 
C 
     &      1300,2350,2390,2430,2440,2450,2460,1300,2540,2540,
C           WALK KILL POUR  EAT DRNK  RUB TOSS QUIT FIND INVN 
C 
     &      2570,2620,2640,1300,1300,1300,2720,2730,2750,1300,
C           FEED FILL BLST SCOR  FOO  BRF READ BREK WAKE SUSP 
C 
     &      1300,1890,1900,1910,1920,1930,2900,2910,2920,2930) VERB 
C           HOUR LOVE KISS MAGI SAVE RSTR MOVE TURN WAIT WHY
C 
 1570 CALL BUG(24)
C 
C  ANALYSE AN OBJECT WORD.  SEE IF THE THING IS HERE, WHETHER WE'VE GOT A VERB
C  YET, AND SO ON.  OBJECT MUST BE HERE UNLESS VERB IS "FIND" OR "INVENT(ORY)"
C  (AND NO NEW VERB YET TO BE ANALYSED).  WATER AND OIL ARE ALSO FUNNY, SINCE 
C  THEY ARE NEVER ACTUALLY DROPPED AT ANY LOCATION, BUT MIGHT BE HERE INSIDE
C  THE BOTTLE OR AS A FEATURE OF THE LOCATION.
C 
 1580 OBJ=K 
C 
D     WRITE(CRT,3020) LOC,VERB,I,J,OBJ,PLACE(K),PLAC(K) 
D3020 FORMAT("1580: LOC=",I6,"  VERB=",I6,"  I,J=",2I6,"  OBJ=",I6, 
D    &  /"  PLACE(OBJ)=",I6,"  PLAC(OBJ)=",I6)
C 
      IQ=0
      IF(HERE(OBJ)) IQ=1
      JQ=0
      IF(HERE(K)) JQ=1
      LQ=0
      IF(TOTNG(OBJ)) LQ=1 
      MQ=0
      IF(.NOT.TOTNG(OBJ)) MQ=1
C 
D     WRITE(CRT,3030) IQ,JQ,LQ,MQ 
D3030 FORMAT("HERE(OBJ)",I2,"   HERE(K)",I2,"   TOTNG(OBJ)",I2, 
D    &  "   .NOT.TOTNG",I2) 
C 
      IF((FIXED(K).NE.LOC) .AND. (PLACE(OBJ).NE.LOC) .AND.
     &  (PLACE(OBJ).NE.-1)) GO TO 1610
 1590 IF(WD2(1).NE.0) GO TO 1510
      IF(VERB.NE.0) GO TO 1560
      WRITE(CRT,1600) 
 1600 FORMAT("What do you want to do with the ",$) 
      CALL ITEM(WD1,2H? ) 
      GO TO 1320
C 
 1610 IF(K.NE.GRATE) GO TO 1620 
      IF(LOC.EQ.1.OR.LOC.EQ.4.OR.LOC.EQ.7) K=DPRSSN 
      IF(LOC.GT.9.AND.LOC.LT.15)K=ENTRNC
      IF(K.NE.GRATE) GO TO 1680 
 1620 IF(K.NE.DWARF) GO TO 1630 
      DO I=1,5
        IF(DLOC(I).EQ.LOC.AND.DFLAG.GE.2) GO TO 1590
      ENDDO 
 1630 IF((LIQ(0).EQ.K.AND.HERE(BOTTLE)).OR.K.EQ.LIQLC(LOC)) GO TO 1590
      IF(OBJ.NE.PLANT.OR..NOT.AT(PLANT2).OR.PROP(PLANT2).EQ.0)
     &  GO TO 1640
      OBJ=PLANT2
      GO TO 1590
 1640 IF(OBJ.NE.KNIFE.OR.KNFLOC.NE.LOC) GO TO 1650
      KNFLOC=-1 
      SPK=116 
      GO TO 1300
 1650 IF(OBJ.NE.ROD.OR..NOT.HERE(ROD2)) GO TO 1660
      OBJ=ROD2
      GO TO 1590
 1660 IF((VERB.EQ.FIND.OR.VERB.EQ.INVENT).AND.WD2(1).EQ.0) GO TO 1590
      WRITE(CRT,1670) 
 1670 FORMAT("I don't see any ",$) 
      CALL ITEM(WD1,2H. ) 
      GO TO 1310
C 
C  FIGURE OUT THE NEW LOCATION
C 
C  GIVEN THE CURRENT LOCATION IN "LOC", AND A MOTION VERB NUMBER IN "K", PUT
C  THE NEW LOCATION IN "NEWLOC".  THE CURRENT LOC IS SAVED IN "OLDLOC" IN CASE
C  HE WANTS TO RETREAT.  THE CURRENT OLDLOC IS SAVED IN OLDLC2, IN CASE HE
C  DIES.  (IF HE DOES, NEWLOC WILL BE LIMBO, AND OLDLOC WILL BE WHAT KILLED 
C  HIM, SO WE NEED OLDLC2, WHICH IS THE LAST PLACE HE WAS SAFE.)
C 
 1680 KK=KEY(LOC) 
      NEWLOC=LOC
      IF(KK.EQ.0) CALL BUG(26)
      IF(K.EQ.NULL) GO TO 1010
      IF(K.EQ.BACK) GO TO 1810
      IF(K.EQ.LOOK) GO TO 1860
      IF(K.EQ.CAVE) GO TO 1870
      OLDLC2=OLDLOC 
      OLDLOC=LOC
      IF(LOC.LT.1 .OR. LOC.GT.800 .OR. KK.LT.1 .OR. KK.GT.800) THEN 
        WRITE(CRT,'("1680: MAIN: LOC,KK:",2I6)') LOC,KK 
        CALL BUG(29)
      ENDIF 
C 
 1690 ITEMP=TRAVEL(KK)
      LL=ABS(ITEMP)
      IF(KK.LT.1 .OR. KK.GT.800) CALL BUG(25) 
      IF(LL.EQ.1 .OR. LL.EQ.K) GO TO 1700 
      IF(TRAVEL(KK).LT.0) GO TO 1880
      KK=KK+1 
      GO TO 1690
C 
 1700 NEWLOC=TRVCON(KK) 
      IF(KK.LT.1 .OR. KK.GT.800) CALL BUG(26) 
      K=MOD(NEWLOC,100) 
      IF(NEWLOC.LE.300) GO TO 1720
      IF(PROP(K).NE.NEWLOC/100-3) GO TO 1740
 1710 IF(TRAVEL(KK).LT.0) CALL BUG(25)
      KK=KK+1 
      GO TO 1700
C 
 1720 IF(NEWLOC.LE.100) GO TO 1730
      IF(TOTNG(K).OR.(NEWLOC.GT.200.AND.AT(K))) GO TO 1740
      GO TO 1710
C 
 1730 IF(NEWLOC.NE.0.AND..NOT.PCT(INT(NEWLOC))) GO TO 1710 
 1740 NEWLOC=TRVLOC(KK) 
      IF(NEWLOC.LE.300) GO TO 1010
      IF(NEWLOC.LE.500) GO TO 1750
      CALL RSPEK(NEWLOC-500)
      NEWLOC=LOC
      GO TO 1010
C 
C  SPECIAL MOTIONS COME HERE. 
C  SPECIAL CASE NUMBER NNN (NNN=301-500). 
C 
 1750 NEWLOC=NEWLOC-300 
      GO TO (1770 ,1780 ,1790 ) NEWLOC
 1760 CALL BUG(20)
C 
C  TRAVEL 301.  PLOVER-ALCOVE PASSAGE.  CAN CARRY ONLY EMERALD.  NOTE: TRAVEL 
C  TABLE MUST INCLUDE "USELESS" ENTRIES GOING THROUGH PASSAGE, WHICH CAN NEVER
C  BE USED FOR ACTUAL MOTION, BUT CAN BE SPOTTED BY "GO BACK".
C 
 1770 NEWLOC=99+100-LOC 
      IF(HOLDNG.EQ.0.OR.(HOLDNG.EQ.1.AND.TOTNG(EMRALD))) GO TO 1010 
      NEWLOC=LOC
      CALL RSPEK(117) 
      GO TO 1010
C 
C  TRAVEL 302.  PLOVER TRANSPORT.  DROP THE EMERALD (ONLY USE SPECIAL TRAVEL IF 
C  TOTNG IT), SO HE'S FORCED TO USE THE PLOVER-PASSAGE TO GET IT OUT.  HAVING 
C  DROPPED IT, GO BACK AND PRETEND HE WASN'T CARRYING IT AFTER ALL. 
C 
 1780 CALL DROP(EMRALD,LOC) 
      GO TO 1710
C 
C  TRAVEL 303.  TROLL BRIDGE.  MUST BE DONE ONLY AS SPECIAL MOTION SO THAT
C  DWARVES WON'T WANDER ACROSS AND ENCOUNTER THE BEAR.  (THEY WON'T FOLLOW THE
C  PLAYER THERE BECAUSE THAT REGION IS FORBIDDEN TO THE PIRATE.)  IF
C  PROP(TROLL)=1, HE'S CROSSED SINCE PAYING, SO STEP OUT AND BLOCK HIM. 
C  (STANDARD TRAVEL ENTRIES CHECK FOR PROP(TROLL)=0.)  SPECIAL STUFF FOR BEAR.
C 
 1790 IF(PROP(TROLL).NE.1) GO TO 1800 
      CALL PSPEK(TROLL,1) 
      PROP(TROLL)=0 
      CALL MOVE(TROLL2,0) 
      CALL MOVE(TROLL2+100,0) 
      CALL MOVE(TROLL,PLAC(TROLL))
      CALL MOVE(TROLL+100,FIXD(TROLL))
      CALL JUGGLE(CHASM)
      NEWLOC=LOC
      GO TO 1010
C 
 1800 NEWLOC=PLAC(TROLL)+FIXD(TROLL)-LOC
      IF(PROP(TROLL).EQ.0) PROP(TROLL)=1
      IF(.NOT.TOTNG(BEAR)) GO TO 1010 
      CALL RSPEK(162) 
      PROP(CHASM)=1 
      PROP(TROLL)=2 
      CALL DROP(BEAR,NEWLOC)
      FIXED(BEAR)=-1
      PROP(BEAR)=3
      IF(PROP(SPICES).LT.0) TALLY2=TALLY2+1 
      OLDLC2=NEWLOC 
      GO TO 1960
C 
C  END OF SPECIALS. 
C 
C  HANDLE "GO BACK".  LOOK FOR VERB WHICH GOES FROM LOC TO OLDLOC, OR TO OLDLC2 
C  IF OLDLOC HAS FORCED-MOTION.  K2 SAVES ENTRY -> FORCED LOC -> PREVIOUS LOC.
C 
 1810 K=OLDLOC
      IF(FORCED(K)) K=OLDLC2
      OLDLC2=OLDLOC 
      OLDLOC=LOC
      K2=0
      IF(K.NE.LOC) GO TO 1820 
      CALL RSPEK(91)
      GO TO 1010
C 
 1820 LL=TRVLOC(KK) 
      IF(LL.EQ.K) GO TO 1850
      IF(LL.GT.300) GO TO 1830
      J=KEY(LL) 
      IF(FORCED(LL).AND.TRVLOC(KK).EQ.K) K2=KK
 1830 IF(TRAVEL(KK).LT.0) GO TO 1840
      KK=KK+1 
      GO TO 1820
C 
 1840 KK=K2 
      IF(KK.NE.0) GO TO 1850
      CALL RSPEK(140) 
      GO TO 1010
C 
 1850 ITEMP=TRAVEL(KK)
      K=ABS(ITEMP) 
      KK=KEY(LOC) 
      GO TO 1690
C 
C  LOOK.  CAN'T GIVE MORE DETAIL.  PRETEND IT WASN'T DARK (THOUGH IT MAY "NOW"
C  BE DARK) SO HE WON'T FALL INTO A PIT WHILE STARING INTO THE GLOOM. 
C 
 1860 IF(DETAIL.LT.3) CALL RSPEK(15)
      DETAIL=DETAIL+1 
      WZDARK=.FALSE.
      ABB(LOC)=0
      GO TO 1010
C 
C  CAVE.  DIFFERENT MESSAGES DEPENDING ON WHETHER ABOVE GROUND. 
C 
 1870 IF(LOC.LT.8) CALL RSPEK(57) 
      IF(LOC.GE.8) CALL RSPEK(58) 
      GO TO 1010
C 
C  NON-APPLICABLE MOTION.  VARIOUS MESSAGES DEPENDING ON WORD GIVEN.
C 
 1880 SPK=12
      IF(K.GE.43.AND.K.LE.50) SPK=9 
      IF(K.EQ.29.OR.K.EQ.30) SPK=9
      IF(K.EQ.7.OR.K.EQ.36.OR.K.EQ.37) SPK=10 
      IF(K.EQ.11.OR.K.EQ.19) SPK=11 
      IF(VERB.EQ.FIND.OR.VERB.EQ.INVENT) SPK=59 
      IF(K.EQ.62.OR.K.EQ.65) SPK=42 
      IF(K.EQ.17) SPK=80
      CALL RSPEK(SPK) 
      GO TO 1010
C 
C     PRINCE/PRINCESS - GIRL  
C     PROP(41) STARTS AT ZERO AND GOES TO 2 IF "LOVE" IS USED, 4 IF "KISS"
C     IS USED.  AFTER "KISS" THEY TURN INTO FROGS AND BECOME USELESS.  AFTER
C     "LOVE" THE DOOR TO THE SMALL CHAMBER IS OPENED. 
C 
C     IF IN THE GIRLS BEDROOM AND THE HE TRIES TO LOVE HER, THE 
C     STATUE WILL GET REVENGE.
C 
 1890 IF(LOC.NE.141) THEN 
        IF(LOC.EQ.145) THEN 
          SPK=212 
          PROP(STATU)=2 
        ELSE
          SPK=79
        ENDIF 
      ELSEIF(PROP(41).EQ.0) THEN
        PROP(41)=2
        SPK=203 
      ELSEIF(PROP(41).EQ.2) THEN
        SPK=42
      ELSE
        SPK=205 
      ENDIF 
      GO TO 1300
C 
 1900 IF(LOC.NE.141) THEN 
        IF(LOC.EQ.145) THEN 
          SPK=212 
        ELSE
          SPK=110 
        ENDIF 
      ELSEIF(PROP(41).EQ.4) THEN
        SPK=205 
      ELSE
        SPK=204 
        PROP(41)=4
      ENDIF
      GO TO 1300
C
C  MAGIC MODE
C
 1910 CALL MAGIC
      GO TO 1310
C
C  SAVE GAME
C
 1920 CALL MSPEK(27)
      READ(KBD,'(A)',END=1925) FILENAME
      CALL SAVE(FILENAME)
      IF(.NOT.WIZARD .AND. PRIMTIM(0)) GO TO 2990
      GO TO 1310
 1925 CALL EXIT
C
C  RESTORE GAME
C
 1930 CALL MSPEK(28)
      READ(KBD,'(A)',END=1935) FILENAME
      CALL RESTORE(FILENAME)
      CALL RSPEK(207)
      GO TO 1310
 1935 CALL EXIT
C
C  GAME TOO LONG
C
 1940 CONTINUE
      CALL MSPEK(3)
      IF(.NOT.GUARD(0)) THEN
        IF(YES(221,54,54)) GO TO 1920
        SCORNG=.FALSE.
        GO TO 2990
      ENDIF
      GO TO 1455
C
C  "YOU'RE DEAD, JIM."
C
C  IF THE CURRENT LOC IS ZERO, IT MEANS THE CLOWN GOT HIMSELF KILLED.  WE'LL
C  ALLOW THIS MAXDIE TIMES.  MAXDIE IS AUTOMATICALLY SET BASED ON THE NUMBER OF
C  SNIDE MESSAGES AVAILABLE.  EACH DEATH RESULTS IN A MESSAGE (81, 83, ETC.)
C  WHICH OFFERS REINCARNATION; IF ACCEPTED, THIS RESULTS IN MESSAGE 82, 84,
C  ETC.  THE LAST TIME, IF HE WANTS ANOTHER CHANCE, HE GETS A SNIDE REMARK AS
C  WE EXIT.  WHEN REINCARNATED, ALL OBJECTS BEING CARRIED GET DROPPED AT OLDLC2
C  (PRESUMABLY THE LAST PLACE PRIOR TO BEING KILLED) WITHOUT CHANGE OF PROPS.
C  THE LOOP RUNS BACKWARDS TO ASSURE THAT THE BIRD IS DROPPED BEFORE THE CAGE.
C  (THIS KLUGE COULD BE CHANGED ONCE WE'RE SURE ALL REFERENCES TO BIRD AND CAGE
C  ARE DONE BY KEYWORDS.)  THE LAMP IS A SPECIAL CASE (IT WOULDN'T DO TO LEAVE
C  IT IN THE CAVE).  IT IS TURNED OFF AND LEFT OUTSIDE THE BUILDING (ONLY IF HE
C  WAS CARRYING IT, OF COURSE).  HE HIMSELF IS LEFT INSIDE THE BUILDING (AND
C  HEAVEN HELP HIM IF HE TRIES TO XYZZY BACK INTO THE CAVE WITHOUT THE LAMP!).
C  OLDLOC IS ZAPPED SO HE CAN'T JUST "RETREAT". 
C 
C  THE EASIEST WAY TO GET KILLED IS TO FALL INTO A PIT IN PITCH DARKNESS. 
C 
 1950 CALL RSPEK(23)
      OLDLC2=LOC
C 
C  OKAY, HE'S DEAD.  LET'S GET ON WITH IT.
C 
 1960 IF(CLOSNG) GO TO 1970 
      YEA=YES(81+NUMDIE*2,82+NUMDIE*2,54) 
      NUMDIE=NUMDIE+1 
      IF(NUMDIE.EQ.MAXDIE.OR..NOT.YEA) GO TO 2990 
      PLACE(WATER)=0
      PLACE(OIL)=0
      IF(TOTNG(LAMP)) PROP(LAMP)=0
      DO J=1,100
        I=101-J 
        IF(TOTNG(I)) THEN 
          K=OLDLC2
          IF(I.EQ.LAMP) K=1 
          CALL DROP(I,K)
        ENDIF 
      ENDDO 
      LOC=3 
      OLDLOC=LOC
      GO TO 1230
C 
C  HE DIED DURING CLOSING TIME.  NO RESURRECTION.  TALLY UP A DEATH AND EXIT. 
C 
 1970 CALL RSPEK(131) 
      NUMDIE=NUMDIE+1 
      GO TO 2990
C 
C  CAVE CLOSING AND SCORING 
C 
C 
C  THESE SECTIONS HANDLE THE CLOSING OF THE CAVE.  THE CAVE CLOSES "CLOCK1" 
C  TURNS AFTER THE LAST TREASURE HAS BEEN LOCATED (INCLUDING THE PIRATE'S 
C  CHEST, WHICH MAY OF COURSE NEVER SHOW UP).  NOTE THAT THE TREASURES NEED NOT 
C  HAVE BEEN TAKEN YET, JUST LOCATED.  HENCE CLOCK1 MUST BE LARGE ENOUGH TO GET 
C  OUT OF THE CAVE (IT ONLY TICKS WHILE INSIDE THE CAVE).  WHEN IT HITS ZERO, 
C  WE BRANCH TO 1980 TO START CLOSING THE CAVE, AND THEN SIT BACK AND WAIT FOR
C  HIM TO TRY TO GET OUT.  IF HE DOESN'T WITHIN CLOCK2 TURNS, WE CLOSE THE
C  CAVE; IF HE DOES TRY, WE ASSUME HE PANICS, AND GIVE HIM A FEW ADDITIONAL 
C  TURNS TO GET FRANTIC BEFORE WE CLOSE.  WHEN CLOCK2 HITS ZERO, WE BRANCH TO 
C  1990 TO TRANSPORT HIM INTO THE FINAL PUZZLE.  NOTE THAT THE PUZZLE DEPENDS 
C  UPON ALL SORTS OF RANDOM THINGS.  FOR INSTANCE, THERE MUST BE NO WATER OR
C  OIL, SINCE THERE ARE BEANSTALKS WHICH WE DON'T WANT TO BE ABLE TO WATER, 
C  SINCE THE CODE CAN'T HANDLE IT.  ALSO, WE CAN HAVE NO KEYS, SINCE THERE IS A 
C  GRATE (HAVING MOVED THE FIXED OBJECT!) THERE SEPARATING HIM FROM ALL THE 
C  TREASURES.  MOST OF THESE PROBLEMS ARISE FROM THE USE OF NEGATIVE PROP 
C  NUMBERS TO SUPPRESS THE OBJECT DESCRIPTIONS UNTIL HE'S ACTUALLY MOVED THE
C  OBJECTS. 
C 
C  WHEN THE FIRST WARNING COMES, WE LOCK THE GRATE, DESTROY THE BRIDGE, KILL
C  ALL THE DWARVES (AND THE PIRATE), REMOVE THE TROLL AND BEAR (UNLESS DEAD), 
C  AND SET "CLOSNG" TO TRUE.  LEAVE THE DRAGON; TOO MUCH TROUBLE TO MOVE IT.
C  FROM NOW UNTIL CLOCK2 RUNS OUT, HE CANNOT UNLOCK THE GRATE, MOVE TO ANY
C  LOCATION OUTSIDE THE CAVE (LOC<9), OR CREATE THE BRIDGE.  NOR CAN HE BE
C  RESURRECTED IF HE DIES.  NOTE THAT THE SNAKE IS ALREADY GONE, SINCE HE GOT 
C  TO THE TREASURE ACCESSIBLE ONLY VIA THE HALL OF THE MT. KING.  ALSO, HE'S
C  BEEN IN GIANT ROOM (TO GET EGGS), SO WE CAN REFER TO IT.  ALSO ALSO, HE'S
C  GOTTEN THE PEARL, SO WE KNOW THE BIVALVE IS AN OYSTER.  *AND*, THE DWARVES 
C  MUST HAVE BEEN ACTIVATED, SINCE WE'VE FOUND CHEST. 
C 
 1980 PROP(GRATE)=0 
      PROP(FISSUR)=0
      DO I=1,6
        DSEEN(I)=.FALSE.
        DLOC(I)=0 
      ENDDO 
      CALL MOVE(TROLL,0)
      CALL MOVE(TROLL+100,0)
      CALL MOVE(TROLL2,PLAC(TROLL)) 
      CALL MOVE(TROLL2+100,FIXD(TROLL)) 
      CALL JUGGLE(CHASM)
      IF(PROP(BEAR).NE.3) CALL DESTROY(BEAR)
      PROP(CHAIN)=0 
      FIXED(CHAIN)=0
      PROP(AXE)=0 
      FIXED(AXE)=0
      CALL RSPEK(129) 
      CLOCK1=-1 
      CLOSNG=.TRUE. 
      GO TO 1460
C 
C  ONCE HE'S PANICKED, AND CLOCK2 HAS RUN OUT, WE COME HERE TO SET UP THE 
C  STORAGE ROOM.  THE ROOM HAS TWO LOCS, HARDWIRED AS 115 (NE) AND 116 (SW).
C  AT THE NE END, WE PLACE EMPTY BOTTLES, A NURSERY OF PLANTS, A BED OF 
C  OYSTERS, A PILE OF LAMPS, RODS WITH STARS, SLEEPING DWARVES, AND HIM.  AND 
C  THE SW END WE PLACE GRATE OVER TREASURES, SNAKE PIT, COVEY OF CAGED BIRDS, 
C  MORE RODS, AND PILLOWS.  A MIRROR STRETCHES ACROSS ONE WALL.  MANY OF THE
C  OBJECTS COME FROM KNOWN LOCATIONS AND/OR STATES (E.G. THE SNAKE IS KNOWN TO
C  HAVE BEEN DESTROYED AND NEEDN'T BE CARRIED AWAY FROM ITS OLD "PLACE"), 
C  MAKING THE VARIOUS OBJECTS BE HANDLED DIFFERENTLY.  WE ALSO DROP ALL OTHER 
C  OBJECTS HE MIGHT BE CARRYING (LEST HE HAVE SOME WHICH COULD CAUSE TROUBLE, 
C  SUCH AS THE KEYS).  WE DESCRIBE THE FLASH OF LIGHT AND TRUNDLE BACK. 
C 
 1990 PROP(BOTTLE)=PUT(BOTTLE,115,1)
      PROP(PLANT)=PUT(PLANT,115,0)
      PROP(OYSTER)=PUT(OYSTER,115,0)
      PROP(LAMP)=PUT(LAMP,115,0)
      PROP(ROD)=PUT(ROD,115,0)
      PROP(DWARF)=PUT(DWARF,115,0)
      LOC=115 
      OLDLOC=115
      NEWLOC=115
C 
C  LEAVE THE GRATE WITH NORMAL (NON-NEGATIVE PROPERTY). 
C 
      I=PUT(GRATE,116,0)
      PROP(SNAKE)=PUT(SNAKE,116,1)
      PROP(BIRD)=PUT(BIRD,116,1)
      PROP(CAGE)=PUT(CAGE,116,0)
      PROP(ROD2)=PUT(ROD2,116,0)
      PROP(PILLOW)=PUT(PILLOW,116,0)
C 
      PROP(MIRROR)=PUT(MIRROR,115,0)
      FIXED(MIRROR)=116 
C 
      DO I=1,100
        IF(TOTNG(I)) CALL DESTROY(I)
      ENDDO 
C 
      CALL RSPEK(132) 
      CLOSED=.TRUE. 
      GO TO 1010
C 
C  ANOTHER WAY WE CAN FORCE AN END TO THINGS IS BY HAVING THE LAMP GIVE OUT.
C  WHEN IT GETS CLOSE, WE COME HERE TO WARN HIM.  WE GO TO 2000 IF THE LAMP 
C  AND FRESH BATTERIES ARE HERE, IN WHICH CASE WE REPLACE THE BATTERIES AND 
C  CONTINUE.  2010 IS FOR OTHER CASES OF LAMP DYING.  2020 IS WHEN IT GOES
C  OUT, AND 2780 IS IF HE'S WANDERED OUTSIDE AND THE LAMP IS USED UP, IN
C  WHICH CASE WE FORCE HIM TO GIVE UP.
C 
 2000 CALL RSPEK(188) 
      PROP(BATTER)=1
      IF(TOTNG(BATTER)) CALL DROP(BATTER,LOC) 
      LIMIT=LIMIT+2800
      LMWARN=.FALSE.
      GO TO 1460
C 
 2010 IF(LMWARN.OR..NOT.HERE(LAMP)) GO TO 1460
      LMWARN=.TRUE. 
      SPK=187 
      IF(PLACE(BATTER).EQ.0) SPK=183
      IF(PROP(BATTER).EQ.1) SPK=189 
      CALL RSPEK(SPK) 
      GO TO 1460
C 
 2020 LIMIT=-1
      PROP(LAMP)=0
      IF(HERE(LAMP)) CALL RSPEK(184)
      GO TO 1460
C 
C  ROUTINES FOR PERFORMING THE VARIOUS ACTION VERBS.  MANY INTRANSITIVE 
C  VERBS USE THE TRANSITIVE CODE, AND SOME VERBS USE CODE FOR OTHER VERBS,  
C  AS NOTED BELOW.  RANDOM INTRANSITIVE VERBS COME HERE.
C  CLEAR OBJ JUST IN CASE (SEE "ATTACK"). 
C 
 2030 WRITE(CRT,2040) 
 2040 FORMAT("I don't understand '",$) 
      CALL ITEM(WD1,2H'.) 
      OBJ=0 
      GO TO 1320
C 
C  CARRY, NO OBJECT GIVEN YET.  OK IF ONLY ONE OBJECT PRESENT.
C 
 2050 IF(ATLOC(LOC).EQ.0.OR.LINK(ATLOC(LOC)).NE.0) GO TO 2030 
      DO I=1,5
        IF(DLOC(I).EQ.LOC.AND.DFLAG.GE.2) GO TO 2030
      ENDDO 
      OBJ=ATLOC(LOC)
C 
C  CARRY AN OBJECT.  SPECIAL CASES FOR BIRD AND CAGE (IF BIRD IN CAGE, CAN'T
C  TAKE ONE WITHOUT THE OTHER.  LIQUIDS ALSO SPECIAL, SINCE THEY DEPEND ON
C  STATUS OF BOTTLE.  ALSO VARIOUS SIDE EFFECTS, ETC. 
C 
 2060 IF(TOTNG(OBJ)) GO TO 1300 
      SPK=25
      IF(OBJ.EQ.PLANT.AND.PROP(PLANT).LE.0) SPK=115 
      IF(OBJ.EQ.BEAR.AND.PROP(BEAR).EQ.1) SPK=169 
      IF(OBJ.EQ.CHAIN.AND.PROP(BEAR).NE.0) SPK=170
      IF(OBJ.EQ.SKULL.AND. .NOT.TOTNG(ROD)) PROP(CHARO)=1 
      IF(FIXED(OBJ).NE.0) GO TO 1300
      IF(OBJ.NE.WATER.AND.OBJ.NE.OIL) GO TO 2080
      IF(HERE(BOTTLE).AND.LIQ(0).EQ.OBJ) GO TO 2070 
      OBJ=BOTTLE
      IF(TOTNG(BOTTLE).AND.PROP(BOTTLE).EQ.1) GO TO 2620
      IF(PROP(BOTTLE).NE.1) SPK=105 
      IF(.NOT.TOTNG(BOTTLE)) SPK=104
      GO TO 1300
 2070 OBJ=BOTTLE
 2080 IF(HOLDNG.LT.7) GO TO 2090
      CALL RSPEK(92)
      GO TO 1310
 2090 IF(OBJ.NE.BIRD) GO TO 2110
      IF(PROP(BIRD).NE.0) GO TO 2110
      IF(.NOT.TOTNG(ROD)) GO TO 2100
      CALL RSPEK(26)
      GO TO 1310
 2100 IF(TOTNG(CAGE)) GO TO 2120
      CALL RSPEK(27)
      GO TO 1310
 2110 IF(OBJ.NE.66 .OR. PLACE(42).EQ.144) GO TO 2130
      SPK=208 
      GO TO 1300
C 
 2120 PROP(BIRD)=1
 2130 IF((OBJ.EQ.BIRD.OR.OBJ.EQ.CAGE).AND.PROP(BIRD).NE.0)
     &      CALL CARRY(BIRD+CAGE-OBJ,LOC) 
      CALL CARRY(OBJ,LOC) 
      K=LIQ(0)
      IF(OBJ.EQ.BOTTLE.AND.K.NE.0) PLACE(K)=-1
      GO TO 1280
C 
C  DISCARD OBJECT.  "THROW" ALSO COMES HERE FOR MOST OBJECTS.  SPECIAL CASES
C  FOR BIRD (MIGHT ATTACK SNAKE OR DRAGON) AND CAGE (MIGHT CONTAIN BIRD) AND
C  VASE.  DROP COINS AT VENDING MACHINE FOR EXTRA BATTERIES.
C 
 2140 IF(TOTNG(ROD2).AND.OBJ.EQ.ROD.AND..NOT.TOTNG(ROD))OBJ=ROD2
C 
D     WRITE(CRT,3040) LOC,NEWLOC,OLDLOC,
D    &   CLSSES,(CVAL(I),I=1,6),(PLACE(KLOD),KLOD=1,20) 
D3040 FORMAT("2140: LOC",I6,"  NEWLOC",I6,"  OLDLOC",I6,"  CLSSES",I6/
D    &       "      CVAL",6I6/"PLACE",10I6/6X,10I6) 
C 
      ZZ1=0 
      IF(HERE(OBJ)) ZZ1=1 
      ZZ2=0 
      IF(HERE(SNAKE)) ZZ2=1 
      ZZ3=0 
      IF(HERE(BIRD)) ZZ3=1
      ZZ4=0 
      IF(TOTNG(OBJ)) ZZ4=1
C 
D     WRITE(CRT,3050) ZZ1,ZZ2,ZZ3,ZZ4,OBJ,BIRD,SNAKE,LOC,PLACE(SNAKE) 
D3050 FORMAT("HERE(OBJ)",I2,"   HERE(SNAKE)",I2,"   HERE(BIRD)",I2, 
D    &  "   TOTNG(OBJ)",I2,/,"OBJ,BIRD,SNAKE,LOC,PLACE(SNAKE)",5I6) 
C 
      IF(.NOT.TOTNG(OBJ)) GO TO 1300
      IF(OBJ.NE.BIRD.OR..NOT.HERE(SNAKE)) GO TO 2160
      CALL RSPEK(30)
      IF(CLOSED) GO TO 2790 
      CALL DESTROY(SNAKE) 
C 
C  SET PROP FOR USE BY TRAVEL OPTIONS 
C 
      PROP(SNAKE)=1 
 2150 K=LIQ(0)
      IF(K.EQ.OBJ) OBJ=BOTTLE 
      IF(OBJ.EQ.BOTTLE.AND.K.NE.0) PLACE(K)=0 
      IF(OBJ.EQ.CAGE.AND.PROP(BIRD).NE.0) CALL DROP(BIRD,LOC) 
      IF(OBJ.EQ.BIRD) PROP(BIRD)=0
      CALL DROP(OBJ,LOC)
      GO TO 1310
C 
 2160 IF(OBJ.NE.COINS.OR..NOT.HERE(VEND)) GO TO 2170
      CALL DESTROY(COINS) 
      CALL DROP(BATTER,LOC) 
      CALL PSPEK(BATTER,0)
      GO TO 1310
C 
 2170 IF(OBJ.NE.BIRD.OR..NOT.AT(DRAGON).OR.PROP(DRAGON).NE.0) GO TO 2180
      CALL RSPEK(154) 
      CALL DESTROY(BIRD)
      PROP(BIRD)=0
      IF(PLACE(SNAKE).EQ.PLAC(SNAKE))TALLY2=TALLY2+1
      GO TO 1310
C 
 2180 IF(OBJ.NE.BEAR.OR..NOT.AT(TROLL)) GO TO 2200
      CALL RSPEK(163) 
      CALL MOVE(TROLL,0)
      CALL MOVE(TROLL+100,0)
      CALL MOVE(TROLL2,PLAC(TROLL)) 
      CALL MOVE(TROLL2+100,FIXD(TROLL)) 
      CALL JUGGLE(CHASM)
      PROP(TROLL)=2 
      GO TO 2150
C 
 2190 IF(OBJ.EQ.VASE.AND.LOC.NE.PLAC(PILLOW)) GO TO 2210
      CALL RSPEK(54)
      GO TO 2150
C 
 2200 IF(OBJ.NE.42 .OR. LOC.NE.144) GO TO 2190
      CALL RSPEK(209) 
      CALL DROP(OBJ,LOC)
      GO TO 1310
C 
 2210 PROP(VASE)=2
      IF(AT(PILLOW)) PROP(VASE)=0 
      CALL PSPEK(VASE,PROP(VASE)+1) 
      IF(PROP(VASE).NE.0) FIXED(VASE)=-1
      GO TO 2150
C 
C  SAY.  ECHO WD2 (OR WD1 IF NO WD2 (SAY WHAT?, ETC.).)  MAGIC WORDS OVERRIDE.
C 
 2220 IF(WD2(1).EQ.0) GO TO 2230
      DO I=1,8
        WD1(I)=WD2(I) 
        WD2(I)=0
      ENDDO 
 2230 CALL VOCAB(WD1,-1,I,INDEX)
      IF(I.EQ.62.OR.I.EQ.65.OR.I.EQ.71.OR.I.EQ.2025) GO TO 2250 
      WRITE(CRT,2240) 
 2240 FORMAT("Okay, '",$)
      CALL ITEM(WD1,2H'.) 
      GO TO 1310
C 
 2250 WD2(1)=0
      OBJ=0 
      GO TO 1490
C 
C  LOCK, UNLOCK, NO OBJECT GIVEN.  ASSUME VARIOUS THINGS IF PRESENT.
C 
 2260 SPK=28
      IF(HERE(CLAM))OBJ=CLAM
      IF(HERE(OYSTER)) OBJ=OYSTER 
      IF(AT(DOOR)) OBJ=DOOR 
      IF(AT(GRATE)) OBJ=GRATE 
      IF(OBJ.NE.0.AND.HERE(CHAIN)) GO TO 2030 
      IF(HERE(CHAIN)) OBJ=CHAIN 
      IF(OBJ.EQ.0) GO TO 1300 
C 
C  LOCK, UNLOCK OBJECT.  SPECIAL STUFF FOR OPENING CLAM/OYSTER AND FOR CHAIN. 
C 
 2270 IF(OBJ.EQ.CLAM.OR.OBJ.EQ.OYSTER) GO TO 2290 
      IF(OBJ.EQ.CHAMPA) GO TO 2295
      IF(OBJ.EQ.DOOR) SPK=111 
      IF(OBJ.EQ.DOOR.AND.PROP(DOOR).EQ.1) SPK=54
      IF(OBJ.EQ.CAGE) SPK=32
      IF(OBJ.EQ.KEYS) SPK=55
      IF(OBJ.EQ.GRATE.OR.OBJ.EQ.CHAIN) SPK=31 
      IF(SPK.NE.31.OR..NOT.HERE(KEYS)) GO TO 1300 
      IF(OBJ.EQ.CHAIN) GO TO 2300 
      IF(.NOT.CLOSNG) GO TO 2280
      K=130 
      IF(.NOT.PANIC) CLOCK2=15
      PANIC=.TRUE.
      GO TO 1290
C 
 2280 K=34+PROP(GRATE)
      PROP(GRATE)=1 
      IF(VERB.EQ.LOCK) PROP(GRATE)=0
      K=K+2*PROP(GRATE) 
      GO TO 1290
C 
C  CLAM/OYSTER. 
C 
 2290 K=0 
      IF(OBJ.EQ.OYSTER) K=1 
      SPK=124+K 
      IF(TOTNG(OBJ)) SPK=120+K
      IF(.NOT.TOTNG(TRIDNT)) SPK=122+K
      IF(VERB.EQ.LOCK) SPK=61 
      IF(SPK.NE.124) GO TO 1300 
      CALL DESTROY(CLAM)
      CALL DROP(OYSTER,LOC) 
      CALL DROP(PEARL,105)
      GO TO 1300
C 
C  CHAMPAGNE
C 
 2295 IF((LOC .NE. 145) .AND. (PROP(CHAMPA) .EQ. 0)) THEN 
        SPK=213 
        CALL DESTROY (CHAMPA) 
      ENDIF 
      IF((PROP(CHAMPA) .EQ. 1)) THEN
        SPK=215 
        GO TO 1300
      ENDIF 
      IF((PROP(CHAMPA).EQ. 0) .AND. (LOC .EQ. 145)) THEN
        CALL RSPEK(216) 
        CALL DESTROY(CHAMPA)
        CALL DESTROY(GIRL)
        CALL DROP(GARTER,145) 
        PROP(CHAMPA)=1
        PROP(STATU)=1 
      ENDIF 
      GO TO 1310  
C 
C  CHAIN. 
C 
 2300 IF(VERB.EQ.LOCK) GO TO 2310 
      SPK=171 
      IF(PROP(BEAR).EQ.0) SPK=41
      IF(PROP(CHAIN).EQ.0) SPK=37 
      IF(SPK.NE.171) GO TO 1300 
      PROP(CHAIN)=0 
      FIXED(CHAIN)=0
      IF(PROP(BEAR).NE.3) PROP(BEAR)=2
      FIXED(BEAR)=2-PROP(BEAR)
      GO TO 1300
C 
 2310 SPK=172 
      IF(PROP(CHAIN).NE.0) SPK=34 
      IF(LOC.NE.PLAC(CHAIN)) SPK=173
      IF(SPK.NE.172) GO TO 1300 
      PROP(CHAIN)=2 
      IF(TOTNG(CHAIN)) CALL DROP(CHAIN,LOC) 
      FIXED(CHAIN)=-1 
      GO TO 1300
C 
C  LIGHT LAMP 
C 
 2320 IF(.NOT.HERE(LAMP)) GO TO 1300
      SPK=184 
      IF(LIMIT.LT.0) GO TO 1300 
      PROP(LAMP)=1
      CALL RSPEK(39)
      IF(WZDARK) GO TO 1230 
      GO TO 1310
C 
C  LAMP OFF 
C 
 2330 IF(.NOT.HERE(LAMP)) GO TO 1300
      PROP(LAMP)=0
      CALL RSPEK(40)
      IF(DARK(0)) CALL RSPEK(16)
      GO TO 1310
C 
C  WAVE.  NO EFFECT UNLESS WAVING ROD AT FISSURE. 
C 
 2340 IF((.NOT.TOTNG(OBJ)).AND.(OBJ.NE.ROD.OR..NOT.TOTNG(ROD2)))
     &      SPK=29
      IF(OBJ.NE.ROD.OR..NOT.AT(FISSUR).OR..NOT.TOTNG(OBJ) 
     &      .OR.CLOSNG) GO TO 1300
      PROP(FISSUR)=1-PROP(FISSUR) 
      CALL PSPEK(FISSUR,2-PROP(FISSUR)) 
      GO TO 1310
C 
C  ATTACK.  ASSUME TARGET IF UNAMBIGUOUS.  "THROW" ALSO LINKS HERE. 
C  ATTACKABLE OBJECTS FALL INTO TWO CATEGORIES: ENEMIES (SNAKE, DWARF, ETC.)
C  (BIRD, CLAM).  AMBIGUOUS IF TWO ENEMIES, OR IF NO ENEMIES BUT TWO OTHERS.
C 
 2350 DO I=1,5
        IF(DLOC(I).EQ.LOC.AND.DFLAG.GE.2) GO TO 2360
      ENDDO 
      I=0 
 2360 IF(OBJ.NE.0) GO TO 2370 
      IF(I.NE.0) OBJ=DWARF
      IF(HERE(SNAKE)) OBJ=OBJ*100+SNAKE 
      IF(AT(DRAGON).AND.PROP(DRAGON).EQ.0) OBJ=OBJ*100+DRAGON 
      IF(AT(TROLL)) OBJ=OBJ*100+TROLL 
      IF(HERE(BEAR).AND.PROP(BEAR).EQ.0) OBJ=OBJ*100+BEAR 
      IF(OBJ.GT.100) GO TO 2030 
      IF(OBJ.NE.0) GO TO 2370 
C 
C  CAN'T ATTACK BIRD BY THROWING AXE. 
C 
      IF(HERE(BIRD).AND.VERB.NE.THROW) OBJ=BIRD 
C 
C  CLAM AND OYSTER BOTH TREATED AS CLAM FOR INTRANSITIVE CASE; NO HARM DONE.
C 
      IF(HERE(CLAM).OR.HERE(OYSTER)) OBJ=100*OBJ+CLAM 
      IF(OBJ.GT.100) GO TO 2030 
 2370 IF(OBJ.NE.BIRD) GO TO 2380
      SPK=137 
      IF(CLOSED) GO TO 1300 
      CALL DESTROY(BIRD)
      PROP(BIRD)=0
      IF(PLACE(SNAKE).EQ.PLAC(SNAKE)) TALLY2=TALLY2+1 
      SPK=45
 2380 IF(OBJ.EQ.0) SPK=44 
      IF(OBJ.EQ.CLAM.OR.OBJ.EQ.OYSTER) SPK=150
      IF(OBJ.EQ.SNAKE) SPK=46 
      IF(OBJ.EQ.DWARF) SPK=49 
      IF(OBJ.EQ.DWARF.AND.CLOSED) GO TO 2790
      IF(OBJ.EQ.DRAGON) SPK=167 
      IF(OBJ.EQ.TROLL) SPK=157
      IF(OBJ.EQ.BEAR) SPK=165+(PROP(BEAR)+1)/2
      IF(OBJ.NE.DRAGON.OR.PROP(DRAGON).NE.0) GO TO 1300 
C 
C  FUN STUFF FOR DRAGON.  IF HE INSISTS ON ATTACKING IT, WIN!  SET PROP TO DEAD 
C  MOVE DRAGON TO CENTRAL LOC (STILL FIXED), MOVE RUG THERE (NOT FIXED), AND
C  MOVE HIM THERE, TOO.  THEN DO A NULL MOTION TO GET NEW DESCRIPTION.
C 
      CALL RSPEK(49)
      VERB=0
      OBJ=0 
      CALL GETIN(WD1,WD2,WD3) 
      IF(WD1(1).NE.CYE.AND.WD1(1).NE.CY) GO TO 1450 
      CALL PSPEK(DRAGON,1)
      PROP(DRAGON)=2
      PROP(RUG)=0 
      K=(PLAC(DRAGON)+FIXD(DRAGON))/2 
      CALL MOVE(DRAGON+100,-1)
      CALL MOVE(RUG+100,0)
      CALL MOVE(DRAGON,K) 
      CALL MOVE(RUG,K)
      DO OBJ=1,100
        IF(PLACE(OBJ).EQ.PLAC(DRAGON).OR.PLACE(OBJ).EQ.FIXD(DRAGON))
     &      CALL MOVE(OBJ,K)
      ENDDO 
      LOC=K 
      K=NULL
      GO TO 1680
C 
C  POUR.  IF NO OBJECT, OR OBJECT IS BOTTLE, ASSUME CONTENTS OF BOTTLE. 
C  SPECIAL TESTS FOR POURING WATER OR OIL ON PLANT OR RUSTY DOOR. 
C 
 2390 IF(OBJ.EQ.BOTTLE.OR.OBJ.EQ.0) OBJ=LIQ(0)
      IF(OBJ.EQ.0) GO TO 2030 
      IF(.NOT.TOTNG(OBJ)) GO TO 1300
      SPK=78
      IF(OBJ.NE.OIL.AND.OBJ.NE.WATER) GO TO 1300
      PROP(BOTTLE)=1
      PLACE(OBJ)=0
      SPK=77
      IF(.NOT.(AT(PLANT).OR.AT(DOOR))) GO TO 1300 
C 
      IF(AT(DOOR)) GO TO 2400 
      SPK=112 
      IF(OBJ.NE.WATER) GO TO 1300 
      CALL PSPEK(PLANT,PROP(PLANT)+1) 
      PROP(PLANT)=MOD(PROP(PLANT)+2,6)
      PROP(PLANT2)=PROP(PLANT)/2
      K=NULL
      GO TO 1680
C 
 2400 PROP(DOOR)=0
      IF(OBJ.EQ.OIL)PROP(DOOR)=1
      SPK=113+PROP(DOOR)
      GO TO 1300
C 
C  EAT.  INTRANSITIVE: ASSUME FOOD IF PRESENT, ELSE ASK WHAT.  TRANSITIVE: FOOD 
C  OK, SOME THINGS LOSE APPETITE, REST ARE RIDICULOUS.
C 
 2410 IF(.NOT.HERE(FOOD)) GO TO 2030
 2420 CALL DESTROY(FOOD)
      SPK=72
      GO TO 1300
C 
 2430 IF(OBJ.EQ.FOOD) GO TO 2420
      IF(OBJ.EQ.BIRD.OR.OBJ.EQ.SNAKE.OR.OBJ.EQ.CLAM.OR.OBJ.EQ.OYSTER
     &      .OR.OBJ.EQ.DWARF.OR.OBJ.EQ.DRAGON.OR.OBJ.EQ.TROLL 
     &      .OR.OBJ.EQ.BEAR) SPK=71 
      IF(OBJ.EQ.41 .AND. LOC.EQ.141) GO TO 1890 
      GO TO 1300
C 
C  DRINK.  IF NO OBJECT, ASSUME WATER AND LOOK FOR IT HERE.  IF WATER IS IN 
C  THE BOTTLE, DRINK THAT, ELSE MUST BE AT A WATER LOC, SO DRINK STREAM.
C 
 2440 IF(OBJ.EQ.0.AND.LIQLC(LOC).NE.WATER.AND.(LIQ(0).NE.WATER
     &      .OR..NOT.HERE(BOTTLE))) GO TO 2030
      IF(OBJ.NE.0.AND.OBJ.NE.WATER) SPK=110 
      IF(SPK.EQ.110.OR.LIQ(0).NE.WATER.OR..NOT.HERE(BOTTLE)) GO TO 1300 
      PROP(BOTTLE)=1
      PLACE(WATER)=0
      SPK=74
      GO TO 1300
C 
C  RUB.  YIELDS VARIOUS SNIDE REMARKS.
C 
 2450 IF(OBJ.NE.LAMP) SPK=76
      GO TO 1300
C 
C  THROW.  SAME AS DISCARD UNLESS AXE.  THEN SAME AS ATTACK EXCEPT IGNORE BIRD, 
C  AND IF DWARF IS PRESENT THEN ONE MIGHT BE KILLED.  (ONLY WAY TO DO SO!)
C  AXE ALSO SPECIAL FOR DRAGON, BEAR, AND TROLL.  TREASURES SPECIAL FOR TROLL.
C 
 2460 IF(TOTNG(ROD2).AND.OBJ.EQ.ROD.AND..NOT.TOTNG(ROD)) OBJ=ROD2 
      IF(.NOT.TOTNG(OBJ)) GO TO 1300
      IF(OBJ.GE.50.AND.OBJ.LE.MAXTRS.AND.AT(TROLL)) GO TO 2510
      IF(OBJ.EQ.FOOD.AND.HERE(BEAR)) GO TO 2500 
      IF(OBJ.NE.AXE) GO TO 2140 
C 
C  NEEDN'T CHECK DFLAG IF AXE IS HERE.
C 
      DO I=1,5
        IF(DLOC(I).EQ.LOC) GO TO 2470 
      ENDDO 
      SPK=152 
      IF(AT(DRAGON).AND.PROP(DRAGON).EQ.0) GO TO 2480 
      SPK=158 
      IF(AT(TROLL)) GO TO 2480
      IF(HERE(BEAR).AND.PROP(BEAR).EQ.0) GO TO 2490 
      OBJ=0 
      GO TO 2350
C 
 2470 SPK=48
      IF(RNDM(3).EQ.0) GO TO 2480 
      DSEEN(I)=.FALSE.
      DLOC(I)=0 
      SPK=47
      DKILL=DKILL+1 
      IF(DKILL.EQ.1) SPK=149
 2480 CALL RSPEK(SPK) 
      CALL DROP(AXE,LOC)
      K=NULL
      GO TO 1680
C 
C  THIS'LL TEACH HIM TO THROW THE AXE AT THE BEAR!
C 
 2490 SPK=164 
      CALL DROP(AXE,LOC)
      FIXED(AXE)=-1 
      PROP(AXE)=1 
      CALL JUGGLE(BEAR) 
      GO TO 1300
C 
C  BUT THROWING FOOD IS ANOTHER STORY.
C 
 2500 OBJ=BEAR
      GO TO 2570
C 
 2510 SPK=159 
C 
C  SNARF A TREASURE FOR THE TROLL.
C 
      CALL DROP(OBJ,0)
      CALL MOVE(TROLL,0)
      CALL MOVE(TROLL+100,0)
      CALL DROP(TROLL2,PLAC(TROLL)) 
      CALL DROP(TROLL2+100,FIXD(TROLL)) 
      CALL JUGGLE(CHASM)
      GO TO 1300
C 
C  QUIT.  INTRANSITIVE ONLY.  VERIFY INTENT AND EXIT IF THAT'S WHAT HE WANTS. 
C 
 2520 GAVEUP=YES(22,54,54)
 2530 IF(GAVEUP) GO TO 2990 
      GO TO 1310
C 
C  FIND.  MIGHT BE CARRYING IT, OR IT MIGHT BE HERE.  ELSE GIVE CAVEAT. 
C 
 2540 IF(AT(OBJ).OR.(LIQ(0).EQ.OBJ.AND.AT(BOTTLE))
     &      .OR.K.EQ.LIQLC(LOC)) SPK=94 
      DO I=1,5
        IF(DLOC(I).EQ.LOC.AND.DFLAG.GE.2.AND.OBJ.EQ.DWARF) SPK=94 
      ENDDO 
      IF(CLOSED) SPK=138
      IF(TOTNG(OBJ)) SPK=24 
      GO TO 1300
C 
C  INVENTORY.  IF OBJECT, TREAT SAME AS FIND.  ELSE REPORT ON CURRENT BURDEN. 
C 
 2550 SPK=98
      DO 2560 I=1,100 
        IF(I.EQ.BEAR.OR..NOT.TOTNG(I)) GO TO 2560 
        IF(SPK.EQ.98) CALL RSPEK(99)
        BLKLIN=.FALSE.
        CALL PSPEK(I,-1)
        BLKLIN=.TRUE. 
        SPK=0 
 2560 CONTINUE
      IF(TOTNG(BEAR)) SPK=141 
      GO TO 1300
C 
C  FEED.  IF BIRD, NO SEED.  SNAKE, DRAGON, TROLL: QUIP.  IF DWARF, MAKE HIM
C  MAD.  BEAR, SPECIAL. 
C 
 2570 IF(OBJ.NE.BIRD) GO TO 2580
      SPK=100 
      GO TO 1300
C 
 2580 IF(OBJ.NE.SNAKE.AND.OBJ.NE.DRAGON.AND.OBJ.NE.TROLL) GO TO 2590
      SPK=102 
      IF(OBJ.EQ.DRAGON.AND.PROP(DRAGON).NE.0) SPK=110 
      IF(OBJ.EQ.TROLL) SPK=182
      IF(OBJ.NE.SNAKE.OR.CLOSED.OR..NOT.HERE(BIRD)) GO TO 1300
      SPK=101 
      CALL DESTROY(BIRD)
      PROP(BIRD)=0
      TALLY2=TALLY2+1 
      GO TO 1300
C 
 2590 IF(OBJ.NE.DWARF) GO TO 2600 
      IF(.NOT.HERE(FOOD)) GO TO 1300
      SPK=103 
      DFLAG=DFLAG+1 
      GO TO 1300
C 
 2600 IF(OBJ.NE.BEAR) GO TO 2610
      IF(PROP(BEAR).EQ.0) SPK=102 
      IF(PROP(BEAR).EQ.3) SPK=110 
      IF(.NOT.HERE(FOOD)) GO TO 1300
      CALL DESTROY(FOOD)
      PROP(BEAR)=1
      FIXED(AXE)=0
      PROP(AXE)=0 
      SPK=168 
      GO TO 1300
C 
 2610 SPK=14
      GO TO 1300
C 
C  FILL.  BOTTLE MUST BE EMPTY, AND SOME LIQUID AVAILABLE.  (VASE IS NASTY.)
C 
 2620 KLZ1=LIQ(0) 
      KLZ2=LIQLC(LOC) 
      IF(OBJ.EQ.VASE) GO TO 2630
      IF(OBJ.NE.0.AND.OBJ.NE.BOTTLE) GO TO 1300 
      IF(OBJ.EQ.0.AND..NOT.HERE(BOTTLE)) GO TO 2030 
      SPK=107 
      IF(LIQLC(LOC).EQ.0) SPK=106 
      IF(LIQ(0).NE.0) SPK=105 
      IF(SPK.NE.107) GO TO 1300 
      PROP(BOTTLE)=MOD(COND(LOC),4)/2*2 
      K=LIQ(0)
      IF(TOTNG(BOTTLE))PLACE(K)=-1
      IF(K.EQ.OIL) SPK=108
      GO TO 1300
C 
 2630 SPK=29
      IF(LIQLC(LOC).EQ.0) SPK=144 
      IF(LIQLC(LOC).EQ.0.OR..NOT.TOTNG(VASE)) GO TO 1300
      CALL RSPEK(145) 
      PROP(VASE)=2
      FIXED(VASE)=-1
      GO TO 2160
C 
C  BLAST.  NO EFFECT UNLESS YOU'VE GOT DYNAMITE, WHICH IS A NEAT TRICK! 
C 
 2640 IF(PROP(ROD2).LT.0.OR..NOT.CLOSED) GO TO 1300 
      BONUS=133 
      IF(LOC.EQ.115) BONUS=134
      IF(HERE(ROD2)) BONUS=135
      CALL RSPEK(BONUS) 
      GO TO 2990
C 
C  SCORE.  CALL THE SCORING SECTION.
C 
 2650 SCORNG=.TRUE. 
      CALL SCORING
      SCORNG=.FALSE.
      WRITE(CRT,2670) SCORE,MXSCOR
 2670 FORMAT("If you were to quit now, you would score",I4
     &      ," out of a possible",I4," points.")
      GAVEUP=YES(143,54,54) 
      GO TO 2530
C 
C  FEE FIE FOE FOO (AND FUM).  ADVANCE TO NEXT STATE IF GIVEN IN PROPER ORDER.
C  LOOK UP WD1 IN SECTION 3 OF VOCAB TO DETERMINE WHICH WORD WE'VE GOT.  LAST 
C  WORD ZIPS THE EGGS BACK TO THE GIANT ROOM (UNLESS ALREADY THERE).
C 
 2680 CALL VOCAB(WD1,3,K,INDEX) 
      SPK=42
      IF(FOOBAR.EQ.1-K) GO TO 2690
      IF(FOOBAR.NE.0) SPK=151 
      GO TO 1300
C 
 2690 FOOBAR=K
      IF(K.NE.4) GO TO 1280 
      FOOBAR=0
      IF(PLACE(EGGS).EQ.PLAC(EGGS)
     &      .OR.(TOTNG(EGGS).AND.LOC.EQ.PLAC(EGGS))) GO TO 1300 
C 
C  BRING BACK TROLL IF WE STEAL THE EGGS BACK FROM HIM BEFORE CROSSING. 
C 
      IF(PLACE(EGGS).EQ.0.AND.PLACE(TROLL).EQ.0.AND.PROP(TROLL).EQ.0) 
     &      PROP(TROLL)=1 
      K=2 
      IF(HERE(EGGS)) K=1
      IF(LOC.EQ.PLAC(EGGS)) K=0 
      CALL MOVE(EGGS,PLAC(EGGS))
      CALL PSPEK(EGGS,K)
      GO TO 1310
C 
C  BRIEF.  INTRANSITIVE ONLY.  SUPPRESS LONG DESCRIPTIONS AFTER FIRST TIME. 
C 
 2700 SPK=156 
      ABBNUM=10000
      DETAIL=3
      GO TO 1300
C 
C  READ.  MAGAZINES IN DWARVISH, MESSAGE WE'VE SEEN, AND . . . OYSTER?
C 
 2710 IF(HERE(MAGZIN)) OBJ=MAGZIN 
      IF(HERE(TABLET)) OBJ=OBJ*100+TABLET 
      IF(HERE(MESSAG)) OBJ=OBJ*100+MESSAG 
      IF(CLOSED.AND.TOTNG(OYSTER)) OBJ=OYSTER 
      IF(OBJ.GT.100.OR.OBJ.EQ.0.OR.DARK(0)) GO TO 2030
C 
 2720 IF(DARK(0)) GO TO 1660
      IF(OBJ.EQ.MAGZIN) SPK=190 
      IF(OBJ.EQ.TABLET) SPK=196 
      IF(OBJ.EQ.MESSAG) SPK=191 
      IF(OBJ.EQ.OYSTER.AND.HINTED(2).AND.TOTNG(OYSTER)) SPK=194 
      IF(OBJ.NE.OYSTER.OR.HINTED(2).OR..NOT.TOTNG(OYSTER) 
     &      .OR..NOT.CLOSED) GO TO 1300 
      HINTED(2)=YES(192,193,54) 
      GO TO 1310
C 
C  BREAK.  ONLY WORKS FOR MIRROR IN REPOSITORY AND, OF COURSE, THE VASE.
C 
 2730 IF(OBJ.EQ.MIRROR) SPK=148 
      IF(OBJ.EQ.VASE.AND.PROP(VASE).EQ.0) GO TO 2740
      IF(OBJ.NE.MIRROR.OR..NOT.CLOSED) GO TO 1300 
      CALL RSPEK(197) 
      GO TO 2790
C 
 2740 SPK=198 
      IF(TOTNG(VASE)) CALL DROP(VASE,LOC) 
      PROP(VASE)=2
      FIXED(VASE)=-1
      GO TO 1300
C 
C  WAKE.  ONLY USE IS TO DISTURB THE DWARVES. 
C 
 2750 IF(OBJ.NE.DWARF.OR..NOT.CLOSED) GO TO 1300
      CALL RSPEK(199) 
      GO TO 2790
C 
C SUSPEND.  USE 'GO' TO CONTINUE. 
C 
 2760 CALL SUSPEND
      GO TO 1230
C 
C HOURS.  DISPLAY HOURS IF ANY. 
C 
 2770 CALL MSPEK(6) 
      CALL HOURS
      GO TO 1310
C 
C  YOU CAN'T EXPLORE THE CAVE WITHOUT A LAMP. MUST QUIT.
C 
 2780 CALL RSPEK(185) 
      GAVEUP=.TRUE. 
      GO TO 2990
C 
C  OH DEAR, HE'S DISTURBED THE DWARVES. 
C 
 2790 CALL RSPEK(136) 
      GO TO 2990
C 
C  MOVE COMMAND (WHERE?)
C 
 2900 SPK=43
      GO TO 1300
C 
C  TURN COMMAND (WHICH WAY?)
C 
 2910 SPK=80
      GO TO 1300
C 
C  WAIT COMMAND (ASK WHY) 
C 
 2920 SPK=217 
      GO TO 1300
C 
C  WHY? (WHY NOT?)
C 
 2930 IF(PCT(50)) THEN
        SPK=218 
      ELSE
        SPK=219 
      ENDIF 
      GO TO 1300
C 
C  TALLY UP FINAL SCORE AND END.
C 
 2990 CALL SCORING
C 
      RETURN
      END 

