#!/usr/bin/env python3
"""Turn the files taken off the TOPS-20 pack into C source.

Three things go into the program:

  * ADVENTURE.EXE   the game itself, 143 pages of FORTRAN-10 code and data
  * FOROTS.EXE      the FORTRAN object time system, which the game pulls in
                    at run time with GETSEG and which lives at 0400000
  * the data files   ADVTXT.BIN and friends, which the game opens by name

The first two become memory images, the third a small read-only file
system the monitor consults before it looks on the real disk.
"""
import os, struct, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DUMP = os.path.join(os.path.dirname(ROOT), "dump_original")
SRC  = os.path.join(ROOT, "src")

def load36(p):
    d = open(p, "rb").read()
    return [struct.unpack(">Q", d[i:i+8])[0] for i in range(0, len(d), 8)]

def load_exe(path):
    """Return {process page: [512 words]} and the start address."""
    w = load36(path)
    pages = {}
    start = None
    i = 0
    while i < len(w):
        typ = w[i] >> 18
        ln  = w[i] & 0o777777
        if typ == 0o1776:                      # page directory
            j = i + 1
            while j < i + ln:
                w1, w2 = w[j], w[j+1]
                fpage = w1 & 0o777777777
                ppage = w2 & 0o777777777
                rpt   = w2 >> 27
                for k in range(rpt + 1):
                    lo = (fpage + k) * 512
                    if lo >= len(w):
                        continue               # page past end of file
                    pages[ppage + k] = w[lo:lo+512] + [0] * (512 - len(w[lo:lo+512]))
                j += 2
        elif typ == 0o1775:                    # entry vector
            start = w[i+2] & 0o777777
        elif typ == 0o1777:
            break
        i += ln
    return pages, start

def runs(pages):
    """Collapse a page map into (address, [words]) runs."""
    out = []
    for p in sorted(pages):
        if out and out[-1][0] + len(out[-1][1]) == p * 512:
            out[-1][1].extend(pages[p])
        else:
            out.append((p * 512, list(pages[p])))
    return out

def emit_words(fp, words, per=6):
    for i in range(0, len(words), per):
        fp.write("".join("0%012o," % w for w in words[i:i+per]) + "\n")

def emit_image(fp, name, rs):
    fp.write("const w36 %s[] = {\n" % name)
    for addr, words in rs:
        fp.write("0%o,0%o,\n" % (addr, len(words)))
        emit_words(fp, words)
    fp.write("0,0};\n\n")

# ------------------------------------------------------------------ #
game_pages, game_start = load_exe(os.path.join(DUMP, "ADVENTURE.EXE.36"))
forots_pages, _ = load_exe(os.path.join(DUMP, "FOROTS.EXE.36"))

# GETSEG SYS:FOROTS maps file pages 2-27(octal) at 0400000-0425777; that
# is what the TOPS-20 page map on the live system shows, and it is what
# FOROTS.EXE's own directory asks for.  Keep only that window.
hiseg = {p: w for p, w in forots_pages.items() if 0o400 <= p <= 0o425}

print("game:   %d pages, start %o" % (len(game_pages), game_start))
print("forots: %d pages at %o..%o" % (len(hiseg), min(hiseg), max(hiseg)))

with open(os.path.join(SRC, "image.c"), "w") as fp:
    fp.write("/* Generated by tools/mkimage.py -- do not edit.\n"
             " * <GAMES>ADVENTURE.EXE.1 and the FOROTS high segment,\n"
             " * both taken verbatim off the TOPS-20 pack. */\n"
             '#include "pdp10.h"\n\n')
    emit_image(fp, "image_data", runs(game_pages))
    emit_image(fp, "forots_data", runs(hiseg))
    fp.write("const int image_start = 0%o;\n" % game_start)

# ------------------------------------------------------------------ #
# The data files.  ADVTXT.BIN and ADVVAR.BIN are the game's databases;
# the .DAT and .LOG files are the wizard list and the scoreboard.
FILES = [
    ("ADVTXT.BIN", "ADVTXT.BIN.36", 36),
    ("ADVVAR.BIN", "ADVVAR.BIN.36", 36),
    ("ADVGRP.LOG", "ADVGRP.LOG.36", 36),
    ("ADVWIN.LOG", "ADVWIN.LOG.36", 36),
    ("ADVWIZ.DAT", "ADVWIZ.DAT.36", 36),
    ("WIZDEF.DAT", "WIZDEF.DAT.36", 36),
]

with open(os.path.join(SRC, "data.c"), "w") as fp:
    fp.write("/* Generated by tools/mkimage.py -- do not edit.\n"
             " * The game's data files, as they were in <GAMES>. */\n"
             '#include "pdp10.h"\n\n')
    names = []
    for name, fn, bsize in FILES:
        path = os.path.join(DUMP, fn)
        words = load36(path)
        sym = name.replace(".", "_").lower()
        fp.write("static const w36 %s[] = {\n" % sym)
        emit_words(fp, words)
        fp.write("};\n\n")
        names.append((name, sym, len(words)))
        print("%-12s %6d words" % (name, len(words)))
    fp.write("const builtin_file_t builtin_files[] = {\n")
    for name, sym, n in names:
        fp.write('    { "%s", %s, %d },\n' % (name, sym, n))
    fp.write("    { 0, 0, 0 }\n};\n")
