DELETE-FILE AIC:BRF
DELETE-FILE AIC:LIST
DELETE-FILE AIC:PROG
DELETE-FILE AICF:BRF
DELETE-FILE AICF:LIST
DELETE-FILE ADV-INTER-CB-MJ:PROG
DELETE-FILE AEC:BRF
DELETE-FILE AEC:LIST
DELETE-FILE ADV-EDIT-CB-MJ:PROG
BASIC || READY\s*$
DEFAULT-INTEGER
TABLE-SIZES 1500,35000
COMPILE ADV-INTER-CB-MJ:SYMB,"AIC:LIST","AIC:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
BASIC || READY\s*$
DEFAULT-INTEGER
TABLE-SIZES 1500,35000
COMPILE AICF:SYMB,"AICF:LIST","AICF:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
BASIC || READY\s*$
DEFAULT-INTEGER
TABLE-SIZES 1500,35000
COMPILE ADV-EDIT-CB-MJ:SYMB,"AEC:LIST","AEC:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD AIC:BRF || \* ?$
LOAD LIBRARY-MJ:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "AIC:PROG" || \* ?$
EXIT || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD AICF:BRF || \* ?$
LOAD LIBRARY-MJ:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "ADV-INTER-CB-MJ:PROG" || \* ?$
EXIT || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD AEC:BRF || \* ?$
LOAD LIBRARY-MJ:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "ADV-EDIT-CB-MJ:PROG" || \* ?$
EXIT || @ ?$
