.TH EMPIRE 6
.SH NAME
empire \- global simulation game
.SH SYNOPSIS
.B empire
.SH DESCRIPTION
.PP
Empire is a global economic/political/military simulation game wherein
players, representing national governments, make "real-time"
decisions concerning resource allocation, national goals, international
diplomatic efforts, etc.
Extensive records are kept for all players.
.PP
WARNING -- This game is not only addictive but often peels back
the thin veneer of civilization that hides the maniac within...
.SH AUTHOR
Peter S. Langston
