#!/usr/bin/env python3
r"""Build src/image.c: the TOPS-10 core image of HAUNT.

Source
------
    ..\work\HAUNT.EXE.extracted   = DSKB:[1,4]HAUNT.EXE, 1432 blocks

extracted offline from dskb.dsk of the Steuben Technologies TOPS-10 7.03
pack shipped with eXo's Haunt package.  The game is John E. Laird's OPS4
original -- "Version 4.6, 6-21-82" -- not the unfinished OPS5 rewrite.

File format
-----------
TOPS-10 .EXE.  Word 0 of the file is <1776,,n>, the length of a page-map
directory of n words, terminated by <1777,,1>.  The directory holds pairs

    <flags,,file page>  <count,,process page>

where the page count is the top 9 bits of the second word's left half,
plus one, and a file page of 0 means "zero fill".  Haunt's map:

    file 1-18    -> process 0-17     18 pages
    zero         -> process 18        1
    file 19      -> process 19        1
    zero         -> process 20        1
    file 20-41   -> process 21-42    22
    zero         -> process 43        1
    file 42-252  -> process 44-254   211
    file 253-357 -> process 256-360  105   flags 600000: the high segment

File pages 1..357 are used contiguously; with page 0 for the directory
itself that is 358 pages of 4 blocks = 1432, exactly the size TOPS-10
reports.  Process page 256 is word 400000, the high segment boundary,
and .JBREL/.JBHRL in the loaded image agree with both segment limits.

Output
------
image_data is a chain of <addr, count> headers each followed by count
words, terminated by <0,0>.  Only non-zero runs are emitted.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, '..', '..', 'work', 'HAUNT.EXE.extracted')
OUT  = os.path.join(HERE, '..', 'src', 'image.c')
PAGE = 512
GAP  = 24          # zero words tolerated inside a run before splitting


def load_exe(path):
    b = open(path, 'rb').read()
    ws = [int.from_bytes(b[i:i+8], 'little') for i in range(0, len(b), 8)]
    if (ws[0] >> 18) != 0o1776:
        sys.exit('not an EXE page map: %o' % (ws[0] >> 18))
    dlen = ws[0] & 0o777777
    if (ws[dlen] >> 18) != 0o1777:
        sys.exit('missing 1777 terminator at %d' % dlen)
    mem, npages = {}, 0
    for k in range(1, dlen, 2):
        a, b2 = ws[k], ws[k+1]
        fpage, ppage = a & 0o777777, b2 & 0o777777
        n = ((b2 >> 18) >> 9) + 1
        npages += n
        if fpage == 0:
            continue
        for i in range(n):
            src, dst = (fpage + i) * PAGE, (ppage + i) * PAGE
            for j in range(PAGE):
                w = ws[src + j] if src + j < len(ws) else 0
                if w:
                    mem[dst + j] = w
    return mem, npages, ws


def runs(mem):
    out, addrs = [], sorted(mem)
    cur, start, prev = [], addrs[0], addrs[0]
    for a in addrs:
        if a - prev > GAP:
            out.append((start, cur)); cur, start = [], a
        else:
            cur.extend(mem.get(x, 0) for x in range(prev + 1, a))
        cur.append(mem[a]); prev = a
    out.append((start, cur))
    return out


def main():
    mem, npages, ws = load_exe(SRC)
    blocks = runs(mem)
    hi = max(mem)
    start = ws[0o120] & 0o777777 if 0o120 < len(ws) else 0
    start = mem.get(0o120, 0) & 0o777777
    hiseg = mem.get(0o115, 0) & 0o777777
    with open(OUT, 'w') as f:
        f.write('/* image.c -- generated by tools/mkimage.py; do not edit.\n'
                ' * HAUNT.EXE, John E. Laird, version 4.6, 6-21-82 (OPS4).\n'
                ' * %d pages, %d non-zero words in %d runs, top %o.\n */\n'
                % (npages, len(mem), len(blocks), hi))
        f.write('#include "pdp10.h"\n\n')
        f.write('const int image_start = 0%o;\n' % start)
        f.write('const int image_hisegtop = 0%o;\n\n' % hiseg)
        f.write('const w36 image_data[] = {\n')
        for a, data in blocks:
            f.write('/*%06o*/ 0%o, 0%o,\n' % (a, a, len(data)))
            for i in range(0, len(data), 6):
                f.write('  ' + ', '.join('0%o' % x for x in data[i:i+6]) + ',\n')
        f.write('  0, 0\n};\n')
    print('pages %d, non-zero %d, runs %d, top %o, start %o, hisegtop %o'
          % (npages, len(mem), len(blocks), hi, start, hiseg))
    print('wrote %s' % os.path.normpath(OUT))


if __name__ == '__main__':
    main()
