DELETE-FILE DOD:BRF
DELETE-FILE DOD:LIST
DELETE-FILE DOD:PROG
DELETE-FILE DODF:BRF
DELETE-FILE DODF:LIST
DELETE-FILE DOD-ENB:PROG
BASIC || READY\s*$
TABLE-SIZES 1500,35000
COMPILE DOD-ENB:SYMB,"DOD:LIST","DOD:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
BASIC || READY\s*$
TABLE-SIZES 1500,35000
COMPILE DODF:SYMB,"DODF:LIST","DODF:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD DODF:BRF || \* ?$
LOAD LIBRARY-MJ:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "DOD-ENB:PROG" || \* ?$
EXIT || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD DOD:BRF || \* ?$
LOAD LIBRARY-MJ:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "DOD:PROG" || \* ?$
EXIT || @ ?$
