.TH ORACLE 6
.SH NAME
oracle \- answers those hard questions
.SH SYNOPSIS
.B oracle
.SH DESCRIPTION
.PP
Oracle solves an annoying problem in Computer Science Appreciation.
Have you ever given a snazzy demo only to have your victim say,
"Let's ask the computer what the meaning of life is!" or some
such?  Well, now you have a way out of that one; ask the oracle!
The Oracle answers the trivial questions directly and uses an
amusing heuristic to answer the tough ones.
.SH AUTHOR
Peter S. Langston
