      IMPLICIT INTEGER(A-Z)
      LOGICAL DSEEN,BLKLIN,SAVBLN,HINTED,YES,START
C
      COMMON /TXTCOM/ RTEXT,LINES
      COMMON /VOCCOM/ KTAB,ATAB,TABSIZ
      COMMON /PLACOM/ ATLOC,LINK,PLACE,FIXED,COND,PROP,LOC,LAMP,HOLDNG
      COMMON /MTXCOM/ MTEXT
      COMMON /PTXCOM/ PTEXT
      COMMON /ABBCOM/ ABB
      COMMON /WIZCOM/ WKDAY,WKEND,HOLID,HBEGIN,HEND,HNAME,
     1SHORT,MAGIC,MAGNM,LATNCY,SAVED,SAVET,SETUP
      COMMON /IOSCOM/ TTYI,TTYO,BLKLIN,DBFI,DBINIT,DBSAVE
      COMMON /MTDCOM/ MTDTXT
      COMMON /RANCOM/ R
      COMMON /MSCCOM/ TRAVEL,LTEXT,STEXT,KEY,ACTSPK,
     1CTEXT,CVAL,HINTLC,HINTED,HINTS,DSEEN,DLOC,CLSSES,HNTMAX,
     2PLAC,FIXD,MAXTRS,TALLY,TALLY2,
     3KEYS,GRATE,CAGE,ROD,ROD2,STEPS,BIRD,DOOR,PILLOW,SNAKE,
     4FISSUR,TABLET,CLAM,OYSTER,MAGZIN,DWARF,KNIFE,FOOD,BOTTLE,
     5WATER,OIL,PLANT,PLANT2,AXE,MIRROR,DRAGON,CHASM,TROLL,TROLL2,
     6BEAR,MESSAG,VEND,BATTER,NUGGET,COINS,CHEST,EGGS,TRIDNT,VASE,
     7EMRALD,PYRAM,PEARL,RUG,CHAIN,BACK,LOOK,CAVE,NULL,ENTRNC,
     8DPRSSN,SAY,LOCK,THROW,FIND,INVENT,CHLOC,CHLOC2,DFLAG,DALTLC,
     9SUSPND,TURNS,LMWARN,IWEST,KNFLOC,DETAIL,ABBNUM,SCORNG,NUMDIE,
     1DKILL,FOOBAR,BONUS,CLOCK1,CLOCK2,CLOSNG,PANIC,
     2DEMO,HINT,LIMIT,NEWLOC,OBJ,ODLOC,OLDLC2,OLDLOC,SCORE,
     3SPICES,STICK,VERB,WD1,WD1X,WD2,WD2X,WZDARK,
     4ATTACK,DTOTAL,FOO,HINTM3,I,J,K,K1,K2,KK,KQ,L,LL,MXSCOR,SPK,TK,
     5YEA,CLOSED,GAVEUP,MAXDIE,XXD,XXT,YYD,YYT
C
      DIMENSION LINES(9800)
      DIMENSION TRAVEL(750)
      DIMENSION KTAB(300),ATAB(300)
      DIMENSION LTEXT(150),STEXT(150),KEY(150),COND(150),ABB(150),
     1ATLOC(150)
      DIMENSION PLAC(100),PLACE(100),FIXD(100),FIXED(100),LINK(200),
     1PTEXT(100),PROP(100)
      DIMENSION ACTSPK(35)
      DIMENSION RTEXT(205)
      DIMENSION CTEXT(12),CVAL(12)
      DIMENSION HINTLC(20),HINTED(20),HINTS(20,4)
      DIMENSION MTEXT(35)
      DIMENSION TK(20),DSEEN(6),DLOC(6),ODLOC(6),HNAME(20)
      DIMENSION MTDTXT(100)
      DIMENSION TEXT(70),FNAME(10),FDUMMY(10)
C
      DATA LINSIZ/9800/,TRVSIZ/750/,LOCSIZ/150/,
     1VRBSIZ/35/,RTXSIZ/205/,CLSMAX/12/,HNTSIZ/20/,MAGSIZ/35/
C
      LOGICAL TOTING,HERE,AT,BITSET,DARK,WZDARK,LMWARN,CLOSNG,PANIC,
     1CLOSED,GAVEUP,SCORNG,DEMO,YEA,FORCED,PCT
C
C  PROBEM - NOT PART OF THE GAME.  ADVWIZ CLEARS MTDTXT TO ZERO, WHILE
C  MOTD READS IT AS A CHAIN ENDING AT A NEGATIVE WORD, SO THE CHAIN RUNS
C  OFF THE FRONT OF THE ARRAY.  THIS SHOWS WHAT THE ORIGINAL MACHINE
C  MAKES OF THAT.  RUN IT WITH A SHORT TIME LIMIT.
C
      LOGICAL QALT
C
      CALL IOINIT(0)
      READ(DBINIT)RTEXT,LINES,KTAB,ATAB,TABSIZ,ATLOC,LINK,PLACE,
     1FIXED,COND,PROP,LOC,LAMP,HOLDNG,MTEXT,PTEXT,ABB,WKDAY,WKEND,
     2HOLID,HBEGIN,HEND,HNAME,SHORT,MAGIC,MAGNM,LATNCY,SAVED,
     3SAVET,SETUP,TTYI,TTYO,BLKLIN,DBFI,DBINIT,DBSAVE,
     4MTDTXT,R,TRAVEL,LTEXT,STEXT,
     5KEY,ACTSPK,CTEXT,CVAL,HINTLC,HINTED,HINTS,DSEEN,DLOC,CLSSES,
     6HNTMAX,PLAC,FIXD,MAXTRS,TALLY,TALLY2,
     7KEYS,GRATE,CAGE,ROD,ROD2,STEPS,BIRD,DOOR,PILLOW,SNAKE,
     8FISSUR,TABLET,CLAM,OYSTER,MAGZIN,DWARF,KNIFE,FOOD,BOTTLE,
     9WATER,OIL,PLANT,PLANT2,AXE,MIRROR,DRAGON,CHASM,TROLL,TROLL2,
     1BEAR,MESSAG,VEND,BATTER,NUGGET,COINS,CHEST,EGGS,TRIDNT,VASE,
     2EMRALD,PYRAM,PEARL,RUG,CHAIN,BACK,LOOK,CAVE,NULL,ENTRNC,
     3DPRSSN,SAY,LOCK,THROW,FIND,INVENT,CHLOC,CHLOC2,DFLAG,DALTLC,
     4SUSPND,TURNS,LMWARN,IWEST,KNFLOC,DETAIL,ABBNUM,SCORNG,NUMDIE,
     5DKILL,FOOBAR,BONUS,CLOCK1,CLOCK2,CLOSNG,PANIC,
     6DEMO,HINT,LIMIT,NEWLOC,OBJ,ODLOC,OLDLC2,OLDLOC,SCORE,
     7SPICES,STICK,VERB,WD1,WD1X,WD2,WD2X,WZDARK,
     8ATTACK,DTOTAL,FOO,HINTM3,I,J,K,K1,K2,KK,KQ,L,LL,MXSCOR,SPK,TK,
     9YEA,CLOSED,GAVEUP,MAXDIE,XXD,XXT,YYD,YYT
      WRITE(TTYO,1)MTDTXT(1),MTDTXT(2),MTDTXT(3)
1     FORMAT(' PROBEM: MTDTXT(1..3) =',3I8)
      QALT=.FALSE.
      CALL MOTD(QALT)
      WRITE(TTYO,2)
2     FORMAT(' PROBEM: MOTD RETURNED')
      STOP
      END
