C  iofil.f -- GENERATED by tools/convert.py from
C  ../src_original/IOFIL.FOR.  Do not edit: every change belongs in
C  tools/convert.py or tools/patches.py.  Run
C      python tools/showdiff.py -a
C  for a line-by-line account of every difference from the
C  original.
C	THESE ROUTINES HOPEFULLY DO WHAT THE OLD LIBRARY IFIL
C	AND OFIL ROUTINES DID. WRITTEN AS REPLACEMENTS BY
C	PAUL T. ROBINSON, WESLEYAN UNIV. JUNE 1980
C	DECUS CONVERSION PROGRAMMER
      SUBROUTINE IFILE(IUNIT, NAME, IEXT)
      IMPLICIT INTEGER(A-Z)
      DIMENSION DNAME(2)
      DNAME(1) = NAME
      DNAME(2) = IEXT
      CALL OPNSEQ(IUNIT, DNAME, 2, 1)
      RETURN
      END

      SUBROUTINE OFILE(IUNIT,NAME,IEXT)
      IMPLICIT INTEGER(A-Z)
      DIMENSION DNAME(2)
      DNAME(1) = NAME
      DNAME(2) = IEXT
      CALL OPNSEQ(IUNIT, DNAME, 2, 2)
      RETURN
      END
