.TH BOLO 6
.SH NAME
bolo \- automated gladiator game/language programs
.SH SYNOPSES
.B bolo
b_prog b_prog [ b_prog ... ]
.bd bcc
[\c
.bd \-d\c
] [\c
.bd \-O\c
] files ... [\c
.bd \-o\c
filename]
.bd bdb
[ b_prog ... ]
.bd bs
[\c
.bd \-d\c
] files ... [\c
.bd \-o\c
filename]
.SH DESCRIPTION
.PP
In this game participants use a simple programming language to design
"intelligent" tanks (Bolos) for gladiatorial combat.  Tools are
provided for debugging and testing the Bolo programs as well as the
eventual showdown in the arena.  This game should be used to make
learning the concepts of computer programming fun.  Once the tanks
are programmed they are turned loose in the arena and the players
cheer their creations on...
.PP
The document "\fIB. M. Pages\fR" contains extended Bolo manual pages
for the programs \fIbolo\fR, \fIbcc\fR, \fIbdb\fR, and \fIbs\fR.
The document "\fIBolo Programming Language Reference Manual\fR" is the
strict definition of the Bolo command language and the
"\fIBolo Owner's Guide\fR" (which comes with every new Bolo) contains
much useful information and safety tips.
.SH AUTHOR
Peter S. Langston
.SH SEE ALSO
"\fIB. M. Pages\fR",
"\fIBolo Programming Language Reference Manual\fR",
"\fIBolo Owner's Guide\fR"
