DELETE-FILE AMJ:BRF
DELETE-FILE AMJ:LIST
DELETE-FILE AMJ:PROG
DELETE-FILE AMJF:BRF
DELETE-FILE AMJF:LIST
DELETE-FILE AMJS:BRF
DELETE-FILE AMJS:LIST
DELETE-FILE AMJS:PROG
DELETE-FILE ADVENTURE-MJ:PROG
PASCAL || \$ ?$
COMPILE ADVENTURE-MJ:SYMB,"AMJ:LIST","AMJ:BRF" || COMPILATION TIME(.|\n)*\$ ?$
EXIT || @ ?$
PASCAL || \$ ?$
COMPILE AMJF:SYMB,"AMJF:LIST","AMJF:BRF" || COMPILATION TIME(.|\n)*\$ ?$
EXIT || @ ?$
PASCAL || \$ ?$
COMPILE AMJS:SYMB,"AMJS:LIST","AMJS:BRF" || COMPILATION TIME(.|\n)*\$ ?$
EXIT || @ ?$
NRL || \* ?$
SIZE 1500 || \* ?$
LOAD AMJF:BRF || \* ?$
LOAD EXTRA-PAS-LIB || \* ?$
LOAD PASCAL-LIB-J || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "ADVENTURE-MJ:PROG" || \* ?$
EXIT || @ ?$
NRL || \* ?$
SIZE 1500 || \* ?$
LOAD AMJ:BRF || \* ?$
LOAD EXTRA-PAS-LIB || \* ?$
LOAD PASCAL-LIB-J || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "AMJ:PROG" || \* ?$
EXIT || @ ?$
NRL || \* ?$
SIZE 1500 || \* ?$
LOAD AMJS:BRF || \* ?$
LOAD EXTRA-PAS-LIB || \* ?$
LOAD PASCAL-LIB-J || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "AMJS:PROG" || \* ?$
EXIT || @ ?$
