.TH STARDREK 6
.SH NAME
stardrek \- 3-D excitement
.SH SYNOPSIS
.B stardrek
.SH DESCRIPTION
.PP
.I StarDrek
is unrelated to the numerous "star-trek" games that abound except
in inspiration.  It is a three-dimensional space game played in the
volume of a four space toroid, [strictly speaking it is a three-space
toroid in the same sense that a doughnut is a two-space toroid, but
this sounds better].
.PP
Your mission in
.I StarDrek
is to check out the various ships whose coordinates are given in
your mission vector and dispose of them properly.
"Properly" means blast them to smithereens in the case of Klingons, Romulans,
Vallicians  and  Rigellians.  In the case of Nubian Freighters, the "proper"
thing to do is to drag them to StarBase with your tractor-pressor and then
request a salvage operation (and then it's anybody's guess as to what the
StarFleet brass want to do with ostensibly friendly freighters at StarBase...)
.PP
Each different type of ship has different characteristics and vulnerabilities;
e.g. the Vallicians understand photon torpedos well and consequently use very
powerful ones and are good at withstanding torpedo attacks; on the other hand,
they don't have very good phasers and are relatively vulnerable to them.
As you gain experience you will learn how to deal with each different race.
.PP
When you run the program you will be asked:
.br
.B info|see|play|who|resign|exit|quit?
.PP
These represent:
.TP 10
.B info
print out playing instructions (lengthy)
.TP
.B see
show the ships currently in the StarFleet and their records
.TP
.B play
go out on a mission
.TP
.B who
show the personnel currently in the StarFleet and their records
.TP
.B resign
remove your name from the StarFleet personnel records
.TP
.B exit
return to the shell
.TP
.B quit
synonym for exit
.PP
.SH AUTHOR
Peter S. Langston
.SH SEE ALSO
documentation provided in the game.
