#!/usr/bin/env python
"""Turn the octal-transfer files of FisK into a C source image.

Each .DMP is a WAITS two-segment core image written as one 12-digit octal
word per line:

    file word 0      .. LOWWORDS-1   ->  low  segment, address 0o74 upward
    file word LOWWORDS.. end         ->  high segment, address 0o400000 upward

(Locations 0-0o73 are the accumulators and the monitor-only part of the job
data area; a saved image starts at the vestigial job data area, 0o74.  The
split is confirmed by the canonical SAIL entry sequence

        JRST  START / JRST  REENTER / TDZA 1,1 / MOVEI 1,1

landing exactly on .JBSA, and by HRRZ 16,115 reading the core size.)

The .TXT is the game's message source, five 7-bit ASCII characters per
36-bit word.  The playable image already carries its own copy of that data
in the low segment, obfuscated with XOR 0o64, but the monitor still offers
FISK.TXT on DSK: in case a build asks for it.

    usage: mkimage.py out.c  name=dump.dmp[,text.txt] ...
"""
import sys

LOWWORDS = 56704          # words of low segment present in the file
LOWBASE  = 0o74           # address of file word 0
HIBASE   = 0o400000


def rdoct(path):
    return [int(l, 8) for l in open(path) if l.strip()]


def unpack7(words):
    b = bytearray()
    for w in words:
        for i in range(5):
            b.append((w >> (29 - 7 * i)) & 0x7f)
    return bytes(b)


def carray(f, name, data, per=8):
    f.write("static const unsigned long long %s[%d] = {\n" % (name, len(data)))
    for i in range(0, len(data), per):
        f.write("".join("0x%09XULL," % w for w in data[i:i + per]) + "\n")
    f.write("};\n\n")


def barray(f, name, data, per=20):
    f.write("static const unsigned char %s[%d] = {\n" % (name, len(data)))
    for i in range(0, len(data), per):
        f.write("".join("%d," % c for c in data[i:i + per]) + "\n")
    f.write("};\n\n")


def main():
    out, specs = sys.argv[1], sys.argv[2:]
    if not specs:
        sys.exit(__doc__)
    entries = []
    with open(out, "w") as f:
        f.write("/* generated by tools/mkimage.py - do not edit */\n")
        f.write('#include "fisk.h"\n\n')
        for spec in specs:
            name, files = spec.split("=", 1)
            parts = files.split(",")
            w = rdoct(parts[0])
            if len(w) < LOWWORDS:
                sys.exit("%s: dump too short" % parts[0])
            low, high = w[:LOWWORDS], w[LOWWORDS:]
            text = unpack7(rdoct(parts[1])).rstrip(b"\x00") if len(parts) > 1 else b""
            tag = name.replace(".", "_").replace("-", "_")
            carray(f, "low_" + tag, low)
            carray(f, "high_" + tag, high)
            barray(f, "txt_" + tag, text if text else b"\0")
            entries.append((name, tag, len(low), len(high), len(text)))
            sys.stderr.write("%-8s low %d high %d text %d\n"
                             % (name, len(low), len(high), len(text)))
        f.write("const Image fisk_images[] = {\n")
        for name, tag, nl, nh, nt in entries:
            f.write('    { "%s", low_%s, 0%o, %d, high_%s, 0%o, %d, txt_%s, %d },\n'
                    % (name, tag, LOWBASE, nl, tag, HIBASE, nh, tag, nt))
        f.write("};\n")
        f.write("const int fisk_nimages = %d;\n" % len(entries))


main()
