ASMB,R,L,T,B
      HED             *** UMOVE - BYTE TRANSFER ROUTINE ***
*
*
* PROGRAM:  UMOVE    (UTILITY:  MOVE BYTES)
* NAME:     LARRY SCHUCK
* DATE:     1979-05-18
* PURPOSE:  MOVE A GIVEN NUMBER OF BYTES FROM ONE LOCATION TO ANOTHER
* CALL:     CALL UMOVE(N,SOURCE,SOFF,DEST,DOFF)
* PARAMS:   N      => NUMBER OF BYTES TO BE MOVED
*           SOURCE => NAME OF VARIABLE OR ARRAY WHICH CONTAINS DATA TO
*                     BE MOVED
*           SOFF   => OFFSET OF DATA FROM START OF SOURCE
*                     (EG. 2ND BYTE OF SOURCE HAS OFFSET = 1)
*           DEST   => NAME OF VARIABLE OR ARRAY WHICH IS TO RECEIVE DATA
*           DOFF   => OFFSET FROM START OF DESTINATION WHERE DATA IS TO
*                     BE RECEIVED
*
*
      NAM UMOVE,7 (LMS) 1979-05-18
      ENT UMOVE
      EXT .ENTR
*
COUNT BSS 1
BUFIN BSS 1
OFS1  BSS 1
BOUT  BSS 1
OFS2  BSS 1
UMOVE NOP           ENTRY POINT
      JSB .ENTR     PICK UP INPUT PARAM ADDRESSES
      DEF COUNT
*
      LDA BUFIN     SET UP BYTE ADDRESS WITHIN
      CLE,ELA       SOURCE BUFFER
      ADA OFS1,I
      LDB BOUT      DO SAME FOR DEST BUFFER
      CLE,ELB
      ADB OFS2,I
      MBT COUNT,I   NOW MOVE BYTES
      JMP UMOVE,I     RETURN TO MAIN LINE
      END
