C     FTN5
C======================================================================C
C                                                                      C
C      AA       DDDDDDDDD     VV        VV    00000000         11      C
C     AAAA      DDDDDDDDDD    VV        VV   0000000000       111      C
C    AA  AA     DD       DD   VV        VV  00        00     1111      C
C   AA    AA    DD        DD  VV        VV  00        00       11      C
C  AA      AA   DD        DD  VV        VV  00        00       11      C
C AA        AA  DD        DD  VV        VV  00        00       11      C
C AAAAAAAAAAAA  DD        DD   VV      VV   00        00       11      C
C AAAAAAAAAAAA  DD        DD   VV      VV   00        00       11      C
C AA        AA  DD        DD     VV  VV     00        00       11      C
C AA        AA  DD       DD      VV  VV     00        00       11      C
C AA        AA  DDDDDDDDDD         VV        0000000000    1111111111  C
C AA        AA  DDDDDDDDD          VV         00000000     1111111111  C
C                                                                      C
C======================================================================C
C                                                                      C
C REVISION LIST:                                                       C
C                                                                      C
C======================================================================C
C --DATE-- --BY-- -- D E S C R I P T I O N --                          C
C                                                                      C
C  3/07/81 AW     -ORIGINAL VERSION-                                   C
C                                                                      C
C======================================================================C
      PROGRAM ADVEN
C
C     Modified for HP-21 MXE by Beasley   Sep 78
C     Modified for RTE-6/VM  by Dan Hallock Sep 2025
C
C  ADVENTURES
C
C MODIFIED BY KENT BLACKETT
C             ENGINEERING SYSTEMS GROUP
C             DIGITAL EQUIPMENT CORP.
C             15-JUL-77
C MODIFIED BY     BOB SUPNIK
C           DISK ENGINEERING
C           21-OCT-77
C ORIGINAL VERSION WAS FOR DECSYSTEM-10
C NEXT VERSION WAS FOR FORTRAN IV-PLUS UNDER
C THE IAS OPERATING SYSTEM ON THE PDP-11/70
C THIS VERSION IS FOR FORTRAN IV (V01C OR LATER)
C UNDER RT-11 ON *ANY* PDP-11
C
C
C  CURRENT LIMITS:
C     760 TRAVEL OPTIONS (TRAVEL, TRVSIZ).
C     300 VOCABULARY WORDS (KTAB, ATAB, TABSIZ).
C     150 LOCATIONS (LTEXT, STEXT, KEY, COND, ABB, ATLOC, LOCSIZ).
C     100 OBJECTS (PLAC, PLACE, FIXD, FIXED, LINKX (TWICE), PTEXT, PROP).
C      35 "ACTION" VERBS (ACTSPK, VRBSIZ).
C     215 RANDOM MESSAGES (RTEXT, RTXSIZ).
C      12 DIFFERENT PLAYER CLASSIFICATIONS (CTEXT, CVAL, CLSMAX).
C      20 HINTS, LESS 3 (HINTLC, HINTED, HINTS, HNTSIZ).
C     [MAGIC MESSAGES ARE CURRENTLY DECOMMITTED]
C      35 MAGIC MESSAGES (MTEXT, MAGSIZ).
C  THERE ARE ALSO LIMITS WHICH CANNOT BE EXCEEDED DUE TO THE STRUCTURE OF
C  THE DATABASE.  (E.G., THE VOCABULARY USES N/1000 TO DETERMINE WORD TYPE,
C  SO THERE CAN'T BE MORE THAN 1000 WORDS.)  THESE UPPER LIMITS ARE:
C     1000 NON-SYNONYMOUS VOCABULARY WORDS
C     300 LOCATIONS
C     100 OBJECTS
C
      IMPLICIT INTEGER*2 (A-Z)
      LOGICAL*2 BLKLIN,NOINPT
      LOGICAL*2 LMWARN,CLOSNG,PANIC,HINTED,
     1       CLOSED,GAVEUP,SCORNG,DSEEN
C
      COMMON /TXTCM/ RTEXT,LINES,ASCVAR,LU,ICNTRL
      COMMON /DCBCM/ IDCB2(144)
      COMMON /BLKCM/ BLKLIN,NOINPT
      COMMON /ALPHS/ BLANK,EOF,CYE,CY,CNO,CN,CPO,CUR,CWE,CST,
     1      CEN,CTE
      COMMON /VOCCM/ KTAB,ATAB,A2TAB,TABSIZ
      COMMON /PLACM/ ATLOC,LINKX,PLACE,FIXED,HOLDNG
C     COMMON /MTXCM/ MTEXT
      COMMON /PTXCM/ PTEXT
      COMMON /ABBCM/ ABB
      COMMON /MISCM/ LINUSE,TRVS,CLSSES,OLDLOC,LOC,CVAL,TK,NEWLOC,
     1KEY,PLAC,FIXD,ACTSPK,COND,HINTS,HNTMAX,PROP,TALLY,TALLY2,
     2HINTLC,CHLOC,CHLOC2,DSEEN,DFLAG,DLOC,DALTLC,KEYS,LAMP,GRATE,
     3CAGE,ROD,ROD2,STEPS,BIRD,DOOR,PILLOW,SNAKE,FISSUR,TABLET,
     4CLAM,OYSTER,MAGZIN,DWARF,KNIFE,FOOD,BOTTLE,WATER,OIL,PLANT,
     5PLANT2,AXE,MIRROR,DRAGON,CHASM,TROLL,TROLL2,BEAR,MESSAG,VEND,
     6BATTER,NUGGET,COINS,CHEST,EGGS,TRIDNT,VASE,EMRALD,PYRAM,
     7PEARL,RUG,CHAIN,BACK,LOOK,CAVE,NULL,ENTRNC,DPRSSN,SAY,LOCK,
     8THROW,FIND,INVENT,TURNS,LMWARN,KNFLOC,DETAIL,ABBNUM,
     9NUMDIE,MAXDIE,DKILL,FOOBAR,BONUS,CLOCK1,CLOCK2,
     1CLOSNG,PANIC,CLOSED,GAVEUP,SCORNG,ODLOC,STREAM
      COMMON /MISC2/ I,RTXSIZ,CLSMAX,MAGSIZ,LOCSIZ,CTEXT,STEXT,LTEXT,
     1SECT,TRAVEL,TRVCON,TRVLOC,TRVSIZ,TABNDX,OBJ,J,K,VERB,HNTSIZ,
     2MAXTRS,HINTED,HNTLOC,KK,LIMIT,SPK,WDS(6)
C
      DIMENSION LINES(40)
      DIMENSION TRAVEL(760),TRVCON(760),TRVLOC(760)
      DIMENSION KTAB(300),ATAB(300),A2TAB(300)
      DIMENSION LTEXT(150),STEXT(150),KEY(150),COND(150),ABB(150),
     1      ATLOC(150)
      DIMENSION PLAC(100),PLACE(100),FIXD(100),FIXED(100),LINKX(200),
     1      PTEXT(100),PROP(100)
      DIMENSION ACTSPK(35)
      DIMENSION RTEXT(215)
      DIMENSION CTEXT(12),CVAL(12)
      DIMENSION HINTLC(20),HINTED(20),HINTS(20,4)
C     DIMENSION MTEXT(35)
      DIMENSION TK(20),DSEEN(6),DLOC(6),ODLOC(6)
      DIMENSION NAM(3,3)
      DATA NAM/17473,12630,8224,17473,12886,8224,17473,13142,8224/
C
C     GET TERMINAL LU FROM RMPAR CALL
C
      CALL RMPAR(LINES)
      LU=LINES(1)
C
C
C     CALL INIT(LU)
C     CALL MAIN(LU)
C     CALL EXIT(LU)
C
C     RESTORE PROGRAM SEGMENT ID, RUN SEGMENT, AND REMOVE ID
C
      CALL ADV1
      IF(ICNTRL.LT.0) GO TO 40
C
C     A NEGATIVE VALUE OF ICNTRL AT THIS POINT INDICATES THAT SOMEONE
C     TRIED TO RUN THIS OVER AN ILLEGAL LOGICAL UNIT, AS DEFINED IN
C     ADV1
C
20    CONTINUE
      CALL ADV2
      CALL ADV3
      IF(ICNTRL.GE.0) GO TO 20
C
40    CONTINUE
      END
      SUBROUTINE VOCAB(ID1,ID2,INIT,V)
C
C  LOOK UP ID1:ID2 IN THE VOCABULARY (ATAB AND A2TAB)
C  AND RETURN ITS "DEFINITION" (KTAB), OR
C  -1 IF NOT FOUND.  IF INIT IS POSITIVE, THIS IS AN INIT CALL SETTING
C  UP A KEYWORD VARIABLE, AND NOT FINDING IT CONSTITUTES A BUG.  IT ALSO MEANS
C  THAT ONLY KTAB VALUES WHICH TAKEN OVER 1000 EQUAL INIT MAY BE CONSIDERED.
C  (THUS "STEPS", WHICH IS A MOTION VERB AS WELL AS AN OBJECT, MAY BE LOCATED
C  AS AN OBJECT.)  AND IT ALSO MEANS THE KTAB VALUE IS TAKEN MOD 1000.
C
      IMPLICIT INTEGER*2 (A-Z)
      COMMON /VOCCM/ KTAB,ATAB,A2TAB,TABSIZ
      DIMENSION KTAB(300),ATAB(300),A2TAB(300)
      COMMON /TXTCM/ RTEXT,LINES,ASCVAR,LU,ICNTRL !DWH-ADDED FOR LU
      DIMENSION RTEXT(215), LINES(40) !DWH-ADDED FOR LU

      DO 1 I=1,TABSIZ
      IF(KTAB(I).EQ.-1)GOTO 2
      IF(INIT.GE.0.AND.KTAB(I)/1000.NE.INIT)GOTO 1
      IF(ATAB(I).EQ.ID1 .AND. A2TAB(I).EQ.ID2)GOTO 3
1     CONTINUE
      CALL BUG(LU,21)
C
2     V=-1
      IF(INIT.LT.0)RETURN
C     WRITE(LU,100) ID1,ID2
100   FORMAT(" KEYWORD = ",2A2)
      CALL BUG(LU,5)
C
3     V=KTAB(I)
      IF(INIT.GE.0)V=MOD(V,1000)
C     WRITE(LU,6900) V,ATAB(I),A2TAB(I)
6900  FORMAT(" VOCAB: WORD ",I5,1X,2A2)
      RETURN
      END
      SUBROUTINE BUG(LU,NUM)
      IMPLICIT INTEGER*2 (A-Z)
C
C  THE FOLLOWING CONDITIONS ARE CURRENTLY CONSIDERED FATAL BUGS.  NUMBERS < 20
C  ARE DETECTED WHILE READING THE DATABASE; THE OTHERS OCCUR AT "RUN TIME".
C     0     MESSAGE LINE > 70 CHARACTERS
C     1     NULL LINE IN MESSAGE
C     2     TOO MANY WORDS OF MESSAGES
C     3     TOO MANY TRAVEL OPTIONS
C     4     TOO MANY VOCABULARY WORDS
C     5     REQUIRED VOCABULARY WORD NOT FOUND
C     6     TOO MANY RTEXT OR MTEXT MESSAGES
C     7     TOO MANY HINTS
C     8     LOCATION HAS COND BIT BEING SET TWICE
C     9     INVALID SECTION NUMBER IN DATABASE
C     20    SPECIAL TRAVEL (500>L>300) EXCEEDS GOTO LIST
C     21    RAN OFF END OF VOCABULARY TABLE
C     22    VOCABULARY TYPE (N/1000) NOT BETWEEN 0 AND 3
C     23    INTRANSITIVE ACTION VERB EXCEEDS GOTO LIST
C     24    TRANSITIVE ACTION VERB EXCEEDS GOTO LIST
C     25    CONDITIONAL TRAVEL ENTRY WITH NO ALTERNATIVE
C     26    LOCATION HAS NO TRAVEL ENTRIES
C     27    HINT NUMBER EXCEEDS GOTO LIST
C     28    INVALID MONTH RETURNED BY DATE FUNCTION
C
      WRITE(LU,1) NUM
1     FORMAT (" FATAL ERROR ",I3,", CONSULT YOUR LOCAL WIZARD."/)
      STOP
      END
      BLOCK DATA ADCOM
C
      IMPLICIT INTEGER*2 (A-Z)
      LOGICAL*2 BLKLIN,NOINPT
      LOGICAL*2 LMWARN,CLOSNG,PANIC,HINTED,
     1       CLOSED,GAVEUP,SCORNG,DSEEN
C
      COMMON /TXTCM/ RTEXT,LINES,ASCVAR,LU,ICNTRL
      COMMON /DCBCM/ IDCB2(144)
      COMMON /BLKCM/ BLKLIN,NOINPT
      COMMON /ALPHS/ BLANK,EOF,CYE,CY,CNO,CN,CPO,CUR,CWE,CST,
     1      CEN,CTE
      COMMON /VOCCM/ KTAB,ATAB,A2TAB,TABSIZ
      COMMON /PLACM/ ATLOC,LINKX,PLACE,FIXED,HOLDNG
C     COMMON /MTXCM/ MTEXT
      COMMON /PTXCM/ PTEXT
      COMMON /ABBCM/ ABB
      COMMON /MISCM/ LINUSE,TRVS,CLSSES,OLDLOC,LOC,CVAL,TK,NEWLOC,
     1KEY,PLAC,FIXD,ACTSPK,COND,HINTS,HNTMAX,PROP,TALLY,TALLY2,
     2HINTLC,CHLOC,CHLOC2,DSEEN,DFLAG,DLOC,DALTLC,KEYS,LAMP,GRATE,
     3CAGE,ROD,ROD2,STEPS,BIRD,DOOR,PILLOW,SNAKE,FISSUR,TABLET,
     4CLAM,OYSTER,MAGZIN,DWARF,KNIFE,FOOD,BOTTLE,WATER,OIL,PLANT,
     5PLANT2,AXE,MIRROR,DRAGON,CHASM,TROLL,TROLL2,BEAR,MESSAG,VEND,
     6BATTER,NUGGET,COINS,CHEST,EGGS,TRIDNT,VASE,EMRALD,PYRAM,
     7PEARL,RUG,CHAIN,BACK,LOOK,CAVE,NULL,ENTRNC,DPRSSN,SAY,LOCK,
     8THROW,FIND,INVENT,TURNS,LMWARN,KNFLOC,DETAIL,ABBNUM,
     9NUMDIE,MAXDIE,DKILL,FOOBAR,BONUS,CLOCK1,CLOCK2,
     1CLOSNG,PANIC,CLOSED,GAVEUP,SCORNG,ODLOC,STREAM
      COMMON /MISC2/ I,RTXSIZ,CLSMAX,MAGSIZ,LOCSIZ,CTEXT,STEXT,LTEXT,
     1SECT,TRAVEL,TRVCON,TRVLOC,TRVSIZ,TABNDX,OBJ,J,K,VERB,HNTSIZ,
     2MAXTRS,HINTED,HNTLOC,KK,LIMIT,SPK,WDS(6)
C
      DIMENSION LINES(40)
      DIMENSION TRAVEL(760),TRVCON(760),TRVLOC(760)
      DIMENSION KTAB(300),ATAB(300),A2TAB(300)
      DIMENSION LTEXT(150),STEXT(150),KEY(150),COND(150),ABB(150),
     1      ATLOC(150)
      DIMENSION PLAC(100),PLACE(100),FIXD(100),FIXED(100),LINKX(200),
     1      PTEXT(100),PROP(100)
      DIMENSION ACTSPK(35)
      DIMENSION RTEXT(215)
      DIMENSION CTEXT(12),CVAL(12)
      DIMENSION HINTLC(20),HINTED(20),HINTS(20,4)
C     DIMENSION MTEXT(35)
      DIMENSION TK(20),DSEEN(6),DLOC(6),ODLOC(6)
C
      END
      INTEGER*2 FUNCTION RNDM(RANGE)
C
C A VARIANT USING THE RANDOM NUMBER GENERATOR IN FORLIB.
C
      IMPLICIT INTEGER*2 (A-Z)
      REAL RANDM,SEED
      DIMENSION IPAR(5)
      EQUIVALENCE (I,SEED),(I,IPAR(1)),(J,IPAR(2)),(K,IPAR(3))
      DATA R/0/
C
      IF(R.NE.0) GO TO 1
      R=1
      CALL EXEC(11,IPAR)
      I=IOR(I,K)
      J=IOR(J,K)
1     RNDM= RANDM(SEED) *REAL(RANGE)
C
      RETURN
      END
C     END$

