DELETE-FILE AENB:BRF
DELETE-FILE AENB:LIST
DELETE-FILE AENB:PROG
DELETE-FILE AENBF:BRF
DELETE-FILE AENBF:LIST
DELETE-FILE AENBS:BRF
DELETE-FILE AENBS:LIST
DELETE-FILE AENBS:PROG
DELETE-FILE ADVENTURE-ENB:PROG
BASIC || READY\s*$
TABLE-SIZES 1500,35000
COMPILE ADVENTURE-ENB:SYMB,"AENB:LIST","AENB:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
BASIC || READY\s*$
TABLE-SIZES 1500,35000
COMPILE AENBF:SYMB,"AENBF:LIST","AENBF:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
BASIC || READY\s*$
TABLE-SIZES 1500,35000
COMPILE AENBS:SYMB,"AENBS:LIST","AENBS:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD AENBF:BRF || \* ?$
LOAD LIBRARY-MJ:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "ADVENTURE-ENB:PROG" || \* ?$
EXIT || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD AENB:BRF || \* ?$
LOAD LIBRARY-MJ:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "AENB:PROG" || \* ?$
EXIT || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD AENBS:BRF || \* ?$
LOAD LIBRARY-MJ:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "AENBS:PROG" || \* ?$
EXIT || @ ?$
