.TH FF 6
.SH NAME
ff \- stock manipulation game
.SH SYNOPSIS
.B ff
[ tycoon ]
.SH DESCRIPTION
.PP
Fast Food is a "real-time", multi-player, multi-terminal,
Stock Market game loosely modeled after the commercial
board game \fIAcquire\fR.
.PP
Because this game involves multiple (human) players
it requires a certain amount of synchronization and
cannot be played on the spur of the moment as can single-player games.
Contact Peter Langston ("mail psl" or call 386-6444) if you wish
to be informed of scheduled games.
.PP
In Fast Food tycoons (players) control the development of plots of land into
fast food joints and buy & sell stock in the fast food chains formed thereby.
.PP
The game is driven by \fIupdates\fR which happen at regular intervals
and provide the rhythm of the game.
The most common update rate is daily, providing
a leisurely paced game that lasts several weeks.
In such a game wheeling & dealing are primary activities
(as in games like \fIDiplomacy\fR).
Some players prefer a much faster paced game with updates every three
or four minutes and a total game time of an hour.
These "Blitz FF" games depend a great deal on reflex and "playing hunches";
not unlike the big game played on Wall Street.
.PP
Fast Food includes an on-line manual.
.SH AUTHOR
Peter S. Langston
.SH SEE ALSO
\fIFast Food Information Manual\fR
