#!/usr/bin/env python3
"""Generate the Windows port's Fortran source from Jim Lippard's Unix port.

Reads   ../../src_original/adv462/unix/adv462.f  (made upstream by unix/mkunix.py
        from Multics/adventure_.fortran, the master copy of the game)
Writes  ../.build/adv462w.f

The Unix source builds with MinGW-w64 gfortran as it is.  The port fixes one
bug and changes three things, and each edit asserts how often its text occurs:

  F. /msccom/: vial and mushroom join the common block, so that the new-game
     image carries them (see below).
  1. start: a suspended game may be restored at once.  RESTORE refused a game
     suspended less than latncy/3 minutes ago (30 by default) and wanted a
     wizard for one under latncy (90); the collection's rule is that nothing
     restricts the player.  Prime time needs no change: mkunix.py already
     builds the game with no hours set (in 1980 the cave was closed to all but
     wizards from 8:00 to 16:59 on weekdays).
  2. datime: ADV462_CLOCK (see adv462_win.c) can set the clock, so that a test
     run repeats exactly (the clock seeds ran).
  3. a new subroutine advmsg, through which adv462_win.c prints its few
     messages on the game's own output unit, in order with the game's text.

Everything else Palter's program leaves to the site - addr, size, ldcomn,
svcomn, and advdat, the path of the database - is in adv462_win.c.
"""
import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(here, '..', '..', 'src_original', 'adv462', 'unix', 'adv462.f')
OUT = os.path.join(here, '..', '.build', 'adv462w.f')

with open(SRC, newline='') as f:
    text = f.read()
if '\r' in text:
    sys.exit('mkwin.py: %s has CR characters; expected the LF original' % SRC)


def fix(old, new, count=1):
    """Replace old by new, which must occur exactly count times."""
    global text
    n = text.count(old)
    if n != count:
        sys.exit('mkwin.py: expected %d of %r, found %d' % (count, old, n))
    text = text.replace(old, new)


# 0. Say where this file comes from.
fix('c      Adventure\n',
    'c  windows port of adv462: generated by port/src/mkwin.py from\n'
    'c  src_original/adv462/unix/adv462.f.  do not edit; every change is\n'
    'c  marked "windows port".\n'
    'c\n'
    'c      Adventure\n')

# F. The one fix: vial and mushroom (Platt's objects 81 and 82) are set when
#    the database is read, but they are in no common block, so the new-game
#    image does not carry them.  Every game starts from that image, so in
#    every game both were whatever the stack held: THROW VIAL never found the
#    vial (on Windows vial came out as 895), and a bare EAT, EAT MUSHROOM and
#    the end of the mushroom's strength looked at a random object - on Linux
#    a bare EAT crashed the game.  The 1980 listing has the same common block.
#    They go before djinn, which ends the saved area, as mushturn did.
fix('     &sceptre,skeleton,yacht,flask,pentagram,fog,mushturn,djinn\n'
    'c  2026: objcount and all come from jim\'s 1980 notes (take all/drop all).\n'
    'c  mushturn was not in the block, so suspend/restore lost the mushroom\'s\n'
    'c  strength; it now goes before djinn, which ends the saved area.\n',
    '     &sceptre,skeleton,yacht,flask,pentagram,fog,mushturn,\n'
    '     &vial,mushroom,djinn\n'
    'c  2026: objcount and all come from jim\'s 1980 notes (take all/drop all).\n'
    'c  mushturn was not in the block, so suspend/restore lost the mushroom\'s\n'
    'c  strength; it now goes before djinn, which ends the saved area.\n'
    'c  windows port: fix: vial and mushroom were in no common block either, so\n'
    'c  adventure.newgame did not carry them and every game had them undefined.\n')

# 1. start: no wait before a suspended game may be restored.  setup<0 means
#    RESTORE brought a game back; the test that followed sent a game suspended
#    too recently to "tough beans" (mspeak 2 or 9, then stop).
fix('      soon=.false.\n'
    '      if(setup.ge.0)goto 20\n',
    '      soon=.false.\n'
    'c  windows port: a suspended game may be restored at once, so the\n'
    'c  test of the restart latency (latncy minutes) is not made.\n'
    'c     if(setup.ge.0)goto 20\n'
    '      goto 20\n')

# 2. datime: the clock may be set for a test run.
fix('      data days/31,28,31,30,31,30,31,31,30,31,30,31/\n'
    '      call date_and_time(values=v)\n',
    '      data days/31,28,31,30,31,30,31,31,30,31,30,31/\n'
    'c  windows port: ADV462_CLOCK sets the clock for test runs\n'
    'c  (advclk, in adv462_win.c).\n'
    '      if(advclk(d,t).ne.0)return\n'
    '      call date_and_time(values=v)\n')

# 3. advmsg, after the last program unit.
if not text.endswith('      end\n'):
    sys.exit('mkwin.py: the source does not end with an END line')
text += '''

      subroutine advmsg(text)
c  windows port: print a message from adv462_win.c (ldcomn, svcomn) after
c  a blank line, as the multics versions of those routines did.  unit 6 is
c  ttyo; the common block may not be loaded yet when ldcomn first runs.
      character*(*) text
      write(6,1)text
    1 format(/,1x,a)
      return
      end
'''

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, 'w', newline='\n') as f:
    f.write(text)
print('mkwin.py: wrote %s, %d lines' % (os.path.relpath(OUT), text.count('\n')))
