C     FTN5
C======================================================================C
C                                                                      C
C      AA       DDDDDDDDD     VV        VV    00000000    555555555555 C
C     AAAA      DDDDDDDDDD    VV        VV   0000000000   555555555555 C
C    AA  AA     DD       DD   VV        VV  00        00  55           C
C   AA    AA    DD        DD  VV        VV  00        00  55           C
C  AA      AA   DD        DD  VV        VV  00        00  55           C
C AA        AA  DD        DD  VV        VV  00        00  555555555    C
C AAAAAAAAAAAA  DD        DD   VV      VV   00        00  5555555555   C
C AAAAAAAAAAAA  DD        DD   VV      VV   00        00           55  C
C AA        AA  DD        DD     VV  VV     00        00            55 C
C AA        AA  DD       DD      VV  VV     00        00            55 C
C AA        AA  DDDDDDDDDD         VV        0000000000   555555555555 C
C AA        AA  DDDDDDDDD          VV         00000000    55555555555  C
C                                                                      C
C======================================================================C
C                                                                      C
C REVISION LIST:                                                       C
C                                                                      C
C --DATE-- --BY-- -- D E S C R I P T I O N --                          C
C                                                                      C
C  3/07/81 AW     -ORIGINAL VERSION-                                   C
C                                                                      C
C======================================================================C
C SUBROUTINES FOR ADVENTURE
C
C MODIFIED FOR PDP-11 FORTRAN IV BY
C
C     R. SUPNIK
C     DISK ENGINEERING
C
      SUBROUTINE A5TO1(LU,A,B,C,D)
C
C THIS ROUTINE TAKES THE UP TO 6 CHARACTER "WORD" IN A:B:C
C AND TYPES IT OUT, FOLLOWED BY THE PUNCTUATION MARK IN D.
C IT ALSO APPENDS A CRLF TO GET TO A NEW LINE.
C
      IMPLICIT INTEGER*2 (A-Z)
      COMMON /ALPHS/ BLANK
C
      IF(A .NE. BLANK) WRITE(LU,1) A
      IF(B .NE. BLANK) WRITE(LU,1) B
      IF(C .NE. BLANK) WRITE(LU,1) C
      WRITE(LU,2) D
      RETURN
C
1     FORMAT(A2,$)
2     FORMAT(A2)
C
      END
C  DATA STRUCTURE ROUTINES (VOCAB, DSTRY, JUGGL, MOVE, PUT, CARRY, DROP)
C
C
C     --- program unit removed by the port; see tools/convert.py ---
C
C  LOOK UP ID1:ID2 IN THE VOCABULARY (ATAB AND A2TAB)
C  AND RETURN ITS "DEFINITION" (KTAB), OR
C  -1 IF NOT FOUND.  IF INIT IS POSITIVE, THIS IS AN INIT CALL SETTING
C  UP A KEYWORD VARIABLE, AND NOT FINDING IT CONSTITUTES A BUG.  IT ALSO MEANS
C  THAT ONLY KTAB VALUES WHICH TAKEN OVER 1000 EQUAL INIT MAY BE CONSIDERED.
C  (THUS "STEPS", WHICH IS A MOTION VERB AS WELL AS AN OBJECT, MAY BE LOCATED
C  AS AN OBJECT.)  AND IT ALSO MEANS THE KTAB VALUE IS TAKEN MOD 1000.
C
C     IMPLICIT INTEGER*2 (A-Z)
C     COMMON /VOCCM/ KTAB,ATAB,A2TAB,TABSIZ
C     DIMENSION KTAB(300),ATAB(300),A2TAB(300)
C
C     DO 1 I=1,TABSIZ
C     IF(KTAB(I).EQ.-1)GOTO 2
C     IF(INIT.GE.0.AND.KTAB(I)/1000.NE.INIT)GOTO 1
C     IF(ATAB(I).EQ.ID1 .AND. A2TAB(I).EQ.ID2)GOTO 3
C     CONTINUE
C     CALL BUG(LU,21)
C
C     V=-1
C     IF(INIT.LT.0)RETURN
C     TYPE 100,ID1,ID2
C00   FORMAT(" KEYWORD = ",2A2)
C     CALL BUG(LU,5)
C
C     V=KTAB(I)
C     IF(INIT.GE.0)V=MOD(V,1000)
C     WRITE(12,6900) V,ATAB(I),A2TAB(I)
C900  FORMAT(" VOCAB: WORD ",I5,1X,2A2)
C     RETURN
C     END
C
C
C
      SUBROUTINE DSTRY(OBJECT)
C
C  PERMANENTLY ELIMINATE "OBJECT" BY MOVING TO A NON-EXISTENT LOCATION.
C
      IMPLICIT INTEGER*2 (A-Z)
C
      CALL MOVE(OBJECT,0)
      RETURN
      END
C
C
C
      SUBROUTINE JUGGL(OBJECT)
C
C  JUGGL AN OBJECT BY PICKING IT UP AND PUTTING IT DOWN AGAIN, THE PURPOSE
C  BEING TO GET THE OBJECT TO THE FRONT OF THE CHAIN OF THINGS AT ITS LOC.
C
      IMPLICIT INTEGER*2 (A-Z)
      COMMON /PLACM/ ATLOC,LINKX,PLACE,FIXED,HOLDNG
      DIMENSION ATLOC(150),LINKX(200),PLACE(100),FIXED(100)
C
      I=PLACE(OBJECT)
      J=FIXED(OBJECT)
      CALL MOVE(OBJECT,I)
      CALL MOVE(OBJECT+100,J)
      RETURN
      END
C
C
C
      SUBROUTINE MOVE(OBJECT,WHERE)
C
C  PLACE ANY OBJECT ANYWHERE BY PICKING IT UP AND DROPPING IT.  MAY ALREADY BE
C  TOTING, IN WHICH CASE THE CARRY IS A NO-OP.  MUSTN'T PICK UP OBJECTS WHICH
C  ARE NOT AT ANY LOC, SINCE CARRY WANTS TO REMOVE OBJECTS FROM ATLOC CHAINS.
C
      IMPLICIT INTEGER*2 (A-Z)
      COMMON /PLACM/ ATLOC,LINKX,PLACE,FIXED,HOLDNG
      DIMENSION ATLOC(150),LINKX(200),PLACE(100),FIXED(100)
C
      IF(OBJECT.GT.100)GOTO 1
      FROM=PLACE(OBJECT)
      GOTO 2
1     FROM=FIXED(OBJECT-100)
2     IF(FROM.GT.0.AND.FROM.LE.300)CALL CARRY(OBJECT,FROM)
      CALL DROP(OBJECT,WHERE)
      RETURN
      END
C
C
C
      INTEGER*2 FUNCTION PUT(OBJECT,WHERE,PVAL)
C
C  PUT IS THE SAME AS MOVE, EXCEPT IT RETURNS A VALUE USED TO SET UP THE
C  NEGATED PROP VALUES FOR THE REPOSITORY OBJECTS.
C
      IMPLICIT INTEGER*2 (A-Z)
C
      CALL MOVE(OBJECT,WHERE)
      PUT=(-1)-PVAL
      RETURN
      END
C
C
C
      SUBROUTINE CARRY(OBJECT,WHERE)
C
C  START TOTING AN OBJECT, REMOVING IT FROM THE LIST OF THINGS AT ITS FORMER
C  LOCATION.  INCR HOLDNG UNLESS IT WAS ALREADY BEING TOTED.  IF OBJECT>100
C  (MOVING "FIXED" SECOND LOC), DON'T CHANGE PLACE OR HOLDNG.
C
      IMPLICIT INTEGER*2 (A-Z)
      COMMON /PLACM/ ATLOC,LINKX,PLACE,FIXED,HOLDNG
      DIMENSION ATLOC(150),LINKX(200),PLACE(100),FIXED(100)
C
      IF(OBJECT.GT.100)GOTO 5
      IF(PLACE(OBJECT).EQ.-1)RETURN
      PLACE(OBJECT)=-1
      HOLDNG=HOLDNG+1
5     IF(ATLOC(WHERE).NE.OBJECT)GOTO 6
      ATLOC(WHERE)=LINKX(OBJECT)
      RETURN
6     TEMP=ATLOC(WHERE)
7     IF(LINKX(TEMP).EQ.OBJECT)GOTO 8
      TEMP=LINKX(TEMP)
      GOTO 7
8     LINKX(TEMP)=LINKX(OBJECT)
      RETURN
      END
C
C
C
      SUBROUTINE DROP(OBJECT,WHERE)
C
C  PLACE AN OBJECT AT A GIVEN LOC, PREFIXING IT ONTO THE ATLOC LIST.  DECR
C  HOLDNG IF THE OBJECT WAS BEING TOTED.
C
      IMPLICIT INTEGER*2 (A-Z)
      COMMON /PLACM/ ATLOC,LINKX,PLACE,FIXED,HOLDNG
      DIMENSION ATLOC(150)
      DIMENSION LINKX(200)
      DIMENSION PLACE(100)
      DIMENSION FIXED(100)
C
      IF(OBJECT.GT.100)GOTO 1
      IF(PLACE(OBJECT).EQ.-1)HOLDNG=HOLDNG-1
      PLACE(OBJECT)=WHERE
      GOTO 2
1     FIXED(OBJECT-100)=WHERE
2     IF(WHERE.LE.0)RETURN
      LINKX(OBJECT)=ATLOC(WHERE)
      ATLOC(WHERE)=OBJECT
      RETURN
      END
C UTILITY ROUTINES (RND, BUG)
C
C     --- program unit removed by the port; see tools/convert.py ---
C
C A VARIANT USING THE RANDOM NUMBER GENERATOR IN FORLIB.
C
C     IMPLICIT INTEGER*2 (A-Z)
C     REAL RANDM,SEED
C     DIMENSION IPAR(5)
C     EQUIVALENCE (I,SEED),(I,IPAR(1)),(J,IPAR(2)),(K,IPAR(3))
C     DATA R/0/
C
C     IF(R.NE.0) GO TO 1
C     R=1
C     CALL EXEC(11,IPAR)
C     I=IOR(I,K)
C     J=IOR(J,K)
C     JRAD= RANDM(SEED) *REAL(RANGE)
C     RNDM=JRAD
C     WRITE(12,1000) JRAD,SEED,RANGE
C000  FORMAT("'RANDOM NUMBER'",I8,E12.4,I8)
C
C     RETURN
C     END
C
C
C
C
C     --- program unit removed by the port; see tools/convert.py ---
C     IMPLICIT INTEGER*2 (A-Z)
C
C  THE FOLLOWING CONDITIONS ARE CURRENTLY CONSIDERED FATAL BUGS.  NUMBERS < 20
C  ARE DETECTED WHILE READING THE DATABASE; THE OTHERS OCCUR AT "RUN TIME".
C     0     MESSAGE LINE > 70 CHARACTERS
C     1     NULL LINE IN MESSAGE
C     2     TOO MANY WORDS OF MESSAGES
C     3     TOO MANY TRAVEL OPTIONS
C     4     TOO MANY VOCABULARY WORDS
C     5     REQUIRED VOCABULARY WORD NOT FOUND
C     6     TOO MANY RTEXT OR MTEXT MESSAGES
C     7     TOO MANY HINTS
C     8     LOCATION HAS COND BIT BEING SET TWICE
C     9     INVALID SECTION NUMBER IN DATABASE
C     20    SPECIAL TRAVEL (500>L>300) EXCEEDS GOTO LIST
C     21    RAN OFF END OF VOCABULARY TABLE
C     22    VOCABULARY TYPE (N/1000) NOT BETWEEN 0 AND 3
C     23    INTRANSITIVE ACTION VERB EXCEEDS GOTO LIST
C     24    TRANSITIVE ACTION VERB EXCEEDS GOTO LIST
C     25    CONDITIONAL TRAVEL ENTRY WITH NO ALTERNATIVE
C     26    LOCATION HAS NO TRAVEL ENTRIES
C     27    HINT NUMBER EXCEEDS GOTO LIST
C     28    INVALID MONTH RETURNED BY DATE FUNCTION
C
C     WRITE(LU,1) NUM
C     FORMAT (" FATAL ERROR ",I3,", CONSULT YOUR LOCAL WIZARD."/)
C     STOP
C     END
C     END$

