C     FTN5
C======================================================================C
C                                                                      C
C      AA       DDDDDDDDD     VV        VV    00000000     3333333333  C
C     AAAA      DDDDDDDDDD    VV        VV   0000000000   333333333333 C
C    AA  AA     DD       DD   VV        VV  00        00  33        33 C
C   AA    AA    DD        DD  VV        VV  00        00            33 C
C  AA      AA   DD        DD  VV        VV  00        00            33 C
C AA        AA  DD        DD  VV        VV  00        00         3333  C
C AAAAAAAAAAAA  DD        DD   VV      VV   00        00         3333  C
C AAAAAAAAAAAA  DD        DD   VV      VV   00        00            33 C
C AA        AA  DD        DD     VV  VV     00        00            33 C
C AA        AA  DD       DD      VV  VV     00        00  33        33 C
C AA        AA  DDDDDDDDDD         VV        0000000000   333333333333 C
C AA        AA  DDDDDDDDD          VV         00000000     3333333333  C
C                                                                      C
C======================================================================C
C                                                                      C
C REVISION LIST:                                                       C
C                                                                      C
C --DATE-- --BY-- -- D E S C R I P T I O N --                          C
C                                                                      C
C  3/07/81 AW     -ORIGINAL VERSION-                                   C
C                                                                      C
C======================================================================C
      SUBROUTINE ADV1
C
C     THIS IS THE "INIT" SEGMENT FOR THE HP MODIFICATION OF ADVENTURE.
C     MODIFIED BY BGL, HAYSTACK OBSERVATORY.
C
C  ADVENTURES
C     SUBROUTINE INIT(LU)
C
C MODIFIED BY KENT BLACKETT
C             ENGINEERING SYSTEMS GROUP
C             DIGITAL EQUIPMENT CORP.
C             15-JUL-77
C MODIFIED BY     BOB SUPNIK
C           DISK ENGINEERING
C           21-OCT-77
C ORIGINAL VERSION WAS FOR DECSYSTEM-10
C NEXT VERSION WAS FOR FORTRAN IV-PLUS UNDER
C THE IAS OPERATING SYSTEM ON THE PDP-11/70
C THIS VERSION IS FOR FORTRAN IV (V01C OR LATER)
C UNDER RT-11 ON *ANY* PDP-11
C
C
C  CURRENT LIMITS:
C     760 TRAVEL OPTIONS (TRAVEL, TRVSIZ).
C     300 VOCABULARY WORDS (KTAB, ATAB, TABSIZ).
C     150 LOCATIONS (LTEXT, STEXT, KEY, COND, ABB, ATLOC, LOCSIZ).
C     100 OBJECTS (PLAC, PLACE, FIXD, FIXED, LINKX (TWICE), PTEXT, PROP).
C      35 "ACTION" VERBS (ACTSPK, VRBSIZ).
C     215 RANDOM MESSAGES (RTEXT, RTXSIZ).
C      12 DIFFERENT PLAYER CLASSIFICATIONS (CTEXT, CVAL, CLSMAX).
C      20 HINTS, LESS 3 (HINTLC, HINTED, HINTS, HNTSIZ).
C     [MAGIC MESSAGES HAVE BEEN DECOMMITTED]
C      35 MAGIC MESSAGES (MTEXT, MAGSIZ).
C  THERE ARE ALSO LIMITS WHICH CANNOT BE EXCEEDED DUE TO THE STRUCTURE OF
C  THE DATABASE.  (E.G., THE VOCABULARY USES N/1000 TO DETERMINE WORD TYPE,
C  SO THERE CAN'T BE MORE THAN 1000 WORDS.)  THESE UPPER LIMITS ARE:
C     1000 NON-SYNONYMOUS VOCABULARY WORDS
C     300 LOCATIONS
C     100 OBJECTS
C
      IMPLICIT INTEGER*2 (A-Z)
      LOGICAL*2 BLKLIN,NOINPT
      LOGICAL*2 DSEEN,HINTED
C     Statement-function dummies handed literal constants.
      INTEGER*4 NBIT
      INTEGER*2 LBIT
      LOGICAL*2 BITSET,LMWARN,CLOSNG,PANIC,
     1       CLOSED,GAVEUP,SCORNG
C     SET UP FMP VERSIONS OF FILENAMES-DWH
      CHARACTER*20 CNAM1, CNAM2, CNAM3
C
      COMMON /TXTCM/ RTEXT,LINES,ASCVAR,LU,ICNTRL
      COMMON /DCBCM/ IDCB2(144)
      COMMON /BLKCM/ BLKLIN,NOINPT
      COMMON /ALPHS/ BLANK,EOF,CYE,CY,CNO,CN,CPO,CUR,CWE,CST,
     A               CEN,CTE
      COMMON /VOCCM/ KTAB,ATAB,A2TAB,TABSIZ
      COMMON /PLACM/ ATLOC,LINKX,PLACE,FIXED,HOLDNG
C     COMMON /MTXCM/ MTEXT
      COMMON /PTXCM/ PTEXT
      COMMON /ABBCM/ ABB
      COMMON /MISCM/ LINUSE,TRVS,CLSSES,OLDLOC,LOC,CVAL,TK,NEWLOC,
     1KEY,PLAC,FIXD,ACTSPK,COND,HINTS,HNTMAX,PROP,TALLY,TALLY2,
     2HINTLC,CHLOC,CHLOC2,DSEEN,DFLAG,DLOC,DALTLC,KEYS,LAMP,GRATE,
     3CAGE,ROD,ROD2,STEPS,BIRD,DOOR,PILLOW,SNAKE,FISSUR,TABLET,
     4CLAM,OYSTER,MAGZIN,DWARF,KNIFE,FOOD,BOTTLE,WATER,OIL,PLANT,
     5PLANT2,AXE,MIRROR,DRAGON,CHASM,TROLL,TROLL2,BEAR,MESSAG,VEND,
     6BATTER,NUGGET,COINS,CHEST,EGGS,TRIDNT,VASE,EMRALD,PYRAM,
     7PEARL,RUG,CHAIN,BACK,LOOK,CAVE,NULL,ENTRNC,DPRSSN,SAY,LOCK,
     8THROW,FIND,INVENT,TURNS,LMWARN,KNFLOC,DETAIL,ABBNUM,
     9NUMDIE,MAXDIE,DKILL,FOOBAR,BONUS,CLOCK1,CLOCK2,
     1CLOSNG,PANIC,CLOSED,GAVEUP,SCORNG,ODLOC,STREAM
      COMMON /MISC2/ I,RTXSIZ,CLSMAX,MAGSIZ,LOCSIZ,CTEXT,STEXT,LTEXT,
     1SECT,TRAVEL,TRVCON,TRVLOC,TRVSIZ,TABNDX,OBJ,J,K,VERB,HNTSIZ,
     2MAXTRS,HINTED,HNTLOC,KK
C
C     EXTERNAL ISHFT
      DIMENSION LINES(40)
      DIMENSION TRAVEL(760),TRVCON(760),TRVLOC(760)
      DIMENSION KTAB(300),ATAB(300),A2TAB(300)
      DIMENSION LTEXT(150),STEXT(150),KEY(150),COND(150),ABB(150),
     1      ATLOC(150)
C
C     NOTE: THE VARIABLE NAME "LINK" IS CHANGED TO "LINKX" BECAUSE THE
C     HP SEGMENTATION SOFTWARE USES A ROUTINE CALLED LINK, AND THE POOR
C     MACHINE GETS CONFUSED.
C
      DIMENSION PLAC(100),PLACE(100),FIXD(100),FIXED(100),LINKX(200),
     1      PTEXT(100),PROP(100)
      DIMENSION ACTSPK(35)
      DIMENSION RTEXT(215)
      DIMENSION CTEXT(12),CVAL(12)
      DIMENSION HINTLC(20),HINTED(20),HINTS(20,4)
C     DIMENSION MTEXT(35)
      DIMENSION TK(20),DSEEN(6),DLOC(6),ODLOC(6)
C
C     THIS SECTION FOR HP MACHINES WITH FILES AND ALL THAT SHIT
C
      CHARACTER*88 CIBUF
      EQUIVALENCE (IBUF,CIBUF)
      DIMENSION IBUF(44),IDCB1(144),NAM1(3),NAM2(3)
     A  ,NAM3(3),ISIZE(2),JSIZE(2),QBUF(2),QCOMMA(2),QBLNK(2)
      EQUIVALENCE (IBUF,QBUF(2))
      DATA IDCBS/144/,NAM1/16675,22084,23130/,NAM2/16675,22084,22616/
     A  ,ISIZE/550,44/,QCOMMA/1,8236/,QBLNK/1,8224/,ICR/3/
C  CHANGED ICR to 3 to use cart 3  7/26/05 WTN
     B  ,JSIZE/44,128/,NAM3/16675,22084,22873/,MODEM1/ 4/,MODEM2/12/
C
C
      BITSET(LBIT,NBIT)=IAND(COND(LBIT),ISHFT(1_2,NBIT)).NE.0
C  DESCRIPTION OF THE DATABASE FORMAT
C
C
C  THE DATA FILE CONTAINS SEVERAL SECTIONS.  EACH BEGINS WITH A LINE CONTAINING
C  A NUMBER IDENTIFYING THE SECTION, AND ENDS WITH A LINE CONTAINING "-1".
C
C  SECTION 1: LONG FORM DESCRIPTIONS.  EACH LINE CONTAINS A LOCATION NUMBER,
C     A COMMA, AND A LINE OF TEXT.  THE SET OF (NECESSARILY ADJACENT) LINES
C     WHOSE NUMBERS ARE X FORM THE LONG DESCRIPTION OF LOCATION X.
C  SECTION 2: SHORT FORM DESCRIPTIONS.  SAME FORMAT AS LONG FORM.  NOT ALL
C     PLACES HAVE SHORT DESCRIPTIONS.
C  SECTION 3: TRAVEL TABLE.  EACH LINE CONTAINS A LOCATION NUMBER (X), A SECOND
C     LOCATION NUMBER (Y), AND A LIST OF MOTION NUMBERS (SEE SECTION 4).
C     EACH MOTION REPRESENTS A VERB WHICH WILL GO TO Y IF CURRENTLY AT X.
C     Y, IN TURN, IS INTERPRETED AS FOLLOWS.  LET M=Y/1000, N=Y MOD 1000.
C           IF N<=300   IT IS THE LOCATION TO GO TO.
C           IF 300<N<=500     N-300 IS USED IN A COMPUTED GOTO TO
C                             A SECTION OF SPECIAL CODE.
C           IF N>500    MESSAGE N-500 FROM SECTION 6 IS PRINTED,
C                             AND HE STAYS WHEREVER HE IS.
C     MEANWHILE, M SPECIFIES THE CONDITIONS ON THE MOTION.
C           IF M=0            IT'S UNCONDITIONAL.
C           IF 0<M<100  IT IS DONE WITH M% PROBABILITY.
C           IF M=100    UNCONDITIONAL, BUT FORBIDDEN TO DWARVES.
C           IF 100<M<=200     HE MUST BE CARRYING OBJECT M-100.
C           IF 200<M<=300     MUST BE CARRYING OR IN SAME ROOM AS M-200.
C           IF 300<M<=400     PROP(M MOD 100) MUST *NOT* BE 0.
C           IF 400<M<=500     PROP(M MOD 100) MUST *NOT* BE 1.
C           IF 500<M<=600     PROP(M MOD 100) MUST *NOT* BE 2, ETC.
C     IF THE CONDITION (IF ANY) IS NOT MET, THEN THE NEXT *DIFFERENT*
C     "DESTINATION" VALUE IS USED (UNLESS IT FAILS TO MEET *ITS* CONDITIONS,
C     IN WHICH CASE THE NEXT IS FOUND, ETC.).  TYPICALLY, THE NEXT DEST WILL
C     BE FOR ONE OF THE SAME VERBS, SO THAT ITS ONLY USE IS AS THE ALTERNATE
C     DESTINATION FOR THOSE VERBS.  FOR INSTANCE:
C           15    110022      29    31    34    35    23    43
C           15    14    29
C     THIS SAYS THAT, FROM LOC 15, ANY OF THE VERBS 29, 31, ETC., WILL TAKE
C     HIM TO 22 IF HE'S CARRYING OBJECT 10, AND OTHERWISE WILL GO TO 14.
C           11    303008      49
C           11    9     50
C     THIS SAYS THAT, FROM 11, 49 TAKES HIM TO 8 UNLESS PROP(3)=0, IN WHICH
C     CASE HE GOES TO 9.  VERB 50 TAKES HIM TO 9 REGARDLESS OF PROP(3).
C
C     IN THIS IMPLEMENTATION, THE SECOND LOCATION NUMBER Y HAS BEEN
C     SPLIT INTO M, CONDITIONS, AND N, LOCATION.
C
C  SECTION 4: VOCABULARY.  EACH LINE CONTAINS A NUMBER (N), A TAB, AND A
C     FIVE-LETTER WORD.  CALL M=N/1000.  IF M=0, THEN THE WORD IS A MOTION
C     VERB FOR USE IN TRAVELLING (SEE SECTION 3).  ELSE, IF M=1, THE WORD IS
C     AN OBJECT.  ELSE, IF M=2, THE WORD IS AN ACTION VERB (SUCH AS "CARRY"
C     OR "ATTACK").  ELSE, IF M=3, THE WORD IS A SPECIAL CASE VERB (SUCH AS
C     "DIG") AND N MOD 1000 IS AN INDEX INTO SECTION 6.  OBJECTS FROM 50 TO
C     (CURRENTLY, ANYWAY) 79 ARE CONSIDERED TREASURES (FOR PIRATE, CLOSEOUT).
C  SECTION 5: OBJECT DESCRIPTIONS.  EACH LINE CONTAINS A NUMBER (N), A TAB,
C     AND A MESSAGE.  IF N IS FROM 1 TO 100, THE MESSAGE IS THE "INVENTORY"
C     MESSAGE FOR OBJECT N.  OTHERWISE, N SHOULD BE 000, 100, 200, ETC., AND
C     THE MESSAGE SHOULD BE THE DESCRIPTION OF THE PRECEDING OBJECT WHEN ITS
C     PROP VALUE IS N/100.  THE N/100 IS USED ONLY TO DISTINGUISH MULTIPLE
C     MESSAGES FROM MULTI-LINE MESSAGES; THE PROP INFO ACTUALLY REQUIRES ALL
C     MESSAGES FOR AN OBJECT TO BE PRESENT AND CONSECUTIVE.  PROPERTIES WHICH
C     PRODUCE NO MESSAGE SHOULD BE GIVEN THE MESSAGE ">$<".
C  SECTION 6: ARBITRARY MESSAGES.  SAME FORMAT AS SECTIONS 1, 2, AND 5, EXCEPT
C     THE NUMBERS BEAR NO RELATION TO ANYTHING (EXCEPT FOR SPECIAL VERBS
C     IN SECTION 4).
C  SECTION 7: OBJECT LOCATIONS.  EACH LINE CONTAINS AN OBJECT NUMBER AND ITS
C     INITIAL LOCATION (ZERO (OR OMITTED) IF NONE).  IF THE OBJECT IS
C     IMMOVABLE, THE LOCATION IS FOLLOWED BY A "-1".  IF IT HAS TWO LOCATIONS
C     (E.G. THE GRATE) THE FIRST LOCATION IS FOLLOWED WITH THE SECOND, AND
C     THE OBJECT IS ASSUMED TO BE IMMOVABLE.
C  SECTION 8: ACTION DEFAULTS.  EACH LINE CONTAINS AN "ACTION-VERB" NUMBER AND
C     THE INDEX (IN SECTION 6) OF THE DEFAULT MESSAGE FOR THE VERB.
C  SECTION 9: LIQUID ASSETS, ETC.  EACH LINE CONTAINS A NUMBER (N) AND UP TO 20
C     LOCATION NUMBERS.  BIT N (WHERE 0 IS THE UNITS BIT) IS SET IN COND(LOC)
C     FOR EACH LOC GIVEN.  THE COND BITS CURRENTLY ASSIGNED ARE:
C           0     LIGHT
C           1     IF BIT 2 IS ON: ON FOR OIL, OFF FOR WATER
C           2     LIQUID ASSET, SEE BIT 1
C           3     PIRATE DOESN'T GO HERE UNLESS FOLLOWING PLAYER
C     OTHER BITS ARE USED TO INDICATE AREAS OF INTEREST TO "HINT" ROUTINES:
C           4     TRYING TO GET INTO CAVE
C           5     TRYING TO CATCH BIRD
C           6     TRYING TO DEAL WITH SNAKE
C           7     LOST IN MAZE
C           8     PONDERING DARK ROOM
C           9     AT WITT'S END
C     COND(LOC) IS SET TO 2, OVERRIDING ALL OTHER BITS, IF LOC HAS FORCED
C     MOTION.
C  SECTION 10: CLASS MESSAGES.  EACH LINE CONTAINS A NUMBER (N), A TAB, AND A
C     MESSAGE DESCRIBING A CLASSIFICATION OF PLAYER.  THE SCORING SECTION
C     SELECTS THE APPROPRIATE MESSAGE, WHERE EACH MESSAGE IS CONSIDERED TO
C     APPLY TO PLAYERS WHOSE SCORES ARE HIGHER THAN THE PREVIOUS N BUT NOT
C     HIGHER THAN THIS N.  NOTE THAT THESE SCORES PROBABLY CHANGE WITH EVERY
C     MODIFICATION (AND PARTICULARLY EXPANSION) OF THE PROGRAM.
C  SECTION 11: HINTS.  EACH LINE CONTAINS A HINT NUMBER (CORRESPONDING TO A
C     COND BIT, SEE SECTION 9), THE NUMBER OF TURNS HE MUST BE AT THE RIGHT
C     LOC(S) BEFORE TRIGGERING THE HINT, THE POINTS DEDUCTED FOR TAKING THE
C     HINT, THE MESSAGE NUMBER (SECTION 6) OF THE QUESTION, AND THE MESSAGE
C     NUMBER OF THE HINT.  THESE VALUES ARE STASHED IN THE "HINTS" ARRAY.
C     HNTMAX IS SET TO THE MAX HINT NUMBER (<= HNTSIZ).  NUMBERS 1-3 ARE
C     UNUSABLE SINCE COND BITS ARE OTHERWISE ASSIGNED, SO 2 IS USED TO
C     REMEMBER IF HE'S READ THE CLUE IN THE REPOSITORY, AND 3 IS USED TO
C     REMEMBER WHETHER HE ASKED FOR INSTRUCTIONS (GETS MORE TURNS, BUT LOSES
C     POINTS).
C  SECTION 12: MAGIC MESSAGES. IDENTICAL TO SECTION 6 EXCEPT PUT IN A SEPARATE
C     SECTION FOR EASIER REFERENCE.  MAGIC MESSAGES ARE USED BY THE STARTUP,
C     MAINTENANCE MODE, AND RELATED ROUTINES.
C  SECTION 0: END OF DATABASE.
C  READ THE DATABASE IF WE HAVE NOT YET DONE SO
C
C     WRITE(1,*) '@INIT: LU: ', LU

      CNAM1 = '#ADVZZ' !DWH-ADDED THESE 3 INITS
      CNAM2 = '#ADVXX:::2:344:44' !TYPE 2, 344BLKS, 44 WORD RECLEN
      CNAM3 = '#ADVYY:::2:44:5626'

      BLANK=8224
      CYE=17753
      CNO=20302
      EOF=9278
      CY=8281
      CN=8270
      CPO=20304
      CUR=21077
      CWE=17751
      CST=21587
      CEN=20037
      CTE=17748
      FILSIZ=2100
      TABSIZ=300
      LOCSIZ=150
      VRBSIZ=35
      BLKLIN=.TRUE.
      NOINPT=.TRUE.
      RTXSIZ = 215
      HNTSIZ = 20
      MAGSIZ = 35
      TRVSIZ = 760
      CLSMAX = 12
D     VCOUNT = 0
C
      ! SKIP MODEM TEST           !DWH
C      IF(LU.NE.MODEM1 .AND. LU.NE.MODEM2) GO TO 5
C      WRITE(LU,2020)
C2020  FORMAT("Sorry.  The dwarves didn't pay their phone bill.")
C      ICNTRL=-99
C      GO TO 2
5     WRITE(LU,1000)
1000  FORMAT(/," Initializing data files and such...")
C
C  CLEAR OUT THE VARIOUS TEXT-POINTER ARRAYS.  ALL TEXT IS STORED IN DISK
C  FILE (RANDOM ACCESS ON UNIT 2).  THE TEXT-POINTER ARRAYS CONTAIN RECORD
C  NUMBERS IN THE FILE.  STEXT(N) IS SHORT DESCRIPTION OF LOCATION N.
C  LTEXT(N) IS LONG DESCRIPTION.  PTEXT(N) POINTS TO MESSAGE FOR PROP(N)=0.
C  SUCCESSIVE PROP MESSAGES ARE FOUND BY CHASING POINTERS.  RTEXT CONTAINS
C  SECTION 6'S STUFF.  CTEXT(N) POINTS TO A PLAYER-CLASS MESSAGE.  MTEXT IS FOR
C  SECTION 12.  WE ALSO CLEAR COND.  SEE DESCRIPTION OF SECTION 9 FOR DETAILS.
C
C *******************************************************************
C *                                                                 *
C *   EXPLANATORY NOTES ON THE MODIFICATIONS FOR HP COMPUTERS:      *
C *   FILE #ADVZZ CONTAINS THE ORIGINAL TEXT.  IT IS READ IN AND    *
C *   TRANSFERRED TO FILE #ADVXX FOR USE BY THIS PROGRAM.  INITI-   *
C *   ALIZATION PARAMETERS ARE STORED IN COMMON (AS IN THE ORIGINAL *
C *   VERSION) AND ARE ALSO WRITTEN OUT TO DISC FILE #ADVYY.  IF    *
C *   THIS PROGRAM FINDS THAT FILE #ADVXX ALREADY EXISTS, IT WILL   *
C *   TRY TO READ IN THE COMMON AREA FROM FILE #ADVYY, WHICH IS     *
C *   MUCH FASTER THAN GOING THROUGH ALL THE OTHER NONSENSE EACH    *
C *   TIME.  FILES #ADVXX AND #ADVYY SHOULD BE PURGED IF CHANGES    *
C *   ARE MADE IN THE TEXT FILE SO THAT THIS PROGRAM WILL SET THEM  *
C *   UP AGAIN CORRECTLY.                                           *
C *        FILES ARE NORMALLY KEPT ON CARTRIDGE 50.  IF YOU HAVE    *
C *   REASON TO CHANGE THIS, JUST CHANGE THE VALUE OF "ICR" IN THE  *
C *   DATA STATEMENT WHICH NOW SETS IT TO 80.                       *
C *                                                                 *
C *******************************************************************
C
      DO 1001 I=1,TABSIZ
      KTAB(I)=0
      ATAB(I)=0
      A2TAB(I)=0
      IF(I.GT.100) GO TO 1990
      PTEXT(I)=0
      PROP(I)=0
      PLAC(I)=0
      PLACE(I)=0
      FIXD(I)=0
      FIXED(I)=0
      LINKX(I)=0
      LINKX(I+100)=0
1990  IF(I.LE.RTXSIZ)RTEXT(I)=0
      IF(I.LE.CLSMAX)CTEXT(I)=0
C     IF(I.LE.MAGSIZ)MTEXT(I)=0
      IF(I.LE.VRBSIZ)ACTSPK(I)=0
      IF(I.GT.LOCSIZ)GOTO 1001
      KEY(I)=0
      ABB(I)=0
      ATLOC(I)=0
      STEXT(I)=0
      LTEXT(I)=0
      COND(I)=0
1001  CONTINUE
C
C     CALL ASSIGN(1,'TEXT.TXT')
C     DEFINE FILE 2(FILSIZ,37,U,ASCVAR)
C
C     THIS SECTION MAKES USE OF THE PREVIOUSLY CREATED FILE CONTAINING
C     INITIALIZED COMMON.
C
C     UNCOMMENT NEXT FMPPURGE TO FORCE PROG TO FULLY INITIALIZE EACH RUN
C     CALL FMPPURGE(CNAM3) !DWH:ADDED

C     WRITE(LU) '!!! POSITIVE ERROR CODE INDICATES FILE TYPE NOT ERROR'
C     WRITE(LU) '  @OPEN: CNAM3: ', CNAM3, '; ?DOES #ADVYY EXIST?'
C     CALL OPEN(IDCB1,IERR,NAM3,1,0,ICR,2064)
C     Fast-start cache disabled in the port; see tools/convert.py.
      IERR = -1
C     WRITE(LU,*) '  @AFTER OPEN: IERR: ', IERR
      IF(IERR.LT.0) GO TO 10
C     WRITE(LU,*) '!!! OPENING FAST DATA FILE, #ADVYY.'
      LUX=LU
C     CALL READF(IDCB1,IERR,RTEXT,12720B,LEN)
      LEN=FMPREAD(IDCB1, IERR, ABB, 5626*2)
C     WRITE(LU,*) '  @AFTER READ OF #ADVYY: LEN:',LEN,';IERR:',IERR
      IF(IERR.LT.0 .OR. LEN.NE.5626*2) GO TO 10
C     WRITE(LU,6999) 'FIRST 20 WORDS OF RTEXT TABLE',(RTEXT(I),I=1,20)
C     WRITE(LU,6999) 'FIRST 20 WORDS OF ABB TABLE',(ABB(I),I=1,20)
C     CALL OPEN(IDCB2,IERR,NAM2,1,0,ICR,IDCBS)
      CALL FMPCLOSE(IDCB2,IERR) !DWH-CLEAR OUT DCB OR NEXT OPEN FAILS
      CALL FMPOPEN(IDCB2,IERR,CNAM2,'RO',1)
C     WRITE(LU,*) '@FMPOPEN OF ',CNAM2,': IERR:',IERR
      IF(IERR.LT.0) GO TO 10
      LU=LUX
      CALL CLOSE(IDCB1,IERR)
      GO TO 1110
C
C     IF THE INITIALIZED COMMON FILE OR THE RECONSTRUCTED DATA FILE ARE
C     NOT FOUND, THE PROGRAM COMES HERE FOR FULL INITIALIZATION.
C
10    CONTINUE
C     WRITE(LU) 'CNAM3 DOESN''T EXIST. CLOSE AND DELETE IT'
C     WRITE(LU) '  BEFORE CLOSE '
C     CALL CLOSE(IDCB1,IERR)
      CALL FMPCLOSE(IDCB1, IERR)              !DWH-REPL CLOSE->FMPCLOSE
C     WRITE(LU) '  BEFORE PURGE '
C     CALL PURGE(IDCB1,IERR,NAM3)
      CALL FMPPURGE(CNAM3)              !DWH-REPL PURGE->FMPPURGE
C     WRITE(LU) 'OPEN SOURCE DATA FILE, CNAM1'
C     WRITE(LU) '  BEFORE OPEN: CNAM1: ', CNAM1
C     CALL OPEN(IDCB1,IERR,NAM1,1,0,ICR,2064)
      CALL FMPOPEN(IDCB1, IERR, CNAM1, 'RO', 1)   !DWH REPL FMGR OPEN
C     WRITE(LU,6900) IERR,NAM1
6900  FORMAT(" OPEN ERROR CODE",I6," FROM ",3A2)
C     WRITE(LU) '  BEFORE CREAT: CNAM2: ', CNAM2
C     CALL CREAT(IDCB2,JERR,NAM2,ISIZE,2,0,ICR,IDCBS)
C     WRITE(LU,6901) JERR,NAM2
C     WRITE(LU) 'CREATE & OPEN CNAM2'
      CALL FMPPURGE(CNAM2)
C     WRITE(LU) '  BEFORE OPEN: CNAM2: ', CNAM2
C     CALL OPEN(IDCB2,IERR,NAM2,1,0,ICR,IDCBS)
      CALL FMPOPEN(IDCB2,IERR,CNAM2,'RWCO',1)
C     WRITE(LU,6900) IERR,NAM2
6901  FORMAT("CREAT ERROR CODE",I6," FROM ",3A2)
C
      ASCVAR = 1
      LINUSE=1
      TRVS=1
      CLSSES=1
C
C  START NEW DATA SECTION.  SECT IS THE SECTION NUMBER.
C
1002  CONTINUE
C     WRITE(LU) '@START NEW DATA SECTION'
C     WRITE(LU,6998) '@!!! ATAB:', KTAB(1), ATAB(1),A2TAB(1) !DWH-ADDED
6998  FORMAT(A,I5,1X,2A2) !DWH-ADDED
      CALL CLRQ(QBUF,1,88)
C     CALL READF(IDCB1,IERR,IBUF,44,LEN)
      LEN=FMPREAD(IDCB1,IERR,IBUF,44*2)     !DWH-REPL READF->FMPREAD
C     WRITE(LU,6903) IERR,LEN,(IBUF(KQ),KQ=1,LEN) !DWH-***** UNCOMMENTED
6903  FORMAT(2I8,/,40A2)
C     CALL CODE
      READ(CIBUF,*) SECT
      WRITE(LU,930) SECT
930   FORMAT(" NOW LOADING SECTION",I3,".")
C     READ(5,*) IYN
C     IF(SECT.GT.1) CALL POST(IDCB2,IERR)
      OLDLOC=-1
      GOTO(1100,1004,1004,1030,1040,1004,1004,1050,1060,1070,1004,
     1    1080,1004,932) (SECT+1)
C           (0)  (1)  (2)  (3)  (4)  (5)  (6)  (7)  (8)  (9)  (10)
C          (11) (12)
932   CALL BUG(LU,9)
C
C  SECTIONS 1, 2, 5, 6, 10, 12.  READ MESSAGES AND SET UP POINTERS.
C
1004  CONTINUE
C     IF (SECT.GE.5) THEN
C       WRITE(LU,*) '@1004:SECTS:1/2/5/6/10/12'
C       WRITE(LU,6998) '@!!! ATAB:', KTAB(1), ATAB(1),A2TAB(1)
C     ENDIF
      CALL CLRQ(QBUF,1,80)
C     CALL READF(IDCB1,IERR,IBUF,44,LEN)
      LEN=FMPREAD(IDCB1,IERR,IBUF,44*2)     !DWH-REPL READF->FMPREAD
C     WRITE(LU,6903) IERR,LEN,(IBUF(KQ),KQ=1,LEN) !DWH-UNCOMMENTED
      QBUF(1)=80
20    IF(IPOSQ(QBUF,QCOMMA,1).EQ.6) GO TO 22
      CALL NSRTQ(QBUF,0,QBLNK)
      GO TO 20
22    CONTINUE
      READ(CIBUF(1:5),'(I5)') LOC
      CALL A2GET(CIBUF,7,LINES,40)
1005  FORMAT(I5,1X,40A2)
C     IF(SECT.GT.9) WRITE(LU,6902) LOC,LINES !DWH-UNCOMMENTED
C     WRITE(LU,6902) LOC,LINES !DWH-ADDED
6902  FORMAT(I5,", ",40A2)
C     WRITE(2'ASCVAR) LOC,LINES
C     IF(JERR.NE.-2) CALL WRITF(IDCB2,IERR,IBUF,44)
      IF(JERR.NE.-2) CALL FMPWRITE(IDCB2,IERR,IBUF,44*2) !DWH-WRITF->FMPWRITE
C     WRITE(LU,6789) IERR,JERR
6789  FORMAT("WRITF ERROR",2I5)
      ASCVAR=ASCVAR+1
      LINUSE = ASCVAR-1
      IF(LOC .EQ. -1) GO TO 1002
C     IF(LOC .EQ. -1) THEN
C       WRITE(LU,*) '@END OF BLOCK FOUND (LOC -1)'
C       WRITE(LU,6998) '@!!! ATAB:', KTAB(1), ATAB(1),A2TAB(1)
C       IF (SECT .EQ. 5) STOP 7770
C       GOTO 1002
C     ENDIF
      IF(LOC .EQ. OLDLOC) GO TO 1020
      IF(SECT.EQ.12)GOTO 1013
      IF(SECT.EQ.10)GOTO 1012
      IF(SECT.EQ.6)GOTO 1011
      IF(SECT.EQ.5)GOTO 1010
      IF(SECT.EQ.1)GOTO 1008
C
      STEXT(LOC)=LINUSE
      GOTO 1020
C
1008  LTEXT(LOC)=LINUSE
      GOTO 1020
C
1010  IF(LOC.GT.0.AND.LOC.LE.100)PTEXT(LOC)=LINUSE
      GOTO 1020
C
1011  IF(LOC .GT. RTXSIZ) CALL BUG(LU,6)
      RTEXT(LOC)=LINUSE
      GOTO 1020
C
1012  CTEXT(CLSSES)=LINUSE
      CVAL(CLSSES)=LOC
      CLSSES=CLSSES+1
      GOTO 1020
C
1013  CONTINUE
C     IF(LOC.GT.MAGSIZ)CALL BUG(LU,6)
C     MTEXT(LOC)=LINUSE
C
1020  OLDLOC = LOC
      IF(LINUSE .GE. FILSIZ) CALL BUG(LU,2)
      GOTO 1004
C
C  THE STUFF FOR SECTION 3 IS ENCODED HERE.  EACH "FROM-LOCATION" GETS A
C  CONTIGUOUS SECTION OF THE "TRAVEL" ARRAY.  EACH ENTRY IN TRAVEL IS
C  KEYWORD (FROM SECTION 4, MOTION VERBS), AND IS NEGATED IF
C  THIS IS THE LAST ENTRY FOR THIS LOCATION.  KEY(N) IS THE INDEX IN TRAVEL
C  OF THE FIRST OPTION AT LOCATION N.
C
C  SPECIAL CONDITIONS ON TRAVEL ARE ENCODED IN THE CORRESPONDING
C  ENTRIES OF TRVCON.  THE NEW LOCATION IS IN TRVLOC.
C
C
1030  CONTINUE
C     WRITE(LU) '@1030/SECTION3: BEFORE CLRQ'
      CALL CLRQ(QBUF,1,80)
C     CALL READF(IDCB1,IERR,IBUF,44,LEN)
C     WRITE(LU) '@BEFORE FMPREAD'
      LEN=FMPREAD(IDCB1,IERR,IBUF,44*2)   !DWH-READF->FMPREAD
      LEN=LEN/2                           !DWH-CONVERT BYTES TO WORDS
C     WRITE(LU,*) '@AFTER FMPREAD, LEN=', LEN
C     WRITE(LU,6903) IERR,LEN,(IBUF(KQ),KQ=1,LEN) !DWH-UNCOMMENTED
C     WRITE(LU) '@BEFORE READ(IBUF)'
C     CALL CODE !IF NXT I/O GENS ERROR, ABORT !DWH-DON'T CALL HERE
      READ(CIBUF,*)LOC
C     WRITE(LU) '@AFTER READ(IBUF)'
      IF(LOC.EQ.-1) GOTO 1002
C     WRITE(LU) '@BEFORE 2ND READ(IBUF)'
C     CALL CODE
      READ(CIBUF,*)LOC,J,NEWLOC,TK
      IF(KEY(LOC).NE.0)GOTO 1033
      KEY(LOC)=TRVS
      GOTO 1035
1033  TRAVEL(TRVS-1)=-TRAVEL(TRVS-1)
1035  DO 1037 L=1,20
      IF(TK(L).EQ.0)GOTO 1039
      TRAVEL(TRVS)=TK(L)
      TRVLOC(TRVS)=NEWLOC
      TRVCON(TRVS)=J
      TRVS=TRVS+1
      IF(TRVS.EQ.TRVSIZ)CALL BUG(LU,3)
C     WRITE(LU,4429) LOC,J,NEWLOC,TRAVEL(TRVS),TRVLOC(TRVS),
C    A  TRVCON(TRVS),TRVS
1037  CONTINUE
1039  TRAVEL(TRVS-1)=-TRAVEL(TRVS-1)
C     WRITE(LU,4429) LOC,J,NEWLOC,TRAVEL(TRVS),TRVLOC(TRVS),
C    A  TRVCON(TRVS),TRVS
4429  FORMAT(8I8)
      GOTO 1030
C
C  HERE WE READ IN THE VOCABULARY.  KTAB(N) IS THE WORD NUMBER, ATAB(N) IS
C  THE CORRESPONDING WORD.  THE -1 AT THE END OF SECTION 4 IS LEFT IN KTAB
C  AS AN END-MARKER.
C
1040  CONTINUE
C     WRITE(LU) '@1040/SECT 4'
      DO 1042 TABNDX=1,TABSIZ
1043  CALL CLRQ(QBUF,1,80)
C     CALL READF(IDCB1,IERR,IBUF,44,LEN)
      LEN = FMPREAD(IDCB1,IERR,IBUF,44*2)
      LEN = LEN / 2
C     WRITE(LU,*) '@AFTER FMPREAD, LEN=', LEN
C     WRITE(LU,6903) IERR,LEN,(IBUF(KQ),KQ=1,LEN) !DWH-REMOVED COMMENT
      QBUF(1)=80
40    CONTINUE
C     WRITE(LU,*) 'IPOSQ=', IPOSQ(QBUF,QCOMMA,1)
      IF(IPOSQ(QBUF,QCOMMA,1).EQ.6) GO TO 42
C     WRITE(LU) '@BEFORE NSRTQ'
      CALL NSRTQ(QBUF,0,QBLNK)
      GO TO 40
42    CONTINUE
C     WRITE(LU) '@BEFORE READ(IBUF)'
C     CALL CODE
      READ(CIBUF(1:5),'(I5)') KTAB(TABNDX)
      CALL A2GET(CIBUF,7,ATAB(TABNDX),1)
      CALL A2GET(CIBUF,9,A2TAB(TABNDX),1)
1041  FORMAT(I5,1X,2A2)
C     WRITE(LU,1041) KTAB(TABNDX),ATAB(TABNDX),A2TAB(TABNDX) !DWH-REMOVED CMT
      IF(KTAB(TABNDX).EQ.-1) GOTO 1002
C     IF(KTAB(TABNDX).EQ.-1) THEN
C       WRITE(LU,*) '@DUMP ATAB:' !-DWH:ADDED
C       DO I = 1,20
C         WRITE(LU,1041) KTAB(I), ATAB(I),A2TAB(I)
C       END DO
C       GOTO 1002
C     ENDIF

1042  CONTINUE
      CALL BUG(LU,4)
C
C  READ IN THE INITIAL LOCATIONS FOR EACH OBJECT.  ALSO THE IMMOVABILITY INFO.
C  PLAC CONTAINS INITIAL LOCATIONS OF OBJECTS.  FIXD IS -1 FOR IMMOVABLE
C  OBJECTS (INCLUDING THE SNAKE), OR = SECOND LOC FOR TWO-PLACED OBJECTS.
C
1050  CONTINUE
C     WRITE(LU) '@1050/SEC 7'
      CALL CLRQ(QBUF,1,88)
C     CALL READF(IDCB1,IERR,IBUF,44,LEN)
      LEN = FMPREAD(IDCB1,IERR,IBUF,44/2)  !DWH-REPL READF->FMPREAD
      LEN = LEN / 2
      IBUF(44)=12079
      OBJ=0
      J=0
      K=0
C     CALL CODE
C added wtn 8/1/05
      READ(CIBUF,*) OBJ
      IF (OBJ .EQ. -1) GO TO 1002
C     CALL CODE
C
      READ(CIBUF,*)OBJ,J,K
C     WRITE(LU,14000) OBJ,J,K !DWH-REMOVED COMMENT
14000 FORMAT(3I8)
C     IF(OBJ.EQ.-1)GOTO 1002
C commented above, added wtn..
      IF (K.NE.999)GOTO 1051
      K=0
1051  PLAC(OBJ)=J
C end mods
C #ADVZZ section 7 modified to add ,999 to 2-field entries
      FIXD(OBJ)=K
      GOTO 1050
C
C  READ DEFAULT MESSAGE NUMBERS FOR ACTION VERBS, STORE IN ACTSPK.
C
1060  CONTINUE
C     WRITE(LU) '@1060/SECT 8'
      CALL CLRQ(QBUF,1,80)
C     CALL READF(IDCB1,IERR,IBUF,44,LEN)
      LEN = FMPREAD(IDCB1,IERR,IBUF,44/2)
      LEN = LEN / 2
C     CALL CODE
      READ(CIBUF,*)VERB
      IF(VERB.EQ.-1) GOTO 1002
C     CALL CODE
      READ(CIBUF,*)VERB,J
C     WRITE(LU,*) '@VERB: ', VERB, '; J: ', J
      ACTSPK(VERB)=J
      VCOUNT=MAX(VERB,VCOUNT)
      GOTO 1060
C
C  READ INFO ABOUT AVAILABLE LIQUIDS AND OTHER CONDITIONS, STORE IN COND.
C
1070  CONTINUE
C     WRITE(LU) '@1070/SECT 9'
      CALL CLRQ(QBUF,1,80)
C     CALL READF(IDCB1,IERR,IBUF,44,LEN)
      LEN = FMPREAD(IDCB1,IERR,IBUF,44/2)
      LEN = LEN / 2
C     WRITE(LU,6903) IERR,LEN,(IBUF(KQ),KQ=1,LEN) !DWH-REMOVED COMMENT
C     WRITE(LU) '@FIRST READ(IBUF)'
C     CALL CODE
      READ(CIBUF,*)K
C     WRITE(LU,*) '  @K:', K
      IF(K.EQ.-1) GOTO 1002
C     WRITE(LU) '@SECOND READ(IBUF)'
      DO I=1,20  !DWH-NEED TO INITIALIZE TK TO ZEROS AS READ WON'T
        TK(I)=0
      END DO
C     CALL CODE
C     READ(CIBUF,*)K,TK
      READ(CIBUF,*,IOSTAT=IERR) K,(TK(I),I=1,20) !DWH- ORIG READ FAILS
C     WRITE(LU,*) '  @IERR: ', IERR, '; K:', K, '; TK[1]:', TK(1),
C    A  '; TK(2): ', TK(2), '; TK(3): ', TK(3)
C     WRITE(LU) '@DUMP OF TK ARRAY:'
C     WRITE(LU,6906) IERR, K, (TK(I),I=1,20) !DWH-DUMP TK ARRAY
C6906  FORMAT(2I8,/,20I5)
C     WRITE(LU) '@DO 1071'
      DO 1071 I=1,20
      LOC=TK(I)
      IF(LOC.EQ.0)GOTO 1070
C     IF(BITSET(LOC,K))CALL BUG(LU,8)
1071  COND(LOC)=COND(LOC)+ISHFT(1,K)
C     WRITE(LU,6907) K,LOC,COND(LOC),KQ1,KQ2 !DWH-REMOVED COMMENTD
6907  FORMAT("K,LOC,COND(LOC),BITSET(LOC,K),ISHFT(1,K):",5I6)
      GOTO 1070
C
C  READ DATA FOR HINTS.
C
1080  CONTINUE
C     WRITE(LU) '@1080/SECT 11'
      HNTMAX=0
1081  CALL CLRQ(QBUF,1,80)
C     CALL READF(IDCB1,IERR,IBUF,44,LEN)
      LEN = FMPREAD(IDCB1,IERR,IBUF,44)
      LEN = LEN / 2
C     CALL CODE
      READ(CIBUF,*)K
C     WRITE(LU,*) '@K: ', K
      IF(K.EQ.-1) GOTO 1002
      DO I=1,20 !DWH-NEED TO INIT TK TO ZXEROS AS READ WON'T
        TK(I)=0
      END DO
C     WRITE(LU) '@2ND READ'
C     CALL CODE
C     READ(CIBUF,*)K,TK
      READ(CIBUF,*,IOSTAT=IERR) K,(TK(I),I=1,20) !DWH-ORIG READ FAILS
      IF(K.LT.0.OR.K.GT.HNTSIZ)CALL BUG(LU,7)
      DO 1083 I=1,4
1083  HINTS(K,I)=TK(I)
      HNTMAX=MAX(HNTMAX,K)
      GOTO 1081
C  FINISH CONSTRUCTING INTERNAL DATA FORMAT
C
1100  CONTINUE
C     WRITE(LU) '@1100: COMPLETE FILE CREATION'
      CALL FMPCLOSE(IDCB1,IERR)
C     CALL FMPCLOSE(IDCB2,IERR) !DWH-ADDED - NO, DON'T THINK I WANT THIS
C
C     WHEN THE PROGRAM GETS HERE, IT HAS COMPLETED ITS DISC FILE SETUP
C     AND COMMON INITIALIZATION.  CREATE A NEW COMMON INITIALIZATION FILE
C     AND WRITE COMMON TO IT.

C     !DWH- THE WAY THIS GUY SAVES COMMON AREA TO A FILE IS HORRIBLE.
C     HE TAKES THE FIRST VAR IN COMMON (RTEXT) AND KNOWS THE ENTIRE SIZE
C     OF COMMON SO HE WRITE RTEXT FOR THAT MANY WORDS TO A FILE. I TRIED TO
C     GET THAT TO WORK IN RTE-6/VM & FTN77 AND IT IS PROBLEMATIC. COMMON
C     COMMON IS NOT LAID OUT IN MEMORY AS IT IS IN THE SOURCE. WHILE
C     /TXTCM/RTEXT MIGHT BE FIRST IN THE SOURCE, IF YOU LOOK AT THE LOAD MAP
C     (ADVEN.MAP), YOU SEE THAT /ABBCM/ IS THE FIRST COMMON AREA.
C     I ALSO USED THE MAP TO ADD THE SIZE OF ALL OF THE COMMON AREAS TO
C     FIGURE OUT HOW MANY WORDS (BYTES) TO WRITE. I HAVE IT WORKING, BUT
C     I DON'T KNOW IF LINK WILL ALWAYS PUT COMMONS IN THE SAME ORDER.
C     ON THE OTHER HAND, IF IT DOESN'T THE WRITE (AND PROBABLY READ) WILL
C     FAIL WITH A BOUNDS VOLATION.
C
C     !DWH- UPON FURTHER EXAMINATION OF THE COMMON MEMMORY IN ADVEN.MAP,
C     THE FMP FILE SYSTEM HAS A COUPLE OF MEMORY BLOCKS EMBEDDED IN THE
C     MIDDLE OF THE PROGRAM'S COMMON BLOCKS. ATTEMPTING TO READ/WRITE
C     COMMON MEMORY FROM/TO A FILE IS GOING TO OVERWRITE DATA IN THE
C     FMP BLOCKS. THEREFORE, ADVEN NEEDS TO READ THE SOURCE DATA FILE
C     EACH TIME. TO KEEP THIS SIMPLE (AND SINCE THE EMULATION RUNS MUCH
C     FASTER THAN THE REAL MACHINE), I WILL JUST DELETE <CNAM3> AT START
C     AND LET THE PROGRAM REBUILD IT EACH TIME.

C     CALL CREAT(IDCB1,IERR,NAM3,JSIZE,3,0,ICR,2064)
C     WRITE(LU,*) '@CREATE ', CNAM3
      IERR = -1
C     WRITE(LU,*) '@AFTER FMPOPEN, IERR: ', IERR
      IF(IERR.LT.0) GO TO 1110
C     CALL WRITF(IDCB1,IERR,RTEXT,12720B)
C     LEN=FMPWRITE(IDCB1,IERR,ABB,5626*2)
C     LEN=FMPWRITE(IDCB1,IERR,ADVCOM,5626*2) !DWH-SIZE FROM ADVEN.MAP
C     WRITE(LU,*) '@AFTER FMPWRITE(#ADVYY: LEN: ', LEN, '; IERR: ', IERR
C     WRITE(LU,6999) 'FIRST 20 WORDS OF RTEXT TABLE',(RTEXT(I),I=1,20)
C     WRITE(LU,6999) 'FIRST 20 WORDS OF ABB TABLE',(ABB(I),I=1,20)
6999  FORMAT (A29,/,20I5)
      CALL FMPCLOSE(IDCB1,IERR)
C
1110  CONTINUE
C
C  HAVING READ IN THE DATABASE, CERTAIN THINGS ARE NOW CONSTRUCTED.  PROPS ARE
C  SET TO ZERO.  WE FINISH SETTING UP COND BY CHECKING FOR FORCED-MOTION TRAVEL
C  ENTRIES.  THE PLAC AND FIXD ARRAYS ARE USED TO SET UP ATLOC(N) AS THE FIRST
C  OBJECT AT LOCATION N, AND LINKX(OBJ) AS THE NEXT OBJECT AT THE SAME LOCATION
C  AS OBJ.  (OBJ>100 INDICATES THAT FIXED(OBJ-100)=LOC; LINKX(OBJ) IS STILL THE
C  CORRECT LINKX TO USE.)  ABB IS ZEROED; IT CONTROLS WHETHER THE ABBREVIATED
C  DESCRIPTION IS PRINTED.  COUNTS MOD 5 UNLESS "LOOK" IS USED.
C
C
C  IF THE FIRST MOTION VERB IS 1 (ILLEGAL), THEN THIS IS A FORCED
C  MOTION ENTRY.
C
C     WRITE(LU) '@DO 1102'
      DO 1102 I=1,LOCSIZ
      IF(LTEXT(I).EQ.0.OR.KEY(I).EQ.0)GOTO 1102
      K=KEY(I)
      IF(ABS(TRAVEL(K)).EQ.1)COND(I)=2
1102  CONTINUE
C
C  SET UP THE ATLOC AND LINKX ARRAYS AS DESCRIBED ABOVE.  WE'LL USE THE DROP
C  SUBROUTINE, WHICH PREFACES NEW OBJECTS ON THE LISTS.  SINCE WE WANT THINGS
C  IN THE OTHER ORDER, WE'LL RUN THE LOOP BACKWARDS.  IF THE OBJECT IS IN TWO
C  LOCS, WE DROP IT TWICE.  THIS ALSO SETS UP "PLACE" AND "FIXED" AS COPIES OF
C  "PLAC" AND "FIXD".  ALSO, SINCE TWO-PLACED OBJECTS ARE TYPICALLY BEST
C  DESCRIBED LAST, WE'LL DROP THEM FIRST.
C
      DO 1106 I=1,100
      K=101-I
      IF(FIXD(K).LE.0)GOTO 1106
      CALL DROP(K+100,FIXD(K))
      CALL DROP(K,PLAC(K))
1106  CONTINUE
C
      DO 1107 I=1,100
      K=101-I
      FIXED(K)=FIXD(K)
1107  IF(PLAC(K).NE.0.AND.FIXD(K).LE.0)CALL DROP(K,PLAC(K))
C
C  TREASURES, AS NOTED EARLIER, ARE OBJECTS 50 THROUGH MAXTRS (CURRENTLY 79).
C  THEIR PROPS ARE INITIALLY -1, AND ARE SET TO 0 THE FIRST TIME THEY ARE
C  DESCRIBED.  TALLY KEEPS TRACK OF HOW MANY ARE NOT YET FOUND, SO WE KNOW
C  WHEN TO CLOSE THE CAVE.  TALLY2 COUNTS HOW MANY CAN NEVER BE FOUND (E.G. IF
C  LOST BIRD OR BRIDGE).
C
      MAXTRS=79
      TALLY=0
      TALLY2=0
      DO 1200 I=50,MAXTRS
      IF(PTEXT(I).NE.0)PROP(I)=-1
1200  TALLY=TALLY-PROP(I)
C
C  CLEAR THE HINT STUFF.  HINTLC(I) IS HOW LONG HE'S BEEN AT LOC WITH COND BIT
C  I.  HINTED(I) IS TRUE IFF HINT I HAS BEEN USED.
C
C     WRITE(LU) '@DO 1300'
      DO 1300 I=1,HNTMAX
      HINTED(I)=.FALSE.
1300  HINTLC(I)=0
C
C     IF(JERR.NE.-2) WRITE(LU,931) TABNDX,TABSIZ,VCOUNT,VRBSIZ,CLSSES,
C    1     CLSMAX,HNTMAX,HNTSIZ,TRVS,TRVSIZ,LINUSE,FILSIZ
 931  FORMAT(" USED VS MAX TABLE VALUES:",/
     1     1X,I5," OF ",I5," VOCAB ENTRIES",/
     2     1X,I5," OF ",I5," VERB ENTRIES",/
     3     1X,I5," OF ",I5," CLASS ENTRIES",/
     4     1X,I5," OF ",I5," HINT ENTRIES",/
     5     1X,I5," OF ",I5," TRAVEL ENTRIES",/
     6     1X,I5," OF ",I5," FILE RECORDS",/
     9     )
C
C  DEFINE SOME HANDY MNEMONICS.  THESE CORRESPOND TO OBJECT NUMBERS.
C
      CALL MORE
C     WRITE(LU,6905)
C6905  FORMAT(" RETURNED FROM INITIALIZATION OF VOCAB.")
C
C  INITIALISE THE DWARVES.  DLOC IS LOC OF DWARVES, HARD-WIRED IN.  ODLOC IS
C  PRIOR LOC OF EACH DWARF, INITIALLY GARBAGE.  DALTLC IS ALTERNATE INITIAL LOC
C  FOR DWARF, IN CASE ONE OF THEM STARTS OUT ON TOP OF THE ADVENTURER.  (NO 2
C  OF THE 5 INITIAL LOCS ARE ADJACENT.)  DSEEN IS TRUE IF DWARF HAS SEEN HIM.
C  DFLAG CONTROLS THE LEVEL OF ACTIVATION OF ALL THIS:
C     0     NO DWARF STUFF YET (WAIT UNTIL REACHES HALL OF MISTS)
C     1     REACHED HALL OF MISTS, BUT HASN'T MET FIRST DWARF
C     2     MET FIRST DWARF, OTHERS START MOVING, NO KNIVES THROWN YET
C     3     A KNIFE HAS BEEN THROWN (FIRST SET ALWAYS MISSES)
C     3+    DWARVES ARE MAD (INCREASES THEIR ACCURACY)
C  SIXTH DWARF IS SPECIAL (THE PIRATE).  HE ALWAYS STARTS AT HIS CHEST'S
C  EVENTUAL LOCATION INSIDE THE MAZE.  THIS LOC IS SAVED IN CHLOC FOR REF.
C  THE DEAD END IN THE OTHER MAZE HAS ITS LOC STORED IN CHLOC2.
C
      CHLOC=114
      CHLOC2=140
      DO 1700 I=1,6
1700  DSEEN(I)=.FALSE.
      DFLAG=0
      DLOC(1)=19
      DLOC(2)=27
      DLOC(3)=33
      DLOC(4)=44
      DLOC(5)=64
      DLOC(6)=CHLOC
      DALTLC=18
C
C  OTHER RANDOM FLAGS AND COUNTERS, AS FOLLOWS:
C     TURNS TALLIES HOW MANY COMMANDS HE'S GIVEN (IGNORES YES/NO)
C     LIMIT LIFETIME OF LAMP (NOT SET HERE)
C     KNFLOC      0 IF NO KNIFE HERE, LOC IF KNIFE HERE, -1 AFTER CAVEAT
C     DETAIL      HOW OFTEN WE'VE SAID "NOT ALLOWED TO GIVE MORE DETAIL"
C     ABBNUM      HOW OFTEN WE SHOULD PRINT NON-ABBREVIATED DESCRIPTIONS
C     MAXDIE      NUMBER OF REINCARNATION MESSAGES AVAILABLE (UP TO 5)
C     NUMDIE      NUMBER OF TIMES KILLED SO FAR
C     HOLDNG      NUMBER OF OBJECTS BEING CARRIED
C     DKILL NUMBER OF DWARVES KILLED (UNUSED IN SCORING, NEEDED FOR MSG)
C     FOOBAR      CURRENT PROGRESS IN SAYING "FEE FIE FOE FOO".
C     BONUS USED TO DETERMINE AMOUNT OF BONUS IF HE REACHES CLOSING
C     CLOCK1      NUMBER OF TURNS FROM FINDING LAST TREASURE TILL CLOSING
C     CLOCK2      NUMBER OF TURNS FROM FIRST WARNING TILL BLINDING FLASH
C     LOGICALS WERE EXPLAINED EARLIER
C
      TURNS=0
      LMWARN=.FALSE.
      KNFLOC=0
      DETAIL=0
      ABBNUM=5
C     WRITE(LU) '@DO 1800'
      DO 1800 I=1,5
1800  IF(RTEXT(2*(I-1)+81).NE.0)MAXDIE=I
      NUMDIE=0
      HOLDNG=0
      DKILL=0
      FOOBAR=0
      BONUS=0
      CLOCK1=60
      CLOCK2=50
      CLOSNG=.FALSE.
      PANIC=.FALSE.
      CLOSED=.FALSE.
      GAVEUP=.FALSE.
      SCORNG=.FALSE.
C
C
C
C  FINALLY, SINCE WE'RE CLEARLY SETTING THINGS UP FOR THE FIRST TIME...
C
C     WRITE(LU) '@INIT DONE'
D     PAUSE 'INIT DONE'
1     ICNTRL=100
2     CONTINUE
C     CALL RETRN
      CALL SEGRT                  !DWH-RETURN TO CALLING SEGLD
      END

      SUBROUTINE MORE
C
C     THIS SUBROUTINE DOES MORE "VOCAB" CALLS, BECAUSE THE COMPILER
C     GETS UNHAPPY WITH ALL THE EXTERNAL REFERENCES OR SOME SUCH BULLSHIT
C
C
      IMPLICIT INTEGER*2 (A-Z)
      LOGICAL*2 BLKLIN,NOINPT
      LOGICAL*2 DSEEN,HINTED
C     Statement-function dummies handed literal constants.
      INTEGER*4 NBIT
      INTEGER*2 LBIT
      LOGICAL*2 BITSET,LMWARN,CLOSNG,PANIC,
     1       CLOSED,GAVEUP,SCORNG
C
      COMMON /TXTCM/ RTEXT,LINES,ASCVAR,LU,ICNTRL
      COMMON /BLKCM/ BLKLIN,NOINPT
      COMMON /ALPHS/ BLANK,EOF,CYE,CY,CNO,CN,CPO,CUR,CWE,CST,
     A               CEN,CTE
      COMMON /VOCCM/ KTAB,ATAB,A2TAB,TABSIZ
      COMMON /PLACM/ ATLOC,LINKX,PLACE,FIXED,HOLDNG
C     COMMON /MTXCM/ MTEXT
      COMMON /PTXCM/ PTEXT
      COMMON /ABBCM/ ABB
      COMMON /MISCM/ LINUSE,TRVS,CLSSES,OLDLOC,LOC,CVAL,TK,NEWLOC,
     1KEY,PLAC,FIXD,ACTSPK,COND,HINTS,HNTMAX,PROP,TALLY,TALLY2,
     2HINTLC,CHLOC,CHLOC2,DSEEN,DFLAG,DLOC,DALTLC,KEYS,LAMP,GRATE,
     3CAGE,ROD,ROD2,STEPS,BIRD,DOOR,PILLOW,SNAKE,FISSUR,TABLET,
     4CLAM,OYSTER,MAGZIN,DWARF,KNIFE,FOOD,BOTTLE,WATER,OIL,PLANT,
     5PLANT2,AXE,MIRROR,DRAGON,CHASM,TROLL,TROLL2,BEAR,MESSAG,VEND,
     6BATTER,NUGGET,COINS,CHEST,EGGS,TRIDNT,VASE,EMRALD,PYRAM,
     7PEARL,RUG,CHAIN,BACK,LOOK,CAVE,NULL,ENTRNC,DPRSSN,SAY,LOCK,
     8THROW,FIND,INVENT,TURNS,LMWARN,KNFLOC,DETAIL,ABBNUM,
     9NUMDIE,MAXDIE,DKILL,FOOBAR,BONUS,CLOCK1,CLOCK2,
     1CLOSNG,PANIC,CLOSED,GAVEUP,SCORNG,ODLOC,STREAM
      COMMON /MISC2/ I,RTXSIZ,CLSMAX,MAGSIZ,LOCSIZ,CTEXT,STEXT,LTEXT,
     1SECT,TRAVEL,TRVCON,TRVLOC,TRVSIZ,TABNDX,OBJ,J,K,VERB,HNTSIZ,
     2MAXTRS,HINTED,HNTLOC,KK
C
      DIMENSION LINES(40)
      DIMENSION TRAVEL(760),TRVCON(760),TRVLOC(760)
      DIMENSION KTAB(300),ATAB(300),A2TAB(300)
      DIMENSION LTEXT(150),STEXT(150),KEY(150),COND(150),ABB(150),
     1      ATLOC(150)
      DIMENSION PLAC(100),PLACE(100),FIXD(100),FIXED(100),LINKX(200),
     1      PTEXT(100),PROP(100)
      DIMENSION ACTSPK(35)
      DIMENSION RTEXT(215)
      DIMENSION CTEXT(12),CVAL(12)
      DIMENSION HINTLC(20),HINTED(20),HINTS(20,4)
C     DIMENSION MTEXT(35)
      DIMENSION TK(20),DSEEN(6),DLOC(6),ODLOC(6)
C
C     WRITE(LU,*) '@MORE: LU:', LU
C     WRITE(LU,*) '  @CALLING VOCAB'
      CALL VOCAB(2HKE,2HYS,1,KEYS)
C     WRITE(LU,*) '  @RETURNED FROM VOCAB'
      CALL VOCAB(2HLA,2HMP,1,LAMP)
      CALL VOCAB(2HGR,2HAT,1,GRATE)
      CALL VOCAB(2HCA,2HGE,1,CAGE)
      CALL VOCAB(2HRO,2HD ,1,ROD)
      ROD2=ROD+1
      CALL VOCAB(2HST,2HEP,1,STEPS)
      CALL VOCAB(2HBI,2HRD,1,BIRD)
      CALL VOCAB(2HDO,2HOR,1,DOOR)
      CALL VOCAB(2HPI,2HLL,1,PILLOW)
      CALL VOCAB(2HPI,2HLL,1,PILLOW)
      CALL VOCAB(2HSN,2HAK,1,SNAKE)
      CALL VOCAB(2HFI,2HSS,1,FISSUR)
      CALL VOCAB(2HTA,2HBL,1,TABLET)
      CALL VOCAB(2HCL,2HAM,1,CLAM)
      CALL VOCAB(2HOY,2HST,1,OYSTER)
      CALL VOCAB(2HMA,2HGA,1,MAGZIN)
      CALL VOCAB(2HDW,2HAR,1,DWARF)
      CALL VOCAB(2HKN,2HIF,1,KNIFE)
      CALL VOCAB(2HFO,2HOD,1,FOOD)
      CALL VOCAB(2HBO,2HTT,1,BOTTLE)
      CALL VOCAB(2HWA,2HTE,1,WATER)
      CALL VOCAB(2HOI,2HL ,1,OIL)
      CALL VOCAB(2HPL,2HAN,1,PLANT)
      PLANT2=PLANT+1
      CALL VOCAB(2HAX,2HE ,1,AXE)
      CALL VOCAB(2HMI,2HRR,1,MIRROR)
      CALL VOCAB(2HDR,2HAG,1,DRAGON)
      CALL VOCAB(2HCH,2HAS,1,CHASM)
      CALL VOCAB(2HTR,2HOL,1,TROLL)
      TROLL2=TROLL+1
      CALL VOCAB(2HBE,2HAR,1,BEAR)
      CALL VOCAB(2HME,2HSS,1,MESSAG)
      CALL VOCAB(2HVE,2HND,1,VEND)
      CALL VOCAB(2HBA,2HTT,1,BATTER)
C
C  OBJECTS FROM 50 THROUGH WHATEVER ARE TREASURES.  HERE ARE A FEW.
C
      CALL VOCAB(2HGO,2HLD,1,NUGGET)
      CALL VOCAB(2HCO,2HIN,1,COINS)
      CALL VOCAB(2HCH,2HES,1,CHEST)
      CALL VOCAB(2HEG,2HGS,1,EGGS)
      CALL VOCAB(2HVA,2HSE,1,VASE)
      CALL VOCAB(2HEM,2HER,1,EMRALD)
      CALL VOCAB(2HPY,2HRA,1,PYRAM)
      CALL VOCAB(2HPE,2HAR,1,PEARL)
      CALL VOCAB(2HTR,2HID,1,TRIDNT)
      CALL VOCAB(2HRU,2HG ,1,RUG)
      CALL VOCAB(2HCH,2HAI,1,CHAIN)
C
C  THESE ARE MOTION-VERB NUMBERS.
C
      CALL VOCAB(2HBA,2HCK,0,BACK)
      CALL VOCAB(2HLO,2HOK,0,LOOK)
      CALL VOCAB(2HCA,2HVE,0,CAVE)
      CALL VOCAB(2HNU,2HLL,0,NULL)
      CALL VOCAB(2HEN,2HTR,0,ENTRNC)
      CALL VOCAB(2HDE,2HPR,0,DPRSSN)
      CALL VOCAB(2HST,2HRE,0,STREAM)
C
C  AND SOME ACTION VERBS.
C
      CALL VOCAB(2HSA,2HY ,2,SAY)
      CALL VOCAB(2HLO,2HCK,2,LOCK)
      CALL VOCAB(2HTH,2HRO,2,THROW)
      CALL VOCAB(2HFI,2HND,2,FIND)
      CALL VOCAB(2HIN,2HVE,2,INVENT)
C     WRITE(LU) '@END OF MORE'
      END
C     END$

