C     FTN5
C======================================================================C
C                                                                      C
C      AA       DDDDDDDDD     VV        VV  YY        YY   2222222222  C
C     AAAA      DDDDDDDDDD    VV        VV  YY        YY  222222222222 C
C    AA  AA     DD       DD   VV        VV   YY      YY   22        22 C
C   AA    AA    DD        DD  VV        VV    YY    YY              22 C
C  AA      AA   DD        DD  VV        VV     YY  YY               22 C
C AA        AA  DD        DD  VV        VV      YYYY               22  C
C AAAAAAAAAAAA  DD        DD   VV      VV        YY              22    C
C AAAAAAAAAAAA  DD        DD   VV      VV        YY            22      C
C AA        AA  DD        DD     VV  VV          YY          22        C
C AA        AA  DD       DD      VV  VV          YY        22          C
C AA        AA  DDDDDDDDDD         VV            YY       222222222222 C
C AA        AA  DDDDDDDDD          VV            YY       222222222222 C
C                                                                      C
C======================================================================C
C                                                                      C
C REVISION LIST:                                                       C
C                                                                      C
C --DATE-- --BY-- -- D E S C R I P T I O N --                          C
C                                                                      C
C  3/07/81 AW     -ORIGINAL VERSION-                                   C
C                                                                      C
C======================================================================C
C  ADVENTURES
      SUBROUTINE ADV3
C
C MODIFIED BY KENT BLACKETT
C             ENGINEERING SYSTEMS GROUP
C             DIGITAL EQUIPMENT CORP.
C             15-JUL-77
C MODIFIED BY     BOB SUPNIK
C           DISK ENGINEERING
C           21-OCT-77
C ORIGINAL VERSION WAS FOR DECSYSTEM-10
C NEXT VERSION WAS FOR FORTRAN IV-PLUS UNDER
C THE IAS OPERATING SYSTEM ON THE PDP-11/70
C THIS VERSION IS FOR FORTRAN IV (V01C OR LATER)
C UNDER RT-11 ON *ANY* PDP-11
C
C
C  CURRENT LIMITS:
C     760 TRAVEL OPTIONS (TRAVEL, TRVSIZ).
C     300 VOCABULARY WORDS (KTAB, ATAB, TABSIZ).
C     150 LOCATIONS (LTEXT, STEXT, KEY, COND, ABB, ATLOC, LOCSIZ).
C     100 OBJECTS (IPLAC, IPLACE, FIXD, FIXED, LINKX (TWICE), PTEXT, PROP).
C      35 "ACTION" VERBS (ACTSPK, VRBSIZ).
C     215 RANDOM MESSAGES (RTEXT, RTXSIZ).
C      12 DIFFERENT PLAYER CLASSIFICATIONS (CTEXT, CVAL, CLSMAX).
C      20 HINTS, LESS 3 (HINTLC, HINTED, HINTS, HNTSIZ).
C     [MAGIC MESSAGES HAVE BEEN DECOMMITTED]
C      35 MAGIC MESSAGES (MTEXT, MAGSIZ).
C  THERE ARE ALSO LIMITS WHICH CANNOT BE EXCEEDED DUE TO THE STRUCTURE OF
C  THE DATABASE.  (E.G., THE VOCABULARY USES N/1000 TO DETERMINE WORD TYPE,
C  SO THERE CAN'T BE MORE THAN 1000 WORDS.)  THESE UPPER LIMITS ARE:
C     1000 NON-SYNONYMOUS VOCABULARY WORDS
C     300 LOCATIONS
C     100 OBJECTS
C
      IMPLICIT INTEGER*2 (A-Z)
C     Statement-function dummies handed literal constants; gfortran's
C     integer literals are 32-bit.  (Port change.)
      INTEGER*4 DUMMY,PBOTL,NPCT,NBIT
      INTEGER*2 LBIT
      LOGICAL*2 BLKLIN,NOINPT,FORCED,PCT
      LOGICAL*2 DSEEN,HINTED,YES
      LOGICAL*2 TOTNG,HERE,AT,BITST,DARK,WZDARK,LMWARN,CLOSNG,PANIC,
     1       CLOSED,GAVEUP,SCORNG,YEA
C
      COMMON /TXTCM/ RTEXT,LINES,ASCVAR,LU,ICNTRL
      COMMON /DCBCM/ IDCB2(144)
      COMMON /BLKCM/ BLKLIN,NOINPT
      COMMON /ALPHS/ BLANK,EOF,CYE,CY,CNO,CN,CPO,CUR,CWE,CST,
     1      CEN,CTE
      COMMON /VOCCM/ KTAB,ATAB,A2TAB,TABSIZ
      COMMON /PLACM/ ATLOC,LINKX,IPLACE,FIXED,HOLDNG
C     COMMON /MTXCM/ MTEXT
      COMMON /PTXCM/ PTEXT
      COMMON /ABBCM/ ABB
      COMMON /MISCM/ LINUSE,TRVS,CLSSES,OLDLOC,LOC,CVAL,TK,NEWLOC,
     1KEY,IPLAC,FIXD,ACTSPK,COND,HINTS,HNTMAX,PROP,TALLY,TALLY2,
     2HINTLC,CHLOC,CHLOC2,DSEEN,DFLAG,DLOC,DALTLC,KEYS,LAMP,GRATE,
     3CAGE,ROD,ROD2,STEPS,BIRD,DOOR,PILLOW,SNAKE,FISSUR,TABLET,
     4CLAM,OYSTER,MAGZIN,DWARF,KNIFE,FOOD,BOTTLE,WATER,OIL,PLANT,
     5PLANT2,AXE,MIRROR,DRAGON,CHASM,TROLL,TROLL2,BEAR,MESSAG,VEND,
     6BATTER,NUGGET,COINS,CHEST,EGGS,TRIDNT,VASE,EMRALD,PYRAM,
     7PEARL,RUG,CHAIN,BACK,LOOK,CAVE,NULL,ENTRNC,DPRSSN,SAY,LOCK,
     8THROW,FIND,INVENT,TURNS,LMWARN,KNFLOC,DETAIL,ABBNUM,
     9NUMDIE,MAXDIE,DKILL,FOOBAR,BONUS,CLOCK1,CLOCK2,
     1CLOSNG,PANIC,CLOSED,GAVEUP,SCORNG,ODLOC,STREAM
      COMMON /MISC2/ I,RTXSIZ,CLSMAX,MAGSIZ,LOCSIZ,CTEXT,STEXT,LTEXT,
     1SECT,TRAVEL,TRVCON,TRVLOC,TRVSIZ,TABNDX,OBJ,J,K,VERB,HNTSIZ,
     2MAXTRS,HINTED,HNTLOC,KK,LIMIT,SPK,WD1,WD1A,WD1X,WD2,WD2A,WD2X
C
      DIMENSION LINES(40),MISX(10)
      EQUIVALENCE (MISX,LINUSE)
      DIMENSION TRAVEL(760),TRVCON(760),TRVLOC(760)
      DIMENSION KTAB(300),ATAB(300),A2TAB(300)
      DIMENSION LTEXT(150),STEXT(150),KEY(150),COND(150),ABB(150),
     1      ATLOC(150)
      DIMENSION IPLAC(100),IPLACE(100),FIXD(100),FIXED(100),LINKX(200),
     1      PTEXT(100),PROP(100)
      DIMENSION ACTSPK(35)
      DIMENSION RTEXT(215)
      DIMENSION CTEXT(12),CVAL(12)
      DIMENSION HINTLC(20),HINTED(20),HINTS(20,4)
C     DIMENSION MTEXT(35)
      DIMENSION TK(20),DSEEN(6),DLOC(6),ODLOC(6)
C
C  STATEMENT FUNCTIONS
C
C
C  TOTNG(OBJ)    = TRUE IF THE OBJ IS BEING CARRIED
C  HERE(OBJ)      = TRUE IF THE OBJ IS AT "LOC" (OR IS BEING CARRIED)
C  AT(OBJ)  = TRUE IF ON EITHER SIDE OF TWO-IPLACED OBJECT
C  LIQ(DUMMY)     = OBJECT NUMBER OF LIQUID IN BOTTLE
C  LIQLC(LOC)    = OBJECT NUMBER OF LIQUID (IF ANY) AT LOC
C  BITST(L,N)    = TRUE IF COND(L) HAS BIT N SET (BIT 0 IS UNITS BIT)
C  FORCED(LOC)    = TRUE IF LOC MOVES WITHOUT ASKING FOR INPUT (COND=2)
C  DARK(DUMMY)    = TRUE IF LOCATION "LOC" IS DARK
C  PCT(N)       = TRUE N% OF THE TIME (N INTEGER FROM 0 TO 100)
C
C  WZDARK SAYS WHETHER THE LOC HE'S LEAVING WAS DARK
C  LMWARN SAYS WHETHER HE'S BEEN WARNED ABOUT LAMP GOING DIM
C  CLOSNG SAYS WHETHER ITS CLOSING TIME YET
C  PANIC SAYS WHETHER HE'S FOUND OUT HE'S TRAPPED IN THE CAVE
C  CLOSED SAYS WHETHER WE'RE ALL THE WAY CLOSED
C  GAVEUP SAYS WHETHER HE EXITED VIA "QUIT"
C  SCORNG INDICATES TO THE SCORE ROUTINE WHETHER WE'RE DOING A "SCORE" COMMAND
C  DEMO IS TRUE IF THIS IS A PRIME-TIME DEMONSTRATION GAME
C  YEA IS RANDOM YES/NO REPLY
C
C
      TOTNG(KLOD)=IPLACE(KLOD).EQ.-1
      HERE(KLOD)=IPLACE(KLOD).EQ.LOC.OR.TOTNG(KLOD)
      AT(KLOD)=IPLACE(KLOD).EQ.LOC.OR.FIXED(KLOD).EQ.LOC
      LIQ2(PBOTL)=(1-PBOTL)*WATER+(PBOTL/2)*(WATER+OIL)
      LIQ(DUMMY)=LIQ2(MAX(PROP(BOTTLE),-1-PROP(BOTTLE)))
      LIQLC(KLOD)=LIQ2((MOD(COND(KLOD)/2*2,8)-5)*MOD(COND(KLOD)/4,2)+1)
      BITST(LBIT,NBIT)=IAND(COND(LBIT),ISHFT(1_2,NBIT)).NE.0
      FORCED(KLOD)=COND(KLOD).EQ.2
      DARK(DUMMY)=(MOD(COND(LOC),2).EQ.0).AND.(PROP(LAMP).EQ.0.OR.
     1      .NOT.HERE(LAMP))
      PCT(NPCT)=RNDM(100).LT.NPCT
C  DESCRIPTION OF THE DATABASE FORMAT
C
C
C  THE DATA FILE CONTAINS SEVERAL SECTIONS.  EACH BEGINS WITH A LINE CONTAINING
C  A NUMBER IDENTIFYING THE SECTION, AND ENDS WITH A LINE CONTAINING "-1".
C
C  SECTION 1: LONG FORM DESCRIPTIONS.  EACH LINE CONTAINS A LOCATION NUMBER,
C     A COMMA, AND A LINE OF TEXT.  THE SET OF (NECESSARILY ADJACENT) LINES
C     WHOSE NUMBERS ARE X FORM THE LONG DESCRIPTION OF LOCATION X.
C  SECTION 2: SHORT FORM DESCRIPTIONS.  SAME FORMAT AS LONG FORM.  NOT ALL
C     IPLACES HAVE SHORT DESCRIPTIONS.
C  SECTION 3: TRAVEL TABLE.  EACH LINE CONTAINS A LOCATION NUMBER (X), A SECOND
C     LOCATION NUMBER (Y), AND A LIST OF MOTION NUMBERS (SEE SECTION 4).
C     EACH MOTION REPRESENTS A VERB WHICH WILL GO TO Y IF CURRENTLY AT X.
C     Y, IN TURN, IS INTERPRETED AS FOLLOWS.  LET M=Y/1000, N=Y MOD 1000.
C           IF N<=300   IT IS THE LOCATION TO GO TO.
C           IF 300<N<=500     N-300 IS USED IN A COMPUTED GOTO TO
C                             A SECTION OF SPECIAL CODE.
C           IF N>500    MESSAGE N-500 FROM SECTION 6 IS PRINTED,
C                             AND HE STAYS WHEREVER HE IS.
C     MEANWHILE, M SPECIFIES THE CONDITIONS ON THE MOTION.
C           IF M=0            IT'S UNCONDITIONAL.
C           IF 0<M<100  IT IS DONE WITH M% PROBABILITY.
C           IF M=100    UNCONDITIONAL, BUT FORBIDDEN TO DWARVES.
C           IF 100<M<=200     HE MUST BE CARRYING OBJECT M-100.
C           IF 200<M<=300     MUST BE CARRYING OR IN SAME ROOM AS M-200.
C           IF 300<M<=400     PROP(M MOD 100) MUST *NOT* BE 0.
C           IF 400<M<=500     PROP(M MOD 100) MUST *NOT* BE 1.
C           IF 500<M<=600     PROP(M MOD 100) MUST *NOT* BE 2, ETC.
C     IF THE CONDITION (IF ANY) IS NOT MET, THEN THE NEXT *DIFFERENT*
C     "DESTINATION" VALUE IS USED (UNLESS IT FAILS TO MEET *ITS* CONDITIONS,
C     IN WHICH CASE THE NEXT IS FOUND, ETC.).  TYPICALLY, THE NEXT DEST WILL
C     BE FOR ONE OF THE SAME VERBS, SO THAT ITS ONLY USE IS AS THE ALTERNATE
C     DESTINATION FOR THOSE VERBS.  FOR INSTANCE:
C           15    110022      29    31    34    35    23    43
C           15    14    29
C     THIS SAYS THAT, FROM LOC 15, ANY OF THE VERBS 29, 31, ETC., WILL TAKE
C     HIM TO 22 IF HE'S CARRYING OBJECT 10, AND OTHERWISE WILL GO TO 14.
C           11    303008      49
C           11    9     50
C     THIS SAYS THAT, FROM 11, 49 TAKES HIM TO 8 UNLESS PROP(3)=0, IN WHICH
C     CASE HE GOES TO 9.  VERB 50 TAKES HIM TO 9 REGARDLESS OF PROP(3).
C  SECTION 4: VOCABULARY.  EACH LINE CONTAINS A NUMBER (N), A TAB, AND A
C     FIVE-LETTER WORD.  CALL M=N/1000.  IF M=0, THEN THE WORD IS A MOTION
C     VERB FOR USE IN TRAVELLING (SEE SECTION 3).  ELSE, IF M=1, THE WORD IS
C     AN OBJECT.  ELSE, IF M=2, THE WORD IS AN ACTION VERB (SUCH AS "CARRY"
C     OR "ATTACK").  ELSE, IF M=3, THE WORD IS A SPECIAL CASE VERB (SUCH AS
C     "DIG") AND N MOD 1000 IS AN INDEX INTO SECTION 6.  OBJECTS FROM 50 TO
C     (CURRENTLY, ANYWAY) 79 ARE CONSIDERED TREASURES (FOR PIRATE, CLOSEOUT).
C  SECTION 5: OBJECT DESCRIPTIONS.  EACH LINE CONTAINS A NUMBER (N), A TAB,
C     AND A MESSAGE.  IF N IS FROM 1 TO 100, THE MESSAGE IS THE "INVENTORY"
C     MESSAGE FOR OBJECT N.  OTHERWISE, N SHOULD BE 000, 100, 200, ETC., AND
C     THE MESSAGE SHOULD BE THE DESCRIPTION OF THE PRECEDING OBJECT WHEN ITS
C     PROP VALUE IS N/100.  THE N/100 IS USED ONLY TO DISTINGUISH MULTIPLE
C     MESSAGES FROM MULTI-LINE MESSAGES; THE PROP INFO ACTUALLY REQUIRES ALL
C     MESSAGES FOR AN OBJECT TO BE PRESENT AND CONSECUTIVE.  PROPERTIES WHICH
C     PRODUCE NO MESSAGE SHOULD BE GIVEN THE MESSAGE ">$<".
C  SECTION 6: ARBITRARY MESSAGES.  SAME FORMAT AS SECTIONS 1, 2, AND 5, EXCEPT
C     THE NUMBERS BEAR NO RELATION TO ANYTHING (EXCEPT FOR SPECIAL VERBS
C     IN SECTION 4).
C  SECTION 7: OBJECT LOCATIONS.  EACH LINE CONTAINS AN OBJECT NUMBER AND ITS
C     INITIAL LOCATION (ZERO (OR OMITTED) IF NONE).  IF THE OBJECT IS
C     IMMOVABLE, THE LOCATION IS FOLLOWED BY A "-1".  IF IT HAS TWO LOCATIONS
C     (E.G. THE GRATE) THE FIRST LOCATION IS FOLLOWED WITH THE SECOND, AND
C     THE OBJECT IS ASSUMED TO BE IMMOVABLE.
C  SECTION 8: ACTION DEFAULTS.  EACH LINE CONTAINS AN "ACTION-VERB" NUMBER AND
C     THE INDEX (IN SECTION 6) OF THE DEFAULT MESSAGE FOR THE VERB.
C  SECTION 9: LIQUID ASSETS, ETC.  EACH LINE CONTAINS A NUMBER (N) AND UP TO 20
C     LOCATION NUMBERS.  BIT N (WHERE 0 IS THE UNITS BIT) IS SET IN COND(LOC)
C     FOR EACH LOC GIVEN.  THE COND BITS CURRENTLY ASSIGNED ARE:
C           0     LIGHT
C           1     IF BIT 2 IS ON: ON FOR OIL, OFF FOR WATER
C           2     LIQUID ASSET, SEE BIT 1
C           3     PIRATE DOESN'T GO HERE UNLESS FOLLOWING PLAYER
C     OTHER BITS ARE USED TO INDICATE AREAS OF INTEREST TO "HINT" ROUTINES:
C           4     TRYING TO GET INTO CAVE
C           5     TRYING TO CATCH BIRD
C           6     TRYING TO DEAL WITH SNAKE
C           7     LOST IN MAZE
C           8     PONDERING DARK ROOM
C           9     AT WITT'S END
C     COND(LOC) IS SET TO 2, OVERRIDING ALL OTHER BITS, IF LOC HAS FORCED
C     MOTION.
C  SECTION 10: CLASS MESSAGES.  EACH LINE CONTAINS A NUMBER (N), A TAB, AND A
C     MESSAGE DESCRIBING A CLASSIFICATION OF PLAYER.  THE SCORING SECTION
C     SELECTS THE APPROPRIATE MESSAGE, WHERE EACH MESSAGE IS CONSIDERED TO
C     APPLY TO PLAYERS WHOSE SCORES ARE HIGHER THAN THE PREVIOUS N BUT NOT
C     HIGHER THAN THIS N.  NOTE THAT THESE SCORES PROBABLY CHANGE WITH EVERY
C     MODIFICATION (AND PARTICULARLY EXPANSION) OF THE PROGRAM.
C  SECTION 11: HINTS.  EACH LINE CONTAINS A HINT NUMBER (CORRESPONDING TO A
C     COND BIT, SEE SECTION 9), THE NUMBER OF TURNS HE MUST BE AT THE RIGHT
C     LOC(S) BEFORE TRIGGERING THE HINT, THE POINTS DEDUCTED FOR TAKING THE
C     HINT, THE MESSAGE NUMBER (SECTION 6) OF THE QUESTION, AND THE MESSAGE
C     NUMBER OF THE HINT.  THESE VALUES ARE STASHED IN THE "HINTS" ARRAY.
C     HNTMAX IS SET TO THE MAX HINT NUMBER (<= HNTSIZ).  NUMBERS 1-3 ARE
C     UNUSABLE SINCE COND BITS ARE OTHERWISE ASSIGNED, SO 2 IS USED TO
C     REMEMBER IF HE'S READ THE CLUE IN THE REPOSITORY, AND 3 IS USED TO
C     REMEMBER WHETHER HE ASKED FOR INSTRUCTIONS (GETS MORE TURNS, BUT LOSES
C     POINTS).
C  SECTION 12: MAGIC MESSAGES. IDENTICAL TO SECTION 6 EXCEPT PUT IN A SEPARATE
C     SECTION FOR EASIER REFERENCE.  MAGIC MESSAGES ARE USED BY THE STARTUP,
C     MAINTENANCE MODE, AND RELATED ROUTINES.
C  SECTION 0: END OF DATABASE.
C  START-UP, DWARF STUFF
C
C     ICNTRL GIVES THE LOCATION TO JUMP TO FROM THE FIRST HALF OF WHAT
C     USED TO BE A PERFECTLY GOOD SINGLE SUBROUTINE, NOW ANOTHER SEGMENT
C     OF THIS PROGRAM.  STATEMENTS REFERENCED IN THAT HALF ARE DUPLICATED
C     AT THE END OF THIS PROGRAM WITH ANOTHER SET OF ICNTRL VALUES.
C
C     LOCAT1=LCO(LOC)
C     LOCAT2=LCO(MISX)
C     WRITE(LU,6900) ICNTRL,LOC,LOCAT1,LOCAT2,MISX(5)
6900  FORMAT(" ENTERED ADV3 WITH ICNTRL = ",2I5,2O7,I5)
      GO TO  (12600, 8010, 8000, 8040, 9070, 9080, 9120, 9130,
     A         8140, 9150, 8180, 8200, 9220, 9230, 8240, 8250,
     B         8260, 8270, 8300, 8310, 9010, 9020, 9030, 9040,
     C         9090, 9140, 9160, 9170, 9190, 9210, 9270, 9280,
     D         9290, 20000)  ICNTRL
C
8000  WRITE(LU, 8002)
8002  FORMAT(" I DON'T UNDERSTAND ",$)
      CALL A5TO1(LU,WD1,WD1A,WD1X,2H".)
      OBJ=0
      GOTO 2600
C
C  CARRY, NO OBJECT GIVEN YET.  OK IF ONLY ONE OBJECT PRESENT.
C
8010  IF(ATLOC(LOC).EQ.0.OR.LINKX(ATLOC(LOC)).NE.0)GOTO 8000
      DO 8012 I=1,5
      IF(DLOC(I).EQ.LOC.AND.DFLAG.GE.2)GOTO 8000
8012  CONTINUE
      OBJ=ATLOC(LOC)
C
C  CARRY AN OBJECT.  SPECIAL CASES FOR BIRD AND CAGE (IF BIRD IN CAGE, CAN'T
C  TAKE ONE WITHOUT THE OTHER.  LIQUIDS ALSO SPECIAL, SINCE THEY DEPEND ON
C  STATUS OF BOTTLE.  ALSO VARIOUS SIDE EFFECTS, ETC.
C
9010  IF(TOTNG(OBJ))GOTO 2011
      SPK=25
      IF(OBJ.EQ.PLANT.AND.PROP(PLANT).LE.0)SPK=115
      IF(OBJ.EQ.BEAR.AND.PROP(BEAR).EQ.1)SPK=169
      IF(OBJ.EQ.CHAIN.AND.PROP(BEAR).NE.0)SPK=170
      IF(FIXED(OBJ).NE.0)GOTO 2011
      IF(OBJ.NE.WATER.AND.OBJ.NE.OIL)GOTO 9017
      IF(HERE(BOTTLE).AND.LIQ(0).EQ.OBJ)GOTO 9018
      OBJ=BOTTLE
      IF(TOTNG(BOTTLE).AND.PROP(BOTTLE).EQ.1)GOTO 9220
      IF(PROP(BOTTLE).NE.1)SPK=105
      IF(.NOT.TOTNG(BOTTLE))SPK=104
      GOTO 2011
9018  OBJ=BOTTLE
9017  IF(HOLDNG.LT.7)GOTO 9016
      CALL RSPEK(92)
      GOTO 2012
9016  IF(OBJ.NE.BIRD)GOTO 9014
      IF(PROP(BIRD).NE.0)GOTO 9014
      IF(.NOT.TOTNG(ROD))GOTO 9013
      CALL RSPEK(26)
      GOTO 2012
9013  IF(TOTNG(CAGE))GOTO 9015
      CALL RSPEK(27)
      GOTO 2012
9014  IF(OBJ.NE.66 .OR. IPLACE(42).EQ.144) GO TO 9019
      SPK=208
      GO TO 2011
C
9015  PROP(BIRD)=1
9019  IF((OBJ.EQ.BIRD.OR.OBJ.EQ.CAGE).AND.PROP(BIRD).NE.0)
     1      CALL CARRY(BIRD+CAGE-OBJ,LOC)
      CALL CARRY(OBJ,LOC)
      K=LIQ(0)
      IF(OBJ.EQ.BOTTLE.AND.K.NE.0)IPLACE(K)=-1
      GOTO 2009
C
C  DISCARD OBJECT.  "THROW" ALSO COMES HERE FOR MOST OBJECTS.  SPECIAL CASES FOR
C  BIRD (MIGHT ATTACK SNAKE OR DRAGON) AND CAGE (MIGHT CONTAIN BIRD) AND VASE.
C  DROP COINS AT VENDING MACHINE FOR EXTRA BATTERIES.
C
9020  IF(TOTNG(ROD2).AND.OBJ.EQ.ROD.AND..NOT.TOTNG(ROD))OBJ=ROD2
C     WRITE(LU,6906) MISX,(IPLACE(KLOD),KLOD=1,20)
C6906 FORMAT("9020 ",10I7)
      ZZ1=0
      IF(HERE(OBJ)) ZZ1=1
      ZZ2=0
      IF(HERE(SNAKE)) ZZ2=1
      ZZ3=0
      IF(HERE(BIRD)) ZZ3=1
      ZZ4=0
      IF(TOTNG(OBJ)) ZZ4=1
C     WRITE(LU,6969) ZZ1,ZZ2,ZZ3,ZZ4,OBJ,BIRD,SNAKE,LOC,IPLACE(SNAKE)
C6969 FORMAT("HERE(OBJ)",I2,"   HERE(SNAKE)",I2,"   HERE(BIRD)",I2,
C    A  "   TOTNG(OBJ)",I2,/,"OBJ,BIRD,SNAKE,LOC,IPLACE(SNAKE)",5I6)
      IF(.NOT.TOTNG(OBJ))GOTO 2011
      IF(OBJ.NE.BIRD.OR..NOT.HERE(SNAKE))GOTO 9024
      CALL RSPEK(30)
      IF(CLOSED)GOTO 19000
      CALL DSTRY(SNAKE)
C  SET PROP FOR USE BY TRAVEL OPTIONS
      PROP(SNAKE)=1
9021  K=LIQ(0)
      IF(K.EQ.OBJ)OBJ=BOTTLE
      IF(OBJ.EQ.BOTTLE.AND.K.NE.0)IPLACE(K)=0
      IF(OBJ.EQ.CAGE.AND.PROP(BIRD).NE.0)CALL DROP(BIRD,LOC)
      IF(OBJ.EQ.BIRD)PROP(BIRD)=0
      CALL DROP(OBJ,LOC)
      GOTO 2012
C
9024  IF(OBJ.NE.COINS.OR..NOT.HERE(VEND))GOTO 9025
      CALL DSTRY(COINS)
      CALL DROP(BATTER,LOC)
      CALL PSPEK(BATTER,0)
      GOTO 2012
C
9025  IF(OBJ.NE.BIRD.OR..NOT.AT(DRAGON).OR.PROP(DRAGON).NE.0)GOTO 9026
      CALL RSPEK(154)
      CALL DSTRY(BIRD)
      PROP(BIRD)=0
      IF(IPLACE(SNAKE).EQ.IPLAC(SNAKE))TALLY2=TALLY2+1
      GOTO 2012
C
9026  IF(OBJ.NE.BEAR.OR..NOT.AT(TROLL))GOTO 9027
      CALL RSPEK(163)
      CALL MOVE(TROLL,0)
      CALL MOVE(TROLL+100,0)
      CALL MOVE(TROLL2,IPLAC(TROLL))
      CALL MOVE(TROLL2+100,FIXD(TROLL))
      CALL JUGGL(CHASM)
      PROP(TROLL)=2
      GOTO 9021
C
9028  IF(OBJ.EQ.VASE.AND.LOC.NE.IPLAC(PILLOW))GOTO 9029
      CALL RSPEK(54)
      GOTO 9021
C
9027  IF(OBJ.NE.42 .OR. LOC.NE.144) GO TO 9028
      CALL RSPEK(209)
      CALL DROP(OBJ,LOC)
      GO TO 2012
C
9029  PROP(VASE)=2
      IF(AT(PILLOW))PROP(VASE)=0
      CALL PSPEK(VASE,PROP(VASE)+1)
      IF(PROP(VASE).NE.0)FIXED(VASE)=-1
      GOTO 9021
C
C  SAY.  ECHO WD2 (OR WD1 IF NO WD2 (SAY WHAT?, ETC.).)  MAGIC WORDS OVERRIDE.
C
9030  IF(WD2.EQ.0)GOTO 9031
      WD1=WD2
      WD1A=WD2A
      WD1X=WD2X
9031  CALL VOCAB(WD1,WD1A,-1,I)
      IF(I.EQ.62.OR.I.EQ.65.OR.I.EQ.71.OR.I.EQ.2025)GOTO 9035
      WRITE(LU, 9032)
9032  FORMAT(" OKAY, '",$)
      CALL A5TO1(LU,WD1,WD1A,WD1X,2H".)
      GOTO 2012
C
9035  WD2=0
      OBJ=0
      GOTO 2630
C
C  LOCK, UNLOCK, NO OBJECT GIVEN.  ASSUME VARIOUS THINGS IF PRESENT.
C
8040  SPK=28
      IF(HERE(CLAM))OBJ=CLAM
      IF(HERE(OYSTER))OBJ=OYSTER
      IF(AT(DOOR))OBJ=DOOR
      IF(AT(GRATE))OBJ=GRATE
      IF(OBJ.NE.0.AND.HERE(CHAIN))GOTO 8000
      IF(HERE(CHAIN))OBJ=CHAIN
      IF(OBJ.EQ.0)GOTO 2011
C
C  LOCK, UNLOCK OBJECT.  SPECIAL STUFF FOR OPENING CLAM/OYSTER AND FOR CHAIN.
C
9040  IF(OBJ.EQ.CLAM.OR.OBJ.EQ.OYSTER)GOTO 9046
      IF(OBJ.EQ.DOOR)SPK=111
      IF(OBJ.EQ.DOOR.AND.PROP(DOOR).EQ.1)SPK=54
      IF(OBJ.EQ.CAGE)SPK=32
      IF(OBJ.EQ.KEYS)SPK=55
      IF(OBJ.EQ.GRATE.OR.OBJ.EQ.CHAIN)SPK=31
      IF(SPK.NE.31.OR..NOT.HERE(KEYS))GOTO 2011
      IF(OBJ.EQ.CHAIN)GOTO 9048
      IF(.NOT.CLOSNG)GOTO 9043
      K=130
      IF(.NOT.PANIC)CLOCK2=15
      PANIC=.TRUE.
      GOTO 2010
C
9043  K=34+PROP(GRATE)
      PROP(GRATE)=1
      IF(VERB.EQ.LOCK)PROP(GRATE)=0
      K=K+2*PROP(GRATE)
      GOTO 2010
C
C  CLAM/OYSTER.
9046  K=0
      IF(OBJ.EQ.OYSTER)K=1
      SPK=124+K
      IF(TOTNG(OBJ))SPK=120+K
      IF(.NOT.TOTNG(TRIDNT))SPK=122+K
      IF(VERB.EQ.LOCK)SPK=61
      IF(SPK.NE.124)GOTO 2011
      CALL DSTRY(CLAM)
      CALL DROP(OYSTER,LOC)
      CALL DROP(PEARL,105)
      GOTO 2011
C
C  CHAIN.
9048  IF(VERB.EQ.LOCK)GOTO 9049
      SPK=171
      IF(PROP(BEAR).EQ.0)SPK=41
      IF(PROP(CHAIN).EQ.0)SPK=37
      IF(SPK.NE.171)GOTO 2011
      PROP(CHAIN)=0
      FIXED(CHAIN)=0
      IF(PROP(BEAR).NE.3)PROP(BEAR)=2
      FIXED(BEAR)=2-PROP(BEAR)
      GOTO 2011
C
9049  SPK=172
      IF(PROP(CHAIN).NE.0)SPK=34
      IF(LOC.NE.IPLAC(CHAIN))SPK=173
      IF(SPK.NE.172)GOTO 2011
      PROP(CHAIN)=2
      IF(TOTNG(CHAIN))CALL DROP(CHAIN,LOC)
      FIXED(CHAIN)=-1
      GOTO 2011
C
C  LIGHT LAMP
C
9070  IF(.NOT.HERE(LAMP))GOTO 2011
      SPK=184
      IF(LIMIT.LT.0)GOTO 2011
      PROP(LAMP)=1
      CALL RSPEK(39)
      IF(WZDARK)GOTO 2000
      GOTO 2012
C
C  LAMP OFF
C
9080  IF(.NOT.HERE(LAMP))GOTO 2011
      PROP(LAMP)=0
      CALL RSPEK(40)
      IF(DARK(0))CALL RSPEK(16)
      GOTO 2012
C
C  WAVE.  NO EFFECT UNLESS WAVING ROD AT FISSURE.
C
9090  IF((.NOT.TOTNG(OBJ)).AND.(OBJ.NE.ROD.OR..NOT.TOTNG(ROD2)))
     1      SPK=29
      IF(OBJ.NE.ROD.OR..NOT.AT(FISSUR).OR..NOT.TOTNG(OBJ)
     1      .OR.CLOSNG)GOTO 2011
      PROP(FISSUR)=1-PROP(FISSUR)
      CALL PSPEK(FISSUR,2-PROP(FISSUR))
      GOTO 2012
C
C  ATTACK.  ASSUME TARGET IF UNAMBIGUOUS.  "THROW" ALSO LINKXS HERE.  ATTACKABLE
C  OBJECTS FALL INTO TWO CATEGORIES: ENEMIES (SNAKE, DWARF, ETC.)  AND OTHERS
C  (BIRD, CLAM).  AMBIGUOUS IF TWO ENEMIES, OR IF NO ENEMIES BUT TWO OTHERS.
C
9120  DO 9121 I=1,5
      IF(DLOC(I).EQ.LOC.AND.DFLAG.GE.2)GOTO 9122
9121  CONTINUE
      I=0
9122  IF(OBJ.NE.0)GOTO 9124
      IF(I.NE.0)OBJ=DWARF
      IF(HERE(SNAKE))OBJ=OBJ*100+SNAKE
      IF(AT(DRAGON).AND.PROP(DRAGON).EQ.0)OBJ=OBJ*100+DRAGON
      IF(AT(TROLL))OBJ=OBJ*100+TROLL
      IF(HERE(BEAR).AND.PROP(BEAR).EQ.0)OBJ=OBJ*100+BEAR
      IF(OBJ.GT.100)GOTO 8000
      IF(OBJ.NE.0)GOTO 9124
C  CAN'T ATTACK BIRD BY THROWING AXE.
      IF(HERE(BIRD).AND.VERB.NE.THROW)OBJ=BIRD
C  CLAM AND OYSTER BOTH TREATED AS CLAM FOR INTRANSITIVE CASE; NO HARM DONE.
      IF(HERE(CLAM).OR.HERE(OYSTER))OBJ=100*OBJ+CLAM
      IF(OBJ.GT.100)GOTO 8000
9124  IF(OBJ.NE.BIRD)GOTO 9125
      SPK=137
      IF(CLOSED)GOTO 2011
      CALL DSTRY(BIRD)
      PROP(BIRD)=0
      IF(IPLACE(SNAKE).EQ.IPLAC(SNAKE))TALLY2=TALLY2+1
      SPK=45
9125  IF(OBJ.EQ.0)SPK=44
      IF(OBJ.EQ.CLAM.OR.OBJ.EQ.OYSTER)SPK=150
      IF(OBJ.EQ.SNAKE)SPK=46
      IF(OBJ.EQ.DWARF)SPK=49
      IF(OBJ.EQ.DWARF.AND.CLOSED)GOTO 19000
      IF(OBJ.EQ.DRAGON)SPK=167
      IF(OBJ.EQ.TROLL)SPK=157
      IF(OBJ.EQ.BEAR)SPK=165+(PROP(BEAR)+1)/2
      IF(OBJ.NE.DRAGON.OR.PROP(DRAGON).NE.0)GOTO 2011
C  FUN STUFF FOR DRAGON.  IF HE INSISTS ON ATTACKING IT, WIN!  SET PROP TO DEAD,
C  MOVE DRAGON TO CENTRAL LOC (STILL FIXED), MOVE RUG THERE (NOT FIXED), AND
C  MOVE HIM THERE, TOO.  THEN DO A NULL MOTION TO GET NEW DESCRIPTION.
      CALL RSPEK(49)
      VERB=0
      OBJ=0
      CALL GETIN(LU,WD1,WD1A,WD1X,WD2,WD2A,WD2X)
      IF(WD1.NE.CYE.AND.WD1.NE.CY)GOTO 2608
      CALL PSPEK(DRAGON,1)
      PROP(DRAGON)=2
      PROP(RUG)=0
      K=(IPLAC(DRAGON)+FIXD(DRAGON))/2
      CALL MOVE(DRAGON+100,-1)
      CALL MOVE(RUG+100,0)
      CALL MOVE(DRAGON,K)
      CALL MOVE(RUG,K)
      DO 9126 OBJ=1,100
      IF(IPLACE(OBJ).EQ.IPLAC(DRAGON).OR.IPLACE(OBJ).EQ.FIXD(DRAGON))
     1      CALL MOVE(OBJ,K)
9126  CONTINUE
      LOC=K
      K=NULL
      GOTO 8
C
C  POUR.  IF NO OBJECT, OR OBJECT IS BOTTLE, ASSUME CONTENTS OF BOTTLE.
C  SPECIAL TESTS FOR POURING WATER OR OIL ON PLANT OR RUSTY DOOR.
C
9130  IF(OBJ.EQ.BOTTLE.OR.OBJ.EQ.0)OBJ=LIQ(0)
      IF(OBJ.EQ.0)GOTO 8000
      IF(.NOT.TOTNG(OBJ))GOTO 2011
      SPK=78
      IF(OBJ.NE.OIL.AND.OBJ.NE.WATER)GOTO 2011
      PROP(BOTTLE)=1
      IPLACE(OBJ)=0
      SPK=77
      IF(.NOT.(AT(PLANT).OR.AT(DOOR)))GOTO 2011
C
      IF(AT(DOOR))GOTO 9132
      SPK=112
      IF(OBJ.NE.WATER)GOTO 2011
      CALL PSPEK(PLANT,PROP(PLANT)+1)
      PROP(PLANT)=MOD(PROP(PLANT)+2,6)
      PROP(PLANT2)=PROP(PLANT)/2
      K=NULL
      GOTO 8
C
9132  PROP(DOOR)=0
      IF(OBJ.EQ.OIL)PROP(DOOR)=1
      SPK=113+PROP(DOOR)
      GOTO 2011
C
C  EAT.  INTRANSITIVE: ASSUME FOOD IF PRESENT, ELSE ASK WHAT.  TRANSITIVE: FOOD
C  OK, SOME THINGS LOSE APPETITE, REST ARE RIDICULOUS.
C
8140  IF(.NOT.HERE(FOOD))GOTO 8000
8142  CALL DSTRY(FOOD)
      SPK=72
      GOTO 2011
C
9140  IF(OBJ.EQ.FOOD)GOTO 8142
      IF(OBJ.EQ.BIRD.OR.OBJ.EQ.SNAKE.OR.OBJ.EQ.CLAM.OR.OBJ.EQ.OYSTER
     1      .OR.OBJ.EQ.DWARF.OR.OBJ.EQ.DRAGON.OR.OBJ.EQ.TROLL
     2      .OR.OBJ.EQ.BEAR)SPK=71
      IF(OBJ.EQ.41 .AND. LOC.EQ.141) GO TO 9300
      GOTO 2011
C
C  DRINK.  IF NO OBJECT, ASSUME WATER AND LOOK FOR IT HERE.  IF WATER IS IN
C  THE BOTTLE, DRINK THAT, ELSE MUST BE AT A WATER LOC, SO DRINK STREAM.
C
9150  IF(OBJ.EQ.0.AND.LIQLC(LOC).NE.WATER.AND.(LIQ(0).NE.WATER
     1      .OR..NOT.HERE(BOTTLE)))GOTO 8000
      IF(OBJ.NE.0.AND.OBJ.NE.WATER)SPK=110
      IF(SPK.EQ.110.OR.LIQ(0).NE.WATER.OR..NOT.HERE(BOTTLE))GOTO 2011
      PROP(BOTTLE)=1
      IPLACE(WATER)=0
      SPK=74
      GOTO 2011
C
C  RUB.  YIELDS VARIOUS SNIDE REMARKS.
C
9160  IF(OBJ.NE.LAMP)SPK=76
      GOTO 2011
C
C  THROW.  SAME AS DISCARD UNLESS AXE.  THEN SAME AS ATTACK EXCEPT IGNORE BIRD,
C  AND IF DWARF IS PRESENT THEN ONE MIGHT BE KILLED.  (ONLY WAY TO DO SO!)
C  AXE ALSO SPECIAL FOR DRAGON, BEAR, AND TROLL.  TREASURES SPECIAL FOR TROLL.
C
9170  IF(TOTNG(ROD2).AND.OBJ.EQ.ROD.AND..NOT.TOTNG(ROD))OBJ=ROD2
      IF(.NOT.TOTNG(OBJ))GOTO 2011
      IF(OBJ.GE.50.AND.OBJ.LE.MAXTRS.AND.AT(TROLL))GOTO 9178
      IF(OBJ.EQ.FOOD.AND.HERE(BEAR))GOTO 9177
      IF(OBJ.NE.AXE)GOTO 9020
      DO 9171 I=1,5
C  NEEDN'T CHECK DFLAG IF AXE IS HERE.
      IF(DLOC(I).EQ.LOC)GOTO 9172
9171  CONTINUE
      SPK=152
      IF(AT(DRAGON).AND.PROP(DRAGON).EQ.0)GOTO 9175
      SPK=158
      IF(AT(TROLL))GOTO 9175
      IF(HERE(BEAR).AND.PROP(BEAR).EQ.0)GOTO 9176
      OBJ=0
      GOTO 9120
C
9172  SPK=48
      IF(RNDM(3).EQ.0)GOTO 9175
      DSEEN(I)=.FALSE.
      DLOC(I)=0
      SPK=47
      DKILL=DKILL+1
      IF(DKILL.EQ.1)SPK=149
9175  CALL RSPEK(SPK)
      CALL DROP(AXE,LOC)
      K=NULL
      GOTO 8
C
C  THIS'LL TEACH HIM TO THROW THE AXE AT THE BEAR!
9176  SPK=164
      CALL DROP(AXE,LOC)
      FIXED(AXE)=-1
      PROP(AXE)=1
      CALL JUGGL(BEAR)
      GOTO 2011
C
C  BUT THROWING FOOD IS ANOTHER STORY.
9177  OBJ=BEAR
      GOTO 9210
C
9178  SPK=159
C  SNARF A TREASURE FOR THE TROLL.
      CALL DROP(OBJ,0)
      CALL MOVE(TROLL,0)
      CALL MOVE(TROLL+100,0)
      CALL DROP(TROLL2,IPLAC(TROLL))
      CALL DROP(TROLL2+100,FIXD(TROLL))
      CALL JUGGL(CHASM)
      GOTO 2011
C
C  QUIT.  INTRANSITIVE ONLY.  VERIFY INTENT AND EXIT IF THAT'S WHAT HE WANTS.
C
8180  GAVEUP=YES(22,54,54)
8185  IF(GAVEUP)GOTO 20000
      GOTO 2012
C
C  FIND.  MIGHT BE CARRYING IT, OR IT MIGHT BE HERE.  ELSE GIVE CAVEAT.
C
9190  IF(AT(OBJ).OR.(LIQ(0).EQ.OBJ.AND.AT(BOTTLE))
     1      .OR.K.EQ.LIQLC(LOC))SPK=94
      DO 9192 I=1,5
9192  IF(DLOC(I).EQ.LOC.AND.DFLAG.GE.2.AND.OBJ.EQ.DWARF)SPK=94
      IF(CLOSED)SPK=138
      IF(TOTNG(OBJ))SPK=24
      GOTO 2011
C
C  INVENTORY.  IF OBJECT, TREAT SAME AS FIND.  ELSE REPORT ON CURRENT BURDEN.
C
8200  SPK=98
      DO 8201 I=1,100
      IF(I.EQ.BEAR.OR..NOT.TOTNG(I))GOTO 8201
      IF(SPK.EQ.98)CALL RSPEK(99)
      BLKLIN=.FALSE.
      CALL PSPEK(I,-1)
      BLKLIN=.TRUE.
      SPK=0
8201  CONTINUE
      IF(TOTNG(BEAR))SPK=141
      GOTO 2011
C
C  FEED.  IF BIRD, NO SEED.  SNAKE, DRAGON, TROLL: QUIP.  IF DWARF, MAKE HIM
C  MAD.  BEAR, SPECIAL.
C
9210  IF(OBJ.NE.BIRD)GOTO 9212
      SPK=100
      GOTO 2011
C
9212  IF(OBJ.NE.SNAKE.AND.OBJ.NE.DRAGON.AND.OBJ.NE.TROLL)GOTO 9213
      SPK=102
      IF(OBJ.EQ.DRAGON.AND.PROP(DRAGON).NE.0)SPK=110
      IF(OBJ.EQ.TROLL)SPK=182
      IF(OBJ.NE.SNAKE.OR.CLOSED.OR..NOT.HERE(BIRD))GOTO 2011
      SPK=101
      CALL DSTRY(BIRD)
      PROP(BIRD)=0
      TALLY2=TALLY2+1
      GOTO 2011
C
9213  IF(OBJ.NE.DWARF)GOTO 9214
      IF(.NOT.HERE(FOOD))GOTO 2011
      SPK=103
      DFLAG=DFLAG+1
      GOTO 2011
C
9214  IF(OBJ.NE.BEAR)GOTO 9215
      IF(PROP(BEAR).EQ.0)SPK=102
      IF(PROP(BEAR).EQ.3)SPK=110
      IF(.NOT.HERE(FOOD))GOTO 2011
      CALL DSTRY(FOOD)
      PROP(BEAR)=1
      FIXED(AXE)=0
      PROP(AXE)=0
      SPK=168
      GOTO 2011
C
9215  SPK=14
      GOTO 2011
C
C  FILL.  BOTTLE MUST BE EMPTY, AND SOME LIQUID AVAILABLE.  (VASE IS NASTY.)
C
9220  KLZ1=LIQ(0)
      KLZ2=LIQLC(LOC)
      IF(OBJ.EQ.VASE)GOTO 9222
      IF(OBJ.NE.0.AND.OBJ.NE.BOTTLE)GOTO 2011
      IF(OBJ.EQ.0.AND..NOT.HERE(BOTTLE))GOTO 8000
      SPK=107
      IF(LIQLC(LOC).EQ.0)SPK=106
      IF(LIQ(0).NE.0)SPK=105
      IF(SPK.NE.107)GOTO 2011
      PROP(BOTTLE)=MOD(COND(LOC),4)/2*2
      K=LIQ(0)
      IF(TOTNG(BOTTLE))IPLACE(K)=-1
      IF(K.EQ.OIL)SPK=108
      GOTO 2011
C
9222  SPK=29
      IF(LIQLC(LOC).EQ.0)SPK=144
      IF(LIQLC(LOC).EQ.0.OR..NOT.TOTNG(VASE))GOTO 2011
      CALL RSPEK(145)
      PROP(VASE)=2
      FIXED(VASE)=-1
      GOTO 9024
C
C  BLAST.  NO EFFECT UNLESS YOU'VE GOT DYNAMITE, WHICH IS A NEAT TRICK!
C
9230  IF(PROP(ROD2).LT.0.OR..NOT.CLOSED)GOTO 2011
      BONUS=133
      IF(LOC.EQ.115)BONUS=134
      IF(HERE(ROD2))BONUS=135
      CALL RSPEK(BONUS)
      GOTO 20000
C
C  SCORE.  GO TO SCORING SECTION, WHICH WILL RETURN TO 8241 IF SCORNG IS TRUE.
C
8240  SCORNG=.TRUE.
      GOTO 20000
C
8241  SCORNG=.FALSE.
      WRITE(LU, 8243) SCORE,MXSCOR
8243  FORMAT(" IF YOU WERE TO QUIT NOW, YOU WOULD SCORE",I4
     1      ," OUT OF A POSSIBLE",I4,".")
      GAVEUP=YES(143,54,54)
      GOTO 8185
C
C  FEE FIE FOE FOO (AND FUM).  ADVANCE TO NEXT STATE IF GIVEN IN PROPER ORDER.
C  LOOK UP WD1 IN SECTION 3 OF VOCAB TO DETERMINE WHICH WORD WE'VE GOT.  LAST
C  WORD ZIPS THE EGGS BACK TO THE GIANT ROOM (UNLESS ALREADY THERE).
C
8250  CALL VOCAB(WD1,WD1A,3,K)
      SPK=42
      IF(FOOBAR.EQ.1-K)GOTO 8252
      IF(FOOBAR.NE.0)SPK=151
      GOTO 2011
C
8252  FOOBAR=K
      IF(K.NE.4)GOTO 2009
      FOOBAR=0
      IF(IPLACE(EGGS).EQ.IPLAC(EGGS)
     1      .OR.(TOTNG(EGGS).AND.LOC.EQ.IPLAC(EGGS)))GOTO 2011
C  BRING BACK TROLL IF WE STEAL THE EGGS BACK FROM HIM BEFORE CROSSING.
      IF(IPLACE(EGGS).EQ.0.AND.IPLACE(TROLL).EQ.0.AND.PROP(TROLL).EQ.0)
     1      PROP(TROLL)=1
      K=2
      IF(HERE(EGGS))K=1
      IF(LOC.EQ.IPLAC(EGGS))K=0
      CALL MOVE(EGGS,IPLAC(EGGS))
      CALL PSPEK(EGGS,K)
      GOTO 2012
C
C  BRIEF.  INTRANSITIVE ONLY.  SUPPRESS LONG DESCRIPTIONS AFTER FIRST TIME.
C
8260  SPK=156
      ABBNUM=10000
      DETAIL=3
      GOTO 2011
C
C  READ.  MAGAZINES IN DWARVISH, MESSAGE WE'VE SEEN, AND . . . OYSTER?
C
8270  IF(HERE(MAGZIN))OBJ=MAGZIN
      IF(HERE(TABLET))OBJ=OBJ*100+TABLET
      IF(HERE(MESSAG))OBJ=OBJ*100+MESSAG
      IF(CLOSED.AND.TOTNG(OYSTER))OBJ=OYSTER
      IF(OBJ.GT.100.OR.OBJ.EQ.0.OR.DARK(0))GOTO 8000
C
9270  IF(DARK(0))GOTO 5190
      IF(OBJ.EQ.MAGZIN)SPK=190
      IF(OBJ.EQ.TABLET)SPK=196
      IF(OBJ.EQ.MESSAG)SPK=191
      IF(OBJ.EQ.OYSTER.AND.HINTED(2).AND.TOTNG(OYSTER))SPK=194
      IF(OBJ.NE.OYSTER.OR.HINTED(2).OR..NOT.TOTNG(OYSTER)
     1      .OR..NOT.CLOSED)GOTO 2011
      HINTED(2)=YES(192,193,54)
      GOTO 2012
C
C  BREAK.  ONLY WORKS FOR MIRROR IN REPOSITORY AND, OF COURSE, THE VASE.
C
9280  IF(OBJ.EQ.MIRROR)SPK=148
      IF(OBJ.EQ.VASE.AND.PROP(VASE).EQ.0)GOTO 9282
      IF(OBJ.NE.MIRROR.OR..NOT.CLOSED)GOTO 2011
      CALL RSPEK(197)
      GOTO 19000
C
9282  SPK=198
      IF(TOTNG(VASE))CALL DROP(VASE,LOC)
      PROP(VASE)=2
      FIXED(VASE)=-1
      GOTO 2011
C
C  WAKE.  ONLY USE IS TO DISTURB THE DWARVES.
C
9290  IF(OBJ.NE.DWARF.OR..NOT.CLOSED)GOTO 2011
      CALL RSPEK(199)
      GOTO 19000
C
C SUSPEND.  CANT IN THIS VERSION.
C        IMPROVEMENT! SUSPEND IS NOW POSSIBLE.
C     !DWH - REMOVED THIS, ISN'T WORKING PROPERLY WITH RTE-6/VM
C
8300  CONTINUE
      CALL RSPEK(206)
C     CALL EXEC(6,0,1)
C     CALL RMPAR(WD1)
C     IF(WD1.NE.0) LU=WD1
C     CALL RSPEK(207)
      GO TO 2000
C
C HOURS.  NONE IN THIS VERSION
C
8310  CALL RSPEK(202)
      GO TO 2012
C  HINTS
C
C  COME HERE IF HE'S BEEN LONG ENOUGH AT REQUIRED LOC(S) FOR SOME UNUSED HINT.
C  HINT NUMBER IS IN VARIABLE "HINT".  BRANCH TO QUICK TEST FOR ADDITIONAL
C  CONDITIONS, THEN COME BACK TO DO NEAT STUFF.  GOTO 40010 IF CONDITIONS ARE
C  MET AND WE WANT TO OFFER THE HINT.  GOTO 40020 TO CLEAR HINTLC BACK TO ZERO,
C  40030 TO TAKE NO ACTION YET.
C
12600 CALL RSPEK(185)
      GAVEUP=.TRUE.
      GOTO 20000
C
C
C  OH DEAR, HE'S DISTURBED THE DWARVES.
C
19000 CALL RSPEK(136)
C
C  EXIT CODE.  WILL EVENTUALLY INCLUDE SCORING.  FOR NOW, HOWEVER, ...
C
C  THE PRESENT SCORING ALGORITHM IS AS FOLLOWS:
C     OBJECTIVE:          POINTS:        PRESENT TOTAL POSSIBLE:
C  GETTING WELL INTO CAVE   25                    25
C  EACH TREASURE < CHEST    12                    60
C  TREASURE CHEST ITSELF    14                    14
C  EACH TREASURE > CHEST    16                   144
C  SURVIVING             (MAX-NUM)*10             30
C  NOT QUITTING              4                     4
C  REACHING "CLOSNG"        25                    25
C  "CLOSED": QUIT/KILLED    10
C            KLUTZED        25
C            WRONG WAY      30
C            SUCCESS        45                    45
C  CAME TO WITT'S END        1                     1
C  ROUND OUT THE TOTAL       2                     2
C                                       TOTAL:   350
C  (POINTS CAN ALSO BE DEDUCTED FOR USING HINTS.)
C
20000 SCORE=0
      MXSCOR=0
C
C  FIRST TALLY UP THE TREASURES.  MUST BE IN BUILDING AND NOT BROKEN.
C  GIVE THE POOR GUY 2 POINTS JUST FOR FINDING EACH TREASURE.
C
      DO 20010 I=50,MAXTRS
      IF(PTEXT(I).EQ.0)GOTO 20010
      K=12
      IF(I.EQ.CHEST)K=14
      IF(I.GT.CHEST)K=16
      IF(PROP(I).GE.0)SCORE=SCORE+2
      IF(IPLACE(I).EQ.3.AND.PROP(I).EQ.0)SCORE=SCORE+K-2
      MXSCOR=MXSCOR+K
20010 CONTINUE
C
C  NOW LOOK AT HOW HE FINISHED AND HOW FAR HE GOT.  MAXDIE AND NUMDIE TELL US
C  HOW WELL HE SURVIVED.  GAVEUP SAYS WHETHER HE EXITED VIA QUIT.  DFLAG WILL
C  TELL US IF HE EVER GOT SUITABLY DEEP INTO THE CAVE.  CLOSNG STILL INDICATES
C  WHETHER HE REACHED THE ENDGAME.  AND IF HE GOT AS FAR AS "CAVE CLOSED"
C  (INDICATED BY "CLOSED"), THEN BONUS IS ZERO FOR MUNDANE EXITS OR 133, 134,
C  135 IF HE BLEW IT (SO TO SPEAK).
C
      SCORE=SCORE+(MAXDIE-NUMDIE)*10
      MXSCOR=MXSCOR+MAXDIE*10
      IF(.NOT.(SCORNG.OR.GAVEUP))SCORE=SCORE+4
      MXSCOR=MXSCOR+4
      IF(DFLAG.NE.0)SCORE=SCORE+25
      MXSCOR=MXSCOR+25
      IF(CLOSNG)SCORE=SCORE+25
      MXSCOR=MXSCOR+25
      IF(.NOT.CLOSED)GOTO 20020
      IF(BONUS.EQ.0)SCORE=SCORE+10
      IF(BONUS.EQ.135)SCORE=SCORE+25
      IF(BONUS.EQ.134)SCORE=SCORE+30
      IF(BONUS.EQ.133)SCORE=SCORE+45
20020 MXSCOR=MXSCOR+45
C
C  DID HE COME TO WITT'S END AS HE SHOULD?
C
      IF(IPLACE(MAGZIN).EQ.108)SCORE=SCORE+1
      MXSCOR=MXSCOR+1
C
C  DID HE FUCK THE PRINCESS, BUT NOT KISS HER?
C
      IF(PROP(41).EQ.2) SCORE=SCORE+3
      MXSCOR=MXSCOR+3
C
C  ROUND IT OFF.
C
      SCORE=SCORE+2
      MXSCOR=MXSCOR+2
C
C  DEDUCT POINTS FOR HINTS.  HINTS < 4 ARE SPECIAL; SEE DATABASE DESCRIPTION.
C
      DO 20030 I=1,HNTMAX
20030 IF(HINTED(I))SCORE=SCORE-HINTS(I,2)
C
C  RETURN TO SCORE COMMAND IF THAT'S WHERE WE CAME FROM
C
      IF(SCORNG) GOTO 8241
C
C  THAT SHOULD BE ENOUGH.  LET'S TELL HIM ALL ABOUT IT
C
      WRITE (LU,20100) SCORE,MXSCOR,TURNS
20100 FORMAT(/" YOU SCORED",I4," OUT OF A POSSIBLE",I4,
     1      ",USING",I5," TURNS.")
C
      DO 20200 I=1,CLSSES
      IF(CVAL(I).GE.SCORE) GOTO 20210
20200 CONTINUE
      WRITE (LU,20202)
20202 FORMAT(/" YOU JUST WENT OFF MY SCALE!!"/)
      GOTO 25000
C
20210 CALL SPEK(CTEXT(I))
      IF(I.EQ.CLSSES-1) GOTO 20220
      K=CVAL(I)+1-SCORE
      WRITE (LU,20212) K
20212 FORMAT(/" TO ACHIEVE THE NEXT HIGHER RATING, YOU NEED",I3,
     1      " MORE POINT",$)
      IF (K.EQ.1) WRITE (LU,20213)
      IF (K.NE.1) WRITE (LU,20214)
20213 FORMAT("+."/)
20214 FORMAT("S."/)
      GOTO 25000
C
20220 WRITE (LU,20222)
20222 FORMAT (/" TO ACHEIVE THE NEXT HIGHER RATING ",
     1      "WOULD BE A NEAT TRICK!"//" CONGRATULATIONS!!"/)
C
25000 ICNTRL=-99
      CALL SUSP(2,2)
      GOTO 80000
2600  ICNTRL=101
      GOTO 80000
2011  ICNTRL=102
      GOTO 80000
2012  ICNTRL=103
      GOTO 80000
2009  ICNTRL=104
      GOTO 80000
2630  ICNTRL=105
      GOTO 80000
2010  ICNTRL=106
      GOTO 80000
2000  ICNTRL=107
      GOTO 80000
2608  ICNTRL=109
      GOTO 80000
8     ICNTRL=109
      GOTO 80000
5190  ICNTRL=110
      GOTO 80000
9300  ICNTRL=111
80000 CONTINUE
      CALL SEGRT
C
C
      END
C     END$

