.TH GRAMS 6
.SH NAME
grams \- anagram game
.SH SYNOPSIS
.B grams
[\fB-r\fR]
[\fB-w\fR#]
.SH DESCRIPTION
.PP
Grams is a game based on anagrams, brute competitiveness,
and typing prowess.
.PP
The program will provide playing instructions if allowed to do so.
.PP
The \fB-r\fR argument displays the records of the best anagrammers.
.PP
The \fB-w\fR argument allows selection of word length (default is \fB-w5\fR).
.SH AUTHOR
Peter S. Langston
