/* Auto-generated embedded Lisp source for Faemar */

static const char GAME_LSP_SOURCE[] =
    "; THIS IS THE HEART OF MY DUNGEON SYSTEM.  THE BASIC IDEA IS THAT THINGS\n"
    "; CARRY ALL OF THE IMPORTANT INFORMATION AROUND WITH THEM (INCLUDING VERBS)\n"
    "; ON THEIR PROPERTY LISTS.  EVERYTHING IS ASSUMED TO HAVE CERTAIN PROPERTIES:\n"
    ";    STREN  -  A MEASURE OF THE WEIGHT THAT THEY CAN CARRY (ALSO THE AMOUNT\n"
    ";		 OF FORCE THAT THEY CAN RESIST).\n"
    ";    WEIGH  -  THE TOTAL WEIGHT OF THE OBJECT (INCLUDING CONTENTS)\n"
    ";    I-VOL  -  THE HOLDING CAPACITY (VOLUME) (IN CUBIC INCHES)\n"
    ";    O-VOL  -  THE ACTUAL OUTSIDE VOLUME (IN CUBIC INCHES)\n"
    ";    LONG   -  THE LENGTH OF THE OBJECT (IN INCHES)\n"
    ";    WIDE   -  THE WIDTH\n"
    ";    DEEP   -  THE DEPTH.  IT IS ASSUMED THAT LONG >= WIDE >= DEEP.\n"
    ";                          NOTE THAT DEEP=0 => SHARP!\n"
    ";    FLAGS  -  A 36-BIT WORD FULL OF FLAGS.  DEFINE WHATEVER YOU LIKE!\n"
    ";		 (IF YOU LEAVE IT OUT, A 0 WILL BE ASSUMED)\n"
    ";              I HAVE %OPEN% %TRANSPARENT% %LOCKED% AND MAY NEED OTHERS.\n"
    ";    NAME   -  A QUOTED LIST CONTAINING A SHORT NAME (FIRST LETTER CAPITAL)\n"
    ";    DESC   -  EVALUATES TO A LIST SUITABLE FOR TELL (THE FUNCTION)\n"
    ";		NOTE THAT COND'S AND APPEND'S ARE ESPECIALLY USEFUL.\n"
    ";\n"
    ";  EVERYTHING IS ASSUMED TO HAVE ONE OF THE TWO FOLLOWING:\n"
    ";    IN     -  THE OBJECT WHOSE CONTENTS I AM A MEMBER OF     OR\n"
    ";    PART   -  THE OBJECT WHICH I AM A PART OF\n"
    ";  GOING UP THESE **MUST** EVENTUALLY STOP AT AN OBJECT.\n"
    ";\n"
    ";  THE FOLLOWING ARE OPTIONAL, BUT SHOULD BE USED RATHER THAN SOMETHING \n"
    ";  ELSE INTENDED FOR THE SAME THING:\n"
    ";    HOLDS  -  A LIST OF THE INTERNAL NAMES OF THE CONTENTS OF THE OBJECT\n"
    ";    PARTS  -  A LIST OF THE INTERNAL NAMES OF THE COMPONENTS OF THE OBJECT\n"
    ";    VERBS  -  A LIST OF DOTTED-PAIRS\n"
    ";		CAR=THE WORD WHICH WILL MATCH (ONLY ONE)\n"
    ";		CDR=THE ACTION TO TAKE. WILL BE EVAL'D IF CAR MATCHES THE VERB.\n"
    ";		YOU MAY RECOGNISE THESE AS A-LIST LIKE CONSTRUCTS.\n"
    ";		NOTE THAT ALL OF THE GENERALITY OF LISP IS AVAILABLE HERE!!\n"
    ";\n"
    ";  ANY OTHER PROPERTIES YOU WANT ARE FINE.  YOU NEED TO MAKE YOUR VERBS\n"
    ";  AWARE OF THEM.\n"
    ";\n"
    ";  THE REMAINDER OF THE FILE IS A COLLECTION OF SOME OF THE BASICS NEEDED.\n"
    "(PRINC '\"Now loading FAEMAR. Please be patient.\")\n"
    "\n"
    "(DECIMAL)\n"
    "\n"
    "(DEFPROP ALLFNS T SPECIAL) (DEFPROP ALLVALUES T SPECIAL)\n"
    "(SETQ ALLFNS (SETQ ALLVALUES NIL))\n"
    "\n"
    "; ENTER ADDS THINGS TO THE BEGINNING OF LISTS IF NOT ALREADY THERE:\n"
    "(DE ENTER (X L)\n"
    "  (COND ((MEMBER X L) L)\n"
    "	(T (CONS X L))))\n"
    "\n"
    "; REDEFINE %DEFIN TO KEEP A LIST OF NAMES OF DEFINED FUNCTIONS:\n"
    "(DE %DEFIN (X V F P)\n"
    "  (PROG (R)\n"
    "	(SETQ R (COND ( (GETL X '(EXPR FEXPR SUBR FSUBR LSUBR MACRO))\n"
    "			(LIST X 'Redefined) )\n"
    "		      ( T X )))\n"
    "	(SETQ ALLFNS (ENTER X ALLFNS))\n"
    "	(PUTPROP X (NCONC (LIST (QUOTE LAMBDA) V) F) P)\n"
    "	(RETURN R)))\n"
    "\n"
    "; DV IS A LOT LIKE SETQ, BUT KEEPS A LIST OF NAMES OF VARS IN ALLVALUES:\n"
    "(DF DV (%%L)\n"
    "    (PROG2 (SETQ ALLVALUES (ENTER (CAR %%L) ALLVALUES))\n"
    "	   (SET (CAR %%L) (EVAL (CADR %%L)))))\n"
    "\n"
    "(DEFPROP !X T SPECIAL)\n"
    "\n"
    "; SPECIAL KEEPS A LIST OF SPECIALS IN THE FIRST ARG AND DECLARES THE\n"
    ";  REST OF THE LIST TO BE SPECIALS:\n"
    "(DF SPECIAL (!X)\n"
    "  (MAPC (FUNCTION\n"
    "	 (LAMBDA (L) (SET (CAR !X) (ENTER L (EVAL (CAR !X))))\n"
    "		     (PUTPROP L T 'SPECIAL)))\n"
    "	(CDR !X)))\n"
    "\n"
    "(SETQ SPECIALS (SETQ ALLDEFS (SETQ ALLFNS (SETQ ALLVALUES NIL))))\n"
    "\n"
    "(SPECIAL SPECIALS\n"
    "	 %OPEN% %TRANSPARENT% %OPENABLE% %LOCKED% %EDIBLE% %VISITED%\n"
    "	 %BREAKABLE% PLAYER INFIN VERBS OBJECT INDIRECT OBJECTS %MSG\n"
    "	 COUNTERS %N %THING %ADJ %FINAL %AVAIL DETERMINERS LINE VERB PREP\n"
    "	 PREPOSITIONS ALLDEFS ALLVALUES UNIVERSE %BURNABLE% DIR ADJECTIVES)\n"
    "\n"
    ";  INFIN IS USED SPECIALLY IN ADD AND SUBTRACT (HOPEFULLY NEVER OVERFLOWS)\n"
    "(DV INFIN 1.7014118E+38)\n"
    "\n"
    "(DV %OPEN% 1) (DV %TRANSPARENT% 2) (DV %OPENABLE% 4) (DV %EDIBLE% 8)\n"
    "(DV %LOCKED% 16) (DV %VISITED% 32) (DV %BREAKABLE% 64) (DV %BURNABLE% 128)\n"
    "\n"
    "; DT IS USED TO LOAD PROPERTY LISTS.\n"
    ";  IT TAKES THE FIRST THING AND MAKES AN ATOM WITH THAT NAME AND VALUE.\n"
    ";   IT THEN GRABS THINGS IN LISTS OF PROP-NAME FOLLOWED BY VALUE AND\n"
    ";   STUFFS THEM ONTO THE PROPERTY-LIST OF THE THING IT CREATED.\n"
    "(DF DT (%LIST)\n"
    " (PROG (%NAME)\n"
    "   (SETQ %NAME (SET (CAR %LIST) (CAR %LIST)))\n"
    "   (SETQ ALLDEFS (ENTER %NAME ALLDEFS))\n"
    "   (PUTPROP %NAME 0.0 'I-VOL)\n"
    "A  (COND( (NULL (SETQ %LIST (CDR %LIST))) (GO B) )\n"
    "	( (EQ (CAAR %LIST) 'IN)\n"
    "	  (PUTPROP (CADAR %LIST)\n"
    "		   (ENTER %NAME (GET (CADAR %LIST) 'HOLDS))\n"
    "		   'HOLDS) )\n"
    "	( (EQ (CAAR %LIST) 'PART)\n"
    "	  (PUTPROP (CADAR %LIST)\n"
    "		   (ENTER %NAME (GET (CADAR %LIST) 'PARTS))\n"
    "		   'PARTS) )\n"
    "	( (EQ (CAAR %LIST) 'ADJ)\n"
    "	  (SETQ ADJECTIVES\n"
    "		(REMOVE-DUPLICATES (CONS (EVAL (CADAR %LIST))\n"
    "					 ADJECTIVES))) ))\n"
    "   (PUTPROP %NAME (EVAL (CADAR %LIST)) (CAAR %LIST))\n"
    "   (GO A)\n"
    "B  (COND( (NULL (GET %NAME 'O-VOL))\n"
    "	  (PUTPROP %NAME\n"
    "		   (MULTIPLY (GET %NAME 'LONG)\n"
    "			     (MULTIPLY (GET %NAME 'WIDE)\n"
    "				       (GET %NAME 'DEEP)))\n"
    "		   'O-VOL) ))\n"
    "   (COND( (GET %NAME 'IN)\n"
    "	  (PROG (%DAD)\n"
    "	    (SETQ %DAD %NAME)\n"
    "       LOOP (COND( (SETQ %DAD (GET %DAD 'IN))\n"
    "		   (PUTPROP %DAD\n"
    "			    (SUBTRACT (GET %DAD 'I-VOL)\n"
    "				      (GET %NAME 'O-VOL))\n"
    "			    'I-VOL)\n"
    "		   (PUTPROP %DAD\n"
    "			    (SUBTRACT (GET %DAD 'STREN)\n"
    "				      (GET %NAME 'WEIGH))\n"
    "			    'STREN)\n"
    "		   (GO LOOP) ))) ))\n"
    "   (RETURN %NAME)))\n"
    "\n"
    "; DECODE TAKES ATOMS AND TRIES TO PUT THEM INTO A FORM THAT DT (ABOVE)\n"
    ";  WILL LIKE IF IT SEES.  SHOULD BE USEFUL FOR DUMPING THE DATA-BASE.\n"
    ";  SPRINT WILL HELP MAKE THINGS LOOK NICE.\n"
    "(DE DECODE (%THING)\n"
    "  (PROG (%LIST1 %LIST2)\n"
    "    (COND( (NOT(ATOM %THING)) (RETURN NIL) ))\n"
    "    (SETQ %LIST2 (CDR %THING))\n"
    "  A (COND( (NULL %LIST2)\n"
    "	   (RETURN (APPEND (LIST 'DT %THING) %LIST1)) )\n"
    "	 ( (NOT (OR (EQ (CAR %LIST2) 'VALUE)\n"
    "		    (EQ (CAR %LIST2) 'PNAME)))\n"
    "	   (SETQ %LIST1 (CONS (LIST (CAR %LIST2)\n"
    "				    (COND( (ATOM (CADR %LIST2))\n"
    "					   (CADR %LIST2) )\n"
    "					 ( T\n"
    "					   (LIST 'QUOTE (CADR %LIST2)) )))\n"
    "			      %LIST1))) )\n"
    "    (SETQ %LIST2 (CDDR %LIST2))\n"
    "    (GO A)))\n"
    "\n"
    "; MULTIPLY UNDERSTANDS INFIN AND SHOULDN'T OVERFLOW VERY OFTEN.\n"
    "(DE MULTIPLY (%X %Y)\n"
    "  (COND( (OR (EQ %X INFIN) (EQ %Y INFIN)) INFIN )\n"
    "       ( T (TIMES %X %Y) )))\n"
    "\n"
    "; DR (DEFINE ROOM) TRIES TO MAKE ALL OF THE APPROPRIATE ASSUMPTIONS ABOUT\n"
    ";  ROOMS, AND MAKES SURE THAT ROOMS HAVE INSIDE-VOLUMES AND ARE PART\n"
    ";  OF THE UNIVERSE.\n"
    "(DF DR (%LIST)\n"
    "  (PROG (%NAME)\n"
    "    (SETQ %NAME (SET (CAR %LIST) (CAR %LIST)))\n"
    "    (SETQ ALLDEFS (ENTER %NAME ALLDEFS))\n"
    "    (PUTPROP %NAME INFIN 'STREN)\n"
    "    (PUTPROP %NAME INFIN 'WEIGH)\n"
    "    (PUTPROP %NAME INFIN 'O-VOL)\n"
    "    (PUTPROP %NAME INFIN 'LONG)\n"
    "    (PUTPROP %NAME INFIN 'WIDE)\n"
    "    (PUTPROP %NAME INFIN 'DEEP)\n"
    "    (PUTPROP %NAME UNIVERSE 'PART)\n"
    "    (PUTPROP UNIVERSE (ENTER %NAME (GET UNIVERSE 'PARTS)) 'PARTS)\n"
    "  A (COND( (NULL (SETQ %LIST (CDR %LIST))) (GO B) )\n"
    "	 ( (EQ (CAAR %LIST) 'ADJ)\n"
    "	   (SETQ ADJECTIVES\n"
    "		 (REMOVE-DUPLICATES (CONS (EVAL (CADAR %LIST))\n"
    "					  ADJECTIVES))) ))\n"
    "    (PUTPROP %NAME (EVAL (CADAR %LIST)) (CAAR %LIST))\n"
    "    (GO A)\n"
    "  B (COND( (NULL (GET %NAME 'I-VOL))\n"
    "	   (PUTPROP %NAME INFIN 'I-VOL) ))\n"
    "    (RETURN %NAME)))\n"
    "\n"
    "; IS LOOKS AT FLAG WORDS AND OR'S THEM WITH BIT PATTERNS.\n"
    ";  IF ANY OF THEM WERE ON IT RETURNS T ELSE NIL.\n"
    "(DE GETNUM (I P)\n"
    "  (PROG (%TEMP)\n"
    "    (RETURN (COND( (NOT(NUMBERP(SETQ %TEMP (GET I P)))) 0. )\n"
    "		 ( T  %TEMP ) ))))\n"
    "\n"
    "(DE IS (%THING %BITS)\n"
    "  (COND ((EQ 0 (BOOLE 1 %BITS (GETNUM %THING 'FLAGS))) NIL)\n"
    "	(T)))\n"
    "\n"
    "(DE SET-FLAG (%BITS %THING)\n"
    "  (PUTPROP %THING (BOOLE 7 %BITS (GETNUM %THING 'FLAGS)) 'FLAGS))\n"
    "\n"
    "(DE RESET-FLAG (%BITS %THING)\n"
    "  (PUTPROP %THING (BOOLE 2 %BITS (GETNUM %THING 'FLAGS)) 'FLAGS))\n"
    "\n"
    "(DE SHARP (%THING) (NOT (GREATERP (GET %THING 'DEEP) 0)) )\n"
    "\n"
    "; WHERE IS USEFUL FOR FOLLOWING OWNERSHIP CHAINS UPWARD.\n"
    ";    IT LOOKS FOR AN \"IN\" PROPERTY AND RETURNS THAT  OR \n"
    ";    IT LOOKS FOR A \"PART\" PROPERTY AND RETURNS THAT.\n"
    ";    HENCE (CADR (WHERE THING)) IS THE \"FATHER\" OF THING.\n"
    "(DE WHERE (%THING)\n"
    "  (COND ( (NOT (ATOM %THING)) (WHERE (CADR %THING)) )\n"
    "	( (GET %THING 'IN)\n"
    "	  (LIST 'IN (GET %THING 'IN)) )\n"
    "	( (GET %THING 'PART)\n"
    "	  (LIST 'PART (GET %THING 'PART)) )\n"
    "	( T\n"
    "	  (LIST NIL NIL) ) ) )\n"
    "\n"
    "; HERE IS JUST WHERE THE PLAYER IS.\n"
    "(DE HERE NIL (GET 'PLAYER 'IN))\n"
    "\n"
    "; DELETE IS A PERFECTLY USEFUL FUNCTION THAT SHOULD HAVE BEEN HERE.\n"
    ";   IT RETURNS A LIST WHICH IS JUST LIKE THE INPUT LIST EXCEPT THAT\n"
    ";   ALL OCCURRENCES OF THING HAVE BEEN ELIMINATED.\n"
    "(DE DELETE (%THING %LIST)\n"
    "  (COND ( (NULL %LIST) NIL )\n"
    "	( (EQUAL %THING (CAR %LIST)) (DELETE %THING (CDR %LIST)) )\n"
    "	( T (CONS (CAR %LIST) (DELETE %THING (CDR %LIST))) )))\n"
    "\n"
    "; TELL PRINTS OUT THE TEXT, CHECKING FOR LINE LENGTH AND SPECIAL THINGS:\n"
    ";   %NULL% PRINTS NOTHING, %NS% SUPPRESSES THE SPACE BETWEEN OBJECTS, AND\n"
    ";   %CRLF% IS A NEWLINE.\n"
    "(DE TELL (%TEXT)\n"
    "  (PROG (%O)\n"
    "  A (COND( (NULL %TEXT) (RETURN) ))\n"
    "    (SETQ %O (CAR %TEXT))\n"
    "    (COND( (EQUAL %O '%NULL%)\n"
    "	   (RETURN) )\n"
    "	 ( (EQUAL %O '%CRLF%)\n"
    "	   (TERPRI) (GO B) )\n"
    "	 ( (AND (CDR %TEXT)\n"
    "		(EQUAL (CADR %TEXT) '%NS%)\n"
    "		(GREATERP (CHRCT) (FLATSIZE %O)))\n"
    "	   (PRINC %O) (SETQ %TEXT (CDR %TEXT)) (GO B) )\n"
    "	 ( (AND (CDR %TEXT)\n"
    "		(EQUAL (CADR %TEXT) '%NS%))\n"
    "	   (TERPRI) (PRINC %O) (SETQ %TEXT (CDR %TEXT)) (GO B) )\n"
    "	 ( (GREATERP (CHRCT) (FLATSIZE %O))\n"
    "	   (PRINC %O) )\n"
    "	 ( T (TERPRI) (PRINC %O) ) )\n"
    "    (TYO 32)\n"
    "  B (SETQ %TEXT (CDR %TEXT))\n"
    "    (GO A) ))\n"
    "\n"
    "; TAB IS USED BY *INVENT TO PRINT A SPECIFIEBER OF SPACES\n"
    "(DE TAB (%N)\n"
    "  (COND ( (EQ 0 %N) NIL )\n"
    "	( (TYO 32) (TAB (SUB1 %N)) )))\n"
    "\n"
    "; DESCRIBE RECURSIVELY PRINTS THE DESCRIPTIONS (SEE ABOVE ON PROP NAMES)\n"
    ";    OF OBJECTS. IF THEY ARE OPEN OR TRANSPARENT, THEN THEIR CONTENTS\n"
    ";    ARE ALSO DESCRIBED.\n"
    "(DE DESCRIBE (%THING)\n"
    "  (PROG (%LIST)\n"
    "    (COND ( (NULL %THING) (RETURN '(%NULL%)) )\n"
    "	  ( (NOT (GET %THING 'DESC)) (RETURN '(%NULL%)) )\n"
    "	  ( (NOT (IS %THING %VISITED%))\n"
    "	    (TELL (EVAL (GET %THING 'DESC))) ))\n"
    "             ; NOTE THAT EVAL'ING ALLOWS THE DESCRIPTION TO CHANGE.\n"
    "    (COND ( (IS %THING (PLUS %OPEN% %TRANSPARENT%))\n"
    "	    (SETQ %LIST (APPEND (GET %THING 'PARTS) (GET %THING 'HOLDS))) )\n"
    "	  ( T  (SETQ %LIST (GET %THING 'PARTS)) ))\n"
    "    (MAPC (FUNCTION\n"
    "	    (LAMBDA (%O) (COND ( (GET %O 'DESC) (DESCRIBE %O) )) ))\n"
    "	  %LIST)\n"
    "    (RETURN '(%NULL%))))\n"
    "\n"
    "; OPEN WILL TRY TO OPEN ANYTHING.  CHECKS ARE MADE FOR OPENABLE AND\n"
    ";   LOCKED FIRST, THEN THE OPEN BIT OF THE FLAGS WORD IS TURNED ON.\n"
    ";   A MESSAGE IS RETURNED, BUT CAN BE IGNORED IF YOU WANT.\n"
    "(DE OPEN NIL\n"
    "  (SETQ DIR 'open)\n"
    "  (COND ( (NOT (IS OBJECT %OPENABLE%))\n"
    "	  '(I don't know how to open such a thing/.) )\n"
    "	( (IS OBJECT %OPEN%) '(It is already open/.) )\n"
    "	( (IS OBJECT %LOCKED%) '(It is locked/.) )\n"
    "	( INDIRECT '(I don't understand that/.) )\n"
    "	( (OBJECT-ACTION) )\n"
    "	( T\n"
    "	  (COND( (MOVE OBJECT PLAYER)\n"
    "		 (TELL '(/( %NS% Taken/. /) %CRLF%)) ))\n"
    "	  (SET-FLAG %OPEN% OBJECT)\n"
    "	  (PUTPROP OBJECT\n"
    "		   (ENTER 'open (DELETE 'close (GET OBJECT 'ADJ)))\n"
    "		   'ADJ)\n"
    "	  (TELL (APPEND (GET OBJECT 'NAME) '(%NS% : opened/.)))\n"
    "	  (COND( (GET OBJECT 'HOLDS)\n"
    "		 (PUTPROP OBJECT (GET OBJECT 'INVENT) 'TEMP)\n"
    "		 (REMPROP OBJECT 'INVENT)\n"
    "		 (TELL (*INVENT OBJECT 0))\n"
    "		 (PUTPROP OBJECT (GET OBJECT 'TEMP) 'INVENT)\n"
    "		 (REMPROP OBJECT 'TEMP) ))\n"
    "	  '(%NULL%) )))\n"
    "\n"
    "; CLOSE IS VERY SIMILAR TO OPEN. IT DOESN'T CHECK THE LOCKED BIT BECAUSE\n"
    ";   IT IS ASSUMED TO HAVE BEEN TURNED OFF IN ORDER TO OPEN.\n"
    "(DE CLOSE NIL\n"
    "  (SETQ DIR 'close)\n"
    "  (COND ( (NOT (IS OBJECT %OPENABLE%))\n"
    "	  '(I don't know how to close such a thing/.) )\n"
    "	( INDIRECT '(I don't understand that/.) )\n"
    "	( (OBJECT-ACTION) )\n"
    "	( T\n"
    "	  (COND( (MOVE OBJECT PLAYER)\n"
    "		 (TELL '(/( %NS% Taken/. /)  %CRLF%)) ))\n"
    "	  (RESET-FLAG %OPEN% OBJECT)\n"
    "	  (PUTPROP OBJECT\n"
    "		   (ENTER 'close (DELETE 'open (GET OBJECT 'ADJ)))\n"
    "		   'ADJ)\n"
    "	  (APPEND (GET OBJECT 'NAME) '(%NS% : closed/.)))))\n"
    "\n"
    "; TAKE PUTS THE OBJECT MENTIONED TO THE PLAYERS HOLDINGS. SEE MOVE.\n"
    "(DE TAKE NIL\n"
    "  (SETQ DIR 'take)\n"
    "  (COND ( (MEMQ OBJECT (GET PLAYER 'HOLDS))\n"
    "	  '(You already have it/.) )\n"
    "	( (AND INDIRECT\n"
    "	       (MEMQ PREP '(on from in upon within)))\n"
    "	  (COND( (OBJECT-ACTION) )\n"
    "	       ( (NOT (MEMQ OBJECT (*AVAIL INDIRECT)))\n"
    "	  	 '(It is not there/.) )\n"
    "	       ( (MOVE OBJECT PLAYER)\n"
    "		 (APPEND (GET OBJECT 'NAME) '(%NS% : taken/.)) )\n"
    "	       ( T %MSG ) ) )\n"
    "	( INDIRECT '(I don't understand that/.) )\n"
    "	( (OBJECT-ACTION) )\n"
    "	( (MOVE OBJECT PLAYER)\n"
    "	  (APPEND (GET OBJECT 'NAME) '(%NS% : taken/.)) )\n"
    "	( T %MSG ) ))\n"
    "\n"
    "; DROP PUTS SOMETHING FROM THE PLAYERS HOLDINGS INTO THE PLAYERS\n"
    ";   CONTAINER.  IF MOVE WAS USED TO GET IT, THE MOVE HERE CAN'T FAIL.\n"
    "(DE DROP NIL\n"
    "  (SETQ DIR 'drop)\n"
    "  (COND ( (NOT (MEMQ OBJECT (*AVAIL PLAYER)))\n"
    "  	  '(You aren't carrying it/.) )\n"
    "	( (AND INDIRECT\n"
    "	       (MEMQ PREP '(in on upon within into onto)))\n"
    "	  (COND( (OBJECT-ACTION) )\n"
    "	       ( (MOVE OBJECT INDIRECT)\n"
    "		 (APPEND (GET OBJECT 'NAME) '(%NS% : dropped/.)) )\n"
    "	       ( T  %MSG )) )\n"
    "	( INDIRECT '(I don't understand that/.) )\n"
    "	( (OBJECT-ACTION) )\n"
    "	( (MOVE OBJECT (HERE))\n"
    "	  (APPEND (GET OBJECT 'NAME) '(%NS% : dropped/.)) )\n"
    "	( T %MSG ) ))\n"
    "\n"
    "; AVAILABLE IS A PREDICATE WHICH TELLS IF SOMETHING IS IN THE\n"
    ";   PLAYERS \"REACH\", THAT IS, IN THE PLAYER'S POSSESSION (AND VISIBLE)\n"
    ";   OR SOMEWHERE IN THE CURRENT ROOM.  IT KEEPS GOING DOWN OPEN THINGS AS\n"
    ";   FAR AS IT CAN.\n"
    "(DE AVAILABLE (%THING) (MEMQ %THING (*AVAIL (HERE))))\n"
    "\n"
    "; *AVAIL RETURNS A LIST OF THE AVAILABLE THINGS.\n"
    ";   IT LOOKS ALL THE WAY DOWN THROUGH OPEN AND TRANSPARENT THINGS.\n"
    "(DE *AVAIL (%PLACE)\n"
    "  (PROG (%LIST)\n"
    "    (COND( (NULL %PLACE) (RETURN NIL) )\n"
    "	 ( (IS %PLACE (PLUS %OPEN% %TRANSPARENT%))\n"
    "	   (SETQ %LIST (APPEND (GET %PLACE 'HOLDS) (GET %PLACE 'PARTS))) )\n"
    "	 ( T  (SETQ %LIST (GET %PLACE 'PARTS)) ))\n"
    "    (RETURN (REMOVE-DUPLICATES (APPEND %LIST\n"
    "				       (LIST %PLACE)\n"
    "				       (APPLY (FUNCTION APPEND)\n"
    "					      (MAPCAR (FUNCTION *AVAIL)\n"
    "						      %LIST)))))))\n"
    "\n"
    "(DE REMOVE-DUPLICATES (%LIST)\n"
    "  (COND( (NULL %LIST) NIL )\n"
    "       ( (MEMBER (CAR %LIST) (CDR %LIST)) (REMOVE-DUPLICATES (CDR %LIST)) )\n"
    "       ( T  (CONS (CAR %LIST) (REMOVE-DUPLICATES (CDR %LIST))) )))\n"
    "\n"
    "; *MOVE IS THE FRONT END FOR MOVE (WHICH IS REALLY A PREDICATE).\n"
    "(DE *MOVE NIL\n"
    " (PROG (%TEMP)\n"
    "  (COND( (NULL OBJECT) (RETURN '(Move what?)) )\n"
    "       ( (NULL INDIRECT)\n"
    "	 (RETURN (APPEND '(Where shall I move the)\n"
    "			 (DOWNSHIFT OBJECT)\n"
    "			 '(%NS% ?))) )\n"
    "       ( (NOT (MEMQ OBJECT (*AVAIL PLAYER)))\n"
    "	 (COND( (MOVE OBJECT PLAYER)\n"
    "		(TELL '( /( %NS% Taken/. %NS% /) %CRLF%)) )\n"
    "	      ( T  (RETURN %MSG) )) ) )\n"
    "  (COND( (SETQ %TEMP (OBJECT-ACTION))\n"
    "	 (RETURN %TEMP) )\n"
    "       ( (MOVE OBJECT INDIRECT)\n"
    "	 (RETURN '(OK/.)) )\n"
    "       ( T  \n"
    "	 (RETURN %MSG)))))\n"
    "\n"
    "(DE LOOK NIL\n"
    " (PROG (%TEMP)\n"
    "  (SETQ DIR 'look)\n"
    "  (COND( (AND (NULL OBJECT)\n"
    "	      (NULL INDIRECT))\n"
    "	 (TELL (GET (HERE) 'NAME))\n"
    "	 (COND( (GET (HERE) 'LOOK) (TELL (EVAL (GET (HERE) 'LOOK))) ))\n"
    "	 (RESET-FLAG %VISITED% (HERE))\n"
    "	 (TERPRI)\n"
    "	 (TELL (DESCRIBE (HERE)))\n"
    "	 (SET-FLAG %VISITED% (HERE))\n"
    "	 (RETURN '(%NULL%)) )\n"
    "       ( (AND (NULL OBJECT)\n"
    "	      (EQ PREP 'at))\n"
    "	 (COND( (SETQ %TEMP (OBJECT-ACTION))\n"
    "		(RETURN %TEMP) )\n"
    "	      ( (MOVE INDIRECT PLAYER)\n"
    "		(TELL '( /( %NS% Taken/. %NS% /) %CRLF%)) ))\n"
    "	 (COND( (GET INDIRECT 'LOOK)\n"
    "		(RETURN (EVAL (GET INDIRECT 'LOOK))) )\n"
    "	      ( T  (RETURN (APPEND '(I see nothing special about the)\n"
    "				   (DOWNSHIFT INDIRECT) '(%NS% /.))) )) )\n"
    "       ( (NULL INDIRECT)\n"
    "	 (COND( (SETQ %TEMP (OBJECT-ACTION))\n"
    "		(RETURN %TEMP) )\n"
    "	      ( (MOVE OBJECT PLAYER)\n"
    "		(TELL '( /( %NS% Taken/. %NS% /) %CRLF%)) ))\n"
    "	 (COND( (GET OBJECT 'LOOK)\n"
    "		(RETURN (EVAL (GET OBJECT 'LOOK))) )\n"
    "	      ( T  (RETURN (APPEND '(I see nothing special about the)\n"
    "				   (DOWNSHIFT OBJECT) '(%NS% /.))) )) )\n"
    "       ( (NOT (IS INDIRECT %TRANSPARENT%))\n"
    "	 (RETURN (APPEND '(How does one look through a)\n"
    "			 (DOWNSHIFT INDIRECT) '(%NS% ?))) )\n"
    "       ( (SETQ %TEMP (OBJECT-ACTION))\n"
    "	 (RETURN %TEMP) )\n"
    "       ( (GET OBJECT 'LOOK)\n"
    "	 (RETURN (EVAL (GET OBJECT 'LOOK))) )\n"
    "       ( T\n"
    "	 (RETURN (APPEND '(I see nothing special about the)\n"
    "		 (DOWNSHIFT OBJECT) '(%NS% /.))) ))))\n"
    "\n"
    "; THIS IS A GLOBAL THAT WILL CONTAIN A LIST OF COUNTERS (AS THEY ARE\n"
    ";   NEEDED).  DO WILL WALK DOWN THE LIST, DECREMENTING THE COUNTERS AND\n"
    ";   EVAL'ING THE OTHER HALVES. FORM IS ( (COUNTER.WHAT-TO-DO) ... )\n"
    ";   THE COUNTER GETS TO ZERO, THE WHOLE THING IS REMOVED FROM THE LIST.\n"
    "(DV COUNTERS NIL)\n"
    "\n"
    "; OBJECT-ACTION SEARCHES THE OBJECTS INVOLVED FOR VERBS. FIRST THE INDIRECT\n"
    ";   OBJECT IS SEARCHED, IF NOTHING HAPPENS THERE, THE DIRECT OBJECT IS\n"
    ";   SEARCHED. IF NEITHER WANT TO DO ANYTHING, RETURN NIL. OTHERWISE RETURN\n"
    ";   WHATEVER THEY RETURNED.\n"
    "(DE OBJECT-ACTION NIL\n"
    "  (PROG (%TEMP)\n"
    "    (COND ( (AND INDIRECT\n"
    "		 (SETQ %TEMP (ASSOC (*FIVE* DIR) (GET INDIRECT 'VERBS)))\n"
    "		 (SETQ %TEMP (EVAL (CDR %TEMP))))\n"
    "	    (RETURN %TEMP) )\n"
    "; ABOVE: ASSOC IS USED TO SEARCH THE INDIRECT OBJECT'S VERB LIST.\n"
    "	  ( (AND OBJECT\n"
    "		 (SETQ %TEMP (ASSOC (*FIVE* DIR) (GET OBJECT 'VERBS)))\n"
    "		 (SETQ %TEMP (EVAL (CDR %TEMP))))\n"
    "	    (RETURN %TEMP) )\n"
    "; ABOVE: SEARCH THE INDIRECT OBJECT'S VERB LIST.\n"
    "	  ( T (RETURN NIL) )) ) )\n"
    "\n"
    "; %MSG IS THE PLACE WHERE THE MESSAGE RETURNED FROM ADD-THING IS STASHED.\n"
    ";  IF MOVE FAILS, YOU HAVE THE CHOICE OF PRINTING OUT %MSG OR NOT.\n"
    "(DV %MSG NIL)\n"
    "\n"
    "; MOVE IS THE REAL WORK-HORSE OF THE DATA-STRUCTURE ROUTINES.\n"
    ";  **NOTE** IT IS A PREDICATE (RETURNS T OR NIL)! IT MERELY TELLS YOU\n"
    ";  IF THE THING THAT YOU ARE TRYING SUCCEEDED. IF IT RETURNS NIL, THE\n"
    ";  GLOBAL %MSG CONTAINS THE ERROR MESSAGE THAT IT CREATES.\n"
    ";\n"
    ";  MOVE DOES THE WORK TO ENSURE THAT VOLUMES AND STRENGTHS ARE ALL CHANGED\n"
    ";  CORRECTLY.  THERE ARE 3 CASES:\n"
    ";	1) THE DESTINATION IS A SON OF THE START.\n"
    ";		ADD THE THING ALL THE WAY ON DOWN TO THE DESTINATION BUT\n"
    ";		DON'T ADJUST THE START.\n"
    ";	2) THE START IS A SON OF THE DESTINATION.\n"
    ";		REMOVE THE THING FROM THE START ALL THE WAY TO THE DESTINATION\n"
    ";		BUT DON'T ADJUST THE DESTINATION.\n"
    ";	3) THE START AND DESTINATION HAVE A COMMON FATHER.\n"
    ";		REMOVE FROM THE START ALL THE WAY (BUT NOT INCLUDING) THE\n"
    ";		FATHER AND ADD FROM (BUT NOT INCLUDING) DAD DOWN TO DEST.\n"
    "(DE MOVE (%THING %DEST)\n"
    "  (PROG (%START %DAD %HERE %STOP)\n"
    "    (SETQ DIR 'move)\n"
    "    (COND( (NULL %THING) \n"
    "	   (SETQ %MSG '(What do you want to move?)) (RETURN NIL) )\n"
    "	 ( (NULL %DEST)\n"
    "	   (SETQ %MSG '(Where do you want to move it to?)) (RETURN NIL) )\n"
    "	 ( (EQUAL %DEST (SETQ %START (CADR (WHERE %THING))))\n"
    "	   (SETQ %MSG '(It is already there/.)) (RETURN NIL) )\n"
    "	 ( (SETQ %STOP (OBJECT-ACTION))\n"
    "	   (SETQ %MSG %STOP) (RETURN NIL) )\n"
    "	 ( (IS-SON %DEST %START)\n"
    "	   (SETQ %DAD %START) )		; CASE 1.\n"
    "	 ( (IS-SON %START %DEST)\n"
    "	   (SETQ %DAD %DEST) )		; CASE 2.\n"
    "	 ( T\n"
    "	   (PROG NIL			; CASE 3. FIND THE COMMON FATHER.\n"
    "	     (SETQ %HERE %START)	;  START UPWARD FROM START.\n"
    "	   A (COND( (IS-SON %DEST %HERE) (GO B) ))\n"
    "	     (SETQ %HERE (CADR (WHERE %HERE)))\n"
    "	     (GO A)\n"
    "	   B (SETQ %DAD %DEST)		; AND UPWARD FROM DESTINATION.\n"
    "	   C (COND( (IS-SON %START %DAD) (GO D) ))\n"
    "	     (SETQ %DAD (CADR (WHERE %DAD)))\n"
    "	     (GO C)\n"
    "	   D (COND( (IS-SON %HERE %DAD) (SETQ %DAD %HERE) )))))\n"
    "; ABOVE: THE THREE CLAUSES SET THE CORRECT FATHER.\n"
    "    (SETQ %HERE %START)			; REMOVE UP TO DAD.\n"
    "  A (COND( (IS-SON %DAD %HERE) (GO B) ))\n"
    "    (REMOVE-THING %THING %HERE)\n"
    "    (SETQ %HERE (CADR (WHERE %HERE)))\n"
    "    (GO A)\n"
    "  B (SETQ %HERE %DEST)			; ADD FROM DEST UP TO DAD.\n"
    "  C (COND( (IS-SON %DAD %HERE)\n"
    "	   (COND( (GET %THING 'PART)	; DONE: MOVE THE THING.\n"
    "		  (REMPROP %THING 'PART)\n"
    "		  (PUTPROP %START (DELETE %THING (GET %START 'PARTS)) 'PARTS) )\n"
    "		( T\n"
    "		  (PUTPROP %START (DELETE %THING (GET %START 'HOLDS)) 'HOLDS)))\n"
    "	   (PUTPROP %THING %DEST 'IN)\n"
    "	   (PUTPROP %DEST (APPEND (GET %DEST 'HOLDS) (LIST %THING)) 'HOLDS)\n"
    "	   (RETURN T))\n"
    "	 ( (SETQ %MSG (ADD-THING %THING %HERE)) ; ADD-THING RETURNS MESSAGE\n"
    "	   (GO D) ))			; IF FAILURE, BACK IT OUT!\n"
    "    (SETQ %HERE (CADR (WHERE %HERE)))\n"
    "    (GO C)\n"
    "; BELOW: FIX UP THE MESSAGE AND BACK OUT THE ADJUSTMENTS.\n"
    ";  NEEDED TO ENSURE THAT EVERYTHING STAYS COPASETIC.\n"
    "  D (SETQ %STOP %HERE)\n"
    "    (SETQ %HERE %START)\n"
    "  E (COND( (EQUAL %HERE %DAD) (GO F) ))\n"
    "    (ADD-THING %THING %HERE)		; CAN'T FAIL CAUSE JUST REMOVED!\n"
    "    (SETQ %HERE (CADR (WHERE %HERE)))\n"
    "    (GO E)\n"
    "  F (SETQ %HERE %DEST)\n"
    "  G (COND( (EQUAL %HERE %STOP) (RETURN NIL) ))\n"
    "    (REMOVE-THING %THING %HERE)\n"
    "    (GO G) ))\n"
    "\n"
    "; INVENTORY PRINTS THE CONTENTS OF THE PLAYER AS LONG AS THEY ARE VISIBLE.\n"
    ";  AN OBJECT WITHOUT A DESCRIPTION IS INVISIBLE AS ARE OBJECTS WITHIN\n"
    ";  OTHER OBJECTS WHICH ARE THEMSELVES CLOSED.\n"
    "(DE INVENTORY NIL\n"
    "  (COND( (NULL (GET PLAYER 'HOLDS))\n"
    "	 '(You are empty handed/.) )\n"
    "       ( T  (TELL '(You are carrying:))\n"
    "	    (MAPC (FUNCTION (LAMBDA (%O) (*INVENT %O 0)))\n"
    "		  (GET PLAYER 'HOLDS))\n"
    "	    '(%NULL%) )))\n"
    "\n"
    "(DE *INVENT (%THING %N)\n"
    "  (PROG (%LIST)\n"
    "    (COND( (NULL %THING) (RETURN '(%NULL%)) )\n"
    "	 ( (GET %THING 'INVENT)\n"
    "	   (TERPRI) (TAB %N) (TELL (EVAL (GET %THING 'INVENT))) ))\n"
    "    (COND( (NOT(IS %THING (PLUS %OPEN% %TRANSPARENT%))) (RETURN '(%NULL%)) ))\n"
    "    (COND( (EVAL (CONS (FUNCTION OR)\n"
    "		       (MAPCAR (FUNCTION (LAMBDA (%O) (GET %O 'INVENT)))\n"
    "			       (SETQ %LIST (GET %THING 'HOLDS)))))\n"
    "	   (TERPRI) (TAB %N)\n"
    "	   (TELL (APPEND '(The) (DOWNSHIFT %THING) '(contains:)))\n"
    "	   (MAPC (FUNCTION (LAMBDA (%O) (*INVENT %O (PLUS %N 3))))\n"
    "		 %LIST) ))\n"
    "    (RETURN '(%NULL%))))\n"
    "\n"
    "(DE DONT-KNOW NIL\n"
    "  (APPEND '(I don't know the word ' %NS%) (LIST DIR) '(%NS% '/.)))\n"
    "\n"
    "; ADD-THING DOES THE CHECKING FOR FIT (SEE MOVE). IT IS A KIND OF REVERSE\n"
    ";   PREDICATE: RETURNS NIL IF IT FIT, AND A MESSAGE OTHERWISE.\n"
    "(DE ADD-THING (%THING %PLACE)\n"
    "  (PROG (%WEIGHT %STRENGTH %T-VOL %P-VOL)\n"
    "    (COND( (NOT(IS %PLACE %OPEN%))		; LOOK FOR SHARP THINGS\n"
    "	   (COND( (NOT (SHARP %THING))\n"
    "		  (RETURN (APPEND (GET %PLACE 'NAME) '(%NS% : not open/.))) )\n"
    "		( (GREATERP (GET %THING 'STREN) (GET %PLACE 'STREN))\n"
    "		  (SETQ %T-VOL 'cut) (SETQ %P-VOL %PLACE) )\n"
    "		( (GREATERP (GET PLAYER 'STREN) (GET %THING 'STREN))\n"
    "		  (SETQ %T-VOL 'break) (SETQ %P-VOL %THING) )\n"
    "		( T\n"
    "		  (RETURN (APPEND (GET %PLACE 'NAME) '(%NS% : too tough/.))) ))\n"
    "	   (COND( (IS %P-VOL %BREAKABLE%)\n"
    "		  (SETQ %WEIGHT OBJECT)\n"
    "		  (SETQ OBJECT %P-VOL)\n"
    "		  (COND( (NOT (SETQ %P-VOL (ASSOC %T-VOL VERBS)))\n"
    "			 (SETQ DIR %T-VOL)\n"
    "			 (RETURN (DONT-KNOW)) ))\n"
    "		  (SETQ OBJECT %WEIGHT)\n"
    "		  (RETURN '(%NULL%)) )\n"
    "		( T\n"
    "		  (RETURN (APPEND (GET %P-VOL 'NAME) '(%NS% : won't)\n"
    "				  (LIST %T-VOL))) )) )\n"
    "	( (GREATERP (SETQ %WEIGHT (GET %THING 'WEIGH))\n"
    "		    (SETQ %STRENGTH (GET %PLACE 'STREN)))\n"
    "	  (COND( (IS %PLACE %BREAKABLE%)\n"
    "		 (SETQ %WEIGHT OBJECT)\n"
    "		 (SETQ OBJECT %P-VOL)\n"
    "		 (*BREAK)\n"
    "		 (SETQ OBJECT %WEIGHT)\n"
    "		 (RETURN '(%NULL%)) )\n"
    "		( T\n"
    "		  (RETURN (APPEND (GET %THING 'NAME)\n"
    "			  '(%NS% : too heavy/.))) )) )\n"
    "	( (GREATERP (SETQ %T-VOL (GET %THING 'O-VOL))\n"
    "		    (SETQ %P-VOL (GET %PLACE 'I-VOL)))\n"
    "	  (COND( (AND (IS %PLACE %BREAKABLE%)\n"
    "		      (SHARP %THING))\n"
    "		 (SETQ %WEIGHT OBJECT)\n"
    "		 (SETQ OBJECT %P-VOL)\n"
    "		 (CUT)\n"
    "		 (SETQ OBJECT %WEIGHT)\n"
    "		 (RETURN '(%NULL%)) )\n"
    "		( T\n"
    "		  (RETURN (APPEND (GET %PLACE 'NAME)\n"
    "			  '(%NS% : no room left/.))) )) )\n"
    "	( (GREATERP (GET %THING 'LONG) (GET %PLACE 'LONG))\n"
    "	  (COND( (AND (IS %PLACE %BREAKABLE%)\n"
    "		      (SHARP %THING)\n"
    "		      (SETQ %STRENGTH (ASSOC 'cut (GET %PLACE 'VERBS))))\n"
    "		 (SETQ %WEIGHT OBJECT)\n"
    "		 (SETQ OBJECT %P-VOL)\n"
    "		 (TELL (EVAL (CDR %STRENGTH)))\n"
    "		 (SETQ OBJECT %WEIGHT)\n"
    "		 (RETURN '(%NULL%)) )\n"
    "	       ( T\n"
    "		 (RETURN (APPEND (GET %THING 'NAME)\n"
    "				 '(%NS% : won't fit/.))) )) ) )\n"
    "    (PUTPROP %PLACE (SUBTRACT %STRENGTH %WEIGHT) 'STREN)\n"
    "    (PUTPROP %PLACE (SUBTRACT %P-VOL %T-VOL) 'I-VOL)\n"
    "    (RETURN NIL)))\n"
    "\n"
    "; REMOVE-THING MAKES THE REMOVAL ADJUSTMENTS.\n"
    "(DE REMOVE-THING (%THING %PLACE)\n"
    "  (PROG NIL\n"
    "    (PUTPROP %PLACE (ADD (GET %PLACE 'STREN) (GET %THING 'WEIGH)) 'STREN)\n"
    "    (PUTPROP %PLACE (ADD (GET %PLACE 'I-VOL) (GET %THING 'O-VOL)) 'I-VOL)\n"
    "    (RETURN NIL)))\n"
    "\n"
    "\n"
    "; IS-SON IS A LOT LIKE *AVAIL, BUT DOESN'T CHECK FOR OPEN OR TRANSPARENT.\n"
    "(DE IS-SON (%THING %PLACE)\n"
    "  (PROG (%LIST)\n"
    "    (COND( (NULL %PLACE) (RETURN NIL) )\n"
    "	 ( (EQUAL %THING %PLACE) (RETURN T) )\n"
    "	 ( (MEMBER %THING\n"
    "		   (SETQ %LIST (APPEND (GET %PLACE 'HOLDS)\n"
    "				       (GET %PLACE 'PARTS))))\n"
    "	   (RETURN T) )\n"
    "	 ( T (RETURN (EVAL (CONS (FUNCTION OR)\n"
    "				 (MAPCAR (FUNCTION\n"
    "					   (LAMBDA (%O) (IS-SON %THING %O)))\n"
    "					 %LIST))))))))\n"
    "\n"
    "; ADD KNOWS ABOUT INFIN.  SHOULD NEVER OVERFLOW.\n"
    "(DE ADD (%X %Y)\n"
    "  (COND( (OR (EQUAL %X INFIN) (EQUAL %Y INFIN)) INFIN )\n"
    "       ( T (*PLUS %X %Y) )))\n"
    "\n"
    "; SUBTRACT KNOWS ABOUT INFIN.\n"
    "(DE SUBTRACT (%X %Y)\n"
    "  (COND( (EQUAL %X INFIN) INFIN )\n"
    "       ( T (*DIF %X %Y) )))\n"
    "\n"
    "; MOVE-TO PUTS THE PLAYER IN A NEW ROOM, IF POSSIBLE.  IT CLOSES THE OLD\n"
    ";   ROOM AND OPENS THE NEW ROOM SO THAT *AVAIL WORKS RIGHT.\n"
    "(DE MOVE-TO (%PLACE)\n"
    "  (PROG (%TEMP)\n"
    "    (SETQ %TEMP (HERE))\n"
    "    (SET-FLAG %OPEN% %PLACE)\n"
    "    (COND( (MOVE PLAYER %PLACE) \n"
    "	   (COND( (GET %PLACE 'INIT) (EVAL (GET %PLACE 'INIT)) ))\n"
    "	   (TELL (GET %PLACE 'NAME))\n"
    "	   (COND( (OR (NOT (IS %PLACE %VISITED%))\n"
    "		      (APPLY (FUNCTION APPEND)\n"
    "			     (MAPCAR\n"
    "			       (FUNCTION (LAMBDA (%O) (GET %O 'DESC)))\n"
    "			       (APPEND (GET %PLACE 'PARTS)\n"
    "				       (GET %PLACE 'HOLDS)))))\n"
    "		  (TERPRI) ))\n"
    "; ALL THAT JUST TO KEEP FROM BLANK LINES!\n"
    "	   (TELL (DESCRIBE %PLACE))\n"
    "	   (RESET-FLAG %OPEN% %TEMP)\n"
    "	   (SET-FLAG %VISITED% %PLACE)\n"
    "	   (RETURN '(%NULL%)) )\n"
    "         ( T\n"
    "	   (RESET-FLAG %OPEN% %PLACE)\n"
    "	   (RETURN %MSG) ) ) ) )\n"
    "\n"
    "; IS-OBJECT IS USED TO CHECK AND SEE IF A WORD REPRESENTS A KNOWN OBJECT.\n"
    ";   THE KEY IS AN A-LIST OF PAIRS: (word.(THING1 ... THINGN)).\n"
    ";   THIS LIST IS SEARCHED BY ASSOC AND THE CDR IS INTERSECTED WITH *AVAIL.\n"
    ";   THE RESULT IS A LIST OF ALL THE THINGS CALLED BY THAT WORD THAT ARE\n"
    ";   AVAILABLE.\n"
    "(DE IS-OBJECT (%THING)\n"
    "  (PROG (%FINAL %TEMP %AVAIL)\n"
    "    (COND( (NULL %THING) (RETURN NIL) )	; THIS SEEMS TO BE THE PLACE\n"
    "					; TO DO DEFAULTS (FROM FRAME?)\n"
    "	 ( (MEMQ (CAR %THING) DETERMINERS)\n"
    "	   (SETQ %THING (CDR %THING)) )); STRIP OFF A DETERMINER\n"
    "    (COND( (NULL %THING)\n"
    "	   (TELL '(I don't understand that/.))\n"
    "	   (RETURN '%ERR%) )\n"
    "	 ( (NOT (SETQ %AVAIL\n"
    "		      (ASSOC (*FIVE* (CAR (LAST %THING))) OBJECTS)))\n"
    "	   (TELL (APPEND '(I don't know the word ' %NS%)\n"
    "			 (LAST %THING) '(%NS% '/.)))\n"
    "	   (RETURN '%ERR%) )\n"
    "	 ( (NULL (SETQ %AVAIL (INTERSECT (CDR %AVAIL)\n"
    "					(*AVAIL (HERE)))))\n"
    "	   (TELL (APPEND '(I see no) %THING '(here/.)))\n"
    "	   (RETURN '%ERR%) )\n"
    "	 ( T (RETURN\n"
    "	      (PROG NIL\n"
    "	       (SETQ %TEMP (REVERSE (CDR (REVERSE %THING))))\n"
    "	       (COND( (NULL %TEMP)\n"
    "		      (SETQ %FINAL %AVAIL)\n"
    "		      (GO DONE) ))\n"
    "	       (MAPC\n"
    "	         (FUNCTION (LAMBDA (%ADJ)\n"
    "			    (MAPC\n"
    "			      (FUNCTION (LAMBDA (%OBJ)\n"
    "				          (COND( (MEMQ (*FIVE* %ADJ)\n"
    "						       (GET %OBJ 'ADJ))\n"
    "					         (SETQ %FINAL\n"
    "						       (ENTER %OBJ %FINAL)) )\n"
    "					       ( T\n"
    "					         (SETQ %FINAL\n"
    "						    (DELETE %OBJ %FINAL)) ))))\n"
    "			      %AVAIL)))\n"
    "	         %TEMP)\n"
    "          DONE (COND( (NULL (SETQ %FINAL (REMOVE-DUPLICATES %FINAL)))\n"
    "		      (TELL (APPEND '(I see no) %THING '(here/.)))\n"
    "		      (RETURN '%ERR%) )\n"
    "		    ( (GREATERP (LENGTH %FINAL) 1)	; SHOULD APPLY ANY\n"
    "							; RESTRICTIONS HERE.\n"
    "		      (TELL (APPEND '(Which) %THING '(shall I use?)))\n"
    "		      (RETURN '%ERR%) )\n"
    "		    ( T\n"
    "		      (RETURN (CAR %FINAL)) )) ))))))\n"
    "\n"
    "; PARSE TRIES TO BREAK A COMMAND AT A PREPOSITION. THE FIRST WORD IS ASSUMED\n"
    ";   TO BE THE VERB, EVERYTHING UP TO THE PREP IS THE DIRECT OBJECT,\n"
    ";   EVERYTHING AFTER THE PREP IS THE INDIRECT OBJECT.\n"
    "(DE PARSE (LINE)\n"
    "  (PROG NIL\n"
    "    (COND( (EQUAL LINE '(again)) (RETURN T) ))\n"
    "    (SETQ VERB (CAR LINE))	; THIS NEEDS TO BE CHECKED VERSUS\n"
    "				; A LIST OF VERBS (PERHAPS W/ FRAMES).\n"
    "				; REMEMBER \"SAY\" AND \"GO\" W/ VARIANTS.\n"
    "    (COND( (NOT(SETQ VERB (ASSOC (*FIVE* VERB) VERBS)))\n"
    "	   (SETQ DIR (CAR LINE))\n"
    "	   (TELL (DONT-KNOW))\n"
    "	   (RETURN '%ERR%) ))\n"
    "    (SETQ DIR (CAR VERB))	; REMEMBER THE ACTUAL COMMAND WORD\n"
    "    (SETQ VERB (CDR VERB))	; STRIP OF THE MATCHER WORD\n"
    "    (SETQ LINE (CDR LINE))\n"
    "    (SETQ INDIRECT (SETQ OBJECT (SETQ PREP NIL)))\n"
    "  A (COND( (NULL LINE)		; NO PREP WAS FOUND\n"
    "	   (COND( (EQ (SETQ OBJECT (IS-OBJECT OBJECT)) '%ERR%)\n"
    "		  (RETURN (SETQ OBJECT NIL)) )\n"
    "		( T (RETURN T) )) )\n"
    "	 ( (MEMQ (CAR LINE) PREPOSITIONS)	; FOUND A PREP, SPLIT LINE\n"
    "	   (SETQ PREP (CAR LINE))\n"
    "	   (COND( (EQ (SETQ OBJECT (IS-OBJECT OBJECT)) '%ERR%)\n"
    "		  (RETURN (SETQ OBJECT NIL)) )\n"
    "		( (EQ (SETQ INDIRECT (IS-OBJECT (CDR LINE))) '%ERR%)\n"
    "		  (RETURN (SETQ INDIRECT NIL)) )\n"
    "		( T (RETURN T) )) ))\n"
    "    (SETQ OBJECT (APPEND OBJECT (LIST (CAR LINE))))\n"
    "    (SETQ LINE (CDR LINE))\n"
    "    (GO A) ))\n"
    "\n"
    "(DV DETERMINERS '(a an the this that these those))\n"
    "\n"
    "(DV PREPOSITIONS '(abaft aboard about above across after against along\n"
    "  alongside amid among amongst around as astride at athwart atop before\n"
    "  behind beneath beside besides between betwixt beyond by below in on with\n"
    "  into upon out over of to for from through past under towards off toward\n"
    "  throughout using within) )\n"
    "\n"
    "(DV ADJECTIVES '(north south east west open close locke) )\n"
    "\n"
    "; INTERSECT TAKES THE INTERSECTION OF TWO LISTS.\n"
    "(DE INTERSECT (%LIST1 %LIST2)\n"
    "  (PROG (%RESULT)\n"
    "  A (COND( (NULL %LIST1) (RETURN %RESULT) )\n"
    "	 ( (MEMQ (CAR %LIST1) %LIST2)\n"
    "	   (SETQ %RESULT (ENTER (CAR %LIST1) %RESULT)) ))\n"
    "    (SETQ %LIST1 (CDR %LIST1))\n"
    "    (GO A)))\n"
    "\n"
    "; GETLINE IS A TRY AT AN INPUT ROUTINE.  IT DOWNSHIFTS CAPITALS SO THAT IT\n"
    ";   ALWAYS RETURNS A LIST OF LOWER CASE WORDS.\n"
    "(DE GETLINE NIL\n"
    "  (PROG (%C %W %M)\n"
    "  A (COND( (AND(GREATERP (SETQ %C (TYI)) 64.)\n"
    "	       (LESSP %C 91.))		; DOWNSHIFT UPPERCASE\n"
    "	   (SETQ %W (APPEND %W (LIST (ASCII (PLUS %C 32))))))\n"
    "	 ( (AND(GREATERP %C 96.)\n"
    "	       (LESSP %C 123.))		; LEAVE LOWERCASE UNTOUCHED\n"
    "	   (SETQ %W (APPEND %W (LIST (ASCII %C)))) )\n"
    "	 ( (EQUAL %C 46.)		; A PERIOD\n"
    "	   (COND( %W (RETURN (APPEND %M (LIST (READLIST %W)))) )\n"
    "		( %M (RETURN %M) )\n"
    "		( T  (RETURN '(nothing)) )) )\n"
    "	 ( (EQUAL %C 44.)		; A COMMA\n"
    ";	   (SETQ %M (APPEND %M (LIST (READLIST %W)) '(%C%)))\n"
    "	   (COND( %W  (SETQ %M (APPEND %M (LIST (READLIST %W)))) ))\n"
    "	   (SETQ %W NIL) )\n"
    "	 ( (EQUAL %C 13.)		; A RETURN\n"
    "	   (TYI)			; STRIP OFF THE LF\n"
    "	   (COND( %W (RETURN (APPEND %M (LIST (READLIST %W)))) )\n"
    "		( %M (RETURN %M) )\n"
    "		( T  (RETURN '(nothing)) )) )\n"
    "	 ( T\n"
    "	   (COND( %W (SETQ %M (APPEND %M (LIST (READLIST %W)))) ))\n"
    "	   (SETQ %W NIL) ) )\n"
    "    (GO A) ) )\n"
    "\n"
    "; START IS JUST A LOOP AROUND THE EXECUTOR.\n"
    "(DE START NIL\n"
    "  (PROG NIL\n"
    "    (TYI) (TYI)\n"
    "    (LINELENGTH 72)\n"
    "    (TELL '(%CRLF% Good Luck! %CRLF% %CRLF%))\n"
    "    (SETQ OBJECT (SETQ INDIRECT (SETQ PREP NIL)))\n"
    "    (TELL (LOOK))\n"
    "    (SET-FLAG %VISITED% (HERE))\n"
    "; MAKE SURE THAT THE STARTING ROOM IS VISITED\n"
    "    (TERPRI)\n"
    "  A (COND( (PARSE (GETLINE)) (TELL (EVAL VERB)) ))\n"
    "    (MAPC (FUNCTION\n"
    "	    (LAMBDA (%O) (COND( (GREATERP (EVAL (CAR %O)) 0)\n"
    "				(EVAL (CDR %O))\n"
    "				(SET (CAR %O)\n"
    "				     (SUB1 (EVAL (CAR %O)))) )\n"
    "			      ( T  (SETQ COUNTERS (DELETE %O COUNTERS)) ))))\n"
    "	  COUNTERS)\n"
    "; ABOVE: MAPC CDR'S DOWN THE COUNTER LIST.\n"
    "    (TERPRI)\n"
    "    (GO A)))\n"
    "\n"
    "(DSKINQ (LAP.FNS))\n"
    "\n"
    "(DE D (%N) (ADD1 (RAN %N)))\n"
    "\n"
    "(DE PCT (%N) (LESSP (D 100) %N))\n"
    "\n"
    "(DF ONE-OF (%LIST)\n"
    "  (PROG (%TEMP)\n"
    "    (COND( (NULL %LIST) (RETURN NIL) ))\n"
    "    (SETQ %TEMP (RAN (LENGTH %LIST)))\n"
    "  A (COND( (EQ %TEMP 0) (RETURN (EVAL (CAR %LIST))) ))\n"
    "    (SETQ %TEMP (SUB1 %TEMP))\n"
    "    (SETQ %LIST (CDR %LIST))\n"
    "    (GO A) ))\n"
    "\n"
    "; DOWNSHIFT GRABS THE NAME OF A THING AND DOWNSHIFTS THE FIRST\n"
    ";   CHARACTER OF EACH WORD.\n"
    "(DE DOWNSHIFT (%THING)\n"
    "  (MAPCAR\n"
    "    (FUNCTION\n"
    "      (LAMBDA (%O)\n"
    "	(READLIST (CONS (PROG (%C) (RETURN\n"
    "			  (COND( (EQ (SETQ %C (CAR (EXPLODE %O))) 'A) 'a )\n"
    "			       ( (EQ %C 'B) 'b ) ( (EQ %C 'C) 'c )\n"
    "			       ( (EQ %C 'D) 'd ) ( (EQ %C 'E) 'e )\n"
    "			       ( (EQ %C 'F) 'f ) ( (EQ %C 'G) 'g )\n"
    "			       ( (EQ %C 'H) 'h ) ( (EQ %C 'I) 'i )\n"
    "			       ( (EQ %C 'J) 'j ) ( (EQ %C 'K) 'k )\n"
    "			       ( (EQ %C 'L) 'l ) ( (EQ %C 'M) 'm )\n"
    "			       ( (EQ %C 'N) 'n ) ( (EQ %C 'O) 'o )\n"
    "			       ( (EQ %C 'P) 'p ) ( (EQ %C 'Q) 'q )\n"
    "			       ( (EQ %C 'R) 'r ) ( (EQ %C 'S) 's )\n"
    "			       ( (EQ %C 'T) 't ) ( (EQ %C 'U) 'u )\n"
    "			       ( (EQ %C 'V) 'v ) ( (EQ %C 'W) 'w )\n"
    "			       ( (EQ %C 'X) 'x ) ( (EQ %C 'Y) 'y )\n"
    "			       ( (EQ %C 'Z) 'z ) ( T %C ))))\n"
    "			(CDR (EXPLODE %O))))))\n"
    "    (LAST (GET %THING 'NAME))))\n"
    "\n"
    "(DE *FIVE* (%THING)\n"
    "  (COND( (GREATERP (FLATSIZE %THING) 5)\n"
    "	 (PROG (%LIST)\n"
    "	   (RETURN\n"
    "	     (READLIST (CONS (CAR (SETQ %LIST (EXPLODE %THING)))\n"
    "			     (CONS (CADR %LIST)\n"
    "				   (CONS (CADDR %LIST)\n"
    "					 (CONS (CADDDR %LIST)\n"
    "					       (NCONS (CAR(CDDDDR %LIST)))))))\n"
    "       ) ) ) )\n"
    "       ( T  %THING )))\n"
    "\n"
    "(DE EAT NIL\n"
    " (PROG2\n"
    "  (SETQ DIR 'eat)\n"
    "  (COND( (NULL OBJECT) '(Eat what?) )\n"
    "       ( (AND PREP\n"
    "	      (NOT (MEMQ PREP '(with using))))\n"
    "	 '(I don't understand that/.) )\n"
    "       ( (AND INDIRECT\n"
    "	      (NOT (MEMQ INDIRECT (GET PLAYER 'HOLDS))))\n"
    "	 (APPEND '(You need to take the) (DOWNSHIFT INDIRECT) '(first/.)) )\n"
    "       ( (NOT (IS OBJECT %EDIBLE%))\n"
    "	 (ONE-OF (APPEND '(I am afraid that the) (DOWNSHIFT OBJECT)\n"
    "			 '(won't agree with you/.))\n"
    "		 '(I think that I am going to be sick/.)\n"
    "		 '(What a revolting idea/.)\n"
    "		 (APPEND '(The) (DOWNSHIFT OBJECT) '(looks inedible/.))) )\n"
    "       ( (OBJECT-ACTION) )\n"
    "       ( T\n"
    "	 (TELL (APPEND '(Thank you/. The) (DOWNSHIFT OBJECT)\n"
    "		       '(was delicious/.)))\n"
    "	 (MOVE OBJECT UNIVERSE)\n"
    "	 '(%NULL%) ))))\n"
    "\n"
    "(DE CUT NIL\n"
    " (PROG2\n"
    "  (SETQ DIR 'cut)\n"
    "  (COND( (NULL OBJECT) '(Cut what?) )\n"
    "       ( (AND PREP\n"
    "	      (NOT (MEMQ PREP '(with using))))\n"
    "	 '(I don't understand that/.) )\n"
    "       ( (NULL INDIRECT) '(With what?) )\n"
    "       ( (NOT (SHARP INDIRECT))\n"
    "	 (APPEND '(You can't cut with the) (DOWNSHIFT INDIRECT) '(%NS% /.)) )\n"
    "       ( (NOT (IS OBJECT %BREAKABLE%))\n"
    "	 (ONE-OF '(It is beyond your power to do that/.)\n"
    "		 (APPEND '(The) (DOWNSHIFT OBJECT) '(can't be cut/.))\n"
    "		 (APPEND '(The) (DOWNSHIFT OBJECT) '(is tougher than it\n"
    "		 	 looks/. Nothing happens/.))\n"
    "		 '(Your blows are ineffective/. It is unharmed/.)) )\n"
    "       ( (OBJECT-ACTION) )\n"
    "       ( T (*BREAK) ))))\n"
    "\n"
    "(DE *BREAK NIL\n"
    " (PROG2\n"
    "  (SETQ DIR 'break)\n"
    "  (COND( (NULL OBJECT) '(Break what?) )\n"
    "       ( (AND PREP\n"
    "	      (NOT (MEMQ PREP '(with using))))\n"
    "	 '(I don't understand that/.) )\n"
    "       ( (NOT (IS OBJECT %BREAKABLE%))\n"
    "	 (ONE-OF '(It is beyond your power to do that/.)\n"
    "		 (APPEND '(The) (DOWNSHIFT OBJECT) '(is unbreakable/.))\n"
    "		 (APPEND '(The) (DOWNSHIFT OBJECT) '(is tougher than it\n"
    "		 	 looks/. Nothing happens/.))\n"
    "		 '(Your blows are ineffective/. It is unharmed/.)) )\n"
    "       ( (OBJECT-ACTION) )\n"
    "       ( T\n"
    "	 (MAPC (FUNCTION (LAMBDA (%O) \n"
    "			   (PROG2\n"
    "			     (MOVE %O (HERE))\n"
    "			     (TELL (APPEND '(%CRLF%) (EVAL (GET %O 'INVENT))\n"
    "					   '(falls out/.))))))\n"
    "			 (GET OBJECT 'HOLDS))\n"
    "	 (RESET-FLAG %BREAKABLE% OBJECT)\n"
    "	 (SET-FLAG %OPEN% OBJECT)\n"
    "	 (PUTPROP OBJECT (ENTER 'broke (GET OBJECT 'ADJ)) 'ADJ)\n"
    "	 '(%NULL%) ))))\n"
    "\n"
    "(DT UNIVERSE (STREN INFIN) (WEIGH INFIN) (I-VOL INFIN) (LONG INFIN)\n"
    "	     (WIDE INFIN) (DEEP INFIN) (FLAGS %OPEN%) )\n"
    "\n"
    "(DECIMAL)\n"
    "\n"
    "(DSKINQ FAEMAR)\n"
    "\n"
    "(RAN INFIN)\n"
    "\n"
    "(PROG NIL\n"
    "      (TYO 27)\n"
    "      (TYO 72)\n"
    "      (TYO 27)\n"
    "      (TYO 74)\n"
    "      (RETURN\n"
    "	(TELL '(Done! %CRLF%))))\n"
    ""
;

static const char FAEMAR_SOURCE[] =
    "(DV VERBS '((get TAKE) (take TAKE) (exit EXIT) (nothi QUOTE (%NULL%))\n"
    "  (carry TAKE) (drop *DROP) (throw *DROP) (exami LOOK) (open OPEN)\n"
    "  (close CLOSE) (l LOOK) (n WALK) (s WALK) (e WALK) (w WALK) (ne WALK)\n"
    "  (nw WALK) (se WALK) (sw WALK) (in WALK) (stop EXIT) (burn BURN) (out WALK)\n"
    "  (inven INVENTORY) (i INVENTORY) (break *BREAK) (hit *BREAK) (d WALK)\n"
    "  (u WALK) (enter WALK) (cut CUT) (lock *LOCK) (move *MOVE) (unloc *UNLOCK)\n"
    "  (quit EXIT) (look LOOK) (eat EAT) (put *MOVE) (rname GET (HERE) 'NAME)\n"
    "  (swim ONE-OF '(I don't really see how/.) '(I think that swimming is best\n"
    "		 performed in water/.) '(Perhaps it is your head that is\n"
    "		 swimming/.) )\n"
    "))\n"
    "\n"
    "; FOR HIDING SECRET DOORS!\n"
    "(DV %SECRET% %VISITED%)\n"
    "\n"
    "(DE WALK NIL\n"
    "  (PROG (%TEMP)\n"
    "    (COND( (SETQ %TEMP (ASSOC (*FIVE* DIR) (GET (HERE) 'VERBS)))\n"
    "	   (RETURN (EVAL (CDR %TEMP))) )\n"
    "	 ( T (RETURN BLOCKED) ))))\n"
    "\n"
    "(DE *DROP NIL\n"
    "  (PROG2\n"
    "    (COND( (EQ OBJECT (CAR (GET HAND 'HOLDS)))\n"
    "	   (REMPROP HAND 'HOLDS) ))\n"
    "    (DROP)))\n"
    "\n"
    "(DE *UNLOCK NIL\n"
    "  (COND( (NULL OBJECT) '(Unlock what?) )\n"
    "       ( (NOT (IS OBJECT %LOCKED%)) '(It is not locked/.) )\n"
    "       ( (OBJECT-ACTION) )\n"
    "       ( T (RESET-FLAG %LOCKED% OBJECT)\n"
    "	 (APPEND (DOWNSHIFT OBJECT) '(%NS% : unlocked/.)) )))\n"
    "\n"
    "(DE *LOCK NIL\n"
    "  (COND( (NULL OBJECT) '(Lock what?) )\n"
    "       ( (IS OBJECT %LOCKED%) '(It is already locked/.) )\n"
    "       ( (OBJECT-ACTION) )\n"
    "       ( T (APPEND '(I don't know how to lock the)\n"
    "		   (DOWNSHIFT OBJECT) '(%NS% /.)) )))\n"
    "\n"
    "(DV BLOCKED (DV BLOCKED-BY-BUSHES\n"
    "		'(The vegetation is too thick to go in that direction/.)))\n"
    "\n"
    "(DV BLOCKED-BY-WALLS '(There is a wall there/.))\n"
    "\n"
    "(DR START (NAME '(Outside Complex)) (FLAGS %OPEN%)\n"
    "	  (VERBS '((n.(MOVE-TO BOS)))) (DESC ''(\n"
    "	  You are at the top of a large wooded hill/. Winds buffet the\n"
    "	  hill continuously/, blowing and whistling through the trees/,\n"
    "	  vines/, and other vegetation which blanket the prominence on\n"
    "	  all sides/. You are facing a stronghold complex carved from a\n"
    "	  great rock outcropping at the crest of the hill/. The rock is\n"
    "	  a heavy blackish slate /( %NS% broken in places %NS% /) %NS%\n"
    "	  /, which seems to be all around/. To the north you see a big\n"
    "	  stairway made of the same blackish stone/.)) )\n"
    "\n"
    "(DT PLAYER (STREN 2E2) (WEIGH 2E2) (I-VOL 3456.0) (FLAGS %OPEN%)\n"
    "	   (LONG 72.0) (WIDE 3E1) (DEEP 2E1) (IN START) (NAME '(Player)) )\n"
    "\n"
    "(DT HAND (NAME '(Hand)) (STREN 2E2) (WEIGH 0) (LONG 72E0) (WIDE 4E0)\n"
    "	 (DEEP 1E0) (FLAGS %OPEN%) (PART PLAYER) (I-VOL 1728.0)\n"
    "	 (ADJ '(my your right left))\n"
    "	 (DAMAG 4) (VERBS '((move COND( (AND (EQ INDIRECT HAND)\n"
    "					    (EQ PREP 'on))\n"
    "				       (COND( (MOVE OBJECT HAND)\n"
    "					      (SETQ INDIRECT (SETQ PREP NIL))\n"
    "					      (*DROP)\n"
    "					      (PUTPROP OBJECT HAND 'PART)\n"
    "					      (PUTPROP HAND (ENTER OBJECT\n"
    "							    (GET HAND 'PARTS))\n"
    "							    'PARTS)\n"
    "					      (APPEND (GET OBJECT 'NAME)\n"
    "						      '(%NS% : wearing/.)) )\n"
    "					    ( T %MSG )) )\n"
    "				     ( (EQ INDIRECT HAND)\n"
    "				       (SETQ INDIRECT (SETQ PREP NIL))\n"
    "				       (TAKE)\n"
    "				       (PUTPROP HAND (LIST OBJECT) 'HOLDS)\n"
    "				       (APPEND (GET OBJECT 'NAME)\n"
    "					       '(%NS% : holding/.)) )))) )\n"
    "\n"
    "(DR BOS	(NAME '(Base Of The Stairs))\n"
    "	(VERBS '((s MOVE-TO START) (n MOVE-TO TOS) (u MOVE-TO TOS)))\n"
    "	(DESC '(APPEND '(\n"
    "	You are standing at the base of a large stairway that has been\n"
    "	carved out of the living rock of the hillside/. The steps are\n"
    "	about ten feet wide and go up about twenty feet to a doorway/.)\n"
    "	(DESCRIBE-DOORS))) )\n"
    "\n"
    "(DT MACE (NAME '(Mace)) (STREN 5E3) (WEIGH 3E1) (LONG 22.0) (WIDE 6.0)\n"
    "	 (DEEP 6.0) (O-VOL 136.0) (IN BOS) (INVENT ''(A heavy mace))\n"
    "	 (ADJ '(heavy)) (LOOK ''(\n"
    "	 The mace is a spiked ball about a span-and-a-half in diameter which\n"
    "	 is attached to a wooden handle a cubit long/. It looks as though it\n"
    "	 has seen good hard use/. Your initials are stamped in the leather\n"
    "	 strap that serves as a wrist-band/.))\n"
    "	 (DESC ''(\n"
    "	 There is a heavy-looking mace here/.)) (DAMAG 8) )\n"
    "\n"
    "(ARRAY NUMBER T '(2 . 9))\n"
    "(STORE (NUMBER 2) '(two))   (STORE (NUMBER 3) '(three))\n"
    "(STORE (NUMBER 4) '(four))  (STORE (NUMBER 5) '(five))\n"
    "(STORE (NUMBER 6) '(six))   (STORE (NUMBER 7) '(seven))\n"
    "(STORE (NUMBER 8) '(eight)) (STORE (NUMBER 9) '(nine))\n"
    "\n"
    "(DE DESCRIBE-DOORS NIL\n"
    "  (PROG (%NUM %RESULT %LIST)\n"
    "    (SETQ %NUM (EVAL (CONS 'PLUS\n"
    "		      (MAPCAR (FUNCTION\n"
    "				(LAMBDA (%O) (COND( (IS %O %BREAKABLE%) 0 )\n"
    "						  ( T 1 ))))\n"
    "			      (SETQ %LIST\n"
    "				    (INTERSECT (*AVAIL (HERE))\n"
    "					       (ASSOC 'door OBJECTS)))))))\n"
    "    (COND( (EQ %NUM 0) )\n"
    "	 ( (EQ %NUM 1)\n"
    "	   (SETQ %RESULT '(There is a broken door here)) )\n"
    "	 ( T\n"
    "	   (SETQ %RESULT (APPEND '(There are) (NUMBER %NUM)\n"
    "				 '(broken doors here))) ))\n"
    "    (COND( (AND (NOT (IS DR1 %BREAKABLE%))\n"
    "		(MEMQ DR1 %LIST))\n"
    "	   (SETQ %RESULT (APPEND %RESULT '(%NS% /, and the entry-way\n"
    "					   stands open/.))) )\n"
    "	 ( (GREATERP %NUM 0)\n"
    "	   (SETQ %RESULT (APPEND %RESULT '(%NS% /.))) ))\n"
    "    (COND( (AND (IS DR1 %BREAKABLE%)\n"
    "		(MEMQ DR1 %LIST))\n"
    "	   (SETQ %RESULT (APPEND '(There is a wooden door hanging by\n"
    "				   the top hinge in the entry-way doorway/.\n"
    "				   It swings slowly in the strong winds/.)\n"
    "				 %RESULT)) ))\n"
    "    (RETURN %RESULT)))\n"
    "\n"
    "(DR TOS	(NAME '(Top Of The Stairs))\n"
    "	(VERBS '((s PROG2\n"
    "		     (SETQ BLOCKED BLOCKED-BY-BUSHES)\n"
    "		     (MOVE-TO BOS))\n"
    "		 (d PROG2\n"
    "		     (SETQ BLOCKED BLOCKED-BY-BUSHES)\n"
    "		     (MOVE-TO BOS))\n"
    "		 (n COND( (IS DR1 %OPEN%)\n"
    "			  (SETQ BLOCKED BLOCKED-BY-WALLS)\n"
    "			  (MOVE-TO ENT) )\n"
    "			( T CLOSED ))\n"
    "		 (in COND( (IS DR1 %OPEN%)\n"
    "			   (SETQ BLOCKED BLOCKED-BY-WALLS)\n"
    "			   (MOVE-TO ENT) )\n"
    "			 ( T CLOSED ))\n"
    "		 (enter COND( (IS DR1 %OPEN%)\n"
    "			      (SETQ BLOCKED BLOCKED-BY-WALLS)\n"
    "			      (MOVE-TO ENT) )\n"
    "			    ( T CLOSED ))))\n"
    "	(INIT '(PUTPROP DR1 (ENTER 'north (DELETE 'south (GET DR1 'ADJ)))\n"
    "			     'ADJ))\n"
    "	(DESC '(APPEND '(\n"
    "	You are at the top of the stairs/, facing a doorway in the rock/.\n"
    "	You look out over the hillside/, and there is nothing but vegetation\n"
    "	and rocks as far as you can see/. In particular/, you notice that the\n"
    "	trees are very tall and prevent you from seeing more than a bow-shot\n"
    "	or two in any direction/.) (DESCRIBE-DOORS))) )\n"
    "\n"
    "(DT BUSHES (NAME '(Vegetation)) (STREN INFIN) (WEIGH INFIN) (LONG INFIN)\n"
    "	   (WIDE INFIN) (DEEP INFIN) (PART START) (PART BOS) (PART TOS)\n"
    "	   (ADJ '(thick heavy lush)) (LOOK ''(\n"
    "	   The vegetation around you is so heavy that it restricts your\n"
    "	   travel/.  There are lots of bushes and dwarf trees/. Most are\n"
    "	   only about waist-high/, but there are some which reach to your\n"
    "	   shoulders/.  The ground itself is hard to see because of the\n"
    "	   heavy layer of leaves and pine needles/.)) )\n"
    "\n"
    "(DT TREES (NAME '(Trees)) (STREN INFIN) (WEIGH INFIN) (LONG INFIN)\n"
    "	  (WIDE INFIN) (DEEP INFIN) (PART START) (PART BOS) (PART TOS)\n"
    "	  (ADJ '(dwarf tall)) (LOOK ''(\n"
    "	  The trees are many and varied/. There are small ones that look like\n"
    "	  some sort of manzanita/, all the way up to the giants which must be\n"
    "	  some form of redwood/. The most common type must be strictly a local\n"
    "	  variety because you can't identify them/.  They have almost no bark\n"
    "	  and have a very hard wood/.)) )\n"
    "\n"
    "(DV CLOSED '(The door there is closed/.))\n"
    "\n"
    "(DR ENT	(LONG 36E1) (WIDE 36E1) (DEEP 12E1) (NAME '(Entrance))\n"
    "	(VERBS '((s COND( (IS DR1 %OPEN%) (MOVE-TO TOS) )\n"
    "			( T CLOSED ))\n"
    "		 (out COND( (IS DR1 %OPEN%) (MOVE-TO TOS) )\n"
    "			  ( T CLOSED ))\n"
    "		 (exit COND( (IS DR1 %OPEN%) (MOVE-TO TOS) )\n"
    "			   ( T CLOSED ))\n"
    "		 (n COND( (IS DR3 %OPEN%) (MOVE-TO HL1) )\n"
    "			( T CLOSED ))\n"
    "		 (e COND( (IS DR2 %OPEN%) (MOVE-TO HL2) )\n"
    "			( T CLOSED ))\n"
    "		 (w COND( (IS DR4 %OPEN%) (MOVE-TO HL3) )\n"
    "			( T CLOSED ))))\n"
    "	(INIT '(PROG NIL\n"
    "		(PUTPROP DR1 (ENTER 'south (DELETE 'north (GET DR1 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(PUTPROP DR2 (ENTER 'east (DELETE 'west (GET DR2 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(PUTPROP DR3 (ENTER 'north (DELETE 'south (GET DR3 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(PUTPROP DR4 (ENTER 'west (DELETE 'east (GET DR4 'ADJ)))\n"
    "			 'ADJ)))\n"
    "	(DESC '(APPEND '(\n"
    "	As you walk through the doorway/, you find yourself in a very\n"
    "	dark room/.  It takes a moment for your eyes to adjust to the\n"
    "	darkness/. After your eyes have adjusted/, you see that you are\n"
    "	standing in a square room with nicely finished stone walls/.\n"
    "	You estimate that the room is about ten paces long in each\n"
    "	direction/. You also notice that there are doors in the middle\n"
    "	of each of the four walls/. The air is heavy/, wet/, and musty/.\n"
    "	In fact/, it seems that burning anything will be slow and difficult\n"
    "	since the atmosphere resists combustion/.) (DESCRIBE-DOORS))))\n"
    "\n"
    "(DV DOOR-LOOK '(The door is about a span thick and is made of some very\n"
    "		strong/, grainy/, dark wood /( %NS% probably from the trees\n"
    "		outside of the complex %NS% /) %NS% /.  The hinges and other\n"
    "		hardware are made of brass/, but are otherwise worthless/.))\n"
    "\n"
    "(DE BREAK-DOOR NIL\n"
    " (PROG NIL\n"
    "  (COND( (NULL INDIRECT)\n"
    "	 (COND( PREP\n"
    "		(RETURN '(I don't understand that/.)) )\n"
    "	      ( (GET HAND 'HOLDS)\n"
    "		(SETQ PREP 'with)\n"
    "		(SETQ INDIRECT (CAR (GET HAND 'HOLDS))) )\n"
    "	      ( T\n"
    "		(RETURN '(With what?)) )) ))\n"
    "  (COND( (NULL (GET INDIRECT 'DAMAG))\n"
    "	 (RETURN\n"
    "	  (ONE-OF (APPEND '(The) (DOWNSHIFT INDIRECT)\n"
    "			  't possibly harm the door/.))\n"
    "		  (APPEND '(It would hurt the) (DOWNSHIFT INDIRECT)\n"
    "			  '(more than the door/.))\n"
    "		  '(Don't be ridiculous!)\n"
    "		  '(That won't do any good/.))) )\n"
    "       ( T\n"
    "	 (PUTPROP OBJECT\n"
    "		  (DIFFERENCE (GET OBJECT 'STREN)\n"
    "			      (D (GET INDIRECT 'DAMAG)))\n"
    "		  'STREN)\n"
    "	 (COND( (NOT (GREATERP (GET OBJECT 'STREN) 0))\n"
    "		(PUTPROP OBJECT 0.0 'STREN)\n"
    "		(PUTPROP OBJECT '(broke) 'ADJ)\n"
    "		(RESET-FLAG %BREAKABLE% OBJECT)\n"
    "		(TELL (APPEND '(SCRUNCH! %CRLF% The door collapses/. %CRLF%)\n"
    "			      (DESCRIBE-DOORS)))\n"
    "		(COND( (AND (EQUAL OBJECT D13)\n"
    "			    (GET BLADE 'PART))\n"
    "		       (MOVE BLADE ACR) ))\n"
    "		(RETURN NIL) )	; LET *BREAK FINISH BREAKING THE DOOR\n"
    "	      ( T\n"
    "		(RETURN\n"
    "		 (ONE-OF '(The door appears to weaken from the battering/.)\n"
    "			 '(The edges of the door begin to splinter under your\n"
    "			   blows/.)\n"
    "			 '(THUNK!)\n"
    "			 '(You have made a great dent in the wood/.)\n"
    "			 '(CRUNCH! %CRLF% The door shakes/.)\n"
    "			 '(The door begins to crack/.))) )) )))\n"
    "\n"
    "(DT DR1	(NAME '(Door)) (STREN (PLUS (D 6) 3)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPEN% %OPENABLE% %BREAKABLE%))\n"
    "	(ADJ '(open broke entry first)) (LOOK 'DOOR-LOOK)\n"
    "	(INVENT ''(A broken door)) (PART TOS) (PART ENT) (PART BOS)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (open COND( (IS DR1 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS DR1 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DT FLASK (STREN 5.0) (WEIGH 0.5) (LONG 3E0) (WIDE 3E0) (DEEP 0.5) (IN ENT)\n"
    "	  (NAME '(Piece Of Broken Flask)) (ADJ '(broke)) (FLAGS %BREAKABLE%)\n"
    "	  (VERBS '( (break.'(The piece of flask crunches nicely/.)) ))\n"
    "	  (INVENT ''(A piece of a broken flask)) (LOOK ''(\n"
    "	  The piece of flask is made of a very crude glass-like substance/.\n"
    "	  There are no traces of whatever was once in the flask/.))\n"
    "	  (DESC '(COND( (MEMQ (GET FLASK 'IN) '(START BOS TOS ENT))\n"
    "			'(There is a piece of a broken flask here which\n"
    "			  is being blown around by the wind/.) )\n"
    "		      ( T '(There is a piece of a broken flask here/.) ))))\n"
    "\n"
    "(DT TWIGS (STREN 5.0) (WEIGH 0.2) (LONG 4E0) (WIDE 2E0) (DEEP 1E0) (IN ENT)\n"
    "	  (FLAGS (PLUS %BURNABLE% %BREAKABLE%))\n"
    "	  (VERBS '((break.'(The leaves and twigs scatter some more/.))\n"
    "		   (hit.'(The leaves and twigs scatter some more/.))))\n"
    "	  (NAME '(Handful Of Leaves And Twigs)) (ADJ '(scatt))\n"
    "	  (INVENT ''(A handful of leaves and twigs)) (LOOK ''(\n"
    "	  The leaves and twigs are clearly from the trees surrounding the\n"
    "	  complex/. Apparently the fierce wind blew them inside/.))\n"
    "	  (DESC '(COND( (MEMQ (GET TWIGS 'IN) '(START BOS TOS ENT))\n"
    "			'(There are some leaves and twigs scattered by the\n"
    "			  wind here/.) )\n"
    "		      ( T '(There are some leaves and twigs scattered\n"
    "			    here/.) ))))\n"
    "\n"
    "(DR HL1	(NAME '(Northern Hall)) (LONG 24E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((n COND( (IS DR5 %OPEN%) (MOVE-TO ACR) )\n"
    "			( T CLOSED ))\n"
    "		 (s COND( (IS DR3 %OPEN%) (MOVE-TO ENT) )\n"
    "			( T CLOSED )))) (ADJ '(north short))\n"
    "	(INIT '(PROG NIL\n"
    "		(PUTPROP DR3 (ENTER 'south (DELETE 'north (GET DR3 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(PUTPROP DR5 (ENTER 'north (DELETE 'south (GET DR5 'ADJ)))\n"
    "			 'ADJ)))\n"
    "	(DESC '(APPEND '(\n"
    "	You have entered a short north-south hallway which has doorways\n"
    "	at either end/.  The hallway is four paces wide and the ceiling\n"
    "	is about two or two-and-a-half cubits above your head/.)\n"
    "	(DESCRIBE-DOORS))))\n"
    "\n"
    "(DT DR3	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE%))\n"
    "	(ADJ '(close north))\n"
    "	(INVENT ''(A broken door)) (PART HL1) (PART ENT) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (open COND( (IS DR3 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS DR3 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DR HL2	(NAME '(Eastern Hall)) (LONG 24E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((w COND( (IS DR2 %OPEN%) (MOVE-TO ENT) )\n"
    "			( T CLOSED ))\n"
    "		 (e MOVE-TO IN1))) (ADJ '(east short))\n"
    "	(INIT '(PUTPROP DR2 (ENTER 'west (DELETE 'east (GET DR2 'ADJ)))\n"
    "			'ADJ))\n"
    "	(DESC '(APPEND '(\n"
    "	You have entered a short hallway which leads east-west/. It is four\n"
    "	paces wide and the ceiling is about two cubits above your head/. To\n"
    "	the west is a doorway/, and to the east is a four-way intersection of\n"
    "	halls which is well lit/.) (DESCRIBE-DOORS))))\n"
    "\n"
    "(DT DR2	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE%))\n"
    "	(ADJ '(close east))\n"
    "	(INVENT ''(A broken door)) (PART HL2) (PART ENT) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (open COND( (IS DR2 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS DR2 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DR HL3	(NAME '(Western Hall)) (LONG 24E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((e COND( (IS DR4 %OPEN%) (MOVE-TO ENT) )\n"
    "			( T CLOSED ))\n"
    "		 (w MOVE-TO IN2))) (ADJ '(west short))\n"
    "	(INIT '(PUTPROP DR4 (ENTER 'east (DELETE 'south (GET DR4 'ADJ)))\n"
    "			'ADJ))\n"
    "	(DESC '(APPEND '(\n"
    "	You have entered a short hallway which leads east-west/. It is four\n"
    "	paces wide and the ceiling is about two cubits above your head/. To\n"
    "	the east is a doorway/, and to the west is a four-way intersection of\n"
    "	halls which is rather dark/.) (DESCRIBE-DOORS))))\n"
    "\n"
    "(DT DR4	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE%))\n"
    "	(ADJ '(close west))\n"
    "	(INVENT ''(A broken door)) (PART HL3) (PART ENT) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (open COND( (IS DR4 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS DR4 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DR IN1	(NAME '(Lighted Intersection)) (LONG 12E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((n MOVE-TO HL4) (s MOVE-TO HL6) (e MOVE-TO HL5)\n"
    "		 (w MOVE-TO HL2))) (DESC ''(\n"
    "	You are at a four-way intersection of hallways/. There is an opening\n"
    "	in the ceiling that causes the intersection to be well lit/. To the\n"
    "	north/, east/, and west are halls ending in doorways/, while to the\n"
    "	south is a hall that appears to open out into a room/. The north and\n"
    "	south halls are about ten or twelve paces long/, and the east and west\n"
    "	halls are about seven or eight paces long/.)) )\n"
    "\n"
    "(DR HL6	(NAME '(Trashy Hallway)) (LONG 36E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((n MOVE-TO IN1) (s MOVE-TO TRS))) (ADJ '(trash))\n"
    "	(DESC ''(\n"
    "	You are in a north-south hallway that goes from the lighted\n"
    "	intersection into a room that appears to be filled with trash and\n"
    "	other refuse/.)) )\n"
    "\n"
    "(DT TRASH (NAME '(Trash)) (STREN 1E0) (WEIGH 1E0) (LONG 12E0) (WIDE 6E0)\n"
    "	  (DEEP 2E0) (FLAGS %BURNABLE%) (IN HL6) (ADJ '(small))\n"
    "	  (INVENT ''(A small pile of trash)) (LOOK ''(\n"
    "	  The small pile of trash is mostly leaves and twigs/, but there\n"
    "	  are small shreds of paper mixed in/.)) (DESC ''(\n"
    "	  There is a small pile of trash here/.)) )\n"
    "\n"
    "(DR HL5	(NAME '(Sooty Hallway)) (LONG 24E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((w MOVE-TO IN1) (e COND( (IS DR8 %OPEN%) (MOVE-TO MET) )\n"
    "					( T CLOSED )))) (ADJ '(sooty))\n"
    "	(INIT '(PUTPROP DR8 (ENTER 'east (DELETE 'west (GET DR8 'ADJ)))\n"
    "			'ADJ))\n"
    "	(DESC '(APPEND '(\n"
    "	You are in an east-west hallway with a door to the east and the\n"
    "	lighted intersection to the west/.) (DESCRIBE-DOORS))) )\n"
    "\n"
    "(DR HL4	(NAME '(Access Hallway)) (LONG 36E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((s MOVE-TO IN1) (n COND( (IS DR7 %OPEN%) (MOVE-TO RM4) )\n"
    "					( T CLOSED )))) (ADJ '(acces))\n"
    "	(INIT '(PUTPROP DR7 (ENTER 'north (DELETE 'south (GET DR7 'ADJ)))\n"
    "			'ADJ))\n"
    "	(DESC '(APPEND '(\n"
    "	You are in a north-south hallway that goes from a lighted\n"
    "	intersection /( %NS% at the south end %NS% /) to a doorway /( %NS%\n"
    "	at the north end %NS% /) %NS% /.) (DESCRIBE-DOORS))) )\n"
    "\n"
    "(DR MET	(NAME '(Meeting Room)) (LONG 6E2) (WIDE 48E1) (DEEP 24E1)\n"
    "	(VERBS '((w COND( (IS DR8 %OPEN%) (MOVE-TO HL5) )\n"
    "			( T CLOSED ))\n"
    "		 (se PROG2\n"
    "		      (TELL '(You see a very small opening in the south wall\n"
    "			      and attempt to squeeze through it/././. %CRLF%))\n"
    "		      (MOVE-TO RT1)))) (ADJ '(meeti))\n"
    "	(INIT '(PROG NIL\n"
    "		(PUTPROP DR8 (ENTER 'west (DELETE 'east (GET DR8 'ADJ)))\n"
    "			 'ADJ))\n"
    "		(COND( (EQUAL (CAR (GET MET 'ADJ)) FPL) (RETURN) )\n"
    "		     ( T (PUTPROP MET (REVERSE (GET MET 'ADJ)) 'ADJ) )))\n"
    "	(DESC '(APPEND (DESCRIBE-DOORS) '(\n"
    "	The first thing that you notice is that this room has obviously\n"
    "	been ransacked more than once/, in fact/, probably many times/.\n"
    "	The room itself is large /( %NS% about twenty paces wide by about\n"
    "	fifteen paces deep %NS% /) and has a very high ceiling/. Curiously/,\n"
    "	there is a breeze blowing toward the south/.))) )\n"
    "\n"
    "(DT DR8	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE%))\n"
    "	(ADJ '(close))\n"
    "	(INVENT ''(A broken door)) (PART HL5) (PART MET) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (open COND( (IS DR8 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS DR8 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DT FPL	(NAME '(Huge Fireplace)) (STREN INFIN) (WEIGH INFIN) (LONG 24E1)\n"
    "	(WIDE 12E1) (DEEP 24E0) (FLAGS %OPEN%) (PART MET) (I-VOL 1728E1)\n"
    "	(ADJ '(huge giant big)) (LOOK ''(\n"
    "	The firplace is made of brick/. You notice that there is no chimney/,\n"
    "	which accounts for the soot on the ceiling/.))\n"
    "	(DESC ''(\n"
    "	At the north end of the room is a huge fireplace that takes up most\n"
    "	of the north wall/.)) )\n"
    "\n"
    "(DT SOOT (NAME '(Soot)) (STREN INFIN) (WEIGH INFIN) (LONG INFIN) (WIDE INFIN)\n"
    "	 (DEEP INFIN) (PART HL5) (PART IN1) (PART MET) (ADJ '(black))\n"
    "	 (LOOK ''(\n"
    "	 The soot is obviously the result of someone trying to burn\n"
    "	 something in this wet atmosphere/.)) (DESC ''(\n"
    "	 There is some black soot on the ceiling/.)) )\n"
    "\n"
    "(DT ASH	(NAME '(Ashes And Burnt Logs)) (STREN 1E1) (WEIGH 1E1) (LONG 23E0)\n"
    "	(WIDE 15E0) (DEEP 6E0) (IN FPL) (INVENT ''(Some burnt logs and ashes))\n"
    "	(ADJ '(burnt burne)) (DESC '(APPEND '(\n"
    "	There are some ashes and burned logs in the) (DOWNSHIFT (GET ASH 'IN))\n"
    "	'(%NS% /.))) )\n"
    "\n"
    "(DT CHAIRS (NAME '(Armchairs)) (STREN 1E1) (WEIGH 3E1) (LONG 48E0) (WIDE 33E0)\n"
    "	   (DEEP 15E0) (IN MET) (INVENT ''(Mangled armchairs))\n"
    "	   (ADJ '(mangl broke demol)) (DESC ''(\n"
    "	   There are three objects in the room which you can barely recognize\n"
    "	   as once having been armchairs/, but they have been pretty well\n"
    "	   demolished/.)) )\n"
    "\n"
    "(DT BENCH (NAME '(Broken Benches)) (STREN 1E1) (WEIGH 4E1) (LONG 6E1)\n"
    "	  (WIDE 18E1) (DEEP 18E1) (IN MET) (INVENT ''(Broken benches))\n"
    "	  (ADJ '(broke)) (DESC ''(\n"
    "	  There are a couple of broken benches in the room/. All of them\n"
    "	  have been tipped over and strewn about/.)) )\n"
    "\n"
    "(DR TRS	(NAME '(Trash Room)) (LONG 48E1) (WIDE 24E1) (DEEP 12E1)\n"
    "	(ADJ '(trash)) (VERBS '((n MOVE-TO HL6) (ne MOVE-TO RT3)))\n"
    "	(DESC ''(\n"
    "	You have entered a room that obviously has been used as a trash\n"
    "	dump for the stronghold/.)) )\n"
    "\n"
    "(DT JUNK (NAME '(Garbage Pile)) (STREN INFIN) (WEIGH INFIN) (LONG 48E1)\n"
    "	 (WIDE 12E1) (DEEP 12E1) (FLAGS %BURNABLE%) (IN TRS)\n"
    "	 (ADJ '(big huge giant)) (LOOK ''(\n"
    "	 The big pile of garbage contains lots of things/, all inextricably\n"
    "	 wound together in a giant mess/. There are pieces of parchment/,\n"
    "	 paper/, cloth/, twigs/, branches/, leaves/, and a bunch of other\n"
    "	 things that you can't quite see/. It looks almost like a huge\n"
    "	 bird or nesting animal has mashed this all together to make a\n"
    "	 nest/. Now that you look closely/, you see that there is a largish\n"
    "	 hole in the northeast corner of the room/. You could fit through/,\n"
    "	 but it would be a tight squeeze/.)) (DESC ''(\n"
    "	 There is a gigantic pile of trash that fills more than half the\n"
    "	 room/. It is so big that you can't really see the size of the\n"
    "	 room/.)) )\n"
    "\n"
    "(DR RT1	(NAME '(Rat's Crawl)) (LONG 84E1) (WIDE 48E0) (DEEP 39E0)\n"
    "	(VERBS '((s MOVE-TO RT2) (n MOVE-TO MET))) (ADJ '(rats rat))\n"
    "	(DESC ''(\n"
    "	You are in a very narrow crawlway which is only about a pace wide/.\n"
    "	The ceiling is so low that you must stoop over in order to move at\n"
    "	all/. You can see a very small opening to north that is partially\n"
    "	covered and that there is clearly a large room beyond the end of the\n"
    "	tunnel/. The crawlway winds off toward the south/.)) )\n"
    "\n"
    "(DR RT2 (NAME '(Rat's Lair)) (LONG 73E0) (WIDE 52E0) (DEEP 6E1)\n"
    "	(VERBS '((n MOVE-TO RT1) (s MOVE-TO RT3))) (ADJ '(rats rat))\n"
    "	(DESC ''(\n"
    "	You have crawled through some twisty tunnels/, at times almost too\n"
    "	small for you to fit through/, and come into a slightly larger\n"
    "	chamber/. It is almost tall enough for you to stand erect/, but the\n"
    "	chamber is still very cramped/. Fighting would be difficult/.)) )\n"
    "\n"
    "(DR RT3	(NAME '(Rat's Crawl)) (LONG 84E1) (WIDE 48E0) (DEEP 39E0)\n"
    "	(VERBS '((e MOVE-TO RT2) (w MOVE-TO TRS))) (ADJ '(rats rat))\n"
    "	(DESC ''(\n"
    "	You are in a very narrow crawlway which is only about a pace wide/.\n"
    "	The ceiling is so low that you must stoop over in order to move at\n"
    "	all/. You can see an opening to the west that is partially covered/,\n"
    "	and that the crawlway winds off toward the east/.)) )\n"
    "\n"
    "(DT COINS (NAME '(Rat's Treasure)) (STREN INFIN) (WEIGH 2E1) (LONG 15E0)\n"
    "	  (WIDE 15E0) (DEEP 5E0) (IN RT2) (INVENT ''(Some coins and gems))\n"
    "	  (ADJ '(rats rat))\n"
    "	  (VERBS '((take PROG2\n"
    "			  (PUTPROP PLAYER (PLUS 50 (GETNUM PLAYER 'SCORE))\n"
    "				   'SCORE) NIL)))\n"
    "	  (LOOK ''(\n"
    "	  The pile of treasure consists of about one hundred gold pieces/,\n"
    "	  about twenty-five silver pieces/, and about seventy-five copper\n"
    "	  pieces/. There are also three gems worth about one hundred/, fifty/,\n"
    "	  and seventy-five gold pieces respectively/. You are unable to\n"
    "	  untangle these things from the rest of the junk that the rat piled\n"
    "	  with them/. Perhaps a jeweler could do it/.))\n"
    "	  (DESC ''(\n"
    "	  There is a pile of rat nesting materials here/. There are gems and\n"
    "	  coins tangled in the pile!)) )\n"
    "\n"
    "(DR RM4	(NAME '(Access Room)) (LONG 36E1) (WIDE 36E1) (DEEP 12E1)\n"
    "	(INIT '(PROG NIL\n"
    "		(PUTPROP DR7 (ENTER 'south (DELETE 'north (GET DR7 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(PUTPROP D12 (ENTER 'west (DELETE 'east (GET D12 'ADJ)))\n"
    "			 'ADJ))) (ADJ '(acces))\n"
    "	(VERBS '((s COND( (IS DR7 %OPEN%) (MOVE-TO HL4) )\n"
    "			( T CLOSED ))\n"
    "		 (w COND( (IS D12 %OPEN%) (MOVE-TO ACR) )\n"
    "			( T CLOSED )))) (DESC ''(\n"
    "	You have gone into a dark/, dank room that is about ten paces\n"
    "	square/. There are doors to the west and south and dirt on the\n"
    "	floor/.)) )\n"
    "\n"
    "(DT COBWEBS (NAME '(Cobwebs)) (STREN 1E-5) (WEIGH 0E0) (LONG 2E1) (WIDE 2E1)\n"
    "	    (DEEP 0.1) (FLAGS %BREAKABLE%) (PART RM4) (ADJ '(spide))\n"
    "	    (VERBS '((break PROG2 '(The cobwebs scatter and disappear/.)\n"
    "				  NIL)\n"
    "		     (move PROG2 '(The cobwebs are out of reach/.) NIL)\n"
    "		      )) (LOOK ''(\n"
    "	    You are no expert on spiders/, but the web looks to be unbroken\n"
    "	    and as though the owner hasn't been here in a long while/.))\n"
    "	    (DESC ''(You notice that there are some cobwebs in the\n"
    "	    southeastern corner of the room/.)) )\n"
    "\n"
    "(DT DR7	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE%))\n"
    "	(ADJ '(close))\n"
    "	(INVENT ''(A broken door)) (PART HL4) (PART RM4) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (open COND( (IS DR7 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS DR7 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DR RM6	(NAME '(Access Room)) (LONG 36E1) (WIDE 36E1) (DEEP 12E1)\n"
    "	(INIT '(PROG NIL\n"
    "		(PUTPROP DR6 (ENTER 'south (DELETE 'north (GET DR6 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(PUTPROP D11 (ENTER 'east (DELETE 'west (GET D11 'ADJ)))\n"
    "			 'ADJ))) (ADJ '(acces))\n"
    "	(VERBS '((s COND( (IS DR6 %OPEN%) (MOVE-TO HL7) )\n"
    "			( T CLOSED ))\n"
    "		 (e COND( (IS D11 %OPEN%) (MOVE-TO ACR) )\n"
    "			( T CLOSED )))) (DESC ''(\n"
    "	You have gone into a dark/, dank room that is about ten paces\n"
    "	square/. There are doors to the east and south and dirt on the\n"
    "	floor/.)) )\n"
    "\n"
    "(DT STUB (NAME '(Torch Stub)) (STREN 2E1) (WEIGH 1E0) (LONG 12E0) (WIDE 2E0)\n"
    "	 (DEEP 2E0) (FLAGS %BURNABLE%) (IN RM6) (ADJ '(torch burnt out burne))\n"
    "	 (INVENT ''(A burnt-out torch stub)) (DESC '(APPEND '(\n"
    "	 There is a burn-out stub of a torch in the)\n"
    "	 (DOWNSHIFT (GET STUB 'IN)) '(%NS% /.))) )\n"
    "\n"
    "(DR ACR	(NAME '(Access Room)) (LONG 6E2) (WIDE 36E1) (DEEP 12E1)\n"
    "	(INIT '(PROG NIL\n"
    "		(PUTPROP DR5 (ENTER 'south (DELETE 'north (GET DR5 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(PUTPROP D12 (ENTER 'east (DELETE 'west (GET D12 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(PUTPROP D11 (ENTER 'west (DELETE 'east (GET D11 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(SETQ %C13% 2)\n"
    "		(SETQ COUNTERS\n"
    "		      (CONS '(%C13% COND( (EQUAL (HERE) ACR)\n"
    "					  (COND( (NOT (IS D13 %SECRET%)) NIL )\n"
    "					       ( (PCT 10)\n"
    "						 (RESET-FLAG %SECRET% D13)\n"
    "						 (TERPRI)\n"
    "						 (TELL '(You detect that\n"
    "						  there is something strange\n"
    "						  about the wall in the\n"
    "						  northeast corner of the\n"
    "						  room!))\n"
    "						 (TELL (DESCRIBE D13)) )\n"
    "					       ( T (SETQ %C13% 2) )) ))\n"
    "			    COUNTERS))))\n"
    "	    (VERBS '((e COND( (IS D12 %OPEN%) (MOVE-TO RM4) )\n"
    "			    ( T CLOSED ))\n"
    "		     (s COND( (IS DR5 %OPEN%) (MOVE-TO HL1) )\n"
    "			    ( T CLOSED ))\n"
    "		     (w COND( (IS D11 %OPEN%) (MOVE-TO RM6) )\n"
    "			    ( T CLOSED ))\n"
    "		    (ne COND( (IS D13 %OPEN%) (MOVE-TO BOS) )\n"
    "			    ( (IS D13 %SECRET%) BLOCKED )\n"
    "			    ( T CLOSED )))) (ADJ '(acces))\n"
    "    (LOOK '(COND( (AND (IS D13 %SECRET%)\n"
    "		       (PCT 17))\n"
    "		  (RESET-FLAG %SECRET% D13)\n"
    "		  (TELL '(You detect that there is something strange about the\n"
    "			  wall in the northeast corner of the room!))\n"
    "		  (DESCRIBE D13) )\n"
    "		( T '(I see nothing special about the access room/.) )))\n"
    "    (DESC ''(\n"
    "    You have entered a largish room /( %NS% about twenty paces by about\n"
    "    twelve paces %NS% /) with clean-swept floors/. In fact/, this is the only\n"
    "    place other than the dark entrance room where you can remember seeing\n"
    "    a floor without loose dirt/.)) )\n"
    "   \n"
    "(DT HILT (NAME '(Dagger Hilt)) (STREN INFIN) (WEIGH 1E0) (LONG 5E0) (WIDE 2E0)\n"
    "	 (DEEP 1E0) (IN ACR) (INVENT ''(A broken dagger hilt))\n"
    "	 (ADJ '(dagge broke)) (LOOK ''(\n"
    "	 The tiny part of the blade that remains attached to the hilt is very\n"
    "	 twisted/. It looks as though someone tried to use it as a pry-bar/.))\n"
    "	 (DESC ''(There is the hilt of a broken dagger near the north wall/.))\n"
    ")\n"
    "    \n"
    "(DT D13	(NAME '(Door)) (STREN (PLUS (D 20) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0)	(ADJ '(close locke secre))\n"
    "	(FLAGS (PLUS %OPENABLE% %BREAKABLE% %LOCKED% %SECRET%))\n"
    "	(INVENT ''(A broken door)) (PART ACR) (PART BOS)\n"
    "	(LOOK '(COND( (IS D13 %SECRET%)\n"
    "		      '(I see no secret door here/.) )\n"
    "		    ( '(\n"
    "	The door is carefully carved from the stone wall/. It is so well\n"
    "	concealed that it is easy to understand why you did not see it\n"
    "	earlier/.) )))\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (unloc COND( (NOT (AVAILABLE KEY))\n"
    "			      '(You are not carrying the right key/.) )\n"
    "			    ( T\n"
    "			      (RESET-FLAG %LOCKED% D13)\n"
    "			      '(Door: unlocked/.) ))\n"
    "		 (open COND( (IS D13 %BREAKABLE%)\n"
    "			     (MOVE BLADE ACR)\n"
    "			     (TELL '(The dagger blade falls to the ground/.))\n"
    "			     NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS D13 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) ))))\n"
    "	(DESC '(COND( (IS D13 %SECRET%) '(%NULL%) )\n"
    "		    ( (GET BLADE 'PART) '(%NULL%) )\n"
    "		    ( (APPEND '(There is a secret door)\n"
    "			      (COND( (EQUAL ACR (HERE))\n"
    "				     '(in the northeast corner of the\n"
    "				       room/.) )\n"
    "				   ( T '(in the wall to the south/.) ))) )))\n"
    ")\n"
    "\n"
    "(DT BLADE (NAME '(Dagger Blade)) (STREN INFIN) (WEIGH 0.5) (LONG 8E0)\n"
    "	  (WIDE 1.5) (DEEP 0E0) (PART D13) (ADJ '(broke dagge))\n"
    "	  (INVENT ''(A broken dagger blade))\n"
    "	  (LOOK '(COND( (IS D13 %SECRET%) '(I see no blade here/.) )\n"
    "		      ( '(\n"
    "	  One end of the blade is twisted as though someone tried to use it\n"
    "	  as a pry-bar/.) )))\n"
    "	  (DESC '(COND( (IS D13 %SECRET%) '(%NULL%) )\n"
    "		      ( (GET BLADE 'PART)\n"
    "			'(There is a tiny piece of the blade of a knife\n"
    "			  sticking out of the wall in the northeast corner!) )\n"
    "		      ( '(There is the blade of a broken dagger on the\n"
    "			  ground near the entrance to the room/.) )))\n"
    "	  (VERBS '(move COND( (EQUAL D13 (GET BLADE 'PART))\n"
    "			     '(You can't seem to pull the blade out of the\n"
    "			       crack in the wall/.) ))) )\n"
    "\n"
    "(DT DR5	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE% %LOCKED%))\n"
    "	(ADJ '(close locke))\n"
    "	(INVENT ''(A broken door)) (PART HL1) (PART ACR) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (unloc QUOTE (You are not carrying the right key/.))\n"
    "		 (open COND( (IS DR7 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS DR7 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DT D11	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE% %LOCKED%))\n"
    "	(ADJ '(close locke))\n"
    "	(INVENT ''(A broken door)) (PART ACR) (PART RM6) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (unloc QUOTE (You are not carrying the right key/.))\n"
    "		 (open COND( (IS D11 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS D11 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DT D12	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE% %LOCKED%))\n"
    "	(ADJ '(close locke))\n"
    "	(INVENT ''(A broken door)) (PART ACR) (PART RM4) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (unloc QUOTE (You are not carrying the right key/.))\n"
    "		 (open COND( (IS D12 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS D12 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DR IN2	(NAME '(Dark Intersection)) (LONG 12E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((n MOVE-TO HL7) (s MOVE-TO HL8) (e MOVE-TO HL3)\n"
    "		 (w MOVE-TO HL9))) (DESC ''(\n"
    "	You are at a four-way intersection of hallways/. It is dark here/. To\n"
    "	the north/, east/, and west are halls ending in doorways/, while to\n"
    "	the south is a hall that appears to go a ways and then turn west/. The\n"
    "	north and south halls are about ten or twelve paces long/, and the\n"
    "	east and west halls are about seven or eight paces long/.)) )\n"
    "\n"
    "(DR HL7	(NAME '(Muddy Hallway)) (LONG 36E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((s MOVE-TO IN2) (n COND( (IS DR6 %OPEN%) (MOVE-TO RM6) )\n"
    "					( T CLOSED )))) (ADJ '(muddy))\n"
    "	(INIT '(PUTPROP DR6 (ENTER 'north (DELETE 'south (GET DR6 'ADJ)))\n"
    "			'ADJ))\n"
    "	(DESC '(APPEND '(\n"
    "	You are in a north-south hallway that goes from a dark intersection\n"
    "	/( %NS% at the south end %NS% /) to a doorway /( %NS% at the north\n"
    "	end %NS% /) %NS% /. The floor is muddy and the footing unsure/.)\n"
    "	(DESCRIBE-DOORS))) )\n"
    "\n"
    "(DT DR6	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE%))\n"
    "	(ADJ '(close))\n"
    "	(INVENT ''(A broken door)) (PART HL7) (PART RM6) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (open COND( (IS DR6 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS DR6 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DR HL9	(NAME '(Wet Hallway)) (LONG 24E1) (WIDE 12E1) (DEEP 12E1)\n"
    "	(VERBS '((e MOVE-TO IN2) (w COND( (IS DR9 %OPEN%) (MOVE-TO FRM) )\n"
    "					( T CLOSED )))) (ADJ '(wet))\n"
    "	(INIT '(PUTPROP DR9 (ENTER 'west (DELETE 'east (GET DR9 'ADJ)))\n"
    "			'ADJ))\n"
    "	(DESC '(APPEND '(\n"
    "	You are in an east-west hallway with a door to the west and the\n"
    "	dark intersection to the east/. The air here is very humid and\n"
    "	clean-smelling/, much like after a spring rain/. You notice that there\n"
    "	is a thin layer of moisture all over the rock of the walls/.)\n"
    "	(DESCRIBE-DOORS))) )\n"
    "\n"
    "(DR FRM	(NAME '(Fountain Room)) (LONG 36E1) (WIDE 36E1) (DEEP 18E1)\n"
    "	(VERBS '((e COND( (IS DR9 %OPEN%) (MOVE-TO HL9) )\n"
    "			( T CLOSED ))\n"
    "		 (w COND( (IS D14 %OPEN%) (MOVE-TO SHR) )\n"
    "			( T CLOSED )))) (ADJ '(fount))\n"
    "	(INIT '(PROG NIL\n"
    "		(PUTPROP DR9 (ENTER 'east (DELETE 'west (GET DR9 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(PUTPROP D14 (ENTER 'west (DELETE 'east (GET D14 'ADJ)))\n"
    "			 'ADJ)))\n"
    "	(DESC '(APPEND (DESCRIBE-DOORS) '(\n"
    "	The room itself is about ten paces square and has a high ceiling/.\n"
    "	Like in the hallway outside/, the air is clean-smelling but humid/.\n"
    "	There are doors to the east and west/.))) )\n"
    "\n"
    "(DT DR9	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE%))\n"
    "	(ADJ '(close))\n"
    "	(INVENT ''(A broken door)) (PART HL9) (PART FRM) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (open COND( (IS DR9 %BREAKABLE%) NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS DR9 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DT FOUNTAIN (NAME '(Fountain)) (STREN INFIN) (WEIGH INFIN) (LONG 6E1)\n"
    "	     (WIDE 6E1) (DEEP 6E1) (I-VOL INFIN) (FLAGS %OPEN%) (PART FRM)\n"
    "	     (VERBS '((move COND( (EQ INDIRECT FOUNTAIN)\n"
    "				 (COND( (MEMQ PREP '(to into in))\n"
    "					(SETQ PREP (SETQ INDIRECT NIL))\n"
    "					(COND( (MOVE OBJECT FOUNTAIN)\n"
    "					       (PUTPROP FOUNTAIN\n"
    "						        (GET FOUNTAIN 'HOLDS)\n"
    "						        'PARTS)\n"
    "					       (REMPROP FOUNTAIN 'HOLDS)\n"
    "					       '(OK/.) )\n"
    "					     ( %MSG )) )\n"
    "				      ( (EQ PREP 'from)\n"
    "					(PUTPROP FOUNTAIN\n"
    "						 (GET FOUNTAIN 'PARTS)\n"
    "						 'HOLDS)\n"
    "					(REMPROP FOUNTAIN 'PARTS)\n"
    "					(SETQ INDIRECT (SETQ PREP NIL))\n"
    "					(TELL '(As you reach into the water\n"
    "						some of the coins disappear/.\n"
    "						%CRLF%) )\n"
    "					(TELL (TAKE))\n"
    "					(PUTPROP FOUNTAIN\n"
    "						 (GET FOUNTAIN 'HOLDS)\n"
    "						 'PARTS)\n"
    "					(REMPROP FOUNTAIN 'HOLDS)\n"
    "					'(%NULL%) )) ))))\n"
    "	     (ADJ '(large big)) (LOOK ''(\n"
    "	     There are a large number of coins of various types at the bottom\n"
    "	     of the basin/, clearly visible through the water/.))\n"
    "	     (DESC '(APPEND '(\n"
    "	     In the middle of the room is a large/, circular fountain/. It has\n"
    "	     a large central jet that shoots water to almost eye-height before\n"
    "	     the water falls into the basin/.  All in all/, a very pleasant\n"
    "	     sight/.) (COND( (GET FOUNTAIN 'PARTS)\n"
    "			     '(There is a number of coins of various\n"
    "				types in the fountain/.) )))) )\n"
    "\n"
    "(DT FAKE-COINS (NAME '(Coins)) (STREN INFIN) (WEIGH INFIN) (LONG INFIN)\n"
    "	       (WIDE INFIN) (DEEP INFIN) (IN FOUNTAIN) (ADJ '(wet subme))\n"
    "	       (VERBS '((move.'(The coins are an illusion/.)))) )\n"
    "\n"
    "(DR SHR	(NAME '(Shrine)) (LONG 36E1) (WIDE 24E1) (DEEP 12E1) (ADJ '(evil))\n"
    "	(VERBS '((e COND( (IS D14 %OPEN%) (MOVE-TO FRM) )\n"
    "			( T CLOSED ))))\n"
    "	(INIT '(PROG NIL\n"
    "		(PUTPROP D14 (ENTER 'east (DELETE 'west (GET D14 'ADJ)))\n"
    "			 'ADJ)\n"
    "		(TELL '(The door closes behind you as you pass/. %CRLF%\n"
    "			%CRLF%))\n"
    "		(RESET-FLAG %OPEN% D14)\n"
    "		(PUTPROP D14 (ENTER 'close (DELETE 'open (GET D14 'ADJ)))\n"
    "			 'ADJ))) (DESC ''(\n"
    "	You have entered the shrine of a god that you don't recognise/. The\n"
    "	room itself is about twelve paces wide and about eight paces deep/.\n"
    "	The only exit is through the door behind you/.)))\n"
    "\n"
    "(DT IDOL (NAME '(Idol)) (STREN INFIN) (WEIGH INFIN) (LONG 74E0) (WIDE 48E0)\n"
    "	 (DEEP 36E0) (IN SHR) (ADJ '(stone heavy)) (LOOK ''(\n"
    "	No matter how hard you look/, you can't seem to find out why the\n"
    "	candles are burning or whether or not the eyes are removable/.))\n"
    "	 (DESC ''(\n"
    "	There is a heavy stone idol on a small pedestal at the back of the\n"
    "	room/. It holds a lighted stone candle in each hand/, and it is\n"
    "	clear that the candles are part of the same stone as the rest of the\n"
    "	idol/.)))\n"
    "\n"
    "(DT EYES (NAME '(Idol's Eyes)) (STREN INFIN) (WEIGH 5E0) (LONG 12E0)\n"
    "	 (WIDE 12E0) (DEEP 5E0) (PART IDOL) (INVENT ''(The eyes of the idol))\n"
    "	 (ADJ '(large))\n"
    "	 (DESC '(COND( (GET EYES 'PART) '(The eyes of the idol are large/,\n"
    "					  red gems/, staring at you \n"
    "					  malevalently/.) )\n"
    "		     ( T '(There are some large gems here that were once the\n"
    "			   eyes of a stone idol/.) ))))\n"
    "\n"
    "(DT D14	(NAME '(Door)) (STREN (PLUS (D 10) 10)) (WEIGH 10.0) (LONG 84.0)\n"
    "	(WIDE 42E0) (DEEP 4E0) (FLAGS (PLUS %OPENABLE% %BREAKABLE%))\n"
    "	(ADJ '(close))\n"
    "	(INVENT ''(A broken door)) (PART FRM) (PART SHR) (LOOK 'DOOR-LOOK)\n"
    "	(VERBS '((break BREAK-DOOR)\n"
    "		 (open COND( (IS D14 %BREAKABLE%)\n"
    "			     (TELL '(You hear a soft /\" %NS% GONG %NS% /\"\n"
    "				     as you open the door/. %CRLF%))\n"
    "			     NIL )\n"
    "			   ( T '(You can't open the broken door/.) ))\n"
    "		 (close COND( (IS D14 %BREAKABLE%) NIL )\n"
    "			    ( T '(You can't close the broken door/.) )))) )\n"
    "\n"
    "(DT ROCK (NAME '(Stone)) (STREN INFIN) (WEIGH INFIN) (LONG INFIN) (WIDE INFIN)\n"
    "	 (DEEP INFIN) (PART START) (PART BOS) (PART TOS) (PART ENT) (PART HL2)\n"
    "	 (PART HL1) (PART HL3) (PART HL4) (PART HL5) (PART HL6) (PART MET)\n"
    "	 (PART IN1) (PART TRS) (PART RT1) (PART RT2) (PART RT3) (PART RM4)\n"
    "	 (PART RM6) (PART ACR)\n"
    "	 (ADJ '(black)) (LOOK ''(\n"
    "	 The stone around you is a heavy/, blackish colored slate/. It does\n"
    "	 not crumble or break easily/, in fact/, it is so hard that it is\n"
    "	 very difficult to carve but excellent for walls and floors/.)) )\n"
    "\n"
    "(DV OBJECTS '(\n"
    "	(room ENT HL1 HL2 HL3 HL4 HL5 HL6 HL7 HL8 HL9 H10 IN1 IN2 RM4 RM6\n"
    "	ACR FRM OGR SHR) (outsi START) (entra ENT TOS) (door DR1 DR2 DR3 DR4\n"
    "	DR5 DR6 DR7 DR8 DR9 D10 D11 D12 D13 D14) (hall HL1 HL2 HL3 HL4 HL5 HL6\n"
    "	HL7 HL8 HL9 H10 IN1 IN2) (inter IN1 IN2) (hallw HL1 HL2 HL3 HL4 HL5\n"
    "	HL6 HL7 HL8 HL9 H10 IN1 IN2) (crawl RT1 RT2 RT3) (stair TOS BOS)\n"
    "	(me PLAYER) (i PLAYER) (self PLAYER) (hand HAND) (fist HAND)\n"
    "	(rock ROCK) (rocks ROCK) (stone ROCK) (slate ROCK)\n"
    "	(twigs TWIGS BUSHES) (twig TWIGS BUSHES) (leave TWIGS BUSHES)\n"
    "	(plant BUSHES) (veget BUSHES) (bush BUSHES) (bushe BUSHES)\n"
    "	(tree TREES) (trees TREES) (flask FLASK) (inter IN1 IN2) (mace MACE)\n"
    "	(trash TRASH JUNK) (pile TRASH JUNK COINS FAKE-COINS)\n"
    "	(garba JUNK TRASH) (soot SOOT) (firep FPL) (ashes ASH) (ash ASH)\n"
    "	(logs ASH) (log ASH) (armch CHAIRS) (chair CHAIRS) (bench BENCH)\n"
    "	(treas COINS FAKE-COINS) (gem COINS EYES) (coins COINS FAKE-COINS)\n"
    "	(coin COINS FAKE-COINS) (gems COINS EYES) (webs COBWEBS)\n"
    "	(cobwe COBWEBS) (torch STUB) (stub STUB) (hilt HILT) (blade BLADE)\n"
    "	(key KEY) (fount FOUNTAIN) (candl IDOL) (idol IDOL) (eyes EYES)\n"
    "	(eye EYES)\n"
    ")	     )\n"
    ""
;

