      SUBROUTINE GETDTM(DATE,TIME)
C
C  PORT: REPLACES THE ONE ASSEMBLER MODULE IN THE GAME, WHICH WAS
C
C         TIME  BIN            GET DATE/TIME
C         DATE IN R1 (PACKED), TIME IN R0 (BINARY)
C
C  SO DATE IS THE PACKED JULIAN DATE CONVERTED TO BINARY - YYDDD, TWO
C  DIGIT YEAR, AS THE 370 SVC GAVE IT - AND TIME IS HUNDREDTHS OF A
C  SECOND SINCE MIDNIGHT.  --date/--time OVERRIDE BOTH (SEE POPTS).
C
C  KEEPING THE TWO DIGIT YEAR MATTERS: START DIVIDES DATE BY 1000 AND
C  ADDS 1900 TO GET THE YEAR FOR ITS DAY-OF-WEEK SUM, SO THE PORT IS
C  EXACTLY AS Y2K-BLIND AS THE ORIGINAL, WHICH IS THE POINT.
C
      IMPLICIT INTEGER(A-Z)
      COMMON /POPTCM/ NOFIX,FDATE,FTIME,AUTOWZ,PROGID,PDONE
      DIMENSION V(8),MDAYS(12)
      DATA MDAYS/0,31,59,90,120,151,181,212,243,273,304,334/
C
      IF(FDATE.EQ.0)GOTO 10
      DATE=FDATE
      TIME=FTIME*6000
      RETURN
C
10    CALL DATE_AND_TIME(VALUES=V)
      YEAR=V(1)
      DOY=MDAYS(V(2))+V(3)
      IF(V(2).LE.2)GOTO 20
      IF(MOD(YEAR,4).NE.0)GOTO 20
      IF(MOD(YEAR,100).EQ.0.AND.MOD(YEAR,400).NE.0)GOTO 20
      DOY=DOY+1
20    DATE=MOD(YEAR,100)*1000+DOY
      TIME=((V(5)*60+V(6))*60+V(7))*100+V(8)/10
      RETURN
      END
