      SUBROUTINE PGETLN(UNIT,BUF)
C
C  PORT: READ ONE RECORD OF TEXT INTO A CHARACTER VARIABLE, BLANK
C  PADDED.  THE ORIGINAL READ CHARACTERS STRAIGHT INTO INTEGER ARRAYS
C  WITH "A1" FORMAT.  GFORTRAN ACCEPTS THAT BUT READS THE FIELD AS IF IT
C  WERE NUMERIC - A COMMA ENDS IT AND THE REST OF THE LINE IS LOST - SO
C  EVERY SUCH READ IN THIS PROGRAM GOES THROUGH HERE AND PUNPK INSTEAD.
C
C  END OF FILE ON THE TERMINAL (UNIT 5, SEE IOINIT) ENDS THE PROGRAM
C  QUIETLY, WHICH IS WHAT A PIPED SCRIPT NEEDS; THE ORIGINAL RAN UNDER
C  TSO AND HAD NO END OF FILE TO WORRY ABOUT.
C
      IMPLICIT INTEGER(A-Z)
      CHARACTER*(*) BUF
C
      BUF=' '
      READ(UNIT,1,END=9,ERR=9)BUF
1     FORMAT(A)
      RETURN
9     IF(UNIT.EQ.5)STOP
      WRITE(6,10)UNIT
10    FORMAT(' PORT: END OF FILE ON UNIT',I3)
      STOP
      END
      SUBROUTINE PUNPK(STR,IARR,N)
C
C  PORT: ONE CHARACTER PER WORD, AS "A1" DID ON THE 370.  THE CHARACTER
C  GOES IN THE LOW-ORDER BYTE, WHICH IS THE BYTE GFORTRAN'S "A1" WRITES
C  BACK OUT (THE 370 USED THE HIGH-ORDER BYTE; NOTHING IN THE PROGRAM
C  CARES WHICH, ONLY THAT READING AND WRITING AGREE).
C
      IMPLICIT INTEGER(A-Z)
      CHARACTER*(*) STR
      DIMENSION IARR(N)
C
      DO 10 I=1,N
10    IARR(I)=ICHAR(STR(I:I))
      RETURN
      END
      INTEGER FUNCTION PPACK4(STR)
C
C  PORT: FOUR CHARACTERS IN ONE WORD, AS "A4" DID, FIRST CHARACTER IN
C  THE LOW-ORDER BYTE (SEE PUNPK).
C
      IMPLICIT INTEGER(A-Z)
      CHARACTER*4 STR
C
      PPACK4=0
      DO 10 I=1,4
10    PPACK4=IOR(PPACK4,ISHFT(ICHAR(STR(I:I)),8*(I-1)))
      RETURN
      END
