#!/usr/bin/env python3
"""Build the trimmed RK05 image and the C header that embeds it.

The distribution disk (advent-work.rk05) is a full OS/8 system pack holding
BASIC, TECO, CHESS, music files and much else besides Adventure.  Only the
OS/8 system area and the five files Adventure actually opens are needed, so
every other data block is zeroed before the image is deflated.  The OS/8
directory is left untouched: the entries still name the deleted files, but
nothing ever reads them, and leaving the directory alone means the free-space
map stays valid for the ASAVE.DA file the SAVE command creates.
"""
import sys, zlib, struct, os

BS = 512                      # bytes per OS/8 block (256 twelve-bit words)

# (start block, length) of everything the running game touches, from the
# OS/8 directory of unit RKA0.
KEEP_FILES = [
    (655,  26),   # FRTS.SV    FORTRAN IV run-time system
    (2204, 145),  # ADVENT.LD  the game, as loaded by FRTS
    (2414, 50),   # AINDX.DA   text index
    (2464, 1),    # ADVENT.IN  setup file naming the four data files
    (2625, 144),  # ATEXT.DA   packed message database
]
SYSTEM_BLOCKS = 56            # blocks 0..55: bootstrap, directory, OS/8 head
RKB0_BASE     = 3248          # second logical unit of the RK05
RKB0_DIR      = 7             # its directory segments


def trim(raw):
    d = bytearray(raw)
    keep = set(range(SYSTEM_BLOCKS))
    for start, length in KEEP_FILES:
        keep.update(range(start, start + length))
    keep.update(range(RKB0_BASE, RKB0_BASE + RKB0_DIR))
    zeroed = 0
    for b in range(len(d) // BS):
        if b not in keep and d[b*BS:(b+1)*BS] != bytes(BS):
            d[b*BS:(b+1)*BS] = bytes(BS)
            zeroed += 1
    return bytes(d), zeroed


def emit_header(path, blob, rawlen):
    with open(path, 'w', newline='\n') as f:
        f.write("/* Generated by tools/mkimage.py -- do not edit.\n"
                " * Deflated OS/8 RK05 pack: the original system, FRTS and ADVENT.LD.\n"
                " */\n")
        f.write("#define RK05_RAW_BYTES %du\n" % rawlen)
        f.write("#define RK05_Z_BYTES   %du\n\n" % len(blob))
        f.write("static const unsigned char rk05_z[RK05_Z_BYTES] = {\n")
        for i in range(0, len(blob), 16):
            f.write("  " + ",".join("0x%02x" % c for c in blob[i:i+16]) + ",\n")
        f.write("};\n")


def main():
    src = sys.argv[1]
    hdr = sys.argv[2]
    raw = open(src, 'rb').read()
    trimmed, zeroed = trim(raw)
    blob = zlib.compress(trimmed, 9)
    emit_header(hdr, blob, len(trimmed))
    print("source %d bytes, %d blocks zeroed, deflated to %d bytes"
          % (len(raw), zeroed, len(blob)))
    if '--keep-pack' in sys.argv:
        # The trimmed pack itself, for attaching to SIMH when comparing.
        out = os.path.join(os.path.dirname(hdr) or '.', 'advent-trim.rk05')
        open(out, 'wb').write(trimmed)


if __name__ == '__main__':
    main()
