	IMPLICIT INTEGER(A-Z)
	CHARACTER NAME*15,SECRETNAME*10,UIC*6,PLAYER*252,UIC1*6
	CHARACTER USERNAME*12,TIM*5,KEY1*15,USERNAME1*12
	CHARACTER MONSTER(119)*20
	CHARACTER WALL(4)*5,PICTURE(13)*19,COLOR(11)*6,MONNAM*20
	INTEGER DUNGEON,DUNLVL,SPELLTOREGEN,SPELLS,DAYS,HITPOINTS,
     +TOTALHITPOINTS,EXPERIENCE,GOLD,GOLDONPERSON,STATS(6),MAGIC(8),
     +PROPERTIES(8),CHARLVL,CLASS,ARMORCLASS,XCOORD,YCOORD,HPREGEN,
     +DISEASE,ADJTOAC,PROTEVIL,BLINK,ADJTOHIT,ADJSAVTHR,WISH,
     +SPELLREGEN,LIFE,RUN,ERR,MONHTDICE,MONHDSIDES,MONDXTRTY,
     +MONDDSIDES,MONDMGDICE,MONSA1,MONSA2,MONSA3,MONHITYOU,MONYOUHIT,
     +MONUNDEADMAGIC,BLIND,FLAG,MONNUM,MONLVL,MAP(40,21),MONHTPT,
     +LEVELLENGTH,LEVELWIDTH,STAIRSUPX,STAIRSUPY,STAIRSDOWNX,MOVES,
     +STAIRSDOWNY,LOCATION,NUMBEROFWALLS,EXPERT,PRINTCONTROL,AGE,
     +PRINTFLAG,POINTER(8),MONSTERSTAT(119,2),TRAP,STENCH,DELAY,SOLVED,
     +MONTHTPT
	REAL RAN

	COMMON/BLOCK1/SEED1,NAME,SECRETNAME,USERNAME,UIC,RUN,LIFE,DUNGEON
	COMMON/BLOCK2/SPELLTOREGEN,SPELLS,DAYS,HITPOINTS,EXPERIENCE
	COMMON/BLOCK3/TOTALHITPOINTS,GOLD,GOLDONPERSON,STATS,DELAY
	COMMON/BLOCK4/MAGIC,PROPERTIES,CHARLVL,CLASS,XCOORD
	COMMON/BLOCK5/YCOORD,ARMORCLASS,HPREGEN,DISEASE,ADJTOAC
	COMMON/BLOCK6/PROTEVIL,BLINK,ADJTOHIT,ADJSAVTHR,WISH,SPELLREGEN
	COMMON/BLOCK7/PLAYER,DUNLVL,UIC1,USERNAME1,MONTHTPT
	COMMON/BLOCK8/WALL,PICTURE,COLOR,MONHTDICE,MONHDSIDES,MONNUM
	COMMON/BLOCK9/MONDXTRTY,MONDDSIDES,MONDMGDICE,MONSA1,MONSA2
	COMMON/BLOCK0/MONSA3,MONHITYOU,MONYOUHIT,MONUNDEADMAGIC,MONHTPT
	COMMON/BLOCKA/BLIND,FLAG,MONLVL,MAP,LEVELLENGTH,EXPERT,SOLVED
	COMMON/BLOCKB/LEVELWIDTH,STAIRSUPX,STAIRSUPY,STAIRSDOWNX
	COMMON/BLOCKC/STAIRSDOWNY,LOCATION,NUMBEROFWALLS,PRINTCONTROL
	COMMON/BLOCKD/PRINTFLAG,POINTER,MONNAM,MONSTERSTAT,MONSTER
	COMMON/BLOCKE/TRAP,STENCH,AGE,MOVES
