DELETE-FILE LEGENDF:BRF
DELETE-FILE LEGENDF:LIST
DELETE-FILE LEGENDF:PROG
DELETE-FILE LEGEND-LU:BRF
DELETE-FILE LEGEND-LU:LIST
DELETE-FILE LEGEND-LU:PROG
BASIC || READY\s*$
DEFAULT-INTEGER
TABLE-SIZES 1500,35000
COMPILE LEGEND-LU:ZYMB,"LEGEND-LU:LIST","LEGEND-LU:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
BASIC || READY\s*$
DEFAULT-INTEGER
TABLE-SIZES 1500,35000
COMPILE LEGENDF:ZYMB,"LEGENDF:LIST","LEGENDF:BRF" || STATEMENTS COMPILED[^\n]*\n(.|\n)*\n\S*\s*$
BYE || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD LEGEND-LU:BRF || \* ?$
LOAD LIBRARY-MJ:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "LEGEND-LU:PROG" || \* ?$
EXIT || @ ?$
NRL || \* ?$
SIZE 2700 || \* ?$
LOAD LEGENDF:BRF || \* ?$
LOAD LIBRARY-MJF:BRF || \* ?$
LOAD BASLIBR-H00:BRF || \* ?$
ENTRIES-UNDEFINED || \* ?$
DUMP "LEGENDF:PROG" || \* ?$
EXIT || @ ?$
